### ISSUE TITLE
HttpInputStream -> ArgumentNullException

### ISSUE THREAD

**Issue by montelyno** [ExcelDataReader/ExcelDataReader#101]
Hi there,

i getting an error while passing an HttpInputStream to the ExcelReaderFactory.CreateOpenXmlReader(Stream) method.
The file comes from an Mvc application which posts a file to a System.Web.HttpInputStream (canread/canseek = true)
=> https://msdn.microsoft.com/en-us/library/system.web.httppostedfile.inputstream(v=vs.110).aspx

**Stack:**
   bei Excel.Core.OpenXmlFormat.XlsxWorkbook..ctor(Stream workbookStream, Stream relsStream, Stream sharedStringsStream, Stream stylesStream) in c:\development\ExcelDataReader\Excel\Core\OpenXmlFormat\XlsxWorkbook.cs:Zeile 30.
   bei Excel.ExcelOpenXmlReader.ReadGlobals() in c:\development\ExcelDataReader\Excel\ExcelOpenXmlReader.cs:Zeile 58.
   bei Excel.ExcelOpenXmlReader.Initialize(Stream fileStream) in c:\development\ExcelDataReader\Excel\ExcelOpenXmlReader.cs:Zeile 345.
   bei Excel.ExcelReaderFactory.CreateOpenXmlReader(Stream fileStream) in c:\development\ExcelDataReader\Excel\ExcelReaderFactory.cs:Zeile 74.
   bei *.Shared.ExcelManager.GetReaderForFile(Stream stream, String filename) in 

[...]
Lib from NuGet V. 2.1.2.3, runtime version v4.0.30319 (packages\ExcelDataReader.2.1.2.3\lib\net45\Excel.dll)

Do you have any idea, why this error occurs?
If i open that file with a manual instantiated System.IO.Stream the method works properly and i am getting the correct output.
So there is maybe an error while working with the HttpInputStream.

Thanks in advance for any idea to solve the problem.

Kind regards.
MS

**Comment by Ian1971** [comment]
I'm fairly sure HttpInputStream is canseek = false. So the best bet is to copy it to a memory stream first.
