### ISSUE TITLE
I have an issue storing files on the web server

### ISSUE THREAD

**Issue by prosenba** [ExcelDataReader/ExcelDataReader#104]
I'm a big fan of the ExcelDataReader for years, the version I'm using I have re-wrote the zip.worker not to use the file system at all. I posted that code a few years ago on how to not use the temp dir and to create everything in memory. But I see in this version the program is still using the temp dir. What are the opinions from other developers of the risks of a user uploading a virus and than having it saved to web server hard drive versus of it being in memory the whole time where it can be caught in real time by the anti-virus program?

	string tPath = Path.Combine(_tempPath, entry.Name);
			string path = entry.IsDirectory ? tPath : Path.GetDirectoryName(Path.GetFullPath(tPath));

			if (!Directory.Exists(path))
			{
				Directory.CreateDirectory(path);
			}

**Comment by Ian1971** [comment]
I'm not expert on viruses, but the file would never been run on the web server as an executable so I'm not sure how the virus could infect the server itself. I can see it would be more of an issue if you were making the file available for download again. In any case real time virus protection scans files as well as memory usually doesn't it?

So for me the temp file vs memory question is more around performance and scalability. Clearly it will be faster in memory, but how does it scale if users can upload large spreadsheets?

**Comment by prosenba** [comment]
Thanks for contacting me, we have been using the excel data reader in memory only for two years now. We have about 20 to 30 users at the Uw uploading spreadsheets with about 80 thousand rows I and then we bulk load them into sql server. I saw you have made great improvements with code base since then. I originally modified the code. I worked at Boeing before the Uw and the requirements are stricter than Uw. Security will not approve any app that has saves files on the server. We moved away from jet drivers just for that reason.

Phillip
Sent from iPhone

On Feb 18, 2016, at 3:06 PM, Ian1971 <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not expert on viruses, but the file would never been run on the web server as an executable so I'm not sure how the virus could infect the server itself. I can see it would be more of an issue if you were making the file available for download again. In any case real time virus protection scans files as well as memory usually doesn't it?

So for me the temp file vs memory question is more around performance and scalability. Clearly it will be faster in memory, but how does it scale if users can upload large spreadsheets?

**Comment by Ian1971** [comment]
Makes sense. It might be nice to support both modes, in memory and temp file. I took over maintaining the project at some point so not sure if your mem change was before or after that. Unfortunately I don't really use ExcelDataReader at the moment as on a different project so it is very hard to find any time to make further changes.

**Comment by prosenba** [comment]
Hi Ian,
I would like to share my code with you, I’m not very up to date on github and how to add my code. If you could use it to make the product use the memory option and we can start using the nugget package. I would appreciate if you just listed me as contributor or something would be awesome.
Thanks

**Comment by Ian1971** [comment]
The best way is to fork the project. Make your changes, then submit a pull request. That makes it much easier to see the changes and incorporate them.

**Comment by prosenba** [comment]
Thanks
________________________________________

**Comment by prosenba** [comment]
Hi Ian,
Hope your doing well, sorry about the delay. I checked in my code today with visual studio 2015 via the gitHub plugin. I commented out code that I didn't need anymore so it's all there to see. Do I need to do anything else or will someone review it?

Thanks
________________________________________

**Comment by Ian1971** [comment]
I can't see a pull request. So, assuming you pushed your local changes to your forked repo then go into github and create a pull request.

**Comment by prosenba** [comment]
Should be there now

Phillip
Sent from iPhone

On Mar 22, 2016, at 4:10 PM, Ian1971 <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't see a pull request. So, assuming you pushed your local changes to your forked repo then go into github and create a pull request.

**Comment by wizardgsz** [comment]
Hi Phillip, can't you just support both options: your new in memory implementation and former filesystem method?
Regards and thanks

**Comment by Ian1971** [comment]
I agree, I think it needs to default to the current behaviour and have in-memory as an option. Otherwise  the performance characteristics will change which whilst may be a positive increase for some might have negative consequences for others.

**Comment by wizardgsz** [comment]
We're talking about Open Xml format only, right?

Would be fine, maybe, something like:

	ExcelReaderFactory.CreateOpenXmlReader(Stream fileStream, `ReadOption readOption`)
	public enum ReadOption
	{
		Strict,
		Loose,
		UnzipInMemory, // ?
		UnzipFilesystem // ?
	}

Phillip, do you need help (during my spare time maybe)?

**Comment by wizardgsz** [comment]
I got it!

You commented out a "special" case getting worksheet :)
Please modify it:

        public Stream GetWorksheetStream(string sheetPath)
        {
            //its possible sheetPath starts with /xl. in this case trim the /xl
            if (sheetPath.StartsWith("/xl/"))
                sheetPath = sheetPath.Substring(4);
            exelcontent = "xl/" + sheetPath;
            return getStream(exelcontent);
        }

Other issue should be fixed using UTF8 instead of ASCII encoder.

Last but not least: 

- please could u kindly use always TABS or always SPACES indenting the code?
- rethrowing Exceptions, please substitute `throw ex `with `throw`, otherwise you'll loose call stack...
- you can also set `_exceptionMessage = ex.Message` before

**Comment by prosenba** [comment]
Thanks for the input, I think having an option to select memory or not is a great idea. I will try to help out when I find some bandwidth.
________________________________________

**Comment by wizardgsz** [comment]
Gread job!
The _quick and dirty_ way it's easy as snap you fingers: 10 minutes of work ;-)
Hear you soon and let me know if you need further assistance...

**Comment by wizardgsz** [comment]
Pull request submitted: https://github.com/ExcelDataReader/ExcelDataReader/pull/114

**Comment by prosenba** [comment]
Hi Ian,
I have quick question, how do you implement in memory only? is there a key in the webconfig file or does it work by the method being called?

Thanks
Phillip

________________________________________

**Comment by Ian1971** [comment]
Sorry you confused my a bit with your question. Is this asking how you should implement your change?
