### ISSUE TITLE
No Tables In Dataset

### ISSUE THREAD

**Issue by j1mb0jay** [ExcelDataReader/ExcelDataReader#105]
Hi

The following code is resulting in no tables been being present within the dataset.

Any ideas why ?

 IExcelDataReader reader = ExcelReaderFactory.CreateBinaryReader(File.OpenRead(filename));
var dataset = reader.AsDataSet();
 reader.Close();

https://drive.google.com/file/d/0B2_2nVl1Kfx9bjdFSGxHaEZIUFU/view?usp=sharing

**Comment by Ian1971** [comment]
Not sure. Code looks ok, so must be something to do with the spreadsheet. Do you know where the xls came from?

**Comment by j1mb0jay** [comment]
I believe this Excel file was produced using https://github.com/PHPOffice/PHPExcel

It does open in Excel and also https://github.com/SheetJS/js-xlsx

Cheers

**Comment by Ian1971** [comment]
There might be some subtlety about the way phpexcel creates the files the exceldatareader doesn't handle. One way to check would be to re-save it in the excel, then try that file in exceldatareader.

**Comment by wizardgsz** [comment]
I just downloaded your Google Drive file but I got no errors loading it in exceldatareader.

**Comment by j1mb0jay** [comment]
There was no exception thrown when reading it in. It was just that the was no tables in the dataset. I did also notice that the worksheet name had the string terminate character after each letter /0

**Comment by Magneticdud** [comment]
I also have this problem from an xls file created by a program made in VisualFox.

If I open and save again the xls from Excel, it can find the tables.

The file is this: [filnza nome.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/188470/filnza.nome.zip)

**Comment by wizardgsz** [comment]
Did you load it using BiffView tool?
Error: Stream with name 'Workbook' not found.

**Comment by Magneticdud** [comment]
Yes, my file can't be opened with BiffView. But it work with any Excel and any Open/Libreoffice. Maybe it's Excel 95 file format?

**Comment by wizardgsz** [comment]
@Magneticdud , I think your file is BIFF5 i.e. Microsoft Excel version 5.0 (XL5) as it contains a Stream named Book (instead of Workbook). 

From specs chapter 2.3.2 Compound Document File (BIFF5-BIFF8)
Stream name: Book
Contents: BIFF5 Workbook Stream (➜2.3.3)

Anyhow, the Library should handle both Workbook and Book streams :)

```
XlsRootDirectory dir = new XlsRootDirectory(m_hdr);
XlsDirectoryEntry workbookEntry = dir.FindEntry(WORKBOOK) ?? dir.FindEntry(BOOK);
```

**Comment by wizardgsz** [comment]
Hello @Magneticdud, I further investigate about this issue during weekend.

As also **_Apache POI_** halts in error using "standard" reader:
```
The supplied spreadsheet seems to be Excel 5.0/7.0 (BIFF5) format.
POI only supports BIFF8 format (from Excel versions 97/2000/XP/2003)
```
I read its listings:
See HSSFWorkbook.java
```
// check for previous version of file format
try {
    directory.getEntry(OLD_WORKBOOK_DIR_ENTRY_NAME);
    throw new OldExcelFormatException("The supplied spreadsheet seems to be Excel 5.0/7.0 (BIFF5) format. "
    + "POI only supports BIFF8 format (from Excel versions 97/2000/XP/2003)");
} catch (FileNotFoundException e) {
    // fall through
}
```
See InternalWorkbook.java also
```
/**
* Name of older (pre-Excel 97) Workbook streams, which
*  aren't supported by HSSFWorkbook, only by
*  {@link OldExcelExtractor}
*/
public static final String OLD_WORKBOOK_DIR_ENTRY_NAME = "Book";
```

Summarizing, it seems your supplied file is XL5 format :)
I read **_Visual FoxPro_** can export data as XL8 also, maybe it helps...

Thanks and regards

**Comment by Magneticdud** [comment]
Maybe I can ask the other company to update their old program and export in XL8, but I don't think they're going to do that.

I "solved" the program by adding a big Libreoffice dependency (which I might replace with a portable version), convert to xlsx and then read it with ExcelReaderFactory.CreateOpenXmlReader()...  (in the end it just takes 1.5 seconds longer to load......)
`public void convert()
        {
            var proc1 = new ProcessStartInfo();
            string anyCommand = "--convert-to xlsx:\"Calc MS Excel 2007 XML\"  " + path;
            proc1.UseShellExecute = true;
            proc1.WorkingDirectory = path;
            proc1.FileName = @"C:\Program Files (x86)\LibreOffice 5\program\soffice.exe";
            proc1.Arguments = anyCommand;
            proc1.WindowStyle = ProcessWindowStyle.Hidden;
            Process.Start(proc1);
            var process = Process.Start(proc1);
            process.WaitForExit();
        }
`

**Comment by wizardgsz** [comment]
Understood.

For who installed **_Microsoft Excel_** instead of **_LibreOffice_**, "compatibility pack" (excelcnv.exe) could be an option:
```
"C:\Program Files\Microsoft Office\OfficeXX\excelcnv.exe" 
-oice "C:\temp\MyFile.xls" "C:\temp\MyFile.xlsx"
```
References:
[Free Convert for Excel files (.xls to .xlsx) ](http://justgeeks.blogspot.it/2014/08/free-convert-for-excel-files-xls-to-xlsx.html)
[Microsoft Excel Compatibility Pack](https://support.microsoft.com/en-us/kb/924074)
[Microsoft Excel Compatibility Pack - Windows Update](https://www.microsoft.com/en-US/download/details.aspx?id=3)

**Comment by andersnm** [comment]
@j1mb0jay The project link is down, do you (or anyone reading this) have an .xls from PHPExcel we can test? There's been some recent fixes for third party xls'es. See #211. 

@Magneticdud I tested "filnza nome.zip" a while ago. If i remember correctly it lacks the encoding record and ExcelDataReader throws a NullReferenceException on it. That's still a bug

**Comment by andersnm** [comment]
Just tested a couple xls generated by PHPExcel from the Google search `phpexcel filetype:xls`. The develop branch handles them fine, while the master branch had varying results. This should be ok to close.
