### ISSUE TITLE
Using Chart

### ISSUE THREAD

**Issue by mba645** [ExcelDataReader/ExcelDataReader#106]
Hi there !

I have an Excel file that contains several charts that I have to copy/paste in a Word document.

I am searching for 2 days without finding any hint on what I should look for.
Is there any way to get the charts from an Excel file using ExcelDataReader ?
Or is the solution just in front of my eyes ? 

Thanks for your time,

Regards,
Maxime

**Comment by Ian1971** [comment]
ExcelDataReader doesn't handle charts. Sorry!

**Comment by mba645** [comment]
No problem ! Thanks for answering so fast !
