### ISSUE TITLE
Not reading full content of formatted cells

### ISSUE THREAD

**Issue by srini2204** [ExcelDataReader/ExcelDataReader#108]
if the cell content is 

![image](https://cloud.githubusercontent.com/assets/11763331/13512857/6d4abd8e-e1f1-11e5-9b7d-7ac30e1cd030.png)

the code only reads the first line 

> Get an email account

 and omits the rest of the cell data. What can be done to fix this issue?

**Comment by wizardgsz** [comment]
Maybe you could provide a test case?

**Comment by wizardgsz** [comment]
Did you double check your client app also?
I have no problems reading "multi line" cells in XLS.

Most probably, in XLSX your data is stored as "shared string" having "bold characters" in first line, i.e.
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="1" uniqueCount="1"><si><r><t>Get an email accont</t></r><r><rPr><sz val="10"/><rFont val="Arial"/></rPr><t xml:space="preserve">
Why not get yourself a free email
account? It'a a great way to stay in 
touch with family and friends. You can 
share correspondence, pictures, and 
links to your favourite sites. And with a 
access to fast service over the nbn™
network and you could be up and
running in no time.*</t></r></si></sst>
```
You have to modify `void ReadSharedStrings(Stream xmlFileStream)` handling it.
Please let us know if removing text formatting you're able to read multi-line cells, I have no problems.
Do you need a patch for the library?

**Comment by srini2204** [comment]
@wizardgsz  Yup you are correct.
The changes to ReadSharedStrings fixed it.
Thank you very much

**Comment by wizardgsz** [comment]
I hope @Ian1971 will accept my commit ASAP then :+1:

**Comment by Ian1971** [comment]
cheers
