### ISSUE TITLE
Not reading last column

### ISSUE THREAD

**Issue by felipefujihara** [ExcelDataReader/ExcelDataReader#110]
Hi,

I'm using the following code to read a excel file, but it's not reading the last column:

`public static DataSet ReadExcel2003(Stream stream)
        {
            DataSet result = new DataSet();
            var tmpFile = Path.GetTempPath() + Guid.NewGuid().ToString() + ".xls";

            FileStream fileStream = File.Create(tmpFile, (int)stream.Length);

            byte[] bytesInStream = new byte[stream.Length];
            stream.Read(bytesInStream, 0, bytesInStream.Length);
            fileStream.Write(bytesInStream, 0, bytesInStream.Length);
            fileStream.Close();
            stream.Close();

			Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("pt-BR");
            using (IExcelDataReader excelReader = ExcelReaderFactory.CreateBinaryReader(File.Open(tmpFile, FileMode.Open, FileAccess.Read),ReadOption.Strict))
            {
                result = excelReader.AsDataSet();
            }

            File.Delete(tmpFile);

            return result;
        }
`

I attached the file I'm trying to read, the yellow cells are not being reading.

[6031b574-9284-4129-af7f-aa9fa5d50806.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/169571/6031b574-9284-4129-af7f-aa9fa5d50806.zip)

**Comment by wizardgsz** [comment]
No problems reading both:

result.Tables[0].Rows[1][5] as string
result.Tables[0].Rows[2][5] as double

**Comment by felipefujihara** [comment]
Thi is weird, I'm getting this:

-		result.Tables[0].Rows[1][5]	'result.Tables[0].Rows[1][5]' threw an exception of type 'System.IndexOutOfRangeException'	object {System.IndexOutOfRangeException}

my 'result' does not have index 5

**Comment by felipefujihara** [comment]
![image](https://cloud.githubusercontent.com/assets/12612147/13711769/1c660a6e-e79f-11e5-90a8-9f5b020d52fa.png)

**Comment by wizardgsz** [comment]
Sorry about it...

http://i67.tinypic.com/33p4zuu.png

**Comment by felipefujihara** [comment]
@wizardgsz  I'm not able to open your attachment

**Comment by felipefujihara** [comment]
Can you please share your code?   @wizardgsz

**Comment by felipefujihara** [comment]
I found the issue, the years are stored as text. Looks like thats the problem. @wizardgsz  Do you know how to handle it?
Thanks in advance

**Comment by wizardgsz** [comment]
Yeah, ur right but I'm using the latest trunk release (develop) for .Net 2.0 and not a "branched/modified" build.
I'm wondering why you had problems reading last column (IndexOutOfRangeException): did you run TestApp also?

**Comment by felipefujihara** [comment]
@wizardgsz Yes, I ran TestApp look:

![image](https://cloud.githubusercontent.com/assets/12612147/13777901/9d686298-ea91-11e5-9bd8-7752762d9686.png)
