### ISSUE TITLE
XLS without rows?

### ISSUE THREAD

**Issue by wizardgsz** [ExcelDataReader/ExcelDataReader#111]
I have an XLS structured as:

```
DIMENSIONS at 1295496
ROW at 1295516
LABELSST at 1295530
...
LABELSST at 1295530
LABELSST at 2745118
WINDOW2 at 2745140
EOF at 2745144
1637 at 2745173
```

It means no `Index`and starting with `Dimensions`(and it is not a problem) but without rows, only shared strings.
Has anyone idea how to load such a file?
The Library handles only the first row, even if Excel shows thousands of rows :)
That's because `moveToNextRecordNoIndex`halts founding `EOF at 2745144`.

To bypass the error you need to change `readWorkSheetGlobals`as follows:

```
            XlsBiffRecord trec = rec; // <<< init to previously read record
            XlsBiffDimensions dims = null;

            do
            {
                if (trec.ID == BIFFRECORDTYPE.DIMENSIONS)
                {
                    dims = (XlsBiffDimensions)trec;
                    break;
                }
                trec = m_stream.Read(); // <<< first check, then read next record

            } while (trec != null && trec.ID != BIFFRECORDTYPE.ROW);

```

I'm wonder how read this binary Excel file...
For privacy reason I'm going to modify binary data and I'll upload a test case ASAP.

Thanks for helping me.

**Comment by appel1** [comment]
We've come across a variation of this. No ROW records at all, only LABELSST and NUMBER. 

```DIMENSIONS
LABELSST 
LABELSST```

**Comment by wizardgsz** [comment]
Unfortunately I had no chance to find an efficient solution. You?

**Comment by appel1** [comment]
I've made a small attempt at implementing support for Excel files without ROW records. In your case, is it that there are no ROW records or only one when there are in fact more than one rows?

**Comment by wizardgsz** [comment]
I have two files generated by the same "procedure" by IT supplier, I'll give it a try...
Thanks a lot!

**Comment by wizardgsz** [comment]
Just tested: unfortunately it does not handle my files.
Still loading first ROW only...

**Comment by appel1** [comment]
Ok, a bit difficult without a sample to test with. :)

**Comment by andersnm** [comment]
What is the status of this? @wizardgsz  How did you obtain the initial xls structure? Through ExcelDataReader or some other tool?

**Comment by wizardgsz** [comment]
Yes, I used the Library to dump the data but also [BiffView Tool](http://b2xtranslator.sourceforge.net/download.html#biffviewer)
:)

![](http://b2xtranslator.sourceforge.net/BiffView02.png)

**Comment by appel1** [comment]
The current code in develop doesn't use ROW records so I think we can close this issue.

**Comment by andersnm** [comment]
@wizardgsz I'm closing, but please reopen if it still fails with latest. It would be really useful with an anonymized xls to test with.

For ease, the latest prealpha nugets are here: https://ci.appveyor.com/project/andersnm/exceldatareader/build/3.0.0.40/artifacts

**Comment by wizardgsz** [comment]
Where can I find an example to read Excel using new interface? I need a DataSet to test if new implementation works fine or fail.

**Comment by andersnm** [comment]
Do you have VS2017 to build the current develop branch? The "TestApp" is built with it and easy for random testing.

Otherwise, to use the Nugets above in an earlier VS, you'd have to configure your solution with a Nuget.config. See f.ex https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file

The API and sample code for using ExcelDataReader is mostly unchanged. The biggest change so far is to change from `using Excel;` to `using ExcelDataReader;` in existing code.

**Comment by wizardgsz** [comment]
Unfortunately no administrative user on corporate laptop (and I cannot install new software).

**Comment by appel1** [comment]
@wizardgsz Have you been able to test further with the 3.0 release to verify that this has been fixed?

**Comment by andersnm** [comment]
Without a repro there is nothing to do here.
