### ISSUE TITLE
The last row is not read in XLS file

### ISSUE THREAD

**Issue by Solnake** [ExcelDataReader/ExcelDataReader#113]
XLS file contains 5 rows - 1 header and 4 data. But when try to read the file - the last row is not read. 
Maybe there are some issue in the file because after resave - all rows can be read.
But if uncomment next code inside method moveToNextRecordNoIndex() in class Excel.ExcelBinaryReader:
```
//if (!m_canRead && m_depth > 0) m_canRead = true;

			//if (!m_canRead && m_dbCellAddrsIndex < (m_dbCellAddrs.Length - 1))
			//{
			//	m_dbCellAddrsIndex++;
			//	m_cellOffset = findFirstDataCellOffset((int)m_dbCellAddrs[m_dbCellAddrsIndex]);

			//	m_canRead = readWorkSheetRow();
			//}
```

Everything works properly and original file can be fully read.

[FICHIER_MODELE.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/185703/FICHIER_MODELE.zip)

**Comment by wizardgsz** [comment]
Really strange...
Loaded your file using latest trunk/development build and found no problems.
Isn't it original BIFF rather then the file after "resaving" in Excel?
Are you using older code?

http://it.tinypic.com/view.php?pic=217ces&s=9#.VvL3rXpM4pk

**Comment by Solnake** [comment]
Yes, you are right. everything is correct when use .AsDataSet(); method. 
But in our application we read row by row with method .Read(). 
I think this is an issue in our usage, not in library.
