### ISSUE TITLE
Is there a way to have a NuGet package without dependency on SharpZipLib?

### ISSUE THREAD

**Issue by harrychou** [ExcelDataReader/ExcelDataReader#116]
The company will not OK with using GPL libraries, and also the company use only official NuGet repository. I know the SharpZipLib is not required for .net 4.5, but the NuGet package still has a reference of SharpZipLib. Thank you.

**Comment by Ian1971** [comment]
I think you'd have to build the binary and include that directly. Or need some one to volunteer to put together the nuget package. No time here.

**Comment by rmaziarka** [comment]
How to create the nuget package? I could help because for me it's really important matter to remove connection with SharpZipLib.

**Comment by wizardgsz** [comment]
Maybe you can find something useful in official NuGet documentation:
[Creating and Publishing a Package](http://docs.nuget.org/create/creating-and-publishing-a-package)
Kind regards

**Comment by jtu100** [comment]
Since .NET 4.5 there is a ZipFile class in System.IO.Compression.FileSystem namespace. If there were to be a .NET 4.5+ release of ExcelDataReader then perhaps the SharpZipLib dependency could be removed?
