### ISSUE TITLE
How I can import the tables into a dataSet?

### ISSUE THREAD

**Issue by kylonx** [ExcelDataReader/ExcelDataReader#118]
Hey guys.
I'm currently searching a tutorial or a way to import the tables from the Excel-File into my dataSet.

```
        public Main()
        {
            InitializeComponent();
            FileStream stream = File.Open(@"C:\Users\John\Desktop\tabelle.xlsx", FileMode.Open, FileAccess.Read);
            IExcelDataReader excelReader = ExcelReaderFactory.CreateOpenXmlReader(stream);
            excelReader.IsFirstRowAsColumnNames = true;

            while(excelReader.Read())
            {
                dataSet1 = excelReader.AsDataSet();
            }

            excelReader.Close();
        }
```

**Comment by wizardgsz** [comment]
Maybe it helps:

http://www.dotnetperls.com/dataset

**Comment by kylonx** [comment]
but is my code right?

**Comment by wizardgsz** [comment]
Sorry? Your code does not compile.
See homepage sample code and please note: **Choose one of either 3, 4, or 5**
Not a mix of them ;)

**Comment by oxsmos** [comment]
try this...

`      using (var fileStream = File.Open(file, FileMode.Open, FileAccess.Read))
      {
        dataSet1 = ExcelReaderFactory.CreateBinaryReader(fileStream).AsDataSet();
      }
`
