### ISSUE TITLE
Use first non-empty row with IsFirstRowAsColumnNames (add option ?)

### ISSUE THREAD

**Issue by killergege** [ExcelDataReader/ExcelDataReader#119]
Sometimes I have to parse Excel files that contain an array, but the user added an empty row before the header row, which breaks everything.
It would be nice if ExcelDataReader could just ignore the empty rows when IsFirstRowAsColumnNames is set to true and use the first non-empty row.

As it would change the behavior of the current release, I guess an option could be added.

**Comment by killergege** [comment]
Is it closed because fixed/implemented, or too old ? :)

**Comment by wizardgsz** [comment]
Is seems a "custom" implementation you would have in "reader" classes branching from dev build.
