### ISSUE TITLE
Value contains phonetic string data for xls / xlsm

### ISSUE THREAD

**Issue by ryukbk** [ExcelDataReader/ExcelDataReader#12]
Asian strings such as Japanese can contain phonetic string data (furigana/yomigana), but ExcelDataReader just includes a phonetic string in a string value and doesn't separate them. The expected result is when retrieving a string value it doesn't contain phonetic string data as it's just there to show how to read it.
It seems for xls (BinaryReader) there is an uncommented code,
https://exceldatareader.codeplex.com/discussions/50930
but for xlsm (XmlReader) there's nothing.

**Comment by wizardgsz** [comment]
Actual implementation does not support "multi line" cells.

Just revert changes and add a boolean checking "rPh" tags (i.e. phonetic hints) in ReadSharedStrings:

```
...
}
else if (reader.NodeType == XmlNodeType.Element && reader.LocalName == N_t)
{
	// Skip phonetic string data.
	if (!bSkipPhonetic)
	{
		// Append to the string item.
		sStringItem += reader.ReadElementContentAsString();
	}
}
else if (reader.LocalName == "rPh")
{
	// Phonetic items represents pronunciation hints for some East Asian languages.
	// In the file 'xl/sharedStrings.xml', the phonetic properties appear like:
	// <si>
	//  <t>(a japanese text in KANJI)</t>
	//  <rPh sb="0" eb="1">
	//      <t>(its pronounciation in KATAKANA)</t>
	//  </rPh>
	// </si>
	if (reader.NodeType == XmlNodeType.Element) bSkipPhonetic = true;
	else if (reader.NodeType == XmlNodeType.EndElement) bSkipPhonetic = false;
}
```

**Comment by aadil79** [comment]
We had a similar issue and had to tweak the above proposed solution i.e. instead of 
`else if (reader.LocalName == "rPh")`

it should be 
`if (reader.LocalName == "rPh")`

I was able to run the 4.5 Excel solution(master branch) with my change without any additional failing tests(two test failed for me) Issue_11545 and Issue_11639.The test i added for the use case above passes after i made the fix.
Let me know if this is repository is still taking pull request and i would be glad to make one.

**Comment by Ian1971** [comment]
We are taking pull requests, the problem is I have zero time to test and merge them. I'll happily give someone else rights to do it.

**Comment by wizardgsz** [comment]
May I help?

**Comment by Ian1971** [comment]
Thanks, that would be great. You should get an invite from github.

**Comment by aadil79** [comment]
Hello @wizardgsz and @Ian1971 
I have created a pull request with my changes now. https://github.com/ExcelDataReader/ExcelDataReader/pull/120
