### ISSUE TITLE
ExcelDataReader fails when xls files first work sheet global is XlsBiffDimensions

### ISSUE THREAD

**Issue by igorcrevar** [ExcelDataReader/ExcelDataReader#121]
after that `DataSet result = excelReader.AsDataSet();`throws final exception

"Object reference not set to an instance of an object."
"   at Excel.ExcelBinaryReader.readWorkSheetGlobals(XlsWorksheet sheet, XlsBiffIndex& idx, XlsBiffRow& row) in c:\development\ExcelDataReader\Excel\ExcelBinaryReader.cs:line 368\r\n   at Excel.ExcelBinaryReader.readWholeWorkSheet(XlsWorksheet sheet) in c:\development\ExcelDataReader\Excel\ExcelBinaryReader.cs:line 429\r\n   at Excel.ExcelBinaryReader.AsDataSet(Boolean convertOADateTime) in c:\development\ExcelDataReader\Excel\ExcelBinaryReader.cs:line 937\r\n   at Excel.ExcelBinaryReader.AsDataSet() in c:\development\ExcelDataReader\Excel\ExcelBinaryReader.cs:line 922\r\n   at 

Code is simple

```
  using (FileStream stream = File.Open(inputFilePath, FileMode.Open, FileAccess.Read))
            using (IExcelDataReader excelReader = ExcelReaderFactory.CreateBinaryReader(stream))
            {
                DataSet result = excelReader.AsDataSet();
```

This is only happened for xls generated with ExcelLibrary library. But. those xls can be read by ms excel or google docs so I suppose ExcelDataReader should read those files also. 
Excel reader is installed as usual with `Install-Package ExcelDataReader`
I can provide you with some sample xls if needed

**Comment by igorcrevar** [comment]
Sorry, I didnt open code and see that for Binary reader
```
public int RecordsAffected
		{
			get { throw new NotSupportedException(); }
		}
```

so forget about that. However, problem still exists. I found that sometimes (xls generated with ExcelLibrary at least) in private `bool readWorkSheetGlobals(XlsWorksheet sheet, out XlsBiffIndex idx, out XlsBiffRow row)`, first record which is read is `XlsBiffDimensions` and not `XlsBiffIndex `or `XlsBiffUncalced`. I made simple hack which deals with this problem. If you think this is relevant I can open pull request with my solution

**Comment by ventoshe** [comment]
Igor, 

Can you please share your hack? I'm having the same issue.

Thanks

**Comment by ekincaglar** [comment]
Hi @igorcrevar , could you post your fix here if it's simple? That would save me a lot of time trying to understand the code and debug.

**Comment by igorcrevar** [comment]
Hi guys, I do not have that code anymore. I suppose I delete my local git copy :( Sorry

**Comment by andersnm** [comment]
Closing per #212. The sample output from ExcelLibrary exposed a now-fixed bug in how ExcelDataReader deals with the low level "mini streams". Thanks @igorcrevar for the pointer
