### ISSUE TITLE
The LogManager is not thread safe

### ISSUE THREAD

**Issue by thriolsson** [ExcelDataReader/ExcelDataReader#122]
The static class LogManager is not thread safe. It uses a Dictionary, but it is accessed outside the lock.
The Dictionary class is not tread safe. It is not safe to write **or read** from Dictionary class in parallell.
"Double checking" makes the odds better, but there is still an issue!

```
public static ILog Log(string objectName)
{
    ILog result = null;

    if (_dictionary.ContainsKey(objectName))
        result = _dictionary[objectName];

    if (result == null)
    {
        lock (_sync)
        {
                if (_dictionary.ContainsKey(objectName))
                {
                        result = _dictionary[objectName];
                }
                else
                {
                        result = Excel.Log.Log.GetLoggerFor(objectName);
                      _dictionary.Add(objectName, result);
                }

               result = _dictionary[objectName];
        }
    }

```

**Comment by wizardgsz** [comment]
It would be great if you can further investigate... thanks and regards!

[What's the best way of implementing a thread-safe Dictionary?](http://stackoverflow.com/questions/157933/whats-the-best-way-of-implementing-a-thread-safe-dictionary)

**Comment by Ian1971** [comment]
In what way is it not thread-safe to read from a dictionary? (other than enumeration)

**Comment by Ian1971** [comment]
It would probably be better to use ConcurrentDictionary in any case. But I think that does no kind of read locking either.

**Comment by thriolsson** [comment]
Lookups are not thread safe if the dictionary is changed from another thread at the same time, which can happen in the LogManager implementation.
I think that in this case the best option is to simply do all the dictionary operation inside the lock (and stop the "double checking"). The ConcurrentDictionary is thread safe, but also adds some overhead.
If you do not need thread safe enumeration and have just one or two places where you interact with the collection, my view is that it is faster to just use an ordinary lock that covers both writes and reads.

**Comment by thriolsson** [comment]
In general, none of the commonly used collections in .NET Framework are thread safe for concurrent reading and writing except those in the System.Collections.Concurrent namespace and the simple arrays (which do not supports add or remove).

**Comment by Ian1971** [comment]
I wonder if in reality it would have little impact. 

ContainsKey would either find or not find a key. As this dictionary is only ever going to add items I think the risk is that it would not find a key that existed because the internal size had just increased. In that situation it would go ahead and create a new logger (redundantly, but not the end of the world).

This whole LogManager.Log(this) pattern is actually pretty bad for performance anyway. So I think a better logging framework neutral approach should be found. Perhaps switch to Common.Logging ?

**Comment by thriolsson** [comment]
The thing is that it crash and not just fail to find a key of the dictionary is modified concurrently.

Internally, the dictionary is a hash table that consists of a linked list of buckets. When finding an item, this list is traversed. The list of buckets can be changed when the dictionary is changed and another thread that is traversing the list at the same time might go down an invalid path of links.

Besides, the code in LogManager is inefficient since it traverses the list two times (and sometimes four). First it checks if the item exists in the dictionary, then, if it exists, it traverses it again in order to find it. 
It would be much better to use TryGetValue.
There are not that many items in the dictionary and not that many things are written to the log, so lookups will be fast and there will rarely be any contention.

I bet that an implementation like below would be as fast or even faster. And it would be 100% thread safe. (I guess that if you measured the performance you would find that the hot spot would be the line "string objectName = typeof(T).FullName;" in this class.)

```
        public static ILog Log(string objectName)
        {
            lock (_sync)
            {
                ILog result;
                if (_dictionary.TryGetValue(objectName, out result))
                    return result;

                result = Excel.Log.Log.GetLoggerFor(objectName);
                _dictionary.Add(objectName, result);
                return result;
            }

        }

```

**Comment by Ian1971** [comment]
Makes sense. can you submit a pull request?

**Comment by thriolsson** [comment]
Sure. See https://github.com/ExcelDataReader/ExcelDataReader/pull/123

**Comment by thriolsson** [comment]
Just realized that there is a "Portable.Log.LogManager" too. I will make another Pull request with the same changes to that class.

**Comment by Ian1971** [comment]
thanks

**Comment by thriolsson** [comment]
Done. https://github.com/ExcelDataReader/ExcelDataReader/pull/124
