### ISSUE TITLE
Potential threading issue in XlsBiffStream

### ISSUE THREAD

**Issue by thriolsson** [ExcelDataReader/ExcelDataReader#125]
Since I fixed some other locking issues in LogManager, I also took a look at more places where locking is used. The locking in XlsBiffStream looks a bit strange. The Seek and Read methods use a lock, but not the ReadAt method. The reason why this is a problem in the ReadAt method is that it also uses the m_offset field:

```
if (m_offset + rec.Size > m_size)
    return null;
```

I find this piece of code a bit strange. Perhaps this is not an issue with locking, but rather that it should use offset instead of m_offset? Perhaps it should rather be:

```
if (offset + rec.Size > m_size)
    return null;
```

Another, minor, issue is that you should avoid locking on "this" and use a "private object m_lock" instead. See for instance here for a motivation: http://stackoverflow.com/questions/251391/why-is-lockthis-bad

Another, even more minor, issue in this class is mixed naming conventions (sometimes for fields m_ and sometimes not).

**Comment by Ian1971** [comment]
Yeah, I think there have been many fingers in the pie. Personally I don't like m_ - mostly because it looks ugly. The original authors are long gone though so I'd be hesitant to change anything in that core biff stuff, unless it relates to some real life issue.

**Comment by andersnm** [comment]
The code in question has changed a lot in develop, f.ex ReadAt() no longer exists and the locking is mostly removed. Should be OK to close.
