### ISSUE TITLE
Incorrectly reads some symbols from MS Excel

### ISSUE THREAD

**Issue by AlexanderHryk** [ExcelDataReader/ExcelDataReader#130]
Reading some symbols from excel is not correctly worked. For example, trying to read string "Fel vid l**ä**sning" from cell is interpreted as "Fel vid l**д**sning". Is there any way to solve this?

**Comment by wizardgsz** [comment]
It's always difficult suggest a solution without a test-case, anyhow: did you verify your application encoding?
Verify also if it's just a "visualization" problem of your Windows Forms control.

**Comment by AlexanderHryk** [comment]
the values stored correctly inside my app in string variables. The incorrect value returns from DataSet.

**Comment by wizardgsz** [comment]
Can you share a test-case or should I rather close the incident?
Thanks a lot
