### ISSUE TITLE
Sheets not being read as tables when IsFirstRowAsColumnNames is true.

### ISSUE THREAD

**Issue by ahawes-clarity** [ExcelDataReader/ExcelDataReader#131]
Noticing very odd behavior.

I have an .xlsx file with three sheets.

If I run the code below I get the correct Tables in the resulting DataSet. However, the Columns in each table had generic names (Column 1, Column 2, etc.). So, I looked back at the example code and sure enough I had not set IsFirstRowAsColumnNames = true on the reader. So I add that in (commented out below). Now when the code runs I get 1 Table with the name of the second sheet.

`var excelReader = ExcelReaderFactory.CreateOpenXmlReader(_httpFile.InputStream);
//excelReader.IsFirstRowAsColumnNames = true; //Extra comment to get wrapping correct>>>>>>
mptDataSet = excelReader.AsDataSet();`

__UPDATE:__ It seems the problem is that not all the sheets have table style data. All I really needed was the first sheet. I knew that any data in the other sheets would not be used. However, it seems that the data in the other sheets caused issues with the file parsing so I ended up with incorrect results.

Is there a way to specify which sheet(s) to read?

**Comment by wizardgsz** [comment]
Could you kindly share a test file to further investigate?
Does the file contain sensitive information? 
Kind regards and thanks

**Comment by ahawes-clarity** [comment]
Thanks for the reply.

Here is the file. As you can see it has a tab called “Data Definitions”. That tab contains information that is not needed for the purposes for which I am reading the file. It is extraneous data that just happens to also be in the file. Ideally I would be able to specify only the tabs I wanted to read into the DataTable. However, it would also be acceptable if the data was in the table as I can just ignore it. But not being able to use the file because it happens to have other non-table like data is a problem.

I am telling the client I am working with that we need to only use a file with the first tab content in it. This will work for this situation but in other scenarios it may be a limitation.

Thanks again.

Andrew

**Comment by wizardgsz** [comment]
No attachment :)

**Comment by ahawes-clarity** [comment]
Trying again.

**Comment by wizardgsz** [comment]
Most probably you have to attach it using the web browser. 
Maybe files sent replying via email are "discarded" by GitHub mail server. Don't know.

**Comment by ahawes-clarity** [comment]
[Master Product Template.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/373795/Master.Product.Template.xlsx)

**Comment by wizardgsz** [comment]
Already verified the proposed solution?

If you need to "keep" sheets without rows (except for columns header), you can modify ExcelOpenXmlReader.cs.
Take a look at `AsDataset(bool)` and comment out the test:

```
if (table.Rows.Count > 0)
    dataset.Tables.Add(table);
table.EndLoadData();
```
Assuming you set `IsFirstRowAsColumnNames = true` and without modifying the code, your DataSet will contains only _"Master Product Template"_ sheet

Both _Data Definitions, Sheet3 and Sheet2_ will be discarded as they don't have rows (remember the above test `if (table.Rows.Count > 0)`?).

**Comment by JoeHo42** [comment]
I'm sorry but the proposed solution (changing the source code) does not seem like a good idea to me.

I'd rather see a new property/flag in IExcelDataReader (e.g. IgnoreEmptySheets, default value: true) and then handle the problem dynamically depending on the value of the property.

Requesting to re-open this issue ...!
[Yes, the current default behaviour leads to problems in my application too ...]

**Comment by wizardgsz** [comment]
Ok, thanks a lot for your feedback: we are looking forward to your new implementation then.
With regards 👍
