### ISSUE TITLE
Use Shared Project instead to be able to create single assembly

### ISSUE THREAD

**Issue by appel1** [ExcelDataReader/ExcelDataReader#133]
Did a rough sketch of this here: https://github.com/appel1/ExcelDataReader/tree/projectlayout

Didn't create a pull request from it since it contains other changes, fixes and code cleanup. 

If it is something this project is interested in I can probably create a new branch and pull request with just the shared project changes. Or is the VS2015 requirement a big no-no?

**Comment by wizardgsz** [comment]
Hi @appel1, 
do you think recent [branch](http://github.com/andersnm/ExcelDataReader/tree/retool) meets the requirements of yours?
Unfortunately I can't install VS 2015, could you kindly double check with @andersnm his solution?
Thanks a lot

**Comment by appel1** [comment]
@wizardgsz Yes, looks good to me. 

(There seems to be a build dependency issue so after the first checkout you have to build twice to get the tests to compile)

**Comment by wizardgsz** [comment]
@andersnm just "fixed" it in http://github.com/ExcelDataReader/ExcelDataReader/commit/eb5c760
