### ISSUE TITLE
String read has Chinese phonetic

### ISSUE THREAD

**Issue by xxpniu** [ExcelDataReader/ExcelDataReader#134]
When i try read an excel file(.xlsx). In excel it look like "目录" but i use this code will read like "目录 mu lu".

**Comment by wizardgsz** [comment]
Have you got a test-case to understand what you "expected" to read and what you got?
Did you run the "develop" release also?
Thank You.

**Comment by xxpniu** [comment]
Yes, it the release version. i download it on codeplex.com. And I also try build the source code as release the issue is still have.

**Comment by wizardgsz** [comment]
Try the "develop" branch then, it fixed some issues about phonetic strings.

**Comment by xxpniu** [comment]
Yes I have this type xlsx file. But how can I shard you?

**Comment by wizardgsz** [comment]
Do not include any sensitive information to your files please.

Below you can read: "Attach files by dragging & dropping or selecting them" :-)
Already read the GitHub FAQ and help pages?
Here: [File attachments on issues and pull requests](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/)

Hope it helps!

**Comment by xxpniu** [comment]
Thank you! this FAQ  very helpful for me! And this is my file!
[characters.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/371108/characters.xlsx)

**Comment by wizardgsz** [comment]
Thanks @xxpniu
Double check the following images please.

![characterdata](https://cloud.githubusercontent.com/assets/8364153/16946573/8b94acc6-4daa-11e6-84e6-97ac8923ff8d.png)
![characterdatamagic](https://cloud.githubusercontent.com/assets/8364153/16946580/8ed47aba-4daa-11e6-9ec6-dd4cf6f13b5f.png)

**Comment by xxpniu** [comment]
thank you! the last submit had fixed the bug. My project now work well!
