### ISSUE TITLE
GetOrdinal method not supported exception

### ISSUE THREAD

**Issue by cemremengu** [ExcelDataReader/ExcelDataReader#137]
I am trying to use an `IDataReader` with an `IExcelDataReader` instance to read an `xlsx` file. 

However, I am getting a `method not supported exception` for the `GetOrdinal` method. Is there a work around for this ?

**Comment by wizardgsz** [comment]
Unfortunately, if you really need `int IDataReader.GetOrdinal(string)`, you have to write your own implementation.
Remember that the Library stores "original" column names as `Column.Caption` property; to avoid "duplicates", the column name has "_%d" suffix: double check Excel/Core/Helpers.cs `AddColumnHandleDuplicate` to better understand.
Last but not least: "default" column name for "unnamed" columns is "Column%d" but you can verify it in any reader implementation (e.g. `private const string COLUMN = "Column";`). 

ps. Maybe it helps: [Set Column.Caption to original read columnName (Dont hand duplcate for Caption) #103](https://github.com/ExcelDataReader/ExcelDataReader/pull/103)

**Comment by cemremengu** [comment]
Thanks @wizardgsz . Is there any reason why it's not implemented ? If there nothing special, I can go for a PR once I have a solution

**Comment by wizardgsz** [comment]
Discussion about `GetOrdinal` implementation:

[DbDataReadet.GetOrdinal() - duplicate column name | PC Review](http://www.pcreview.co.uk/threads/dbdatareadet-getordinal-duplicate-column-name.2878122/)

**Comment by wizardgsz** [comment]
Hello @cemremengu, are you planning to work on this "issue"?

**Comment by cemremengu** [comment]
I definitely would like to @wizardgsz when I have some time. Very busy with work at the moment. Is there a deadline ?

**Comment by andersnm** [comment]
I don't think this makes sense anymore after the column name handling was moved into the DataSet package with far more flexibility than before. The readers no longer have sufficient knowledge about the underlying data to reasonably implement GetName(), GetOrdinal() & co.
