### ISSUE TITLE
Not a legal Ole Aut date

### ISSUE THREAD

**Issue by Ian1971** [ExcelDataReader/ExcelDataReader#14]
https://exceldatareader.codeplex.com/discussions/562088

```
 public static object ConvertFromOATime(double value)
    {
        if ((value >= 0.0) && (value < 60.0))
        {
            value++;
        }
        //if (date1904)
        //{
        //    Value += 1462.0;
        //}

      // added to fix out of range problem, sdh, 20140826
      if (value < 657435.0)
      {
        value = 657435.0;
      }
      else if (value > 2958465.99999999)
      {
        value = 2958465.99999999;
      }
        return DateTime.FromOADate(value);
    }
```

**Comment by appel1** [comment]
Another solution would be to make the xlsx reader consistent with the xls reader and support the convertOADate parameter. I don't think it is a good idea to silently throw data away and replace it with 0. 

We could also delay the exception until GetValue and include the raw data in the exception to let the user of the reader decide what to do or be more explicit about it and let the user specify an error handler callback.

**Comment by appel1** [comment]
This would be better handled by the solution proposed in #215 instead of #79.
