### ISSUE TITLE
Not usable with XSLX

### ISSUE THREAD

**Issue by JohnRohner** [ExcelDataReader/ExcelDataReader#140]
Web site.  XSLX import.  AppData write error.

This is because of the need to temporary unzip the file.

I am using this product for XLS, but had to go with EEPlus for XSLX.

No reason not to have an in-memory unzip option.

This program is becoming obsolete and needs a boost.

**Comment by wizardgsz** [comment]
I see at least four options for you:

1. use my implementation https://github.com/ExcelDataReader/ExcelDataReader/pull/114
2. use @prosenba one https://github.com/ExcelDataReader/ExcelDataReader/issues/104
3. use newest .NET Core package by @cemremengu https://github.com/ExcelDataReader/ExcelDataReader/issues/129
4. propose your own solution, maybe the best!

Kind regards
