### ISSUE TITLE
What is the purpose of each of the projects?

### ISSUE THREAD

**Issue by Joev-** [ExcelDataReader/ExcelDataReader#141]
Hi,

I'm trying to make some local changes to this project and include it as a project reference in an existing project. I'd roughly expect to include just one or two projects to achieve my desired results, however I am having some difficulty understanding exactly which projects I would need.

There are Excel.csproj and Excel4.5.csproj in both the Excel and Excel.4.5, what are the differences between these four project files?

Do you have any recommendations for how I'd be able to include this project easily as a project reference?

**Comment by wizardgsz** [comment]
Most probably You can just add reference to .NET 2.0 project: Excel.csproj
Anyhow, right clicking on each, you read the ["Project Dependecies..."](http://dailydotnettips.com/2015/11/25/how-to-identify-the-project-dependencies-in-visual-studio/).

To recap (more details [here](https://github.com/ExcelDataReader/ExcelDataReader/issues/49)), the following projects use Portable libraries and Framework .NET 4.5:
- ExcelDataReader.iOS
- ExcelDataReader.Silverlight
- ExcelDataReader.Portable
- ExcelDataReader.Android
- ExcelDataReader.Desktop
- Excel.4.5

If you're using latest VS 2015, please take a look also at:
- [Use Shared Project instead to be able to create single assembly #133](https://github.com/ExcelDataReader/ExcelDataReader/issues/133)
- [.NET Core Support #129](https://github.com/ExcelDataReader/ExcelDataReader/issues/129)

Have a nice day and welcome!

**Comment by Joev-** [comment]
Hi @wizardgsz 

Those are some useful links, I'm still unsure what the difference between the following files are however:

- Excel/Excel.csproj
- Excel/Excel.4.5.csproj
- Excel.4.5/Excel.csproj
- Excel.4.5/Excel.4.5.csproj

I am looking at the develop branch here, one of those other discussions made me realise how much that branch differs from master however. 

Adding the .NET 2.0 project to my own solution results in it not being able to locate any of the standard System references. Removing and re-adding them does not provide a solution. I felt like I was going around in circles trying to solve that problem. 

Adding the Excel\Excel.4.5.csproj project to my own solution requires me to add the ExcelDataReader.Desktop and .Portable projects too, however the .Portable project also fails to resolve references, however I have a feeling however that this is due to the fact that the nuget packages folder is two levels up rather than one, due to me including this project as a git submodule.

**Comment by wizardgsz** [comment]
Just reading the solution file (.SLN):

**Used projects**
- "Excel", "Excel\Excel.csproj", "{4CB0690E-3E7A-497C-9116-D52024F63195}"
- "Excel.4.5", "Excel.4.5\Excel.4.5.csproj", "{D1905BBD-5F3B-4112-90BD-2D97C8B539C9}"

**Not used :)**
- Excel/Excel.4.5.csproj
- Excel.4.5/Excel.csproj

**Comment by Joev-** [comment]
I thought as much, but though I'd check. Thanks :)
