### ISSUE TITLE
Read all columns if dimension element is present but invalid

### ISSUE THREAD

**Issue by appel1** [ExcelDataReader/ExcelDataReader#142]
Excel can open .xlsx such files so it'd be useful if ExcelDataReader could as well. 

For example the file here https://sgi.sgmarkets.com/rest_en/excel?ticker=SOLEXPD has a dimension element but its value is A1 when there in fact are four columns of data.

**Comment by wizardgsz** [comment]
FYI

[Bug 53611 - Incorret dimension set in created workbook sheet xml file](http://bz.apache.org/bugzilla/show_bug.cgi?id=53611)

**Comment by andersnm** [comment]
It appears a 100% fix involves parsing the ref attribute according to its formal grammar and have additional logic reject valid parse trees refering to single columns/rows or relative cells (and dont set sheet.Dimension in those cases).

Reference for the dimension element:
https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.sheetdimension(v=office.14).aspx

Documentation for the dimension's ref attribute:

"The row and column bounds of all cells in this worksheet. Corresponds to the range that would contain all c elements written under sheetData. Does not support whole column or whole row reference notation. The possible values for this attribute are defined by the ST_Ref simple type (§18.18.62)."

Reference for the "ST_Ref" simple type: 
https://msdn.microsoft.com/en-us/library/dd952022(v=office.12).aspx

It says ST_Ref has the following grammar:

	(A1-cell [":" A1-cell])  / ref-constant

And links to the full grammar here:
https://msdn.microsoft.com/en-us/library/dd906358(v=office.12).aspx

Extracting the relevant grammar rules for "A1-cell" and "ref-constant":

	A1-cell = A1-column A1-row
	A1-area = A1-cell ":" A1-cell
	A1-column = A1-relative-column / A1-absolute-column
	A1-relative-column = 1*2letter / A-to-W 2letter / "X" A-to-E letter / "XF" A-to-D
	A-to-D = %x41-44 / %x61-64
	A-to-E = A-to-D / "E"
	A-to-W = %x41-57 / %x61-77
	letter = %x41-5A / %x61-7A
	A1-absolute-column = "$" A1-relative-column
	A1-row = A1-relative-row / A1-absolute-row
	A1-relative-row = row-digit-sequence
	row-digit-sequence = nonzero-decimal-digit *5decimal-digit /  "10" %x30-33 4decimal-digit / "104" %x30-37 3decimal-digit / "1048" %x30-34 2decimal-digit / "10485" %x30-36 decimal-digit / "104857" %x30-36
	A1-absolute-row = "$" A1-relative-row
	...
	decimal-digit=  %x30-39
	nonzero-decimal-digit = %x31-39
	...
	ref-constant = "#REF!"

**Comment by appel1** [comment]
Should be fixed as part of https://github.com/ExcelDataReader/ExcelDataReader/pull/139.
