### ISSUE TITLE
Security Issue - Entries with relative names can deliver files outside of temp directory

### ISSUE THREAD

**Issue by Tobesat** [ExcelDataReader/ExcelDataReader#143]
XSLX files that have zip entries with relative names (e.g. ../../system32/<filename>.exe) can cause files to be created in places they shouldn't be.

ZipWorker shouldn't generate temp file names using path 'math' based on the zip entry names.  Perhaps using a dictionary to keep track of entry name to temp files would work and not pose a security risk.

**Comment by wizardgsz** [comment]
Any test case?

**Comment by Tobesat** [comment]
The attached XLSX file will create ../temp/bcdefghij.txt relative to where the temp files are written.

[Test1.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/420217/Test1.xlsx)

**Comment by wizardgsz** [comment]
Interesting thoughts... however I can't load it 
- using Excel 2003 and "compatibility pack" the file cannot be converted
- Excel 2007, instead, alerts for "illegal data"
- using my develop branch, I can notice an invalid attribute r='B2'

Unterstood the security issue anyhow. Thanks.

**Comment by andersnm** [comment]
I think this can be closed now as there should be no more concerns with temp files onwards per #139.
