### ISSUE TITLE
Reading wrongly formatted cells

### ISSUE THREAD

**Issue by Ian1971** [ExcelDataReader/ExcelDataReader#15]
From https://exceldatareader.codeplex.com/discussions/560931
"
Hello everyone! I have been reading a lot around my issue but I am still struggling to get an idea how to go around it. Any help would be appreciated! 

I am reading an Excel spreadsheet that can contain wrongly formatted data, e.g. a cell could be formatted as a date but in Excel appears normally- as a string as it contains a string. When I read it with the Excel data reader it appears as 31/12/1899. How can I just get the value of the string as displayed in Excel? 
"

**Comment by mpbill** [comment]
I was having the same issue because I am dealing with a spreadsheet which has large product numbers in one of the columns, my solution was to catch and re-throw the exception in the Helper.cs file:
```csharp
        public static object ConvertFromOATime(double value)
        {
            if ((value >= 0.0) && (value < 60.0))
            {
                value++;
            }
            //if (date1904)
            //{
            //    Value += 1462.0;
            //}
            try
            {
                return DateTime.FromOADate(value);
            }
            catch(ArgumentException)
            {
                throw;
            }
            
        }
```
and then to catch that exception in the calling method in ExcelOpenXmlReader.cs:
```csharp
                        else if (null != a_s) //if something else
                        {
                            XlsxXf xf = _workbook.Styles.CellXfs[int.Parse(a_s)];
                            if (o != null && o.ToString() != string.Empty && IsDateTimeStyle(xf.NumFmtId))
                                try
                                {
                                    o = Helpers.ConvertFromOATime(number);
                                }
                                catch (ArgumentException)
                                {
                                    o = o.ToString();
                                }
                            else if (xf.NumFmtId == 49)
                                o = o.ToString();
                        }
```

If you think this is a good solution let me know.

**Comment by andersnm** [comment]
This was some recent improvements to this behaviour, and more formalized with #238. Cells with strings having date format are now always returned as strings.
