### ISSUE TITLE
Error: Buffer size is less than minimum BIFF record size.

### ISSUE THREAD

**Issue by redflowIT** [ExcelDataReader/ExcelDataReader#153]
HI all,
I get the exception "Error: Buffer size is less than minimum BIFF record size." when I try to access data of the attached file with this simple code:
excelReader = ExcelReaderFactory.CreateBinaryReader(stream, true);
excelReader.IsFirstRowAsColumnNames = true;
DataSet result = excelReader.AsDataSet(true);

I could open the file with Excel without problem.

I tried also the testapp application with same result (exception on line 20 of XlsBiffRecord.cs)

What's wrong in my code ?

Regards
Domenico

[BNLI CC 1 01_2016_20160830_1622043310.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/449973/BNLI.CC.1.01_2016_20160830_1622043310.zip)

**Comment by wizardgsz** [comment]
Could you kindly double check http://github.com/ExcelDataReader/ExcelDataReader/issues/45
Please let us know if it solves your issue.

**Comment by redflowIT** [comment]
No even with this fix I have the same exception: it never use the "new" code with my file.

**Comment by appel1** [comment]
Looks like it is because the record immediately after BOF is DIMENSIONS and because of that the current code skips it.

**Comment by wizardgsz** [comment]
Just guessing...
Are you sure it's BIFF8 or later?

This is another file without ROW records and only LABELSST.
It uses EXTERNSHEET record, isn't it available only for earlier BIFF2-BIFF5 files?

**Comment by redflowIT** [comment]
I'm still having the same problem. A lot of Excel files generated from an ERP that I couldn't process. Is there a new version on the road to fix this issue ?
