### ISSUE TITLE
ExcelBinaryReader - Dispose - m_file

### ISSUE THREAD

**Issue by Seabizkit** [ExcelDataReader/ExcelDataReader#156]
Why does the dispose of ExcelBinaryReader which is Access through IExcelDataReader.
**NOT Call dispose on the file stream**

**Stream m_file;**
 

       `public void Dispose()
		{
			Dispose(true);

			GC.SuppressFinalize(this);
		}

		private void Dispose(bool disposing)
		{
			// Check to see if Dispose has already been called.
			if (!this.disposed)
			{
				if (disposing)
				{
					if (m_workbookData != null) m_workbookData.Dispose();

					if (m_sheets != null) m_sheets.Clear();
				}

				m_workbookData = null;
				m_sheets = null;
				m_stream = null;
				m_globals = null;
				m_encoding = null;
				m_hdr = null;

				disposed = true;
			}
		}

		~ExcelBinaryReader()
		{
			Dispose(false);
		}`

**Comment by wizardgsz** [comment]
Well, I found this article and many comments discussing Close() Vs Dispose() methods; interesting part I can quote:

_In most .NET framework classes, there is no difference between Close() and Dispose(). For example, these methods do the same thing in the System.IO.Stream hierarchy, and it doesn’t matter which of the two methods you call. You should call one but not both._

Reference:
[MSDN Blogs: The (often non-) difference between Close and Dispose](http://blogs.msdn.microsoft.com/kimhamil/2008/03/15/the-often-non-difference-between-close-and-dispose/)

Take also a tour on MS source code pls, in fact Dispose() calls Close():
[File: system\io\stream.cs](http://referencesource.microsoft.com/#mscorlib/system/io/stream.cs,f475705f3e0f663d)

May I close this "non issue"?
Thanks a lot!

**Comment by Seabizkit** [comment]
Hi wizardgsz 
Thanks for response..
I totally get what you are saying as my own research as lead me down the same path.
You may close.... THANKS 
through....
my research lead me to believe that it is more correct to call dispose.
As Dispose my have other logic to ensure everything is finished off including calling close.
its just that in 99% of case it just class close. (this could be wrong, was my take)

**Comment by wizardgsz** [comment]
Twisted reasoning:

- Implementing IDataReader, You **must** explicitly call the [Close](http://msdn.microsoft.com/en-us/library/system.data.idatareader.close(v=vs.110).aspx) method when you are through using the IDataReader to use the associated IDbConnection for any other purpose (Microsoft guidelines).
- IExcelDataReader derives from IDataReader.
- Excel(Xxx)Reader implements IDataReader.
- Excel(Xxx)Reader.Close method closes the Stream (the Library calls `m_file.Close()`)
- The Stream Close method calls Dispose method.
- Moreover, Excel(Xxx)Reader.AsDataSet() calls Close also.

However, there is no problem if you'd rather prefer to explicitly call both Dispose and Close (or just the first or later only).

**Comment by Seabizkit** [comment]
Sounds like you are on it - I just thought i would check if it was closing the stream, and then it just wasn't apparent that is closing the stream, but its a little more nested than i thought.  
Wouldn't it be neater to call close() in the dispose of the main Class
But if you say that its being closed of properly then i will leave it.
More important things to do with your time if you know this is correct.
