### ISSUE TITLE
version 2.1.2.3 Nuget vs github dll wrong

### ISSUE THREAD

**Issue by Seabizkit** [ExcelDataReader/ExcelDataReader#157]
They Are not the same.... 
**github 2.1.2.3 - works
nuget 2.1.2.3 - not working
dll both say 2.1.2.3**

what is not working:
import xls file with IsFirstRowHeaderRow = false
This row will not appear in nuget dll but will in github.
github version is correct as far as i am concerned.

**Comment by wizardgsz** [comment]
Don't worry, just use latest develop build.

**Comment by andersnm** [comment]
All unintended binaries are removed from the develop branch. Not sure what happened with 2.1.2.3 but the one on Nuget.org is the official one that everyone gets
