### ISSUE TITLE
Non-negative number required. Parameter name: count

### ISSUE THREAD

**Issue by Ian1971** [ExcelDataReader/ExcelDataReader#16]
From https://exceldatareader.codeplex.com/workitem/13222
"This exception is produced in XlsBiffSST.cs on last - offset - prefix; The excel file contains Chinese simplified data with some formatting. I don't know how to fix this issue. Your help will be highly appreciated in this regard."

**Comment by andersnm** [comment]
Closing because inactivity, and there's been so many changes to the code in question, chances are this was fixed.
