### ISSUE TITLE
empty row is read

### ISSUE THREAD

**Issue by CHOMNANP** [ExcelDataReader/ExcelDataReader#160]
Anyway to avoid reading empty row in excel? User has remove some rows from the excel. As a result, my program still read those empty row.

Currently I'm using.

FileStream stream = File.Open(filePath, FileMode.Open, FileAccess.Read);
IExcelDataReader excelReader = ExcelReaderFactory.CreateOpenXmlReader(stream);
DataSet result = excelReader.AsDataSet();
excelReader.Close();

Thanks.

**Comment by wizardgsz** [comment]
Yeah! 

You can both:

1. modify the Library "readers", or
2. double-check "empty" rows in your client

**Comment by sridhar90** [comment]
I am facing the same issue? i am getting empty rows whenread from excel.
currently i am writing like this
Dim excelReader As IExcelDataReader
        If System.IO.Path.GetExtension(PartsFileUpload.FileName).Equals(".xlsx") Then
            excelReader = ExcelReaderFactory.CreateOpenXmlReader(PartsFileUpload.FileContent)
        ElseIf System.IO.Path.GetExtension(PartsFileUpload.FileName).Equals(".xls") Then
            excelReader = ExcelReaderFactory.CreateBinaryReader(PartsFileUpload.FileContent)
        End If
        excelReader.IsFirstRowAsColumnNames = True
        partsDs = excelReader.AsDataSet()

**Comment by andersnm** [comment]
It is not entirely apparent from the original issue description, but I suspect this might be a feature request to read a row's visible height (and act upon it). 

It is possible in Excel to collapse a row such that their data is retained while not readily visible to the user. I don't think ExcelDataReader currently treats rows with Height=0 differently from other rows so it is a reasonable request.
