### ISSUE TITLE
Weird chinese-like characters appearing when importing from XLS

### ISSUE THREAD

**Issue by sphengle** [ExcelDataReader/ExcelDataReader#166]
We have a cell containing over 11,000 characters.  About 7,500 of these characters come through in English but the remainder look chinese.  Here's a snippet.

```
  fields is alre<‟愁搀礀 愀 挀漀洀洀漀渀 昀攀愀琀甀爀攀 戀甀琀 眀椀
```

I've stepped through the source code but struggling to find out exactly how this is happening.  I've got as far as XlsBiffSST.ReadStrings().  The first call to ...

var str = XlsStringFactory.CreateXlsString(m_bytes, offset, reader);

...has a value with English, then Chinese, then English.  When the string is finally added to the m_strings array it has lost its final chinese bit.

Any thoughts?

**Comment by wizardgsz** [comment]
Can u share a sample Excel file?
Did you verify latest develop build?
Have a nice w/e

**Comment by appel1** [comment]
Impossible to tell for sure without an example, but it could be a duplicate of #161.

**Comment by andersnm** [comment]
Agree this sounds like #161. Should be fixed in the develop branch, but please reopen and provide a test xls if the problem still exists.
