### ISSUE TITLE
Incorrect encoding of Cyrillic worksheet names in XLS files

### ISSUE THREAD

**Issue by skosterin88** [ExcelDataReader/ExcelDataReader#170]
I have encountered the following problem using the solution. As I open an XLS file with a Cyrillic-named worksheet, I see the worksheet name in the combo box as unreadable symbols. The table itself is shown adequately but the worksheet name is unreadable. As I open an XLSX file with the same content, there is no such problem. I attach the files I used in a ZIP archive here. 

[Test_CyrillicWorksheetName.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/522643/Test_CyrillicWorksheetName.zip)

**Comment by appel1** [comment]
Looks like a duplicate of #152. For BIFF8 the codepage shouldn't be used at all, it is always UTF-16LE.

**Comment by andersnm** [comment]
Closing as fixed.
