### ISSUE TITLE
Handle invalid INDEX records

### ISSUE THREAD

**Issue by appel1** [ExcelDataReader/ExcelDataReader#173]
https://www.newyorkfed.org/microeconomics/sceindex/medialibrary/interactives/sce/sce/downloads/data/FRBNY-SCE-Data.xls

In the linked file there's only one entry in the cell addresses array. I think we could ignore the INDEX record when the addresses array length does not match the row count as given by the FirstExistingRow and LastExistingRow values.

**Comment by appel1** [comment]
Or if the cell address values does not actually point to a DbCell. Not sure which is safest.

**Comment by Ian1971** [comment]
This is where the unit tests are critical because its hard to know which is the best option, so best might be the one that doesn't break all the others ;-)

**Comment by appel1** [comment]
Should be fixed as part of https://github.com/ExcelDataReader/ExcelDataReader/pull/139.
