### ISSUE TITLE
Excel CreateOpenXmlReader - Embedded Image => Brings in only 1 column tables

### ISSUE THREAD

**Issue by InfOracle** [ExcelDataReader/ExcelDataReader#175]
I have a series of xlsx files that are given by a third party vendor and I import the data into a database.  I use:

`Excel.IExcelDataReader excel = Excel.ExcelReaderFactory.CreateOpenXmlReader(filename);`
`DataSet ds = reader.AsDataSet();`

This works 100% of the time for xlsx files up until I started working with these files...I opened one and removed the embedded images and it read the file just fine...Is there a setting to ignore embedded images or a way to remove them In-Code? Thanks.

I'm using Excel 4.5.dll

**Comment by appel1** [comment]
Could you try with the 3.0 release to see if it is fixed? If not or if it still doesn't work with 3.0 could you provide a sample so we can reproduce the issue?

**Comment by andersnm** [comment]
Just tried to repro this using ExcelDataReader 3.0 and the old 2.1 version, but both of them work as expected when testing a quick xlsx with some data, embedded images, shapes and smart art.

**Comment by appel1** [comment]
Then I think we should close the issue. It can always be reopened if we get a sample that we can use to reproduce the issue.

**Comment by andersnm** [comment]
Ok, closing. @InfOracle Please let's know (with an example) if this is still an issue
