### ISSUE TITLE
Cleanup/Restructure the repo

### ISSUE THREAD

**Issue by cemremengu** [ExcelDataReader/ExcelDataReader#176]
I am suggesting that we restructure the repo first and get rid of unnecessary stuff (whether this means dropping the support) or separate them into different packages. So we can focus on the most important stuff.

Some of these are shown below:

```
ExcelDataReader.Android
ExcelDataReader.Desktop
ExcelDataReader.Portable
ExcelDataReader.Silverlight
ExcelDataReader.iOS
```

Secondly, lets hookup this to 'Travis' or 'Appveyor' to get a CI going on (free for open source projects)

**Comment by wizardgsz** [comment]
Well, I suggest to continue discussing on opened "issues" instead of opening new one... IMHO

**Comment by cemremengu** [comment]
Sorry @wizardgsz which one is that can you point me to that ?

**Comment by andersnm** [comment]
I think this is OK now.
