### ISSUE TITLE
incorrect date format representation

### ISSUE THREAD

**Issue by venkatrjv** [ExcelDataReader/ExcelDataReader#177]
I working on excel date retrieving using ExcelDataReader. but it seem that i find issue with date column.

below is the image of excel data:
![error1](https://cloud.githubusercontent.com/assets/22792695/20334199/3b9534f6-abde-11e6-84d7-2a6095b5abc9.JPG)

On retrieving using ExcelDataReader the date format is representing in number.
![error2](https://cloud.githubusercontent.com/assets/22792695/20334201/40d3cf4a-abde-11e6-9a7c-c64b17dd5c13.JPG)

My code is :
```
 using (FileStream stream = File.Open(filePath, FileMode.Open, FileAccess.Read))
                {
                    string fileExe = Path.GetExtension(FileUpload1.PostedFile.FileName);
                    IExcelDataReader excelReader;
                    if (fileExe == ".xls")
                    //1. Reading from a binary Excel file ('97-2003 format; *.xls)
                    {
                        excelReader = ExcelReaderFactory.CreateBinaryReader(stream, true);
                        //var excelReader = Excel.ExcelReaderFactory.CreateBinaryReader(inputStream, true);

                    }//...
                    //2. Reading from a OpenXml Excel file (2007 format; *.xlsx)
                    else
                    {
                        excelReader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                    }
                    var excelDataSet = excelReader.AsDataSet(true);
                    //5. Data Reader methods
                    int j = 0;
                    while (excelReader.Read())
                    {
                        object[] array = new object[excelReader.FieldCount];
                        for (int i = 0; i < excelReader.FieldCount; i++)
                        {
                            if (j == 0)
                            {
                                dt.Columns.Add(i.ToString());
                            }
                            array[i] = excelReader.GetString(i);
                        }
                        j++;
                        dt.Rows.Add(array);
                    }
                    //6. Free resources (IExcelDataReader is IDisposable)
                    excelReader.Close();
                }
```

**Comment by tcsaddul** [comment]
I'm using this function to convert excel dates (number). See if it works

        public static DateTime FromExcelDate(double value)
        {
            return new DateTime(1899, 12, 30).AddDays(value);
        }
 

    On Wednesday, November 16, 2016 1:02 PM, venkatrjv <notifications@github.com> wrote:
 

 I working on excel date retrieving using ExcelDataReader. but it seem that i find issue with date column.below is the image of excel data:
On retrieving using ExcelDataReader the date format is representing in number.
My code is : using (FileStream stream = File.Open(filePath, FileMode.Open, FileAccess.Read))
                {
                    string fileExe = Path.GetExtension(FileUpload1.PostedFile.FileName);
                    IExcelDataReader excelReader;
                    if (fileExe == ".xls")
                    //1. Reading from a binary Excel file ('97-2003 format; *.xls)
                    {
                        excelReader = ExcelReaderFactory.CreateBinaryReader(stream, true);
                        //var excelReader = Excel.ExcelReaderFactory.CreateBinaryReader(inputStream, true);

                    }//...
                    //2. Reading from a OpenXml Excel file (2007 format; *.xlsx)
                    else
                    {
                        excelReader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                    }
                    var excelDataSet = excelReader.AsDataSet(true);
                    //5. Data Reader methods
                    int j = 0;
                    while (excelReader.Read())
                    {
                        object[] array = new object[excelReader.FieldCount];
                        for (int i = 0; i < excelReader.FieldCount; i++)
                        {
                            if (j == 0)
                            {
                                dt.Columns.Add(i.ToString());
                            }
                            array[i] = excelReader.GetString(i);
                        }
                        j++;
                        dt.Rows.Add(array);
                    }
                    //6. Free resources (IExcelDataReader is IDisposable)
                    excelReader.Close();
                }

**Comment by SteveHolle** [comment]
How does the date look in the spreadsheet?  What I have found is that if
the older xls cell format is changed from date to text, the date format is
lost and you need to do the conversion as tcsaddul suggested above.

It is important not to convert the format of the spreadsheet to text before
processing.

To decode these dates, all that should be necessary is to set the AsDataSet
parameter to true as you have done., "excelDataSet =
excelReader.AsDataSet(true);"  Break and examine excelDataSet right after
it is set.  It might be something in your for statement that is causing the
date field to be parsed incorrectly.  It could be the
excelReader.GetString() function.  I suspect that converting the date field
directly to a string with no parsing may be the problem.

**Comment by aggsol** [comment]
This should be a bug. Using `Convert.ToDateTime()` on a cell should yield a valid date.

**Comment by nshanmugam** [comment]
Passing 'true' to the excelReader.AsDataSet method resolved the Date format issue for .xls files. 
DataSet result = excelReader.AsDataSet(true);

**Comment by andersnm** [comment]
Looks like the dates are rendered as double because ConvertOaDates = false.
