### ISSUE TITLE
Reading formatted numbers

### ISSUE THREAD

**Issue by smoloye** [ExcelDataReader/ExcelDataReader#178]
Hi,

I have a column of number formatted to display values to 2 decimal places such that a value of 917.6124 shows as 917.61 on the cell.
When reading the excel file i want to recover 917.61 instead of 917.6124, how can i achieve this using ExcelDataReader without modifying the file?

Thanks,
Sanjeev.

**Comment by tcsaddul** [comment]
IMHO, I would make the rounding in my app.
 

    On Wednesday, November 16, 2016 11:08 PM, smoloye <notifications@github.com> wrote:
 

 Hi,I have a column of number formatted to display values to 2 decimal places such that a value of 917.6124 shows as 917.61 on the cell.
When reading the excel file i want to recover 917.61 instead of 917.6124, how can i achieve this using ExcelDataReader without modifying the file?Thanks,
Sanjeev.—

**Comment by smoloye** [comment]
I cant make the rounding in the app actually because the app reads excel files from different sources and hence different roundings. So i need a way to read the displayed value only.

**Comment by wizardgsz** [comment]
The Library manages "numbers", not formatted "strings". 
So, most probably, you have to branch your solution "interpreting" custom or built-in numerical formats. You have to modify also internal DataTable saving numbers as strings, strings which you applied a format conversion.

Please, for a list of built-in formats, see for example **ExcelBinaryReader.cs** `tryConvertOADateTime(...)` 

Further info in **FORMAT** or **XF** records specifications, _Number Format (41Eh)_, _Extended Format (E0h)_.

Good luck and le me know please!

**Comment by andersnm** [comment]
ExcelDataReader returns number format strings now, which can be used with the [ExcelNumberFormat](https://github.com/andersnm/ExcelNumberFormat) library to obtain formatted values with f.ex a certain number of decimal points.

However, ExcelNumberFormat currently returns only strings. There is an issue to return numeric values from a format: https://github.com/andersnm/ExcelNumberFormat/issues/8
