### ISSUE TITLE
Unable to created ExcelDataReader in Visual Studio for Mac (Mono framework)

### ISSUE THREAD

**Issue by gaurav-clearTax** [ExcelDataReader/ExcelDataReader#179]
### Description

Program.fs(22,22): Error FS3033: The type provider 'ExcelProvider.ExcelProvider+ExcelProvider' reported an error: Could not create ExcelDataReader. Exception - Could not create ExcelDataReader. Exception - Method 'ICSharpCode.SharpZipLib.Zip.ZipEntry.IsCompressionMethodSupported' not found. (FS3033)

### Repro Steps
1. Try using the ExcelDataReader in VisualStudio for Mac
2. You get the error `Could not create ExcelDataReader. Exception - Method 'ICSharpCode.SharpZipLib.Zip.ZipEntry.IsCompressionMethodSupported' not found.`

I guess ICSharpCode.SharpZipLib.Zip is not compatible with mono... because that issue is long due in ExcelProvider.

Is there a work around to make this work with Mono and Visual Studio for Mac?

### Known Work Arounds
- Replaced ICSharpCode.SharpZipLib with DotNetZip or some other alternative?

**Comment by wizardgsz** [comment]
What version of SharpZipLib are you using?
I read that, just quoting: _be aware that the version of SharpZipLib shipped with Mono is old, outdated, and has known bugs._ 

Please refer to:
http://github.com/icsharpcode/SharpZipLib/
http://buxty.com/b/2011/11/sharpziplib-and-mac-os-x/

**Comment by gaurav-clearTax** [comment]
I was using SharpZipLib 0.86
I tried cloning the repo and making changes to make it work using all options available in SharpZipLib, however I still got the same error.

Is there any particular reason for using SharpZipLib?
Is an update planned to handle the Mono framework and Visual Studio for Mac?

**Comment by andersnm** [comment]
The latest prerelease ExcelDataReader Nuget packages are more explicit about its dependencies per target and thus SharpZipLib is no longer needed nor pulled in in projects compatible with net45 or netstandard1.3. Afaik Mono supports both net45 and netstandard1.3 libraries so this case can be closed.

(ExcelDataReader's net20 binary depends on SharpZipLib though)
