### ISSUE TITLE
How to read hyperlink

### ISSUE THREAD

**Issue by dipongkor** [ExcelDataReader/ExcelDataReader#183]
I have a hyperlink column in my excel. I need the url of it. 
How can I get it using this library

Thanks
Atish

**Comment by appel1** [comment]
Do you mean a cell using the =HYPERLINK function? If so it is currently not possible. ExcelDataReader only reads the cached result from Excel formulas.

**Comment by niteshluharuka** [comment]
Any further update to this? Can this be done now? If not, any alternative library that provides this feature?

**Comment by x893** [comment]
Right mouse clink in cell and select Hyperlink... from context menu.
Enter Address: https://github.com and OK

**Comment by appel1** [comment]
Closing this since it should be covered by the more general issue #332 .
