### ISSUE TITLE
How can we export dataset into XLS file?

### ISSUE THREAD

**Issue by MonsterMMORPG** [ExcelDataReader/ExcelDataReader#186]
How can we export dataset into XLS file?

I can read it but i want to export it

**Comment by wizardgsz** [comment]
The Library reads Excel files only. 

You have to Google to find a writer, for example: [Export data from a DataSet into a real Excel 2007 file](http://www.mikesknowledgebase.com/pages/CSharp/ExportToExcel.htm)
