### ISSUE TITLE
Nuget package status

### ISSUE THREAD

**Issue by AndrewGretton** [ExcelDataReader/ExcelDataReader#187]
Are there any plans to update the public Nuget package available here? 

https://www.nuget.org/packages/ExcelDataReader

It was last released in May 2014, and there's been some great work in this repo that isn't available in the public package.

**Comment by andersnm** [comment]
There are new official prerelease packages on Nuget now:
https://www.nuget.org/packages/ExcelDataReader/3.0.0-develop00019
https://www.nuget.org/packages/ExcelDataReader.DataSet/3.0.0-develop00019

Also available to download from here:
https://github.com/ExcelDataReader/ExcelDataReader/releases/tag/v3.0.0-develop00019

Not sure when there'll be a stable release, but hopefully soon. Still reviewing open issues if there's a need to make further breaking changes while we have the chance.
