### ISSUE TITLE
Show visibility column state

### ISSUE THREAD

**Issue by LuisSerrano** [ExcelDataReader/ExcelDataReader#188]
It's posible to know  what is the visibility status in a column after import the xls ?

Thanks

**Comment by andersnm** [comment]
[collapsed.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/1165557/collapsed.zip)

**Comment by andersnm** [comment]
In the upcoming version 3.5.0 it is possible to check `reader.GetColumnWidth(columnIndex) == 0` to determine if a column is hidden/invisible/collapsed
