### ISSUE TITLE
Read minimal things from excel sheet, and read them fast

### ISSUE THREAD

**Issue by dhrumil83** [ExcelDataReader/ExcelDataReader#191]
Only want to know the number of sheets, and the first row for each sheet to figure out the fields.

This is very slow since it seems to read everything: DataSet result = excelReader.AsDataSet();
Code:
IExcelDataReader excelReader = ExcelReaderFactory.CreateOpenXmlReader(new MemoryStream(stream));
excelReader.IsFirstRowAsColumnNames = true;
DataSet result = excelReader.AsDataSet();

Any way to get around this, to load only the sheet info + 1st row into memory so that this operation is fast.

**Comment by appel1** [comment]
Use IExcelDataReader.Read, IExcelDataReader .NextResult and IExcelDataReader.ResultsCount instead.

**Comment by dhrumil83** [comment]
That works. Awesome. Thanks a ton.
