### ISSUE TITLE
AsDataSet method crashes with OutOfMemoryException

### ISSUE THREAD

**Issue by AndreR** [ExcelDataReader/ExcelDataReader#193]
Hello,

I got seven similar files, which are all between 1 and 2 MB in size. However, one of them always crashes with an OutOfMemoryException as soon as I call the AsDataSet method.

The strange thing is, that this only happens in my big project. If I add the current NuGet to a simple cmd app, it runs fine. It consumes a whole lot of RAM, though, between 700 and 800 MB for that 1,222 KB file, to be exact.

Is there a way to solve this, or at least to debug the error further?

**Comment by appel1** [comment]
Is the Excel file publicly available so I can debug it?

**Comment by AndreR** [comment]
@appel1 Unfortunately it is not. It's a file for internal use only. Any chance to help me anyways?

**Comment by appel1** [comment]
You could build the source code and debug yourself to figure out why it allocates a lot of memory.

**Comment by AndreR** [comment]
I might try that, as I find some time.

**Comment by amirjuve** [comment]
I have the same problem, any suggestion?? @AndreR

**Comment by appel1** [comment]
@amirjuve Can you send me the Excel file that triggers this so I can debug this?

**Comment by amirjuve** [comment]
@appel1  your mail please

**Comment by appel1** [comment]
johan.appelgren@gmail.com

**Comment by AndreR** [comment]
@amirjuve Thank you very much. Sounds great. Hopefully it's the exact same error and your file can help in fixing this problem. I haven't found a workaround or solution yet.

**Comment by andersnm** [comment]
How did the testing work out? Does it work with latest develop branch? Was it .xls or .xlsx?

**Comment by appel1** [comment]
I never received any files that could reproduce the described issue.

**Comment by andersnm** [comment]
This is pretty hard to diagnose without anything to go on. Closing this for now. @amirjuve @AndreR I'd be happy to hear if latest version works for you or not

**Comment by amirjuve** [comment]
[https://docs.google.com/spreadsheets/d/1R4o0k2JqPzi8jwOOhQjextNg-yieWiMu72kaxjoKsUU/edit?usp=sharing](url)

**Comment by andersnm** [comment]
@amirjuve Thanks! I saved the linked Google Spreadsheet as an .xlsx and opened with the TestApp from ExcelDataReader's 2.1 and 3.1 repositories, but it seems to work fine for me, and no excess memory usage. Not sure what to look for here?

**Comment by amirjuve** [comment]
@andersnm  Thanks for the quick reply, can you check a .xls [file](https://docs.google.com/spreadsheets/d/1S_7Q5MC30IgT8ziVMfUJvQrtyrTvmPx5fhDoKWcgaNk/edit?usp=drive_web) to be sure.

**Comment by andersnm** [comment]
@amirjuve  Can you try and email me these files instead? You should have my email address from when I requested permission to the documents. 

If I take the file from Google Spreadsheets, it has already been imported and "fixed" by Google Docs, so I cannot diagonose these as-is.

**Comment by amirjuve** [comment]
Can you give me your ersonal mail ?


2017-08-15 15:46 GMT+02:00 andersnm <notifications@github.com>:

**Comment by andersnm** [comment]
@amirjuve I have sent a mail to you with the subject "ExcelDataReader testing" - can you please reply to that?

**Comment by AndreR** [comment]
Thank you! It now works without all the workarounds and it doesn't crash anymore!

**Comment by kevinkwtun** [comment]
@AndreR, how do you solve it? Thanks in advance. I'm also facing same issue when i try to read the excel file which is around 300 MB.

**Comment by andersnm** [comment]
@kevinkwtun When working with large workbooks it is generally prefered to use ExcelDataReaders reader methods (instead of AsDataSet) to avoid loading everything into memory. These methods work on a per-row basis, giving more control how to store the data in your app.

Alternatively you could try to pass `UseColumnDataType = false` as an option to AsDataSet() to halve the amount of memory used. It does not set the DataColumn.ColumnType properties, but avoids creating an internal copy of the the datatables.
