### ISSUE TITLE
ExcelDataReader cannot delete the generated temp files?

### ISSUE THREAD

**Issue by GitClickOk** [ExcelDataReader/ExcelDataReader#195]
I was having the same issue from erw13n user on #135. The Server run out of disk space because ExcelReaderFactory.CreateOpenXmlReader create a so many Temp files...

I see one option is use in memory instead of temp files, but hey, I dont have problems with temp files... I was just guessing if ExcelDataReader doesnt have an option to delete the temp file after finish (ie, when closing/disposing the ExcelDataReader )? 

Windows rarely cleans temp files, and sometimes, with specific tools it performs clean ups only on system restarts, and this is really rare (and dont recomendable) on Web Apps.

Then, I think a really simple solution delete the temp file when closing/disposing the ExcelDataReader, and I think will not break with existing versions (if yes, simply put an option for this, with default to dont clean).

**Comment by wizardgsz** [comment]
Search the forums please, the solution has been already implemented and announced here in the past :)

**Comment by GitClickOk** [comment]
Thanks for your reply, wizardgsz, but sadly  I cannot find this "solution" yet... The only thing I see to fix this is using "memory" instead of temp files. Is it the solution are you talking about? Maybe my google-fu is weak lately...

**Comment by AndreR** [comment]
An in-memory solution would be fabulous! I ran into various problems in combination with impersonation. When reading files inside an impersonation context, it tries to write the temp files into that impersonated user's temp folder, which fails, because it doesn't exist. I will open another ticket for this issue.

**Comment by GitClickOk** [comment]
Yes, AndreR, my problem is near this, my ExcelDataReader is writting on Temp folder of DefaultAppPool user. I think Wizardgsz is talking about #114, but this is different from my request/solution. I want only the ExcelDataReader delete the created temp files (this must be what a "dispose" method does, clean up resources, isnt?), at least as an option.

**Comment by andersnm** [comment]
I think this can be closed now as there should be no more concerns with temp files onwards per #139.
