### ISSUE TITLE
Writing temp files fails while impersonating

### ISSUE THREAD

**Issue by AndreR** [ExcelDataReader/ExcelDataReader#196]
I ran into a problem in combination with impersonation. When reading files inside an impersonation context, it tries to write the temp files into the assembly's user's temp folder with the credentials of the impersonated user. This works on the server, because "everyone" can write to the temp folder there. However, it fails on my local machine, because it executes the software under my own user account, but the impersonated account mustn't write into my own temp folder.

I'm using the [SimpleImpersonation](https://github.com/mj1856/SimpleImpersonation) lib.

```
Using SimpleImpersonation.Impersonation.LogonUser(My.Settings.UncUserdomain, My.Settings.UncUsername, My.Settings.UncUserpassword, SimpleImpersonation.LogonType.Interactive)
  Using str As New IO.FileStream(Path, IO.FileMode.Open, IO.FileAccess.Read, IO.FileShare.ReadWrite)
    Using reader = Excel.ExcelReaderFactory.CreateOpenXmlReader(str)
```

**Comment by andersnm** [comment]
I think this can be closed now as there should be no more concerns with temp files onwards per #139.
