### ISSUE TITLE
Support reading named ranges

### ISSUE THREAD

**Issue by dhrumil83** [ExcelDataReader/ExcelDataReader#197]
Could not find anything that says ExcelDataReader supports reading named range.
Named ranges =>
http://www.contextures.com/xlNames01.html
https://exceljet.net/lessons/how-to-create-a-named-range

If excel file has 10 named ranges, the library could return each of them with the cell range.

**Comment by appel1** [comment]
How would you use this?

**Comment by dhrumil83** [comment]
Could be something like this:

DataSet result = excelReader.AsDataSet();
for(int x = 0; x < result.Tables[0].NamedRange.Count; x++) 
{
  DataTable test = result.Tables[0].NamedRange[x];
 ==========what to do with this table=========
}

**Comment by appel1** [comment]
Afaik there's no such functionality in the DataSet class. It'd have to be something added to the IExcelDataReader interface. 

Is your answer to the question how you'd use this that you want to get a DataTable with the contents of each named range?

**Comment by andersnm** [comment]
See also #25
