### ISSUE TITLE
Columns skipped when DIMENSION record is incorrect

### ISSUE THREAD

**Issue by Ian1971** [ExcelDataReader/ExcelDataReader#2]
Originally posted by stephensjs to the codeplex site, [here](http://exceldatareader.codeplex.com/workitem/13101) original post. 

"A spreadsheet I've encountered in the wild doesn't conform properly to the Excel binary format spec, and in the DIMENSION record uses the zero based index of the last column, rather than the zero based index of the column after the last column, for the colMac value. As a consequence, ExcelDataReader skips reading the last column of the spreadsheet. Excel and OpenOffice both open the file without any problems, and if you save it after opening it, they will fix the bad DIMENSION record.

I've attached the spreadsheet in question. If you're curious about its provenance, you can find it here: http://www.adrbnymellon.com/dr_directory.jsp. You have to look for the "Download to Excel" link, click it, agree to some legalese, and then you can download. 

I've written a patch that allows this file to be read properly. It's similar to the fix for [Issue #12667](http://exceldatareader.codeplex.com/workitem/12667); it compares the number of columns from the DIMENSION record with the number of columns from the first row record, and if the number of columns from the row record is greater, it goes with that. The fix does not cause any existing working tests to fail, and I've included a unit test to exercise the new code. The patch is attached."

[dimension_columns_one_too_few.diff | uploaded via ZenHub](https://www.zenhub.io/files/53e08db36dad3eda140029a1)
[Test_DimensionColumnsOneTooFew.xls | uploaded via ZenHub](https://www.zenhub.io/files/53e08dd26dad3eda140029a2)

[Attachments.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/406974/Attachments.zip)

**Comment by MoosHam** [comment]
I also have Files that I get from a customer that have a DIMENSION of A1, although it has way more columns. ExcelDataReader only reads the first column of that file. I think it would be good, if ExcelDataReader can check if the DIMENSION is correct or not.

**Comment by wizardgsz** [comment]
This old issue refers to XLS Binary Format @MoosHam, not Open XML like yours ;-)

**Comment by andersnm** [comment]
Fixed with #209
