### ISSUE TITLE
String precision format

### ISSUE THREAD

**Issue by mstfbirinci** [ExcelDataReader/ExcelDataReader#200]
When I read excel data using ExcelDataReader, convert it to entity on my application. My excel sheet like [this :](http://imgur.com/cmGe9hm)

When converting excel sheet to DataSetCollection :

`var rawData = excelReader.AsDataSet().Tables[0];`

it contains cell variables on rawData like this:

Column1:1

Column2:10

And then I serialized rawData to Json String;

`var json = JsonConvert.SerializeObject(rawData, Formatting.None);`

This point, json string is shown in visual studio ide two different format:

1 - In visual studio, json string is shown in text visualizer like this:

[{"column1 ": 1.0, "column2 ": 10.0}]

2 - json string is shown in json visualizer like this:

{column1 : "1", column2 : "10"}

Finally, when deserialize json string to entity ;

`JsonConvert.DeserializeObject<List<T>>(json);`

entity fields shown like this:

string column1 = "1.0"

string column2 = "10.0"

I don't why this kind of format difference, Is there any way how to show numeric excel cell in string field like this :

string column1 = "1"

string column2 = "10"

**without any decimal, double conversion and any excel cell formatting?**

**Comment by appel1** [comment]
I think Json.NET always ensures that there's a decimal place when serializing doubles. You'd have to override that behavior in Json.NET.

**Comment by mstfbirinci** [comment]
Yes, I solved the problem by writing a converter class that implements the JSONConverter interface. Thank you for your support.
