### ISSUE TITLE
not a legal oleaut date

### ISSUE THREAD

**Issue by Borja204** [ExcelDataReader/ExcelDataReader#201]
Hello, 

I'm getting this exception in some excel files when running "asDataSet" method.

I'm lost about this. Any tip or help is apreciated.

Thanks

**Comment by appel1** [comment]
The Excel file contains a OADate value that is <= -657435.0 or  >= 2958466.0, that is, they can't be represented as DateTime. You could set convertOADateTime to false so that ExcelDataReader does not attempt to convert OADates to DateTime.

**Comment by Borja204** [comment]
Hello appel,

First of all, thanks for the response. Since I'm not able to manage what does come into the sheet (client is who sends the workbooks) I've tried your siggestion but with no luck:

**Comment by appel1** [comment]
Looks like that parameter is ignored for xlsx files. What does Excel do for such cells? Do you have a sample xlsx file I could take a look at?

**Comment by Borja204** [comment]
Hello Johan,

Unfortunately I cant send an example excel since they contain confidential financial data :(. The problem is also that there are lots of sheets inside each excel, and hundreds of cells inside each sheet, and I'vent found a way to determine wich cell(s) is/are causing the error.

The point is, that inside the workboks there are some sheet that I must read, and another sheets that are garbage. It is probably at 99% that the problem is coming from one those garbage sheets, but I'vent found neither a way to skip those sheets in the asDataSet method which could probably fix also the issue. (For example, read only the sheets that contains in the name the text "READ.THIS")

Regards

**Comment by appel1** [comment]
Instead of using AsDataSet you could use NextResult, Read and GetValue to read just the cells you want. 

```csharp
do
{
    if (reader.Name == "READ.THIS") 
    {
       while (reader.Read())
       {
            for (int i = 0; i < reader.FieldCount; i++)
            {
                object value = reader.GetValue(i);
            }
       }
    }
}
while (reader.NextResult())
```

**Comment by Borja204** [comment]
Hello Johan,

Thanks for the help, I'm trying your solution. Anyways, do you know if there is a simple way to transform an entire sheet in a datatable?

` for (int i = 0; i < reader.FieldCount; i++)
            {
                object value = reader.GetValue(i);
            }`

instead of doing all the loop myself and build the datatable, just make something `like:

`do
{
    if (reader.Name == "READ.THIS") 
    {
       while (reader.Read())
       {
           datatable = reader.asDatatable()
       }
    }
}
while (reader.NextResult())`

Thanks

**Comment by appel1** [comment]
No, there's no AsDataTable but it could quite easily be added.

**Comment by Borja204** [comment]
Hello Appel,

how could be the asDataTable be implemented?

Could you guide me in the easiest and fastest way to read entire sheets by name?

Thanks for your help,

Regards
