### ISSUE TITLE
Can ExcelReader NOT skip empty rows?

### ISSUE THREAD

**Issue by BelikovSergey** [ExcelDataReader/ExcelDataReader#204]
Or at least somehow give real row position in the Excel file.

**Comment by appel1** [comment]
I've tried to change things in my fork to be more consistent with when viewing in Excel. Perhaps you can try it and see if it works better for you?

https://github.com/appel1/ExcelDataReader

**Comment by BelikovSergey** [comment]
I am sorry, that was bug in my code that skip empty lines. But thanks for the link. Any chance nuget package will be updated?
