### ISSUE TITLE
Need testers/contributors for ExcelDataReader.Portable (branch f-portable)

### ISSUE THREAD

**Issue by Ian1971** [ExcelDataReader/ExcelDataReader#21]
The branch f-portable contains the portable version of ExcelDataReader together with a Windows desktop implementation. The V2 ExcelDataReader for .Net 4.5 now uses the portable library.

This will become a V3 release of ExcelDataReader
## Xamarin

I could really do with someone who uses Xamarin to flesh out the ExcelDataReader.iOS and ExcelDataReader.Android projects. It should be pretty easy as there isn't much to implement. Have a look at ExcelDataReader.Desktop - and you'll see that there are really just 3 interfaces to implement
## Current library interface still supported

The existing Excel.IExcelDataReader interface is maintained in the Excel.4.5 project and this makes this release a drop in replacement for the current v2 library.
## .Net 2 still supported (for now)

.Net framework 2 is currently still supported but the code has now diverged so I would like to drop it, or find someone who wants to support framework 2 (I have no need for it).
## Older Excel version support dropped

The v2 library was a bit patchy on anything < Biff8. To make it easier to support going forward only Biff8 is going to be supported. This is anything from Excel 97 onwards.
## Current pull requests & issues

I need to go through these and incorporate into the new code. Help with this would be appreciated also. Bearing in mind that we really require unit tests to be written to first expose the issue and thus demonstrate that the issue exists,. That means we need test files. 

We could also do with a better way of being able to quickly create these test methods. Currently you have to do a few steps to add the excel file and make it referenceable in the test classes. Anything that makes it easier to add these tests with less steps would make maintenance much easier.

**Comment by andersnm** [comment]
I assume this is ok to close with #139 in the haus and netstandard target.
