### ISSUE TITLE
XLS file not being read

### ISSUE THREAD

**Issue by monkeyx-net** [ExcelDataReader/ExcelDataReader#211]
I have an XLS that has been generated by a third party that generates no data or an error when opened with IExcelDataReader excelReader = ExcelReaderFactory.CreateBinaryReader(stream);

Also tried with ReadOption.Loose and tried installing latest development version from nuget

All other programs/online Excel readers seem to open it is as valid XLS file.

If I open and save the file in Excel then it will read the file.

Any advice on how to work around, troubleshoot, fix this issue please? As I want to process the files without a user having to save them as  excel files.

**Comment by andersnm** [comment]
Curious if these Nugets work for you, they fix some issues usually seen with third party generators:
https://ci.appveyor.com/project/andersnm/exceldatareader/build/3.0.0.26/artifacts

If not, can you share an XLS? Do you know how the third party generated it, i.e which library/package?

**Comment by monkeyx-net** [comment]
Hi,
Will try the Nugets later today. I have attached the file I am using. I produce the xls files by using an application that came with some barcode scanners. So not really sure what library has been used. I tested NPOI and that also worked, but would rather use the ExcelDataReader :)
 
[oResults.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/1064694/oResults.zip)

**Comment by andersnm** [comment]
Thanks, just tested oResults.xls with the latest fixes and seems to parse all right.

**Comment by monkeyx-net** [comment]
Thanks for providing the nuget package, I can now parse the oResults.xls I attached as well :)
