### ISSUE TITLE
Reader/dataset options as configuration objects

### ISSUE THREAD

**Issue by andersnm** [ExcelDataReader/ExcelDataReader#213]
This is a "request for comments" while pondering some potentially breaking changes:

ExcelDataReader currently supports three options; `convertOADate` and `readOption` constructor parameters on the ExcelBinaryReader, and `IsFirstRowAsColumnNames` property on the reader interface.

There have been some requests for more ways to controlling the output:

#67 DBNull control
#77 #182 Skip X rows before header
#6 Default name for columns with no name
#36 read a DataSet and leaving the values as string
#95 AsDataSet() without parsing it into DateTime format
#180 Load a single sheet by sheet name
#160 Skip rows where visual height is zero

Other ideas:
- Skip empty rows before headers, callback for skipping rows before headers
- DataSet value formatter callback
- Load specific sheet(s) by sheet names and/or indices
- Fallback/default string encoding (in case xls lacks encoding record, cant use CurrentThread on netstandard)
- Passing password for encrypted spreadsheets
- `ColumnNameHandling` enum to replace `IsFirstRowAsColumnNames`:

```C#
enum ColumnNameHandling {
	NoColumnNames,
	FirstRowColumnNames,
	SkipRowsBeforeColumnNames,
	SkipEmptyRowsBeforeColumnNames,
	SkipRowsCallback
}
```

With the jump to 3.0, I think now is a good time to change the reader constructors and `AsDataSet()` to take an optional, extensible configuration object - instead of the individual configuration parameters. It could look something like this:

```C#
var reader = ExcelReaderFactory.CreateReader(stream, 
	new ExcelReaderOptions() {
		ConvertOADate = true,
		ReadOption = ReadOption.Loose,
		ColumnNameHandling = ColumnNameHandling.SkipRowsBeforeColumnNames,
		SkipRowsBeforeColumnNames = 7,
		SkipRowsCallback = values => ShouldSkipRow(values),
		FallbackEncoding = Encoding.GetEncoding("windows-1252"),
		Password = "Password"
	});

var ds = reader.AsDataSet(
	new ExcelDataSetOptions() {
		IgnoreColumnNames = false,
		EmptyColumnNamePrefix = "Column",
		ReadSheetNames = new List<string>() { "Sheet1", "Sheet5" },
		ReadSheetIndices = new List<int>() { 0 },
		FormatValueCallback = value => FormatValue(value)
	});
```

Of course, many of the above options needs implementing and will not be included at first.

**Comment by naveenlnr** [comment]
Can we have an option like reading selected Columns only into Data Table.
i.e. suppose in the excel sheet we have 10 columns and out of those we want to load only following columns data, like (Column 3, Column 5, Column 8) and can safely ignore the remaining columns.

Currently to do this, i need to create a new data table with selected columns and looping through each row from the original sheet table to select interested columns and adding them into data table row. If it can be done while creating the first data table it will reduce reading huge data into data table and discarding that data later.

**Comment by andersnm** [comment]
@naveenlnr That's a nice addition to the "Other ideas" bullet list- 

Many feature requests have to do with importing only specific data into DataSets:
- Which sheets to import
- Which row to designate header (per sheet!)
- Which columns to import (per sheet!)
- Which rows to import (per sheet!)

A solution for this will probably require some funky configuration syntax or callbacks mechanism. I'm totally open to suggestions for what this could look like :)

**Comment by andersnm** [comment]
Here's an example what the configuration classes and usage could look like initially.

The goals:
- More flexible alternative to `IsFirstRowAsColumnHeaders`
- Use any row for column header, not only the first
- Retain capability of designating row headers per sheet - currently `IsFirstRowAsColumnHeaders` is read/write, and affects the reader behavior after `NextResult()`
- Retain support for `IDataReader.GetName()`, which by definition makes columnn header handling a low level feature on the readers (as opposed to being handled in the DataSet extensions)

```C#
public class ExcelSheetConfiguration
{
	public bool UseHeaderRow { get; set; }

	public Action<IExcelDataReader> ReadHeaderRow { get; set; }
}

public class ExcelReaderConfiguration
{
	public Func<IExcelDataReader, ExcelSheetConfiguration> ConfigureSheet { get; set; }

	public bool ConvertOaDate { get; set; }

	public ReadOption ReadOption { get; set; }
}
```

The `ConfigureSheet` callback would be invoked once per sheet to specify potentially different behavior per sheet. E.g first sheet can have column headers, but not the 2nd sheet.

Example usage, create a reader without column headers:

```C#
// By default the reader does not use column headers:
var reader = ExcelReaderFactory.CreateReader(strm);

// Or explicitly:
var reader = ExcelReaderFactory.CreateReader(strm, 
	new ExcelReaderConfiguration() {
		ConfigureSheet => (sheet) new ExcelSheetConfiguration() {
			UseHeaderRow = false
		}
	}
);
```

To create a reader with column headers from the first row, set `UseHeaderRow = true` in the sheet configuration. 

```C#
var reader = ExcelReaderFactory.CreateReader(strm, 
	new ExcelReaderConfiguration() {
		ConfigureSheet => (sheet) new ExcelSheetConfiguration() {
			UseHeaderRow = true,
			ReadHeaderRow = (reader) => {}
		}
	}
);
```

The callback passed to ReadHeaderRow is optional, and is only invoked if `UseHeaderRow = true`. By default the first row becomes the header, but can advance the reader to any row:

```C#
var reader = ExcelReaderFactory.CreateReader(strm, 
	new ExcelReaderConfiguration() {
		ConfigureSheet => (sheet) new ExcelSheetConfiguration() {
			UseHeaderRow = true,
			ReadHeaderRow = (reader) => {
				// Skip the first two rows, use the third row as header:
				reader.Read(); 
				reader.Read(); 
			}
		}
	}
);
```

An example where only the sheet named "Sheet1" has column names:

```C#

var reader = ExcelReaderFactory.CreateReader(strm, 
	new ExcelReaderConfiguration() {
		ConfigureSheet => (sheet) {
			if (sheet.Name == "Sheet1") {
				return new ExcelSheetConfiguration() {
					UseHeaderRow = true
				};
			} else {
				return ExcelSheetConfiguration();
			}
		}
	}
);
```

Possible issues:
- Too complex/flexible/verbose?
- The callbacks are invoked during `Read()`, there could be unknown pitfalls when callbacks call `Read()` or other methods on the reader
- (afaik) Syntax differences when called from net20 clients

Although this should be pretty straight-forward to implement.

**Comment by andersnm** [comment]
In the master branch `IsFirstRowAsColumnHeaders` *only* affects the AsDataSet() method. It has no effect when using the reader directly, and `IDataRecord.GetName()` throws a NotImplementedException.

The develop branch has some refactorings where `IDataRecord.GetName()` is implemented to return column names when `IsFirstRowAsColumnHeaders` is set.

Now, looking at making `IsFirstRowAsColumnHeaders` more flexible, it no longer feels right to have column names handling at the lowest level in the reader. The `ConfigureSheet` callback stuff make more sense to do only while populating the DataSet.

The readers could simplified and know nothing about column names, and simply treat the sheets as raw grids. Thus:
- Remove `IsFirstRowAsColumnHeaders` from the IExcelDataReader interface
- Remove all `_cellNames` column name handling from low level readers, throw NotImplementedException in GetName() again
- Add AsDataSet configuration object parameter with ConfigureSheet callback for per-sheet column handling

**Comment by andersnm** [comment]
All initial options have been moved to configuration objects, and new options can be added without too much hassle, so this is essentially done.
