### ISSUE TITLE
Expose cell format information

### ISSUE THREAD

**Issue by andersnm** [ExcelDataReader/ExcelDataReader#215]
Some feature requests/issues have to do with more control over cell formatting: #15, #31, #39, #47, #53, #95, #178

Currently ExcelDataReader uses the cell format/style data to interpret values in number cells:
- if ConvertOaDate is true and cell has built-in date format: convert value to DateTime
- if ConvertOaDate is true and cell has custom date format: convert value to DateTime
- if cell has the '@' custom format: convert value to string using default formatting rules

After this the cell format/style is discarded. 

It would be more flexible if ExcelDataReader didn't apply any formatting up front, but instead let users retreive the raw values and formats and apply formatting as needed. F.ex through one or two new public IExcelDataReader methods `GetRawValue()` and `GetRawFormat()`

This would be key to address the above issues; providing a more flexible mechanism to apply formatting as needed. This is also an opportunity to refactor/unify the reader internals dealing with OADates and formatting. There are some concerns with backwards compatibility for existing users doing formatting trickery.

**Comment by appel1** [comment]
Something to consider that could be relaterat to this is exposing more cell metadata like text indentation. 

For GetValue I think it'd be good if it always converted and throws for oadates that can't be represented as DateTime. Combined with a way to get the "raw" value I think it would be quite flexible. Then we could get rid of the whole concertoadate parameter. There's been so many breaking changes in 3.0 so I think this wouldn't make things worse. The current approach of throwing in Read with no way to resume isn't very nice.

**Comment by andersnm** [comment]
In context of #238, the only thing needed for this enhancement is a new function `IExcelDataReader.GetFormat(index)` to obtain the format string for a cell, returns f.ex `General`, `D-MMM-YY`, `#,##0.00`, `@` etc. GetRawValue() isn't really needed.

Additionally, the library could provide utility helper functions for callers to format values based on format strings, but is not directly within the scope of this issue.

**Comment by appel1** [comment]
Sounds good to me.

**Comment by andersnm** [comment]
> provide utility helper functions for callers to format values based on format strings,

This sounds like a great challenge, and not knowing any better I started one here:

https://github.com/andersnm/ExcelNumberFormat

This library is almost usable, and technically could replace the `FormatReader` class in ExcelDataReader already. All the date-related tests required by ExcelDataReader pass. Nearly all the tests adapted from the ssf project pass as well (although many tests are not adapted yet). The failing ssf tests have to do with disagreements in whitespace layout in fractions with more than 7 denominator placeholders (!).

I did some checking for existing Excel compatible number format parsers/renderers. There was one for .NET as part of a commercial product (cannot find this anymore!), and some for Java and Javascript (Apache POI and SheetJS/ssf). But not really anything for .NET.

It is anyhow too soon to merge into ExcelDataReader, and is best kept in a separate repo while considering the options. Bug reports and PR's welcome :-)

**Comment by kendallb** [comment]
Might I suggest something similar to what ClosedXML has which would be a GetFormattedString() function so if you simply want the value formatted as the user would see it in excel as a string, you can call that and not have to deal with the actual formatting information. For a lot of uses this would be all you really need rather than having to interpret the formatting yourself?

**Comment by andersnm** [comment]
Yes, something like that should definitely be supported. 

I've just committed a new function `IExcelDataReader.GetNumberFormatString()`, but the format string isn't so useful in itself. 

The next step should be to replace the FormatReader class with the ExcelNumberFormat library, and expose the parsed NumberFormat instance instead of just the string. This comes with helpers for things like GetFormattedString().

**Comment by kendallb** [comment]
Right, that would be cool. I assume it would also work with DateTime formatting as well?

**Comment by kendallb** [comment]
Just ran into issues with some legacy code in that it needs to see the formatted data as a string, because we interpret the cell as either a dollar value if it is $0.20 or as a percentage if it is 20%. Right now it comes in as 0.20 as a double, so we cannot currently identify this usage.

For now I will probably have to revert back to using OpenXML for reading in the short term to work around this. How much work is left to be able to support a GetStringFormatted() function to get a cell formatted using the Excel formatting information the way the user would see it? Is there anything I can work on to help get that completed?

**Comment by andersnm** [comment]
Example using the new `GetNumberFormatString()` and `NumberFormatString.Format()` methods in the next version:

```c#
string GetFormattedValue(IExcelDataReader reader, int columnIndex, CultureInfo culture) {
	var format = reader.GetNumberFormatString(columnIndex);
	var value = reader.GetValue(columnIndex);
	if (format != null) {
		return format.Format(value, culture);
	}
	return Convert.ToString(value, culture);
}
```

Been wondering to add another method `NumberFormatString.Round()` to return numeric inputs as numbers still, but with number formatting rules applied - i.e round to number of decimals, percent multiply, thousands division.

**Comment by andersnm** [comment]
FYI! Due to unforseen interest in number formatting code, there's now a Nuget package built from a separate project: https://www.nuget.org/packages/ExcelNumberFormat

The plan is to remove the local fork from ExcelDataReader, and instead add a dependency on the ExcelNumberFormat package to keep the formatting code in one place. (this is partly why 3.3 isn't out yet, besides me taking a break for the time being)

**Comment by appel1** [comment]
Could this be designed so that we wouldn't need the additional dependency if you don't use the number formatting?

**Comment by andersnm** [comment]
Currently the parsed number format is used to determine if the cell value is a DateTime or TimeSpan. 

So we could revert to the old FormatReader class again and use that internally to detect types (and implement TimeSpans), and refer users to the ExcelNumberFormat package for more advanced formatting purposes. That'd be ideal in a sense, but there would also be two number format parsers.

Just to mention, personally I'd like to avoid the dependency as well, so I appreciate any discussion about it

**Comment by appel1** [comment]
I'd prefer that approach I think.

**Comment by andersnm** [comment]
Ok, cool. Might as well keep maintaining the fork of the number format _parser_ bits from the ExcelNumberFormat project, but exclude the _formatting_ bits, since we only need to check whether a format contains certain tokens and is already in the repo. The parser should be fairly stable onwards, and is imo preferable over the previous regex stuff. 

Essentially, this means to revert IExcelDataReader.GetNumberFormatString() back to returning a string again, and update the formatting section in the README. (and delete any unused formatting code)

**Comment by kendallb** [comment]
As long as I can get real formatted strings from ExcelDataReader, I am cool. That's the main thing we need, is to be able to read strings and have them formatted correctly.
