### ISSUE TITLE
Handle xls files with row content spread over multiple blocks

### ISSUE THREAD

**Issue by appel1** [ExcelDataReader/ExcelDataReader#217]
I think we can detect this in ReadWorkSheetGlobals and then read the whole sheet for this special case in ReadNextBlock.

**Comment by andersnm** [comment]
Btw, I'm rewriting the xls row reading code to using yield right now. Interesting issue though, wasn't aware this could happen, but I'm not surprised. Do you have xls?

**Comment by appel1** [comment]
It's unfortunate that Excel is so forgiving. And yes, I have a sample xls file.
