### ISSUE TITLE
ISO 8601 format cells not supported

### ISSUE THREAD

**Issue by jameseod** [ExcelDataReader/ExcelDataReader#221]
I have a xlsx spreadsheet where the DataSet returned by AsDataSet() contains bad dates (1899-1-1) rather than the values shown by Excel.

The XML of the relvant cells are like this:

        <c r="A2" s="1" t="d">
            <v>2017-03-16</v>
        </c>

Looking at the ECMA spec, t="d" means that it's a date in ISO 8601 format.

Is this expected to work already?  If not, is there any reason to believe the fix is more than:

```
                        else if (aT == "b") //// boolean
                        {
                            o = _xmlReader.Value == "1";
                        }
+                        else if (aT == "d") //// ISO 8601 date
+                        {
+                            DateTime dt;
+                            if (o != null && DateTime.TryParseExact(o.ToString(), "yyyy-MM-dd", null, DateTimeStyles.None, out dt))
+                                o = dt;
+                        }
                        else if (aS != null) //// if something else
```

Thanks

**Comment by andersnm** [comment]
Fixed
