### ISSUE TITLE
Reading Percentage Column from excel

### ISSUE THREAD

**Issue by iMstry** [ExcelDataReader/ExcelDataReader#223]
I have few percentage column in excel but somehow I am not able to export it to datatable.

Any suggestion ?

**Comment by appel1** [comment]
What happens? What did you expect to happen? Do you have a sample Excel file we could use as a test case?

**Comment by JackMstry** [comment]
Hi,
I have attached a test case for you.
[Charts.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/1094316/Charts.xlsx)

Thanks

**Comment by appel1** [comment]
Currently cell formatting is not available. See #215.

**Comment by JackMstry** [comment]
Thanks for your reply But If I want to do It how can I do it ?
 any suggestion?

**Comment by appel1** [comment]
You'd have to determine what cell contains percentages yourself and format the values yourself.

**Comment by JackMstry** [comment]
Okay will give it a try 

> Thanks :)

`

**Comment by andersnm** [comment]
ExcelDataReader returns number format strings now, which can be used with the [ExcelNumberFormat](https://github.com/andersnm/ExcelNumberFormat) library to obtain formatted values with f.ex percentages.
