### ISSUE TITLE
Request: Excel Data Writer

### ISSUE THREAD

**Issue by dan64** [ExcelDataReader/ExcelDataReader#23]
I'm impressed by the performance of your library and would be very helpful is could add also the possibility to write a DataSet into an Excel file (xlsx or xls).

Thanks

**Comment by Misiu** [comment]
I know this is a bit old, but I'm searching for library with save to excel functionality. ExcelDataReader is awesome. ExcelDataWriter would solve my problem.
I need 3 options: save list of objects, datatable and datareader.
I'm not a C# expert, but I can help if You would consider creating such library.

**Comment by wizardgsz** [comment]
I think everything you need is here, just link Microsoft Open XML SDK library:
http://mikesknowledgebase.azurewebsites.net/pages/CSharp/ExportToExcel.htm

**Comment by srehmanali** [comment]
Hi there, I have tried many of the libraries and ExcelDataReader proved to be best from performance and code maintainability point of view. I understand this post is way too old request but if you can add writing capability it will be very helpful.

Thanks.

**Comment by jhofran** [comment]
https://github.com/mrjono1/FastExcel

**Comment by wizardgsz** [comment]
https://mikesknowledgebase.azurewebsites.net/pages/csharp/exporttoexcel.htm

**Comment by graysuit** [comment]
Recently, I also needed same writer for excel and found NPOI to be best & fast excel writer without excel need to be installed : https://github.com/nissl-lab/npoi
This package works on even .NET v2.0+ : https://www.nuget.org/packages/NPOI/2.3.0
Example: https://stackoverflow.com/a/68073288/14919621
