### ISSUE TITLE
Support BIFF2-4 xls worksheet documents

### ISSUE THREAD

**Issue by andersnm** [ExcelDataReader/ExcelDataReader#234]
These files contain single sheets in pretty much the same format as BIFF5 and 8, but not embedded in a compound document. F.ex the BIFF3.xls test file seems to parse after some dirty hacking. Would be nice to support these for completeness.

**Comment by appel1** [comment]
BIFF5 and 8 doesn't require compound document either but I've never seen any in the wild if we're talking completeness.

**Comment by andersnm** [comment]
This commit also belongs here: 203c33db7db68fd5571e7a1db00b28357a43a26f (typed wrong issue #! :( )

Afaik the only remaining task is to parse the IXFE record - "Index to XF", which currently prevents dates in BIFF2 from working.

The approach taken allows parsing both raw BIFF5-8 workbooks as well as BIFF2-4 worksheet documents.
