### ISSUE TITLE
xls dimensions' LastColumn uses only lower 8 bits

### ISSUE THREAD

**Issue by andersnm** [ExcelDataReader/ExcelDataReader#237]
There is a typo in XlsDimensions.cs when parsing LastColumn in BIFF8:

```c#
FirstRow = ReadUInt32(0x0);
LastRow = ReadUInt32(0x4);
FirstColumn = ReadUInt16(0x8);
LastColumn = (ushort)((ReadUInt16(0x9) >> 8) + 1);

// But should be: (and fixing FieldCount = dims.LastColumn later)
LastColumn = ReadUInt16(0xA);
```

But then this test fails:

```c#
        [TestMethod]
        public void IfNoDimensionDetermineFieldCountByProcessingAllCellColumnIndexes()
        {
            // This xls file has a row record with 256 columns but only values for 6.
            using (var excelReader = ExcelReaderFactory.CreateBinaryReader(Configuration.GetTestWorkbook("Test_Git_Issue_145")))
            {
                var ds = excelReader.AsDataSet();
                Assert.AreEqual(6, ds.Tables[0].Columns.Count);
            }
        }

Message:
   Expected: 6
   But was:  256
```

Presumably the test should assert for 256 columns when all 16 bits are read.

Also: the original code adds 1 to LastColumn, and later subtracts 1 when setting FieldCount. This is inconsistent from BIFF5, which does not add anything to LastColumn - but yet subtracts 1 on FieldCount. Although it still works: the last column is removed on BIFF3-5, but restored again in the first scanning pass.

**Comment by appel1** [comment]
Strange. I thought that test case didn't have any dimension record.
