### ISSUE TITLE
Is there a way to open password protected sheets? 

### ISSUE THREAD

**Issue by VhatAmI** [ExcelDataReader/ExcelDataReader#242]
I am curious if this library supports opening password-protected sheets like EPPlus or not? 

Thanks

**Comment by appel1** [comment]
No, that is currently not supported.

**Comment by andersnm** [comment]
This could be a useful feature. @appel1  How complete is the current xls password code in XlsBiffStream? 

Apparently openxml uses regular zip passwords, but System.IO.Compression does not support reading password-protected zip-files. Which brings us back to #56. 

We can either use SharpZipLib on all targets, switch to DotNetZip, or write/embed a custom zip-implementation using System.IO.Compression.DeflateStream. Personally leaning towards the custom one :)

**Comment by appel1** [comment]
It only handles the specific encryption used in many documents when some content is locked. Just did the minimum we needed at the time for work.

**Comment by andersnm** [comment]
This is implemented for all common password protection schemes. 

There are some isses I'm aware of:
- XLSX documents protected with DES and RC2 open on net20/net45, but throw an exception on netstandard. Afaik these ciphers are being added to the next major release of netstandard 2.0 scheduled for Q3 2017, but not sure if that means they will also become available on netstandard1.3.
- XSLX documents protected with ciphers using CFB mode open on net20/net45, but throw an exception on netstandard.
- XLS/XLSX documents protected with "Extensible Encryption" are not supported at all. This is a scheme for custom encryption providers, and IMHO outside the scope of the initial implementation
- No XLSX tests for CFB mode
