### ISSUE TITLE
Get property 'CodeName' per Worksheet?

### ISSUE THREAD

**Issue by montelyno** [ExcelDataReader/ExcelDataReader#245]
Hi there!

First of all thanks for your really good lib, it helps us a lot!!! 

I have a very specific question to the Microsoft WorkSheet property: CodeName.
Is there a way to extract this property?

My case is, that i want to export multipe WorkSheets with SSRS and then later import this file again.
The user can change the indexes of the sheets, the names etc. so i am searching for an internal reference the user can´t change. There comes CodeName.

Is that possible or to specific for MS?

Kind regards and greetings from Germany

**Comment by andersnm** [comment]
Hi!

This is not supported at the moment, but sounds useful. I'm sure it would be relatively easy to implement

**Comment by montelyno** [comment]
Short hint in addition: There is also a collection in each WorkSheet called "CustomProperties", that could also fit. Basically it is just something like a Dictionary<string,string>.
I think this one is more generic.

https://msdn.microsoft.com/en-us/library/microsoft.office.tools.excel.worksheet.customproperties(VS.80).aspx

**Comment by andersnm** [comment]
CodeName is implemented. Moved the request for custom properties to a separate issue. Thanks for the suggestion @montelyno
