### ISSUE TITLE
Expose function to perform header validation

### ISSUE THREAD

**Issue by jnyrup** [ExcelDataReader/ExcelDataReader#249]
Each month I get some data in a file with .xls extension.
Unfortunately this is some times a binary Excel file and sometimes a plain csv file.

Currently I try parse it as an Excel file and catch `HeaderException` if it was a csv content month.

To avoid catches exceptions like this, it would be nice if the logic to validate the header was exposed.

**Comment by appel1** [comment]
Perhaps we could add a TryCreateReader method to ExcelReaderFactory. I guess it should return false both if the given file is not an Excel file and if it is an Excel file but corrupted.

**Comment by andersnm** [comment]
The absolutely simplest for us would be to refactor the probing code in CreateReader into a couple new public methods f.ex `CanCreateBinaryReader`, `CanCreateOpenXmlReader`, and `CanCreateReader`. 
They will at least reject all CSVs except those starting with "PK". And accept any .zip files as valid OpenXml...

Any more in-depth probing will require creating the reader instance in a try/catch block, but I'm not sure if this belongs to the library.

**Comment by appel1** [comment]
Sure, with the downside that we'd open and probe the file twice in most cases. Presumably the user always want to open the file if the check is successful. But you're right, the user of the library might as well wrap the CreateReader call in a try/catch themselves. Would be more efficient in most cases. 

Perhaps what we should do is better document what exceptions we throw.

**Comment by jnyrup** [comment]
Just to have some code examples: 

With `CreateReader`:
```csharp
using (var stream = File.Open(filePath, FileMode.Open, FileAccess.Read))
{
	try
	{
		using (var reader = ExcelReaderFactory.CreateReader(stream))
		{
		}
	}
	catch (NotSupportedException)
	{
		// read as csv
	}
}
```

With `CreateBinaryReader`:
```csharp
using (var stream = File.Open(filePath, FileMode.Open, FileAccess.Read))
{
	try
	{
		using (var reader = ExcelReaderFactory.CreateBinaryReader(stream))
		{
		}
	}
	catch (HeaderException)
	{
		// read as csv
	}
}
```

With `TryCreateReader`:
```csharp
using (var stream = File.Open(filePath, FileMode.Open, FileAccess.Read))
{
	IExcelDataReader reader = null;

	if (ExcelReaderFactory.TryCreateReader(stream, out reader))
	{
		using (reader)
		{
		}
	}
	else
	{
		// read as csv
	}
}
```

With `CanCreateReader`:
```csharp
using (var stream = File.Open(filePath, FileMode.Open, FileAccess.Read))
{
	if (ExcelReaderFactory.CanCreateReader(stream))
	{
		using (var reader = ExcelReaderFactory.CreateReader(stream))
		{
		}
	}
	else
	{
		// read as csv
	}
}
```
