### ISSUE TITLE
Issue when reading formatted values in cell

### ISSUE THREAD

**Issue by f1ssl** [ExcelDataReader/ExcelDataReader#250]
Hey everybody,

could it be possible that the method of IDataRecord inherited and called from IExcelDataReader: "GetString(int i)" serves a blank string when there are special formatting rules in the excel sheet?

in my example there is a string CO2-Value in which the character "2" is subscripted.

addionally i get an empty string if the cell value consists out of text in two different colors.
for example: hello world. hello in red and world in blue.

Is there and advise anywhere which tells me what kind of formatting is allowed?

For now im working around this by reading a copy of the original excel file without any special formats.

Anybody else may have this behavior?

**Comment by appel1** [comment]
Could you provide a sample document that uses the formatting you want to process so we can take a look?

**Comment by andersnm** [comment]
Can confirm this happens with xlsx, but xls looks OK.

There's a chance this was recently introduced: 38e57191f5858ffc3a62999ce5ca1ce35acc7ce5 :( Before that it combined all <t> elements, but now its only parsing the top level ones.

[colors.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/1156313/colors.zip)

**Comment by f1ssl** [comment]
Here's an example with a subscripted value in A2 and a colored value in A3.

[example.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/1156332/example.xlsx)

**Comment by andersnm** [comment]
@f1ssl Thanks for the bugreport and sample!

**Comment by f1ssl** [comment]
@andersnm you're welcome.
Im sorry, but how i can get the new version now?
Im relatilely inexperienced to github. I'm using Visual Studio with the NuGet Package Manager ... could anybody give me a short advise what to now to fix this error for me?
Thanks

**Comment by andersnm** [comment]
@f1ssl I will try and release a new version on nuget.org within a week or so. 

Until then there are unofficial Nuget packages on the build server:
https://ci.appveyor.com/project/andersnm/exceldatareader/build/build-101/artifacts

You can download these locally and configure a Nuget.config such that the package manager finds them:
https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file

**Comment by f1ssl** [comment]
Thanks a lot
