### ISSUE TITLE
ExcelMapping to objects

### ISSUE THREAD

**Issue by hughbe** [ExcelDataReader/ExcelDataReader#252]
Hi @andersnm,

This may be the wrong place to put this (I couldn't find an email address, and also didn't want to seem spammy), but here goes.

I've developed a library that allows mapping rows from an excel sheet to C# objects such as classes and structs. It builds upon ExcelDataReader in a similar way to the `ToDataSet` extension.

I've named the library [ExcelMapper](https://github.com/hughbe/excel-mapper/)

I've found it to be very customizable as you can override the way mapping is done and provide custom classes. You can see more details in the README, where I've included a bunch of examples. The library is pretty well unit tested so you can see what it can do.

Here's the most basic example. It takes a sheet containing a header and multiple rows. It can automatically map each row to a C# object. You can see how to customize the mapping more in the README

| Name          | Location         | Attendance | Date       | Link                    | Revenue | Successful | Cause   | 
|---------------|------------------|------------|------------|-------------------------|---------|------------|---------| 
| Pub Quiz      | The Blue Anchor  | 20         | 18/07/2017 | http://eventbrite.com   | 100.2   | TRUE       | Charity | 
| Live Music    | The Raven        | 15         | 17/07/2017 | http://ticketmaster.com | 105.6   | FALSE      | Profit  | 
| Live Football | The Rutland Arms | 45         | 16/07/2017 | http://facebook.com     | 263.9   | TRUE       | Profit  | 

```cs
public enum EventCause
{
    Profit,
    Charity
}

public class Event
{
    public string Name { get; set; }
    public string Location { get; set; }
    public int Attendance { get; set; }
    public DateTime Date { get; set; }
    public Uri Link { get; set; }
    public EventCause Cause { get; set; }
}

// ...

using (var stream = File.OpenRead("Pub Events.xlsx"))
using (var importer = new ExcelImporter(stream))
{
    ExcelSheet sheet = importer.ReadSheet();
    Event[] events = sheet.ReadRows<Event>().ToArray();
    Console.WriteLine(events[0].Name); // Pub Quiz
    Console.WriteLine(events[1].Name); // Live Music
    Console.WriteLine(events[2].Name); // Live Football
}

```

The library is inspired by CsvHelper, but has a couple of differences. It also supports things like arrays and nested objects, which is very powerful for converting excel databases to NOSQL JSON databases.

I'd be really interested to see what you think of this project.  We're using this in production to map rows from multiple sheets to objects and then using them inside C#. So it's been guided by our use case. I'm looking to release it as a library that is sharable by others.

I'd like to see if you have any opinions on the library and could help influence the direction of the library at the start. But don't worry, this is not a request for you to become a maintainer or for you to take it under the ExcelDataReader organisation, so please don't feel pressured!

Thansk

**Comment by andersnm** [comment]
@hughbe, I've only looked at ExcelMapper briefly, and looks like a useful and high quality project to me. Wish I had more time to try it out. I don't mind adding a link to your project/packages from our README if/when it's alright with you.
