### ISSUE TITLE
How do you access individual sheets with excel data reader

### ISSUE THREAD

**Issue by nafberger** [ExcelDataReader/ExcelDataReader#253]
Hi I am using the ExcelDataReader (not the dataset, because I am in a net. Core project. how to you access the records in the third sheet. how do you work with the sheets collection. please clarify.
Big Thanks. My email is nafberger@gmail.com

**Comment by appel1** [comment]
Call NextResult() to move the reader to the next sheet. 

https://github.com/ExcelDataReader/ExcelDataReader#how-to-use

```csharp
// 1. Use the reader methods
do {
  while (reader.Read()) {
    // reader.GetDouble(0);
  }
} while (reader.NextResult());
```

**Comment by nafberger** [comment]
Oh thanks
