### ISSUE TITLE
AsDataSet not works or deprecated?

### ISSUE THREAD

**Issue by marcdeveloper** [ExcelDataReader/ExcelDataReader#254]
Hi, I recently installed ExcelDataReader, I try to use reader.AsDataSet, but this method does not exist in recent version.

Is this a bug? or this method is changed in this version? If I use this as is explained in documentation it not works.

Thanks.

**Comment by andersnm** [comment]
Hi, AsDataSet() has been moved to a separate package. 

Install the `ExcelDataReader.DataSet` package to use the AsDataSet() method.

**Comment by marcdeveloper** [comment]
I think It would be interesting add this to documentation
