### ISSUE TITLE
IsFirstRowAsColumnNames alternative

### ISSUE THREAD

**Issue by dcarl1** [ExcelDataReader/ExcelDataReader#258]
Just updated to 3.1 and have lost the IsFirstRowAsColumnNames - what is the new solution for this?

**Comment by andersnm** [comment]
Hi,

This property was moved to a configuration parameter on the AsDataSet() method:

1. Make sure the project has a reference to the `ExcelDataReader.DataSet` package

2. Remove the line of code with `IsFirstRowAsColumnNames`

3. Change the call to AsDataSet() to something like this:

```c#
var result = reader.AsDataSet(new ExcelDataSetConfiguration() {
	ConfigureDataTable = (_) => new ExcelDataTableConfiguration() {
		UseHeaderRow = true
	}
});
```
