### ISSUE TITLE
IsFirstRowAsColumnNames property not found

### ISSUE THREAD

**Issue by PLManeely** [ExcelDataReader/ExcelDataReader#261]
I'm trying to set the IsFirstRowAsColumnNames property and the compiler isn't finding it.  I pulled the latest stable release (3.1.0) of ExcelDataReader and ExcelDataReader.Dataset.
Visual Studio has the following compiler error:

_Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IExcelDataReader' does not contain a definition for 'IsFirstRowAsColumnNames' and no extension method 'IsFirstRowAsColumnNames' accepting a first argument of type 'IExcelDataReader' could be found (are you missing a using directive or an assembly reference?)	Workstation	C:\DBPS\dbps\source\Client\Workstation\TailoredRecordEditor\FormTailoredRecordEditor.cs	2304	Active_

Is there another package I need to install?

Sorry for the Nub question...

**Comment by andersnm** [comment]
Hi,

This property was moved to a configuration parameter on the AsDataSet() method:

1. Make sure the project has a reference to the `ExcelDataReader.DataSet` package

2. Remove the line of code with `IsFirstRowAsColumnNames`

3. Change the call to AsDataSet() to something like this:

```c#
var result = reader.AsDataSet(new ExcelDataSetConfiguration() {
	ConfigureDataTable = (_) => new ExcelDataTableConfiguration() {
		UseHeaderRow = true
	}
});
```

**Comment by andersnm** [comment]
Have updated README.md in an effort to make the above more prominent.

**Comment by vs6681** [comment]
No, above solution didnt worked

**Comment by PaulGrobbelaar** [comment]
Install Nuget ExcelDataReader.DataSet
Add: using System.Data;

**Comment by vs6681** [comment]
![image](https://user-images.githubusercontent.com/22222961/36245921-5428b3da-1253-11e8-9a28-dbab5c8046ba.png)

Here you go

**Comment by KALELDC** [comment]
Instale Nuget ExcelDataReader.DataSet 

using ExcelDataReader;
using Excel;

La librería Excel obligará a que ahora la fila sea : 

Excel.IExcelDataReader excelReader = Excel.ExcelReaderFactory.CreateOpenXmlReader(stream);
excelReader.IsFirstRowAsColumnNames = true;

**Comment by kenleyte11** [comment]
how to visual basic this?

**Comment by kenleyte11** [comment]
> Hi,
> 
> This property was moved to a configuration parameter on the AsDataSet() method:
> 
> 1. Make sure the project has a reference to the `ExcelDataReader.DataSet` package
> 2. Remove the line of code with `IsFirstRowAsColumnNames`
> 3. Change the call to AsDataSet() to something like this:
> 
> ```cs
> var result = reader.AsDataSet(new ExcelDataSetConfiguration() {
> 	ConfigureDataTable = (_) => new ExcelDataTableConfiguration() {
> 		UseHeaderRow = true
> 	}
> });
> ```

How to visual basic this?

**Comment by andersnm** [comment]
Hi @kenleyte11, check this: https://stackoverflow.com/a/46949225

**Comment by kabirfaisal1** [comment]
Hi Keneleyte 
var result = reader.AsDataSet(new ExcelDataSetConfiguration() {
	ConfigureDataTable = (_) => new ExcelDataTableConfiguration() {
		UseHeaderRow = true
	}
});

not working for me, I am getting error on reader (the name 'reader does not exist in the current context')

**Comment by kenleyte11** [comment]
> Hi @kenleyte11, check this: https://stackoverflow.com/a/46949225

Thank you.. this works
![{62AF1695-D9BE-46FF-8E57-244E5D36EDDE}](https://user-images.githubusercontent.com/42526594/62830462-36841500-bc42-11e9-87c0-3af86eae86c9.png)

**Comment by kenleyte11** [comment]
> Hi Keneleyte
> var result = reader.AsDataSet(new ExcelDataSetConfiguration() {
> ConfigureDataTable = (_) => new ExcelDataTableConfiguration() {
> UseHeaderRow = true
> }
> });
> 
> not working for me, I am getting error on reader (the name 'reader does not exist in the current context')

try to do this.....


Using stream As Stream = File.Open(ExcelFile, FileMode.Open, FileAccess.Read)
				Using reader = ExcelReaderFactory.CreateReader(stream)
					Dim x_config As New ExcelDataSetConfiguration
					x_config.ConfigureDataTable = Function(tableReader) New ExcelDataTableConfiguration() With {.UseHeaderRow = True}
					Dim dset As DataSet = reader.AsDataSet(x_config)
