### ISSUE TITLE
AsDataSet() and IsFirstRowAsColumnNames not recognized in version 3.1.0

### ISSUE THREAD

**Issue by Mickdep** [ExcelDataReader/ExcelDataReader#262]
Hey,

Today i updated the ExcelDataReader package to its latest version and i found that it is not working anymore. It doesnt recognize AsDataSet() and IsFirstRowAsColumnNames as properties/methods anymore. My project won't build now.
A namespace such as ExcelDataReader.DataSet doesn't exist either.

When i revert the update to an older verison its working again(2.1.2.3)

My code atm:

            IExcelDataReader excelReader = fileExtension.ToLower().Equals("xls") ? ExcelReaderFactory.CreateBinaryReader(inputStream) : ExcelReaderFactory.CreateOpenXmlReader(inputStream);
            DataSet result = excelReader.AsDataSet();   <----- Won't work
            excelReader.IsFirstRowAsColumnNames = false;    <----- Won't work
            DataTable table = result.Tables[0];

**Comment by andersnm** [comment]
Please see https://github.com/ExcelDataReader/ExcelDataReader/issues/261#issuecomment-321459098

**Comment by tgaadmire** [comment]
Found this problem too. All documentation indicates that this should be possible, but it seems to have been removed, and documentation not updated.

**Comment by cpatterson1177** [comment]
I just came across this today as well. I found out that AsDataSet() is now part of ExcelDataReader.Dataset. I have not been able to find out what happened to IsFirstRowAsColumnNames

**Comment by andersnm** [comment]
This issue seems to get a lot of traffic from search engines, so I'll replicate the newly added section in the README based on https://github.com/ExcelDataReader/ExcelDataReader/issues/261#issuecomment-321459098

## Important note when upgrading from ExcelDataReader 2.x

ExcelDataReader 3 had some breaking changes, and older code may produce error messages similar to:

```
'IExcelDataReader' does not contain a definition for 'AsDataSet'...
'IExcelDataReader' does not contain a definition for 'IsFirstRowAsColumnNames'...
```

To fix:

1. Make sure to rename any `Excel` namespace references in the code to the new namespace `ExcelDataReader`

2. Make sure the project has a reference to the `ExcelDataReader.DataSet` package to use `AsDataSet()`

3. Remove the line of code with `IsFirstRowAsColumnNames` and change the call to AsDataSet() to something like this:

```c#
var result = reader.AsDataSet(new ExcelDataSetConfiguration() {
	ConfigureDataTable = (_) => new ExcelDataTableConfiguration() {
		UseHeaderRow = true
	}
});
```

**Comment by PaulGrobbelaar** [comment]
Install Nuget ExcelDataReader.DataSet
Add: using System.Data;

**Comment by KALELDC** [comment]
Instale Nuget ExcelDataReader;
Instale Nuget ExcelDataReader.DataSet 

using ExcelDataReader;
using Excel;
using System.Data;


La librería Excel obligará a que ahora la fila sea : 

Excel.IExcelDataReader excelReader = Excel.ExcelReaderFactory.CreateOpenXmlReader(stream);
excelReader.IsFirstRowAsColumnNames = true;

**Comment by camap** [comment]
> This issue seems to get a lot of traffic from search engines, so I'll replicate the newly added section in the README based on [#261 (comment)](https://github.com/ExcelDataReader/ExcelDataReader/issues/261#issuecomment-321459098)
> 
> ## Important note when upgrading from ExcelDataReader 2.x
> ExcelDataReader 3 had some breaking changes, and older code may produce error messages similar to:
> 
> ```
> 'IExcelDataReader' does not contain a definition for 'AsDataSet'...
> 'IExcelDataReader' does not contain a definition for 'IsFirstRowAsColumnNames'...
> ```
> 
> To fix:
> 
> 1. Make sure to rename any `Excel` namespace references in the code to the new namespace `ExcelDataReader`
> 2. Make sure the project has a reference to the `ExcelDataReader.DataSet` package to use `AsDataSet()`
> 3. Remove the line of code with `IsFirstRowAsColumnNames` and change the call to AsDataSet() to something like this:
> 
> ```cs
> var result = reader.AsDataSet(new ExcelDataSetConfiguration() {
> 	ConfigureDataTable = (_) => new ExcelDataTableConfiguration() {
> 		UseHeaderRow = true
> 	}
> });
> ```

it works for me, thanks so much
