### ISSUE TITLE
ExcelDataReader.DataSet - .net standard 2.0 support ETA

### ISSUE THREAD

**Issue by SergeyRudakov** [ExcelDataReader/ExcelDataReader#266]
Hello
It seems ExcelDataReader is compatible with .net standard 2.0 but ExcelDataReader.DataSet is not.

Do you have plans to migrate ExcelDataReader.DataSet to the newest .net standard 2.0?
I can remove DataSet dependences but would better wait for new version if it is coming soon.
Thanks,

**Comment by andersnm** [comment]
Yes, been doing some testing already and the next version of ExcelDataReader should support netstandard2.0 - hopefully within a week or two

**Comment by SergeyRudakov** [comment]
Good, Since .NET Standard 2.0 fully supports DataSets - it was not a problem for me to include ExcelDataReader.DataSet project to solution and retarget it to 2.0.  It compiles well.
