### ISSUE TITLE
No data is available for encoding 850

### ISSUE THREAD

**Issue by redowl3** [ExcelDataReader/ExcelDataReader#267]
Hi,

I'm getting an error message when trying to open an xlsx file using ASP.NET Core "No data is available for encoding 850. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method."

Any ideas?  

Many thanks

**Comment by andersnm** [comment]
This sounds almost like the problem described here:
https://github.com/ExcelDataReader/ExcelDataReader#important-note-on-net-core

Do you have a call similar to this somewhere in your initialization code already?
```c#
System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
```

**Comment by redowl3** [comment]
Yes, just read the last bit of your ReadMe and all looks to be working now thanks.  

Awesome library by the way - keep up the great work!

**Comment by felipedourado** [comment]
> This sounds almost like the problem described here:
> https://github.com/ExcelDataReader/ExcelDataReader#important-note-on-net-core
> 
> Do you have a call similar to this somewhere in your initialization code already?
> 
> ```cs
> System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
> ```

Thanks a lot, you help me today!
Save my life and time!
