### ISSUE TITLE
ExcelDataReader GetString(column) exceptions

### ISSUE THREAD

**Issue by SergeyRudakov** [ExcelDataReader/ExcelDataReader#268]
Hello,
I started running reader under .net standard 2.0 and it is throwing errors on type conversion now.

Previous version allow converting values like 0354 to int 354 via GetInt32. This version throws an exception.

The same with GetString(i) method. If underlying type is DateTime, numeric or other - method fails. 
As the result we have to use GetValue or check value's type which makes code less readable and adds more checks.

Is it expected behavior? Is it possible to always return string value from GetString method?

**Comment by andersnm** [comment]
Hi, 

The rationale for this change is somewhat summarized in #239. Essentially for performance reasons and to align with other implementations of the IDataRecord interface. A workaround is to use `Convert.ToString(reader.GetValue(i))` if you want a string.

**Comment by paulirwin** [comment]
@andersnm I think that rationale makes sense as a default, but what about an option in `ExcelReaderConfiguration` to allow for "looser" type conversion via `System.Convert`?

**Comment by andersnm** [comment]
Another workaround/idea is to implement these as a set of new extension methods like AsString(i), AsInt32(i) etc. For example:

```c#
public static namespace ExcelDataReaderConvertExtensions {

	public static string AsString(this IExcelDataReader reader, int i) {
		return Convert.ToString(reader.GetValue(i));
	}

	public static string AsInt32(this IExcelDataReader reader, int i) {
		return Convert.ToInt32(reader.GetValue(i));
	}
	
	///
}
```

Having explicit, separately documented methods for type conversions might be preferable to a behavior-modifying option. Assuming the goal is to address the "loose" nature of Excel spreadsheets with as little code as possible, rather than preserving the behavior/syntax from earlier versions of ExcelDataReader?

**Comment by appel1** [comment]
Why not just use `Convert.ChangeType(reader.GetValue(0), typeof(int))` if you want to read as an int or get an exception if the value can't be converted to an int?

**Comment by andersnm** [comment]
@appel1 I like that idea. The helper methods might look like this:

```c#
public static namespace ExcelDataReaderConvertExtensions {

	public static object GetValueAsType(this IExcelDataReader reader, int i, Type type) {
		return Convert.ChangeType(reader.GetValue(i), type);
	}

	public static T GetValueAsType<T>(this IExcelDataReader reader, int i) {
		return (T)GetValueAsType(reader, i, typeof(T));
	}
}
```

**Comment by appel1** [comment]
That should work. We probably would want an overload that takes an IFormatProvider as well.

**Comment by paulirwin** [comment]
I like the extension method idea, but I don't view it as mutually exclusive to the option approach. We could have both. The benefit to the option approach is you get to maintain the IDataReader contract with looser type conversion. The extension methods could still be there if you don't want to turn on the option.

**Comment by andersnm** [comment]
Generally I'd like to avoid options which modify the low level behavior like this. It's cleaner/simpler to focus on doing one thing, and let callers decide how to convert/format the output. 

F.ex a loosely typed wrapper for IDataReader can be implemented without direct library support:

```c#
public class ConvertDataReader : IDataReader {

	IDataReader BaseReader { get; set; }

	public ConvertDataReader(IDataReader baseReader) {
		BaseReader = baseReader;
	}
	
	public string GetString(int i) {
		return GetValueAsType<string>(i);
	}
	
	public int GetInt32(int i) {
		return GetValueAsType<int>(i);
	}
	
	// ...

	T GetValueAsType<T>(int i) {
		return (T)return Convert.ChangeType(BaseReader.GetValue(i), typeof(T));
	}
}
```

And use it like: `using (var reader = new ConvertDataReader(ExcelReaderFactory.CreateReader(...))) { ... }`

And in case somebody needs a slightly different behavior, the class could take its own options, (e.g never throw, different defaults, with format providers). 

Altho the class should probably implement the IExcelDataReader interface, and it's another question whether it belongs to the base library.

**Comment by Nishi33** [comment]
Thanks SergeyRudakov for putting this question because it helps me a lot to get the right info and something answerable to me by sharing comments in this blog.
