### ISSUE TITLE
Recognition of merged cells

### ISSUE THREAD

**Issue by waclaw66** [ExcelDataReader/ExcelDataReader#269]
Hi.
Is there any possibility to recognize merged cells?
When cell A1 is merged with A2, the value is stored in A1 only. Cell A2 has System.DBNull value, but how detect that is merged with A1?

Thanks in advance.

**Comment by andersnm** [comment]
This is not possible to do at the moment. 

It's a valid feature request, and shares some plumbing work with #215.

**Comment by TimSirmovics** [comment]
I would also like this.

**Comment by andersnm** [comment]
Hi @waclaw66 and @TimSirmovics (and @appel1), do you have any expectations/ideas what this could look like API-wise?

There is progress on reading merged cells in #297 thanks to @Nodrog-82

Looks there are three options, ordered by level of abstraction:
- API to get list of merged cell ranges (maps 1:1 to underlying file format)
- API GetColumnSpan/GetRowSpan per cell (HTML-like abstraction)
- Transparently return same value for all merged cells (practical abstraction)

**Comment by TimSirmovics** [comment]
My personal preference is based entirely on how another Excel API I use works, and that is to return the same value for all merged cells.

**Comment by appel1** [comment]
How would you determine that it is a merged cell? And not two adjacent cells with the same value?

**Comment by TimSirmovics** [comment]
Updated original comment.

**Comment by Nodrog-82** [comment]
For the use of data loads the fact it is merged is irrelevant. To allow display of data in the same layout e.g. web viewer for excel, then it is relevant.

Personally I would prefer to either leave cells as is and expose the merged cell ranges (This has the the least overhead) or an indicator on the cell that it is merged e.g. ref to the merge cell range object.

If I have time tonight I will profile those two options .

**Comment by TimSirmovics** [comment]
I don't think it is irrelevant for data loads. Depending on the format of the data, a value that has been merged across multiple cells can indicate the intent from the author is to show that each of those cells should contain the same value. Consider a table where a value in one column has been merged across multiple rows.

The fact that the actual value is not stored in each cell seems to be an Excel file format implementation detail of not duplicating the value unnecesarily.

**Comment by andersnm** [comment]
Ok, think I prefer to leave the cells as is, and expose only the merged cell ranges. It's the simplest and most flexible from the ExcelDataReader point of view, and that is what counts :)

Later, it's possible to f.ex implement an option how to handle merged cells with AsDataSet(), and have good documentation/code samples for the reader interface.

**Comment by Nodrog-82** [comment]
For my limited purposes of importing to a database, having the value in the cell in code whether it was stored there or whether part of a merged cell make life easier, but I know it may not be what other need.

Looking again at the code, I think I would have to put a new method on "abstract class ExcelDataReader" for "GetMergedDetails" that returns the range then MergedCells operate on. Any better ideas?

 Would adding an option in the ExcelReaderConfiguration on whether to auto populate the cells be useful?

Would you be happier to just expose the MergedCell ranges and let the end developer cope? One word of warning is some cells in the merged range are empty string, others are not loaded at all.

**Comment by Nodrog-82** [comment]
Looks like you beat me to it, I will update the code and resubmit

**Comment by JuneCandy** [comment]
Hey! I encountered this trouble today.My form is like this.
Obviously, "name" and "Gender" are combined cells, and "Hobby" is not.
![qq 20171201175119](https://user-images.githubusercontent.com/23094608/33477337-4b7ea4de-d6c0-11e7-95c9-c3aaf5038a32.png)
I hope to support such a excel.
I saw the code you submitted, Nodrog-82. I hope to update it as soon as possible
Thank you for your efforts

**Comment by andersnm** [comment]
Here is an example MergeCellsReader wrapper class for IExcelDataReader using the new MergeCells property. It returns the top left value of merged cells transparently, and can be used with AsDataSet etc:
 
https://gist.github.com/andersnm/7205389e5e5a71773a9716e0853e3ee7

Usage:
```c#
using (var reader = new MergeCellsReader(ExcelReaderFactory.CreateReader(stream))) {
 ...
}
```

How about a new "ExcelDataReader.Extensions" library for stuff like this?

**Comment by Nodrog-82** [comment]
For my current need I am going via the reader direct due to certain
limitations (e.g. column headers have to be in row 0, whereas I deal with
files with actual headers in row 5 due to users having titles on the first
few rows) I. Not sure how best to add this helper to the Reader without
putting it actually in the reader class which is was decided against.

Having the extensions library is a great Idea and will make it easier for
simple usages of scraping data, not layout/intent.
