### ISSUE TITLE
Huge memory consumption when processing file

### ISSUE THREAD

**Issue by VaDRo** [ExcelDataReader/ExcelDataReader#270]
Hello!

  When I'm reading file manually with code like this:
`
                int rowCntr = 0;

                List<List<object>> rows = new List<List<object>>();

                List<object> row;

                using (var reader = ExcelReaderFactory.CreateReader(stream))
                {
                    try
                    {
                        do
                        {
                            rowCntr++;
                            while (reader.Read())
                            {
                                int columnsCount = reader.FieldCount;
                                row = new List<object>();
                                for (int i = 0; i < columnsCount; i++)
                                {
                                    row.Add(reader.GetValue(i));
                                }
                                rows.Add(row);
                            }
                        } while (reader.NextResult());
                    }
                    catch (Exception)
                    {
                        MessageBox.Show(rowCntr.ToString(), "");
                    }
                }
`
my application grows to approx 400-500 mbytes of operative memory.

When I'm trying to read xls file like this:
`
                
                using (var reader = ExcelReaderFactory.CreateReader(stream))

                {
                    try
                    {
                        result = reader.AsDataSet();
                    }
                    catch (Exception)
                    {
                        MessageBox.Show(", "");
                    }
                }
`
my application grows up to approx 800-900 mbytes of operative memory.
It looks like a problem.
When I debugged first approach, I found that rows collection contains... 1.048.567 elements!
My file contains just 17 (!!!) rows.
It looks like Excel Reader doesn't see the end of non-empty part of the file.

**Comment by VaDRo** [comment]
[_Book442ex.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/1252168/_Book442ex.xlsx)

let me attach sample file

**Comment by andersnm** [comment]
This has been reproduced - thanks for the sample file! This was reported earlier in #193, but without a repro so we've been in the dark until now. 

Apparently all dimension elements in this xlsx are untrustworthy. In particular the first sheet is quite unreasonable:
```xml
<dimension ref="A1:AT1048576"/>
```

Looks like the file was created by LibreOffice/5.3.4.2$Windows_X86_64 (from docprops/app.xml)

**Comment by VaDRo** [comment]
It was edited with LibreOffice. I don't know what is the way this file was created.

I tried to open your solution in Visual Studio and make small manipulations, but I can't do it.
Huge amount of rows in "rows" collection has lists with null elements. It looks like I can add some code that if we have 5 empty rows one by one -> end of data reached. Just as quick solution

**Comment by VaDRo** [comment]
PS: application doesn't free memory after closing ExcelDataReader and data stream. It looks strange too.

**Comment by andersnm** [comment]
A simple fix in ExcelDataReader might be to ignore the dimension element as well as ignoring blank lines at the end of the sheet in `XlsxWorksheet.ReadWorksheetGlobals` where it already counts the number of rows/columns in case the dimension element is missing altogether.

Note that a grid of 1048567x46 objects (ie the size reported by the first sheet) takes approx 400-500mb ram without ExcelDataReader too:
```c#
            List<List<object>> rows = new List<List<object>>();
            for (var i = 0; i < 1048567; ++i)
                rows.Add(new List<object>(46));
            // process uses lots of ram now
```

**Comment by appel1** [comment]
Fine with me. We'd have to check so that it doesn't cause performance problems for large sheets that actually has a valid dimension record though.

**Comment by andersnm** [comment]
Simplified the sample XLSX contents are organized like this:
```
[Row 1: Data]
[Row 1000000: Formatting, no cells]
```
Thus ExcelDataReader expands the implicit contents to 1mil mostly empty rows, which is technically correct.

One solution involves changing ExcelDataReader to only return rows physically present in the file. Callers can use the `Depth` property to determine the actual row index. That lowers the bandwidth dramatically for reader based code like in this issue, although leaves further memory management to the caller. To avoid breaking changes, this can be a new `PhysicalRowsOnly` option and disabled by default.

Anyhow, AsDataSet() should still expand these empty rows so the above won't help there. It needs a separate way to handle (trailing) empty rows, and might consider other kinds of empty rows too:
- The row is physically absent from the file
- The row contains only row formatting, but no cells
- The row contains cells with formatting or formula errors, but no values
- The row contains cells with values, but the row has been hidden

Not sure what this might look like yet.

**Comment by appel1** [comment]
I can't quite make up my mind regarding this. Is metadata for trailing empty rows ever useful? Even once we expose more metadata in the interface? Do we need to change the reader interface at all since it is so easy for the user to skip empty or other kinds of rows themselves? 

For AsDataSet we could add a row filter callback to handle empty or other kinds of rows the user doesn't need to include in the output.

**Comment by VaDRo** [comment]
> To avoid breaking changes, this can be a new PhysicalRowsOnly option and disabled by default.

It's good idea!
In my situation I see totally empty rows - no data, no formatting, no formulas, not hidden.

> Do we need to change the reader interface at all since it is so easy for the user to skip empty or other kinds of rows themselves?

There are no problems with trim empty rows - my program do this.  General problem -> program "eates" huge amount of memory. And after closing reader with all streams -> reader doesn't free consumed memory. If I will load such files 2 or 3 times one-by-one -> OutOfMemory error will be raised! It's very bad thing and I don't know what to do with it.

PS: thank you for fast responce, guys!

**Comment by appel1** [comment]
> There are no problems with trim empty rows - my program do this. General problem -> program "eates" huge amount of memory. And after closing reader with all streams -> reader doesn't free consumed memory. If I will load such files 2 or 3 times one-by-one -> OutOfMemory error will be raised! It's very bad thing and I don't know what to do with it.

So if you don't add anything to the rows list in your example memory still get allocated and not freed? I can't reproduce that using your sample Excel file.

**Comment by VaDRo** [comment]
I'm reading xls(x) file into DataSet. After that I'm just reading data from that DataSet and that's all. Do I need to "close" that DataSet in some way?
That's my code:
`public DataSet ReadExcelFile(String fileName, bool convertOADateTime = false)
        {
            DataSet result = null;

            if (String.IsNullOrEmpty(fileName))
                throw new Exception("File Name is empty");

            if (!File.Exists(fileName))
                throw new Exception("Specified File not found ("+fileName+")");


            using (var stream = File.Open(fileName, FileMode.Open, FileAccess.Read))
            {
                using (var reader = ExcelReaderFactory.CreateReader(stream))
                {
                    try
                    {
                        result = reader.AsDataSet();
                    }
                    catch (Exception)
                    {
                        MessageBox.Show(rowCntr.ToString(), "");
                    }
                }
            }

            return result;
        }`

After calling this function, I'm just using DataSet, but memory, consumed by my program, stays on 700-800 mb level.
If you want to reproduce error - please, create in your test project function above, call it, for example, 5 times, and go through DataSet in foreach loop. 
I think that you will get OutOfMemory Exception.

**Comment by andersnm** [comment]
I think we can resolve this issue (and #160) by implementing a new row filtering callback option for AsDataSet(). By default this option can exclude ALL empty rows, and the caller can override it if needed.

(it won't allow for skipping only trailing empty rows, but isn't a requirement)

**Comment by appel1** [comment]
For AsDataSet I think it makes more sense to include empty lines except for trailing empty lines by default to better match what you see in Excel which I think most expect. The DataSet can't afaik include metadata so trailing lines with just metadata should count as empty solving this issue. Doesn't hurt with a row filter callback also for more advanced scenarios.
