### ISSUE TITLE
Read data by rows(horizontal way)

### ISSUE THREAD

**Issue by butsaty** [ExcelDataReader/ExcelDataReader#271]
Hey,

I just started to use the library from the base example:
```
using (var stream = File.Open(filePath, FileMode.Open, FileAccess.Read)) {
	using (var reader = ExcelReaderFactory.CreateReader(stream)) {
		do {
			while (reader.Read()) {
				// reader.GetDouble(0);
			}
		} while (reader.NextResult());
	}
}
```
reader.Read() runs by columns(in vertical way):
![image](https://user-images.githubusercontent.com/29995129/29979549-387eecc0-8f46-11e7-954e-6e548029b3d3.png)

Can I read the data by rows?

**Comment by appel1** [comment]
No, not directly. You have to read the whole sheet first into a DataTable or other data structure and then read by column.

**Comment by butsaty** [comment]
**appel1**, Thanks for your reply. Unfortunately, I can't use DataTable because of .net Core. 
For example, my real data structure looks like that:
![image](https://user-images.githubusercontent.com/29995129/30020411-fd51e3b2-9163-11e7-8d8a-50816d0f0bcd.png)

It is a little bit complicated to read it via reader.Read(). Maybe there is some opportunity to know when the reader finished to read a column and going to move a cursor to the next one?

**Comment by appel1** [comment]
Data in Excel files are stored by row. If you can't use DataTable then just read the sheet into some other data structure that suites your needs. 

Untested example off the top of my head:
```csharp
List<List<object>> columns = new List<List<object>>();
using (var reader = ExcelReaderFactory.CreateReader(File.OpenRead(path)))
{
  while (reader.Read())
  { 
     for (int i = 0; i < reader.FieldCount; i++)
     {
       if (i <= columns.Count)
         columns.Add(new List<object>());
       columns[i].Add(reader.GetValue(i));
     }
  }
}

// Read by columns
foreach (var column in columns)
{
  foreach (var cell in column)
  {  
     // do stuff
  }
}
```

**Comment by butsaty** [comment]
**appel1**, I tried to use FieldCount but it always returns 2(my doc has 13 columns).
Here is an example file [test3.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/1274877/test3.xlsx)
I use the [pdfConvertor ](https://www.investintech.com/able2extract.html) to get excel files.

**Comment by andersnm** [comment]
Hi! Can confirm latest ExcelDataReader parses 2 columns and 9 rows out of test3.xlsx, but the file has data in 3 columns (and 9 rows).  Thanks for the sample file and mentioning the origin.

Dimension element in sheet1.xml is:
```xml
<dimension ref="A1:B1" />
```

Looks like the pdfConvertor generates xlsx with a broken dimension element. ExcelDataReader uses this element (if present) to determine the number of columns in the sheet. 

In order to fix this in ExcelDataReader, I suspect there is no way around taking the performance hit and always scan the xlsx sheet data once first to find the maximum extents (as for xls).

**Comment by butsaty** [comment]
By the way, it is possible to read it with [EPPlus](https://www.nuget.org/packages/EPPlus/)
