### ISSUE TITLE
Feature Request: .Net Standard 2.0

### ISSUE THREAD

**Issue by aersamkull** [ExcelDataReader/ExcelDataReader#272]
Hi there!

I'd really appreciate support for .Net Standard 2.0 :)

**Comment by andersnm** [comment]
Hi, this is already implemented in the repo, see also #266. If you want to give it a spin, check out the nugets from appveyor here:
https://ci.appveyor.com/project/andersnm/exceldatareader/build/artifacts

Still not sure when this will be released, alas best guess is still "hopefully within a week or two"

**Comment by aersamkull** [comment]
Ok, thank you. So for me there is no more reason not to close this issue :)
