### ISSUE TITLE
ExcelDataReader 3.1.0 dependency causes macOS msbuild error in mono 5.2.0 related to missing AxImp.exe

### ISSUE THREAD

**Issue by andersonkent** [ExcelDataReader/ExcelDataReader#273]
**OS:** macOS Sierra
**Platform:** mono 5.2.0.215

**MSBuild version info:**
Microsoft (R) Build Engine version 15.3.0.0 (d15.3/17f02c2 Thu Jul 20 17:04:26 EDT 2017) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

15.3.0.0

**Description:**
When using ExcelDataReader (and ExcelDataReader.DataSet) as a dependency in a project, msbuild under mono 5.2.0 errors with the following message:

(ResolveComReferences target) -> 
  /Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(2618,5): error MSB3086: Task could not find "AxImp.exe" using the SdkToolsPath "/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/4.5/" or the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.7\WinSDK-NetFx40Tools-x86". Make sure the SdkToolsPath is set and the tool exists in the correct processor specific location under the SdkToolsPath and that the Microsoft Windows SDK is installed [/Users/username/project/project.csproj]

The problem does not happen with xbuild, but since xbuild is deprecated msbuild should be supported.

**Comment by andersnm** [comment]
Hi, I'm not familiar with this error message, but if I understood things correctly, then the msbuild `ResolveComReferences` task is only invoked when there is a `<COMReference>` element in the project file. And COM is afaik Windows-only, so there's likely an issue in your project file when this happens on a mac.

Can you please share your csproj/msbuildproj? Or check if there is an unrelated COMReference in it? Or if ExcelDataReader is referenced as a COM component, what steps did you do to add ExcelDataReader to the project?

xbuild ignores COMReference, so it makes sense this appears only in MSBuild:
[1] http://www.mono-project.com/docs/tools+libraries/tools/xbuild/#limitations

**Comment by andersonkent** [comment]
Thanks for the response. The error only appeared in our build after adding the ExcelDataReader dependency, so it appears something in the packaging (installed via nuget) is causing msbuild to think there is a need to resolve a COM reference. Are there any COM based dependencies in the ExcelDataReader package that might be influencing this?

I suppose there is also a need to file an issue with msbuild to remove the COM task for non-Windows environments.

This issue also appears on a Windows machine where only msbuild and the .NET SDK are installed. So it still seems to be an issue that something in the nuget packaging or dependencies for ExcelDataReader is causing msbuild to call the COM task.

**Comment by andersnm** [comment]
I'm curious exactly what steps you did to add the reference so I can try and repro myself? (E.g "Install-Package" from the Package Manager console, `dotnet add package`, or a wizard in the IDE)

My current theory is to set the [ComVisible(false)] attribute explicitly on the ExcelDataReader assembly. Apparently this property is true by default, so if ExcelDataReader was added to the project using a tool, it makes some sense if the tool added both a COM and .NET Assembly reference in the project files. If this is the case, you should be fine to remove the COMReference to ExcelDataReader from your project file to progress.

**Comment by andersonkent** [comment]
Ugh, well, thanks to your comment, I found the other artifact that got added into the csproj file by the Visual Studio IDE when it added the ExcelDataReader dependency: An actual COMReference to VBIDE.

My apologies. How embarrassing. Thank you for your help.
