### ISSUE TITLE
Can't access xlsx file

### ISSUE THREAD

**Issue by coke187** [ExcelDataReader/ExcelDataReader#274]
![capture](https://user-images.githubusercontent.com/8400541/30679026-4154aee8-9e4b-11e7-993b-f4de249990e0.PNG)
I get this error when I try to read an xlsx file from my UWP application. Any thoughts?

**Comment by andersnm** [comment]
Hi,

Looks like there are special file permission concerns on UWP:
https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions

Unfortunately I have no experience with UWP, so I have no real advice.  You may find an example for opening a file as a stream elsewhere in their docs:
https://docs.microsoft.com/en-us/windows/uwp/files/
