### ISSUE TITLE
After update to 3.2.0 .AsDataSet slows down

### ISSUE THREAD

**Issue by jgasiorowski** [ExcelDataReader/ExcelDataReader#277]
I have a console app which loads 7 excel files one after another (total size around 25MB). 
- on version 3.1.0 (.NET 4.5.2) it takes in average 13 seconds.
- on version 3.2.0 (.NET 4.5.2) it takes in average over 30 seconds.

**Comment by appel1** [comment]
.xls or .xlsx?

**Comment by andersnm** [comment]
I bet it's xlsx, and the slowdown comes from the workaround to parse somewhat broken xlsxes generated by the "pdfConvertor" third party app - which unfortunately affects ALL xlsx:  https://github.com/ExcelDataReader/ExcelDataReader/issues/271#issuecomment-326989381

Alas the slowdown is expected :( There was a choice between compatibility and performance, and compatibility was chosen.

**Comment by appel1** [comment]
I agree that compatibility was the right choice. I'll see if I can find some time to profile the code to see if there's anything that can be done to improve things.

**Comment by jgasiorowski** [comment]
@appel1 all those are .xlsx

**Comment by appel1** [comment]
One thing that stands out is that when you use AsDataSet both ExcelReaderFactory.CreateOpenXmlReader and ExcelDataReaderExtensions.AsDataSet calls Reset causing us to read the work sheet globals twice.

**Comment by appel1** [comment]
Not parsing the cell values when determining the max row and column would probably shave off a little times as well.

**Comment by appel1** [comment]
It looks like I was wrong, Reset is expensive for both binary and xml readers. 

So either we remove the calls to Reset in AsDataSet which would be a breaking change or we change ExcelDataReader to delay the iterator initialization until any call that uses any of the iterators after a call to Reset. 

I think I'm leaning towards the second option. What do you think @andersnm ?

**Comment by andersnm** [comment]
Had some encouraging results from changing Reset() to only reset what's necessary; ie, do not reset the worksheet iterator if already on the first sheet, and do not reset the row iterator if already on the first row on the first sheet. That brought a test benchmark down from 4 sec to 3 sec. Got further down to 2.5sec when combining the two loops in ReadWorksheetGlobals()

**Comment by appel1** [comment]
You still initialize the iterators twice if you use AsDataSet with that approach though if I understand you correctly.

**Comment by andersnm** [comment]
@appel1 Yes, the last call to Reset() in AsDataSet() would still be quite expensive under this scheme (assuming there is more than one sheet).  

Another approach is to cache the worksheet instances: ReadWorksheets() yields new worksheet instances every time it is called, but instead we could parse the worksheets into a list ahead of time, and iterate that in ReadWorksheets(). That should make Reset() pretty muh instant

**Comment by appel1** [comment]
@andersnm Perhaps that'd be good enough. Not optimal though if you just want to read for example the second of five big sheets.

**Comment by andersnm** [comment]
@appel1 Went for a more clever caching mechanism which caches as needed rather than up-front to handle your scenario. The informal test benchmark is down from 4 sec to 1.6 sec.

**Comment by andersnm** [comment]
@jgasiorowski I consider this done, although am curious how 3.3.0 fares in your benchmark

**Comment by jgasiorowski** [comment]
@andersnm I will check that over the weekend and I will update that comment. I am also curious :). Thanks for the effort btw.

**Comment by jgasiorowski** [comment]
@andersnm Sorry it took me so long. I've just returned to commit where I was checking those timings. I made 5 runs and it never took more than 14 seconds on v3.3.0. You are the best ;)
