### ISSUE TITLE
Enable CSV read

### ISSUE THREAD

**Issue by JackMstry** [ExcelDataReader/ExcelDataReader#278]
Can we able to load csv file using ExcelDataReader?

**Comment by wizardgsz** [comment]
Sure! Here it is the WIP: 
http://exceldatareader.codeplex.com/discussions/442962#post1258830
[ExcelCsvReader - CSV reader implementation](http://exceldatareader.codeplex.com/workitem/13097)

**Comment by andersnm** [comment]
I'm closing this since we already have the symbolic issue #1 for CSV support. (Feel free to comment or +1 there to show interest!)

Issue #1 is kept open because adding CSV support is not out of the question, alas it's a lot more work beyond implementing the code snippets in the issue.

**Comment by JackMstry** [comment]
Thanks :)
