### ISSUE TITLE
how to read date and insert it into sql?

### ISSUE THREAD

**Issue by tricman10** [ExcelDataReader/ExcelDataReader#280]
I have in my excel some date fields that are in this format:
 1/4/2016, 2/14/2016, etc.
When i try to insert that fields in a database I get an error:
 String is not recongized as a valid DateTime

this is my code:
` 
IExcelDataReader excelReader;
                    if (System.IO.Path.GetExtension(ope.FileName).ToUpper() == ".XLS")
                    {
                        
                        excelReader = ExcelReaderFactory.CreateBinaryReader(stream,true);
                    }
                    else
                    {
                       
                        excelReader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                    }
                  
                    excelReader.IsFirstRowAsColumnNames = true;
                    DataSet result = excelReader.AsDataSet(true);
                    
                    DataClassesFinPodaciDataContext conn = new DataClassesFinPodaciDataContext();
                    
                    foreach (DataRow dr in result.Tables[0].Rows)
                    {
                       string s1 = Convert.ToString(dr[4]);
                        DateTime conv1 = Convert.ToDateTime(s1);
                        string d2 = Convert.ToString(dr[14]);
                        DateTime conv2 = Convert.ToDateTime(d2);
                        string d3 = Convert.ToString(dr[15]);
                        DateTime conv3 = Convert.ToDateTime(d3);
                        string d4 = Convert.ToString(dr[19]);
                        DateTime conv4 = Convert.ToDateTime(d4);
                        
                        //string d1 = string.Parse()
                        tblFinansijskiPodaci addTable = new tblFinansijskiPodaci()
                        {
                           
                            Firma = Convert.ToInt32(dr[0]),
                            NazFirme = Convert.ToString(dr[1]),
                            VrstaNal = Convert.ToString(dr[2]),
                            BrojNal = Convert.ToInt32(dr[3]),
                            DatumNal = conv1,
                            SifraRJ = Convert.ToInt32(dr[5]),
                            Konto = Convert.ToString(dr[6]),
                            NazivKonta = Convert.ToString(dr[7]),
                            Partner = Convert.ToInt32(dr[8]),
                            NazivPartnera = Convert.ToString(dr[9]),
                            Adresa = Convert.ToString(dr[10]),
                            Mesto = Convert.ToString(dr[11]),
                            PIB = Convert.ToString(dr[12]),
                            BrojDok = Convert.ToString(dr[13]),
                            DatumDok = conv2,
                            DatumVal = conv3,
                            Opis = Convert.ToString(dr[16]),
                            Duguje = Convert.ToInt32(dr[17]),
                            Potrazuje = Convert.ToInt32(dr[18]),
                            DatumZaPDV = conv4,
                            Valuta = Convert.ToString(dr[20]),
                            DevDuguje = Convert.ToInt32(dr[21]),
                            DevPotrazuje = Convert.ToInt32(dr[22]),
                            Oslob = Convert.ToInt32(dr[23]),
                            IznosPDV = Convert.ToInt32(dr[24]),
                            Oslob1 = Convert.ToInt32(dr[25]),
                            IznosOslob = Convert.ToInt32(dr[26]),
                            UvozOsnovica = Convert.ToInt32(dr[27])

                        };
                        //   conn.ExecuteCommand("TRUNCATE TABLE Excel");
                        //  conn.ExecuteCommand("DELETE FROM tblFinansijskiPodaci where ime='a'");
                        conn.tblFinansijskiPodacis.InsertOnSubmit(addTable);

                    }

                    conn.SubmitChanges();
                    excelReader.Close();`

I have also tried 
`double d = double.Parse(Convert.ToString(dr[4]));  
DateTime conv = DateTime.FromOADate(d);`
but that didnt work,since, I think since my date is not in a only numbers format.

**Comment by wizardgsz** [comment]
You should double check locale settings on your DB server.
Try a simple "insert" using SQL Developer (for Oracle) or SSMS (SQL Server) for example...
Is SQL Server default format YYYY-MM-DD?

See also: [how to insert datetime into the SQL Database table](https://stackoverflow.com/questions/5287427/how-to-insert-datetime-into-the-sql-database-table)

**Comment by andersnm** [comment]
"String is not recongized as a valid DateTime" most likely comes from `Convert.ToDateTime()` when it gets an invalid date string. Can you add some diagnostics code to print the date strings pre conversion or run the program in a debugger and find out exactly which value is causing it?

If the Excel sheet contains properly formatted dates, you shouldn't need to convert them at all.

(I also recommend upgrading to latest ExcelDataReader, it has an infinite amount of improvements from 2.x)
