### ISSUE TITLE
how to insert empty date field into sql?

### ISSUE THREAD

**Issue by tricman10** [ExcelDataReader/ExcelDataReader#281]
I have a field in Excel that is datetime in SQL.When I have some data in Excel, everything works great with ConvertToDateTime..
But when a field in Excel is empty, how can I insert NULL value into SQL table?
I thought that I should put DBNull.Value , but that doesn't work.

**Comment by tricman10** [comment]
If someone needs this, this line did the work:
 DateTime? dt = string.IsNullOrEmpty(Convert.ToString(dr[20])) ? (DateTime?)null : DateTime.Parse(Convert.ToString(dr[20]));

**Comment by wizardgsz** [comment]
Exactly, you have to use nullable DateTime?

**Comment by andersnm** [comment]
@tricman10 If your input Excel sheet contains sane dates, you might get away with the following:

```c#
var dt = (DateTime?)dr[20];
```

or more defensively:
```c#
var dt = dr[20] is DateTime ? (DateTime?)dr[20] : null;
```

This avoids additional serializing and parsing, and potential culture problems when running the program on other machines.

**Comment by tricman10** [comment]
@andersnm  
Thank you a lot! You have saved me! it almost worked my way.. in some cases it didn't. and with you solution,it works like a charm! :)

**Comment by andersnm** [comment]
Great news, thanks for the update!
