### ISSUE TITLE
Reading from a different sheet?

### ISSUE THREAD

**Issue by kendallb** [ExcelDataReader/ExcelDataReader#282]
I was going to try to use this library but I cannot find a way to read from something other than the first sheet in the file. Is there an API call to access a sheet via index or name?

**Comment by andersnm** [comment]
If using the reader: Use NextResult() to move the cursor to the next sheet
If using AsDataSet: Use DataSet.Tables

There is some example code using the reader and NextResult() here: https://github.com/ExcelDataReader/ExcelDataReader/issues/201#issuecomment-303347059

**Comment by kendallb** [comment]
Ahh, that makes sense. I see now the docs for NextReader says to advance to the next sheet. Perhaps a more specific code sample in the main readme showing how to find a specific sheet would make it more obvious. Thanks!
