### ISSUE TITLE
Row Count

### ISSUE THREAD

**Issue by rsd20** [ExcelDataReader/ExcelDataReader#285]
Hi 
Is there any way to get a row count without reading through the whole data structure?
The reason i'm asking is that I would like to be able to read through the sheet row by row and give progress back to the user. Rather than use the asDataSet mainly due the large size and differences in the data being imported

**Comment by andersnm** [comment]
A RowsCount is not supported/implemented at the moment, but should be fairly easy to implement: it is already determined internally for both xls and xlsx, but not exposed in ExcelDataReader's public APIs.

**Comment by rsd20** [comment]
Is this likely to be implemented?

**Comment by andersnm** [comment]
I'd be happy to accept a PR implementing this cleanly. But cannot say much about the probabilities for it happening or whether I find the time to do myself. Given an infinite amount of time, it's more likely to happen than not. ;)
