### ISSUE TITLE
SST read position out of range

### ISSUE THREAD

**Issue by vkirienko** [ExcelDataReader/ExcelDataReader#286]
Hi,

After upgrade to 3.2 version I'm getting "SST read position out of range" on files that had no problems before. Unfortunately I can't provide the file (it contains confidential information) and once I try to scramble data and save issue goes away. Not sure how useful stack will be.

```
[InvalidOperationException: SST read position out of range]
   ExcelDataReader.Core.BinaryFormat.XlsSSTReader.ReadUnicodeBytes(Byte[] dest, Int32 offset, Int32 characterCount, Boolean isMultiByte) +308
   ExcelDataReader.Core.BinaryFormat.XlsSSTReader.ReadString() +329
   ExcelDataReader.Core.BinaryFormat.XlsBiffSST.ReadStrings(XlsBiffStream biffStream) +57
   ExcelDataReader.Core.BinaryFormat.XlsWorkbook.ReadWorkbookGlobals(XlsBiffStream biffStream) +802
   ExcelDataReader.Core.BinaryFormat.XlsWorkbook..ctor(Stream stream, String password, Encoding fallbackEncoding) +495
   ExcelDataReader.ExcelBinaryReader..ctor(Stream stream, ExcelReaderConfiguration configuration) +77
   ExcelDataReader.ExcelReaderFactory.CreateBinaryReader(Stream fileStream, ExcelReaderConfiguration configuration) +214
```

Regards,
Vlad Kirienko

**Comment by andersnm** [comment]
Hi and thanks for the report!

I suspect the Shared String Table (SST) in your file contains a string split exactly between its header and string data across the BIFF Continue records. This situation looks to be handled in the old code, but not in the rewritten SST parser in 3.2.0. So far I tried and failed to repro using POI/Java and Excel (have tested literally thousands of files). Have learned that Excel "packs" the SST strings cleverly, making it harder to produce a specific SST binary layout. May try a hex-editor next...

@vkirienko Do you know where the file came from and whether it was generated by a third party library or in Excel? One simple test: If you re-save the problematic file (as xls) in Excel, does it still crash in ExcelDataReader? (if it works after re-save and no other changes, it's likely from a third party)

**Comment by andersnm** [comment]
Used Android Studio, POI and https://hexed.it/ to create a repro for this! Daamn :)

1. Create a BIFF8 xls with two ASCII strings in the SST; one with 8210 length, and one shorter afterwards starting exactly on the Continue record boundary
2. Modify the strings before and after the boundary:
	- Reduce the length of the first string by 3 characters
	- Increase the length of the second string by 2 characters
	- Overwrite the last 3 bytes of the first string with the header of the second string
	- Overwrite the first byte of the Continue record contents with a 0 to indicate multibyte=0
	- Overwrite the remaining two bytes of the previous string header with intelligible ASCII characters

Zipped xls: [sst8210-wot.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/1415378/sst8210-wot.zip)

**Comment by andersnm** [comment]
@vkirienko I believe this is fixed, but would be awesome if you can confirm. Do you have a chance to test these Nugets: ?

https://ci.appveyor.com/project/andersnm/exceldatareader/build/build-148/artifacts

**Comment by vkirienko** [comment]
Thanks a lot! I'll try to test tomorrow and confirm.

**Comment by vkirienko** [comment]
It works on my test file. Thank you! Will you release minor patch or roll it into larger release?

**Comment by andersnm** [comment]
Thanks for the update. The plan is to release version 3.3 with this and some other fixes and features - hopefully within a week or two
