### ISSUE TITLE
Excel file password protection check

### ISSUE THREAD

**Issue by fabri777** [ExcelDataReader/ExcelDataReader#287]
Is it possible to check before reading a file if it requires a password?
Thank you

**Comment by andersnm** [comment]
Not directly, you have to catch `InvalidPasswordException` from one of the CreateReader factory methods if the file requires a password.

(Unfortunately there is a bug in version 3.2 which throws a NullReferenceException if the file requires a password and the Password property of the configuration has the default value of null.)

I assume this is ok to close.
