### ISSUE TITLE
Want to read each sheet alone

### ISSUE THREAD

**Issue by AmrTealeb** [ExcelDataReader/ExcelDataReader#291]
Is it possible to read each sheet alone using the DataReader?

**Comment by appel1** [comment]
What do you mean?

**Comment by anandtpatel** [comment]
How to read all sheets of xls file ?

**Comment by andersnm** [comment]
I'd say the example code in the README should be sufficient whether you want to read one sheet at a time or all at once. It's not clear if anything beyond this is needed.

There's a snippet here how to read a specific sheet: https://github.com/ExcelDataReader/ExcelDataReader/issues/201#issuecomment-303347059

Closing this for now. Although at some point we should probably look into adding more code samples in the wiki or something.
