### ISSUE TITLE
is Excel 2011 on Mac Supported?

### ISSUE THREAD

**Issue by bhagatabhijeet** [ExcelDataReader/ExcelDataReader#293]
Hi,
I am having a trouble running using Excel 2011 on Mac Sierra.
Could someone please help with my question "is Excel 2011 on Mac Supported?"

Also can the readme be changed to explicitly versions supported on Mac.

**Comment by andersnm** [comment]
ExcelDataReader supports reading .xlsx files produced by Excel 2007 and newer, including 2011 on Mac Sierra. What kinds of trouble are you having?

**Comment by abhagatbb** [comment]
Hi @andersnm 
I beg a pardon. 
My Issue was related to System.NotSupportedException about encoding when opening .xls 
file
It got resolved the moment I added following code.
System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);

Thanks for help! The issue/comment is good to be closed

**Comment by andersnm** [comment]
Thanks for the update
