### ISSUE TITLE
Degradation to infinite loop when reading broken files on 3.3.0

### ISSUE THREAD

**Issue by advanceboy** [ExcelDataReader/ExcelDataReader#295]
After upgrade to 3.3.0, reading damaged xls files (e.g. [~test_broken.xls.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/1514130/test_broken.xls.zip)) with a specific pattern will result in an infinite loop.
On 3.2.0, an exception occurred correctly.

Sample code:

```cs
using(var fs = File.OpenRead("~test_broken.xls"))
using(var reader = ExcelReaderFactory.CreateReader(fs)) { }
// on 3.2.0, Exception thrown: System.InvalidOperationException "SST read position out of range"
// on 3.3.0, The CreateReader method does not be returned, it loops infinitely.
```

I think that the fix of #286 is affecting this.

**Comment by andersnm** [comment]
Confirmed. Definitely need to fix this and review for other potential DoS vectors

May I ask how the broken file was produced?

**Comment by advanceboy** [comment]
The sample Excel book file I uploaded is what I intentionally broke in the binary editor.

A third party library for Java has a problem of outputting a broken Excel workbook when the number of characters of the cell becomes larger than a certain number.
I encountered this problem with the file output by that library.

But unfortunately, I do not know the name of the library for that Java....

**Comment by advanceboy** [comment]
Thank you!
It doesn't loops infinitely anymore!
