### ISSUE TITLE
Is there a way to detect and remove filters on a sheet

### ISSUE THREAD

**Issue by SciFi-Bob** [ExcelDataReader/ExcelDataReader#298]
using.asDataset

If the sheet you are processing has the autofilter enabled and (for example) only shows rows where a column is = 1.

Only rows visible in the sheet are imported into the dataset.

Is there a way to either ignore the filter and process all the rows when reading into the Dataset.

**Comment by andersnm** [comment]
I tried to repro this by making both an xls and xlsx with autofilter, but ExcelDataReader ignores the autofilter and returns all rows.

Can you please provide a test file, possibly show your code?

**Comment by SciFi-Bob** [comment]
I apologizes for wasting your time, you are 100% correct!  There must have been another bug in my code when I was testing this.

In my defense I assumed that this feature would be useful to some so accepted that it was there.

Thanks for taking the time to look.
