### ISSUE TITLE
UriFormatException

### ISSUE THREAD

**Issue by aqingde88** [ExcelDataReader/ExcelDataReader#299]
when read a xlsm file I got an error:
 UriFormatException: URI scheme must start with a letter and must.......

how can i do with it?

Thanks for helping me

**Comment by andersnm** [comment]
Hi! I believe the UriFormatException is thrown by the System.Uri constructor, but ExcelDataReader does not use the Uri class anywhere.

Can you please share your code and the full stack trace of the error? If you can provide the .xlsm file that could be helpful as well
