### ISSUE TITLE
Possible null reference exception in tryConvertOADateTime

### ISSUE THREAD

**Issue by Ian1971** [ExcelDataReader/ExcelDataReader#3]
was patch submitted to codeplex (15924 )
ExcelBinaryReader.AsDataSet(true); can cause NullReferenceException

The patch checks the value parameter for null before attempting conversion to DateTime.
[tryConvertOADateTime.patch | uploaded via ZenHub](https://www.zenhub.io/files/53e09c3b7511cda6220048f1)

**Comment by andersnm** [comment]
The patch still exists on CodePlex and wanted to add the following at the start of  ExcelBinaryReader.tryConvertOADateTime:
```
+            if (value == null)
+                return null;
```

This has already been applied.
