### ISSUE TITLE
How skip rows and cells to create the dataset?

### ISSUE THREAD

**Issue by felipeoriani** [ExcelDataReader/ExcelDataReader#300]
Hi guys. 

We are using `ExcelDataReader` and `ExcelDataReader.DataSet` extension available on NuGet, to have the `IExcelDataReader` instance as `DataSet`. It works perfectly for the most of our scenarios and it show us such as a great tool.

There are some scenarios where we need to define the row and column (for sample: `B3` or `D4` or `E10`),  where should start reading data and build the dataSet. For sample, I have worksheets where the data that interest me to extract start on `F2` column (where `F2` is the header line and above it the data).

Is there any way to specify what cell the `DataSet` should start reading using the configuration objects? Or how rows it should skip (for sample, 6 lines and start reading)?

Thank you.

**Comment by andersnm** [comment]
Hi!

Alas there is no way to exclude columns with AsDataSet currently.

But there are two options for skippings rows. The simplest is probably to use the `FilterRow` callback:

```c#
var dataset = reader.AsDataSet(new ExcelDataSetConfiguration() {
	ConfigureDataTable = _ => new ExcelDataTableConfiguration() {
		FilterRow = rowReader => rowReader.Depth > 6
	}
});
```

The above reads only rows when the `Depth` (row index) is greater than 6.

Can also skip rows before the header, with `UseHeaderRow = true`, and the `ReadHeaderRow` callback:

```c#
var dataset = reader.AsDataSet(new ExcelDataSetConfiguration() {
	ConfigureDataTable = _ => new ExcelDataTableConfiguration() {
                UseHeaderRow = true,
		ReadHeaderRow = rowReader => {
		            rowReader.Read();
		            rowReader.Read();
		            rowReader.Read();
		            rowReader.Read();
		            rowReader.Read();
		            rowReader.Read();
                }
	}
});
```

The above skips the 6 first rows, uses the next row as headers, then reads the rest as normal.

Which approach to use probably depends on the use case

**Comment by felipeoriani** [comment]
Thank you @andersnm, 

I have tried some code here with your samples and works fine since the data is on the first column. In my case, where column start on the cell `F2`, I can skip some lines with configuration object and skip column when reading the DataTable. For sample:

```
foreach(DataRow row in table.Rows)
 {
   for (int c = 0; c < table.Columns.Count; c++)
   {
        // skip column where there is no name and data and start reading columns from second one.
        if (c < 1) continue;
                            
        var column = table.Columns[c];

        // use information here
        var data = row[column];

    }
}   
```

I am not sure if it is a good solution but it works as expected. Is there any const on doing it?

As suggestion, would be great if the `ExcelDataSetConfiguration` or `ExcelDataTableConfiguration` have a property to accept a column defined where should it start reading, for sample: 
```
var dataset = reader.AsDataSet(new ExcelDataSetConfiguration() {
	ConfigureDataTable = _ => new ExcelDataTableConfiguration() {
                UseHeaderRow = true,
                StartDataPosition = "F3"
	}
});
```
Or
```
var dataset = reader.AsDataSet(new ExcelDataSetConfiguration() {
	ConfigureDataTable = _ => new ExcelDataTableConfiguration() {
                UseHeaderRow = true,
                StartRowPosition = 3,
                StartColumnPosition = 5
	}
});
```

Thank you :D

**Comment by andersnm** [comment]
I think your first sample looks OK - it does what it needs to do. Alternatively, initialize the for-loop with the first column index to avoid the if-continue statement, f.ex `for (int c = 1; c < table.Columns.Count; c++)...`

The AsDataSet() options could use a new `ExcelDataTableConfiguration.FilterColumn` callback to configure which columns to read into the dataset. This would complement the `FilterRow` callback.

**Comment by felipeoriani** [comment]
Thank you @andersnm for the suggestions. I will try them on my project.

**Comment by Seabizkit** [comment]
it would be super useful, if you could say start x and end y, could this be added, basically the start is done, with the FilterRow 

not tested but i think this would do it right?
```
var start = 6;
var end = 50 000

var dataset = reader.AsDataSet(new ExcelDataSetConfiguration() {
	ConfigureDataTable = _ => new ExcelDataTableConfiguration() {
		FilterRow = rowReader => rowReader.Depth > start  && rowReader.Depth < end ,
                FilterRowExit = rowReader => rowReader.Depth == end 
	}
});
```
but wouldn't it be cooler if there was like FilterRowExit condition of sorts
```
if (configuration.FilterColumn != null && !configuration.FilterColumn(self, i))
{
      //attempting to improve performance but not sure if this just makes it worse, 
      //due to the condition checks, maybe only do this on continuous `continue;`'s
      if(FilterRowExit != null &&  !configuration.FilterRowExit (self, i))
      {
             break;
      }
      continue;
}
```
mmm not convinced this is better, but perhaps someone smarter than i can work out how to include a break; so that it exists faster.

maybe check after every 100-1000 continuous continues, it should check if it should simply exit. maybe this is too much of a mirco improvement? but what is the cost of doing 200 000 + filter columns checks just to continue on all.

**Comment by TheDuQe** [comment]
Another solution, it is quite tricky

`DataTable resultDataTable = new DataTable();
            FileInfo targetFile = new FileInfo(@"C:\Temp\targetExcelFile.xlsx");
            using (FileStream stream = File.Open(targetFile.FullName, FileMode.Open, FileAccess.Read))
            {
                // We return the interface, so that
                IExcelDataReader reader = stream.Name.EndsWith(".xls") ? ExcelReaderFactory.CreateBinaryReader(stream)
                                                                       // xlsx
                                                                       : ExcelReaderFactory.CreateOpenXmlReader(stream);

                DataTable rawWorkSheet = reader.AsDataSet().Tables[sheetindex];
                resultDataTable.TableName= rawWorkSheet.TableName;
                // Remove unwanted coumns if any
                Enumerable.Range(0, Math.Max(startColumnIndex - 1, 0)).ToList().ForEach(indexToRemove => rawWorkSheet.Columns.RemoveAt(indexToRemove));
                // Add all required columns
                resultDataTable.Columns.AddRange(rawWorkSheet.Rows.Cast<DataRow>().Skip(startRowIndex - 1).First() // Header Row
                                                .ItemArray.Select(obj => new DataColumn(obj.ToString())).ToArray());
                // Add all rows
                rawWorkSheet.Rows.Cast<DataRow>().Skip(startRowIndex).ToList().ForEach(row =>
                    {
                        resultDataTable.Rows.Add(row.ItemArray);
                    });

            }`

**Comment by TheDuQe** [comment]
``

``

**Comment by TheDuQe** [comment]
###### How to read from "F2" using first row as column headers : I could not get it working using ExcelDataSetConfiguration.

``
using ExcelDataReader;
using System;
using System.Data;
using System.IO;
using System.Linq;

public static DataTable ReadExcelAsDataTable(
            FileInfo targetFile,
            int sheetindex = 0,
            int startColumnIndex = 0,
            int startRowIndex = 0)
        {
            // See ExcelDataReader Github Readme :  Important note on .NET Core
            System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);

            // Declare result table
            DataTable resultDataTable = new DataTable();

            using (FileStream stream = File.Open(targetFile.FullName, FileMode.Open, FileAccess.Read))
            {
                // We return the interface, so that
                using (IExcelDataReader reader = stream.Name.EndsWith(".xls") ? 
                                ExcelReaderFactory.CreateBinaryReader(stream)   // XLS  file
                              : ExcelReaderFactory.CreateOpenXmlReader(stream)) // XLSX file
                {
                    using (DataTable rawWorkSheet = reader.AsDataSet().Tables[sheetindex])
                    {
                        // Cherry on the cake
                        resultDataTable.TableName = rawWorkSheet.TableName;
                        // Remove unwanted coumns if any
                        Enumerable.Range(0, Math.Max(startColumnIndex - 1, 0)).ToList().ForEach(indexToRemove => rawWorkSheet.Columns.RemoveAt(indexToRemove));
                        // Add all required columns
                        resultDataTable.Columns.AddRange(rawWorkSheet.Rows.Cast<DataRow>().Skip(startRowIndex - 1).First() // Header Row
                                                        .ItemArray.Select(obj => new DataColumn(obj.ToString())).ToArray());
                        // Add all rows
                        rawWorkSheet.Rows.Cast<DataRow>().Skip(startRowIndex).ToList().ForEach(row =>
                        {
                            resultDataTable.Rows.Add(row.ItemArray);
                        });
                    };
                }
            }

            return resultDataTable;
        }

    }
``
