### ISSUE TITLE
ZipWorker, all _zipFile.GetEntry

### ISSUE THREAD

**Issue by gem81** [ExcelDataReader/ExcelDataReader#301]
Problem with case sensitive file names.
if xlsx contains Entry with name xl/SharedStrings.xml, it will be not found.
        public Stream GetSharedStringsStream()
        {
            var zipEntry = _zipFile.GetEntry(string.Format(FileSharedStrings, Format)); //NULL
            return zipEntry?.Open();
        }

it's better to do like this:

        public Stream GetSharedStringsStream()
        {
            var zipEntry = _zipFile.Entries.Where(ent => ent.FullName.Equals(string.Format(FileSharedStrings, Format),StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            return zipEntry?.Open();
        }

have a nice day

**Comment by andersnm** [comment]
Thanks for the report :)
