### ISSUE TITLE
Transform XSL to XLSX

### ISSUE THREAD

**Issue by MtarantoOa** [ExcelDataReader/ExcelDataReader#302]
Hi guys,

I have been researching how to transform an XSL and save it into a XLSX. On the research that Ive made I found that this library can help me to achieve the transformation.
Do you have any example code or can provide any help of how to do it with this library?

I've reed the ReadMe but nothing related to what I need.

Thanks in advance,

Mauricio.

**Comment by wizardgsz** [comment]
Load the DataSet and export it, for example http://www.mikesknowledgebase.com/pages/CSharp/ExportToExcel.htm

**Comment by MtarantoOa** [comment]
@wizardgsz  Thanks for your response. 
You are talking about this: Using the "Export to Excel" library in your own application. Correct?
From what I have learned  You cannot simply rename the file to get it into the new format.
So when I call the CreateExcelFile.CreateExcelDocument with the DataSet of the previous excel and the new name with the new extension; that will be en enough?  

Thanks!

**Comment by andersnm** [comment]
You can use ExcelDataReader to load XLS into a DataSet, but you need to use another library to write in the XLSX format.

F.ex ClosedXML and EPPlus are two libraries capable of writing to XLSX:
https://github.com/ClosedXML/ClosedXML/wiki/Adding-DataSet

https://stackoverflow.com/questions/13669733/export-datatable-to-excel-with-epplus

**Comment by MtarantoOa** [comment]
Im trying to use the example code that is on the Readme. 
But I cant call the AsDataSet method becuase is not defined.

What Im doing wrong?

Thanks!

**Comment by MtarantoOa** [comment]
@andersnm Thanks!
I get it working. Im using ClosedXML  library to save the DataSet into an XLSX file.

For now works as a charm! Thanks!
