### ISSUE TITLE
edit readme

### ISSUE THREAD

**Issue by dtaylor-530** [ExcelDataReader/ExcelDataReader#304]
Perhaps move this line 
'Install the ExcelDataReader.DataSet extension package to use the AsDataSet() method to populate a System.Data.DataSet. This will also pull in the base package. Compatible with net20, net45 and netstandard2.0.'
to under the dataset-header.
I missed it and perhaps others have/would.
Otherwise thanks.

**Comment by andersnm** [comment]
I agree this could be clearer, and others have indeed missed this before :)

Although I do not agree fully with your suggestion, I currently don't have any better ideas myself. Last time I looked at improving this, I started overthinking it and decided to leave it for later. The README could definitely benefit from a slight reorganization somehow.

**Comment by dtaylor-530** [comment]
Ok, well it's up to you.
