### ISSUE TITLE
Formula cell caliculation not refreshed post values updation 

### ISSUE THREAD

**Issue by manojmathe85** [ExcelDataReader/ExcelDataReader#305]
HI

I have a requiremnet where excel file which has a pre populated formulas, when i populate the dependent column values the formulas caliculations are not updated or refreshed. please help me with the same.

Code below.

using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.IT.Sales.RelationshipManagement.Segmentation.DataContracts;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
       
        static void Main(string[] args)
        {

        
            PopulateExcel("E:\\Formula.xlsx");
        
            Console.WriteLine("Hello World!");
        }
                
        private static void PopulateExcel(string Path)
        {

            WorkbookPart WP;
            //WorksheetPart WSP;
            String rId;
            Worksheet WS;
            SheetData StD;
            Row R1;
            Row R2;
            Row R3;
            Cell C1;
            Cell C2;
            Cell C3;
            CellFormula CF;
            CalculationChainPart CP;
            CalculationChain CC;
            CalculationCell CCell;
            Workbook Workbook;
            Sheet ss;
            Sheet Sheet;

            using (SpreadsheetDocument spreadSheet = SpreadsheetDocument.Open(Path, true))
            {
                // Get the SharedStringTablePart. If it does not exist, create a new one.
                WP = spreadSheet.WorkbookPart;
                var wsp = spreadSheet.WorkbookPart.WorksheetParts.FirstOrDefault(); //.ElementAt(sheetnumber);
                SheetData sheetData = wsp.Worksheet.Descendants<SheetData>().LastOrDefault();

                R1 = GetRow(sheetData, 2);
                C1 = new Cell();
                SetCell(C1, "A1", 1);
                sheetData.Append(R1);

                R1.Append(C1);
                
                C2 = new Cell();
                SetCell(C2, "B1", 2);
                
                R1.Append(C2);

                spreadSheet.WorkbookPart.Workbook.CalculationProperties.ForceFullCalculation = true;
                spreadSheet.WorkbookPart.Workbook.CalculationProperties.FullCalculationOnLoad = true;
                wsp.Worksheet.Save();

                // Close the document.
                spreadSheet.Close();
            }

        }

        private static Row GetRow(SheetData wsData, UInt32 rowIndex)
        {
            var row = wsData.Elements<Row>().
            Where(r => r.RowIndex.Value == rowIndex).FirstOrDefault();
            if (row == null)
            {
                row = new Row();
                row.RowIndex = rowIndex;
                wsData.Append(row);
            }
            return row;
        }
        private static void SetCell(Cell cell, string Reference, int Value)
        {
            cell.CellReference = Reference;
            cell.DataType = CellValues.Number;
            cell.CellValue = new CellValue();
            cell.CellValue.Text = Value.ToString();

        }

    }
}
Please help me with the code.
[ConsoleApp1.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/1610133/ConsoleApp1.zip)

**Comment by andersnm** [comment]
Apologies, but this is not the correct place to ask. You are using the OpenXml SDK, which is unrelated to ExcelDataReader. 

I had a brief look however, you have to make sure rows and cells are in the correct order in the DOM, otherwise Excel will report there is a problem and discard them.

It seems to work after tweaking the code as follows:
```c#

                R1 = GetRow(sheetData, 2);
                C1 = new Cell();
                SetCell(C1, "A2", 1);

                R1.InsertAt(C1, 0);
                
                C2 = new Cell();
                SetCell(C2, "B2", 2);
                
                R1.InsertAt(C2, 1);
```

(btw, cell formula in C2 is SUM(A2, B2))
(btw2, R1, C1 and C2 are horrible variable names in this context)

**Comment by manojmathe85** [comment]
Thank you somuch for the response,I totally agree with you on the wrong
place in posting this query i tried couple of forums and nothing helped :(
I am still having some issues is it possible we can sync for couple of mins
? I am reachable at manojmathe85@gmail.com.

Thanks in advance.

*Thanks*

*Manoj*

**Comment by andersnm** [comment]
Hi Manoj,

Sorry, I don't think I can help you. ExcelDataReader is strictly for reading Excel-files, and does not support formulas. I've never used OpenXML SDK directly, but have used ClosedXML a couple years ago and can recommend this for creating XLSX. 

ClosedXML uses the OpenXML SDK too, but builds on top of it to simplify the APIs and hides many of the complex, lower level details like ensuring rows and cells are in order (I guess! Didn't check!). It might be an idea to check out ClosedXML if you're still stuck. They have decent docs with a bunch of examples too: https://github.com/ClosedXML/ClosedXML/wiki

Best of luck =)
