### ISSUE TITLE
Set PrecisionAsDisplayed

### ISSUE THREAD

**Issue by smoloye** [ExcelDataReader/ExcelDataReader#309]
Hi,

i need to be able to read cell display values rather than the stored values. unfortunately i cannot set a fixed precision (when its a number) given i read many files from different sources and each have their own precision.
I've found a way to do it using the PrecisionAsDisplayed property, is it at all possible to set this value using ExcelDataReader? or any other solution to be able to read only the cell display value?

**Comment by andersnm** [comment]
Hi,

ExcelDataReader does not support anything equivalent to PrecisionAsDisplayed directly.

Sounds like this feature request in the ExcelNumberFormat library - if implemented - could be a viable solution: https://github.com/andersnm/ExcelNumberFormat/issues/8

**Comment by smoloye** [comment]
Hi,

Any plans to implement this feature anytime soon?

**Comment by andersnm** [comment]
To be honest, no, I'm not planning on doing that myself soon. It's probably doable in a couple hours max, so it might suddenly happen, but am also happy to review a PR

**Comment by andersnm** [comment]
Btw @smoloye, you could still use the ExcelNumberFormat library to generate the display value for a cell, and then use f.ex decimal.TryParse() to convert the formatted string back to a number. (and possibly sanitize the string first, that is remove non-digits to handle additional formatting). Check out the formatting code sample in the README as a starting point.

Closing this one, hopefully we can solve this perfectly via the ExcelNumberFormat library at some point
