### ISSUE TITLE
ExcelOpenXmlReader: numbers stored as text

### ISSUE THREAD

**Issue by PVLopes** [ExcelDataReader/ExcelDataReader#31]
Hi,

I come to a issue that when using the ExcelOpenXmlReader, the numbers formated as text in Excel are always converted to double, ex: the number 0006181(text) is converted to 6181.0(double).
In line 279 there is a verification to see if the format is text:

```
else if (xf.NumFmtId == 49)
  o = o.ToString();
```

but the convertion is from the object already converted to double!

Sugestion:

```
else if (xf.NumFmtId == 49)
   o = _xmlReader.Value;
```

this will preserve numbers as text, as long as they are formated as text in Excel.

**Comment by andersnm** [comment]
Fixed
