### ISSUE TITLE
Homepage says use CreateCsvReader instead to read CSV files, but nuget ExcelDataReader doesn't contain the method?

### ISSUE THREAD

**Issue by mr-shannon-morahan** [ExcelDataReader/ExcelDataReader#310]

**Comment by mr-shannon-morahan** [comment]
Version 3.3.0

**Comment by andersnm** [comment]
Hi, the section about CSV was just added to the README last night while preparing the next 3.4.0 release. It's coming to Nuget real soon - probably later today or during the weekend.

If you can't wait, the latest Nugets from the build server are very close to the final 3.4 =)
https://ci.appveyor.com/project/andersnm/exceldatareader/build/build-183/artifacts
