### ISSUE TITLE
.xls failure when empty directory entries contain junk data

### ISSUE THREAD

**Issue by ms264556** [ExcelDataReader/ExcelDataReader#312]
I know that empty (STGTY_INVALID) directory entries should be cleared, but  I receive .xls files with junk bytes in these entries.
Opening these files fails because empty entries are processed by CompoundDocument.ReadDirectoryEntry, and the timestamp conversion sometimes fails.
I've created a pull request ( #311 ) which ignores the stream data for STGTY_INVALID entries, instead inserting clean field values as per the specification.

**Comment by andersnm** [comment]
Thank you for pointing this out. It's probably a good idea to validate the input to FromFileTime for all entry types too, just in case. I'll have a look at it

**Comment by ms264556** [comment]
I see you're defaulting out-of-range timestamps and bounds checking the name now.
Maybe you can back-out my STGTY_INVALID check, since junk data won't generate exceptions anymore.

**Comment by andersnm** [comment]
Agreed :)
