### ISSUE TITLE
Azure Storage download excel .xls open and read into dataset using ExcelDataReader

### ISSUE THREAD

**Issue by jsegreti** [ExcelDataReader/ExcelDataReader#317]
Getting the error: The type initializer for 'Excel.ExcelReaderFactory' threw an exception.

I have installed the Nuget: Install-Package ExcelDataReader v3.3.0, and I updated the ExcelDataReader to 3.4.0.

I am trying to download an excel .xls (97 - 2003 format) from Azure Storage  and open the file and load it into a dataset.

It seems I can connect and blockBlobReference.DownloadToStream(memoryStream); successfully.  

But when I try to exec the following line, I received the error: The type initializer for 'Excel.ExcelReaderFactory' threw an exception. 

So I tried it on a local file and still get the same error,  This leads me to believe it it the ExcelReaderFactory.  

Can you help with this issue?  See my code below.  I am working in VS2015,,,,

private void ReadTest_20180208()
{
try
{

// FileStream stream = new FileStream(@"D:\local disk\Test.xls", FileMode.Open);
FileStream stream = new FileStream(@"C:\Temp\ApogeeImport\PROCESS_IMPORT_ACCOUNT_CODES_DATA.xls", FileMode.Open);
IExcelDataReader excelReader = ExcelReaderFactory.CreateBinaryReader(stream);
DataSet result = excelReader.AsDataSet();

}
catch (Exception ex)
{
Response.Write("ReadTest_20180208 Error: " + ex.Message);
}

}

**Comment by andersnm** [comment]
The error message references the `Excel` namespace, but latest versions have changed namespace and DLL file name to `ExcelDataReader`. Sounds like there is a mixup with the DLL from the old version? A possible solution would be to remove any references to the old Excel.dll and `Excel` namespace from your project.
