### ISSUE TITLE
Removing the leading zeros when I use ExcelReader to read it as Dataset from an excel file

### ISSUE THREAD

**Issue by SamyukthaSama** [ExcelDataReader/ExcelDataReader#318]
String ParentXML = String.Empty;
        GenericXMLHelper obj = new GenericXMLHelper();
        ParentXML = ParentXML.Replace(" xmlns=\"http://tempuri.org/\"", String.Empty);

        if (fileUpload.HasFile)
        {
            FileStream stream = File.Open(filePath, FileMode.Open, FileAccess.Read);
            IExcelDataReader excelReader;
            Boolean isXLSX = IsXLSX(fileUpload.FileName);
            String connectionString = String.Empty;
            if (isXLSX)
            {
                excelReader = ExcelReaderFactory.CreateOpenXmlReader(stream);
            }
            else
            {
                excelReader = ExcelReaderFactory.CreateBinaryReader(stream);
            }

            DataSet dataSet = new DataSet();
            excelReader.IsFirstRowAsColumnNames = true;

            DataTable dt = new DataTable();

           **dataSet = excelReader.AsDataSet(true);**
            excelReader.Close();

I was trying to create a dataset reading from excel by using excelreader, even though I have leading zero values in excel file. It is stripping out the leading zeros and giving me the output. How to resolve this issue (like the actual value in the excel is "0940" the output after reading by using excel reader is "940". Any help is greatly appreciated.

**Comment by SamyukthaSama** [comment]
The column format in excel is general format since the clients enter the data and try to upload it so we need to read the data from client excel sheet, still we have leading zeros in General format.

**Comment by andersnm** [comment]
Hi, I believe this is a known problem with earlier versions of ExcelDataReader, but has been fixed since v3.0.

**Comment by SamyukthaSama** [comment]
Thank you Andersnm for replying but any example code please that might help me.

**Comment by SamyukthaSama** [comment]
No worries I fixed it. Thank you
