### ISSUE TITLE
NullReferenceException on closing reader created for .xls files

### ISSUE THREAD

**Issue by analuizatrz** [ExcelDataReader/ExcelDataReader#323]
I am testing the following code for .xls and .xlsx files, and only for .xls files the exception NullReferenceException is raised on excelReader.Close().
(running  under .net framework 4.7.1)

```c#
public virtual IList<IList<string>> ReadRows(string path)
{
    var Rows = new List<IList<string>>();
    using (var stream = File.Open(path, FileMode.Open, FileAccess.Read))
    {
        using (var excelReader = ExcelReaderFactory.CreateReader(stream))
        {
            using (var result = excelReader.AsDataSet())
            {
                var table = result.Tables[0];

                for (int i = 0; i < table.Rows.Count; i++)
                {
                    var row = new List<string>();
                    for (int j = 0; j < table.Columns.Count; j++)
                        row.Add(table.Rows[i].ItemArray[j].ToString());
                    Rows.Add(row);
                }
            }
            excelReader.Close();
        }
        stream.Close();
    }
    return Rows;
}
````

````
Result StackTrace:	
em ExcelDataReader.ExcelBinaryReader.Close()
   em ExcelDataReader.ExcelDataReader`2.Dispose()
   em Services.Extrations.ExcelReader.ReadRows(String filePath)
````

**Comment by analuizatrz** [comment]
In https://github.com/ExcelDataReader/ExcelDataReader/issues/156 they say i could choose between close() or dispose(). I am using dispose() implicitly by writing `using`. However, as I'm running unit tests, the same file gets opened sometimes. For some tests IOException is raised with the message "process cannot access the file".
There are tests for .xlsx and .xls files, and this only happens with .xls files. 

``````
Result StackTrace:	
em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   em System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   em System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   em System.IO.File.Open(String path, FileMode mode, FileAccess access)
   em Services.Extrations.ExcelReader.ReadRows(String path)
````

**Comment by yfayerman** [comment]
NRE likely happens because disposing of dataset in the innermost using is disposing of the reader in the using statement right above. You then call Close method on the already released resource. See https://msdn.microsoft.com/en-us/library/ms182334.aspx for more details.

**Comment by andersnm** [comment]
Hi! Your easiest fix is to remove the calls to `.Close()`. The `using` clause calls `Dispose` which calls `Close` under the hood, so it's a safe change.

However this looks like a bug in ExcelDataReader. Multiple calls to Close shouldn't crash like this. It should of been `Workbook?.Stream?.Dispose();` here:

https://github.com/ExcelDataReader/ExcelDataReader/blob/2f11285d652faccf33a9e20d04d8a97de2807f52/src/ExcelDataReader/ExcelBinaryReader.cs#L23

**Comment by analuizatrz** [comment]
@yfayerman and @andersnm thank you for the answer. But when I remove `close()` IOException is raised with the message "process cannot access the file". I am running unit tests, all of them accessing the same file, so the exception is not raise to all the tests. I think the file keeps opened and the next test can't access it, but it could be something else. I tested both .xlsx and xls and this only happens with .xls files.

````
Result StackTrace:	
em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   em System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   em System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   em System.IO.File.Open(String path, FileMode mode, FileAccess access)
   em Services.Extrations.ExcelReader.ReadRows(String path)
````

**Comment by andersnm** [comment]
@analuizatrz  Could you try and use the overload of `File.Open` taking a `FileShare.Read` parameter
https://msdn.microsoft.com/en-us/library/y973b725(v=vs.110).aspx

Sounds like the issue is with parallell access to the same file. The docs indicate `File.Open()` opens an "unshared FileStream" when the FileShare parameter is missing, and if that means `FileShare.None`, then the behavious matches the documentation: "Declines sharing of the current file. Any request to open the file (by this process or another process) will fail until the file is closed."

It is puzzling if it only happens with xls though..

**Comment by analuizatrz** [comment]
@andersnm This worked for me ! thank you very much 💃

**Comment by andersnm** [comment]
Great! I'll just reopen this until we have fix in for the original NRE issue. :)

Thanks @analuizatrz and @yfayerman
