### ISSUE TITLE
ExcelReaderFactory.CreateReader throwing exception for End of Central Directory mismatch when called with a MemoryStream

### ISSUE THREAD

**Issue by atecce** [ExcelDataReader/ExcelDataReader#327]
Given the following:

```csharp
private static void diffZipArchiveEntry(ZipArchiveEntry zipArchiveEntry1, ZipArchiveEntry zipArchiveEntry2)
{
    using (var stream1 = zipArchiveEntry1.Open())
    using (var stream2 = zipArchiveEntry2.Open())
    using (var xlsxReader1 = ExcelReaderFactory.CreateReader(stream1))
    using (var xlsxReader2 = ExcelReaderFactory.CreateReader(stream2))
    {
        // compare the two streams
    }
}
```

A `System.NotSupportedException` is thrown on the factory method. Just wanted to see if this intentional or not and whether I have to hit the disk and extract these .zip files before comparing the .xlsx inside them or whether it's another issue entirely.

**Comment by andersnm** [comment]
Hi,

ExcelDataReader requires a seekable stream as input, and after verifying with a little program, it appears `ZipArchiveEntry.Open()` does not return a seekable stream.

To avoid the disk, there's also an option to extract into a MemoryStream and pass that to the ExcelReaderFactory, if appropriate for your use case.

```c#
            var zip = System.IO.Compression.ZipFile.OpenRead("..\\..\\test.zip");
            var entry = zip.Entries[0];
            var stream = entry.Open();
            Console.WriteLine("Can seek: " + stream.CanSeek.ToString());

            // Output:
            // Can seek: False
```

**Comment by atecce** [comment]
Hi! Thanks for the prompt response. I have actually gotten passed that and now run into something else. I had resigned myself to writing all these archives to disk, but it would be _awesome_ if I could do this from memory. 

I’m mobile at the moment but the stack trace was something like this:

```   at System.IO.Compression.ZipArchive.ReadCentralDirectory()
   at System.IO.Compression.ZipArchive.get_Entries()
   at ExcelDataReader.Core.ZipWorker.FindEntry(String name)
   at ExcelDataReader.Core.ZipWorker.GetWorkbookStream()
   at ExcelDataReader.Core.OpenXmlFormat.XlsxWorkbook.ReadWorkbook()
   at ExcelDataReader.Core.OpenXmlFormat.XlsxWorkbook..ctor(ZipWorker zipWorker)
   at ExcelDataReader.ExcelOpenXmlReader..ctor(Stream stream)
   at ExcelDataReader.ExcelReaderFactory.CreateReader(Stream fileStream, ExcelReaderConfiguration configuration)
   at RAPDiff.Program.diffXlsxStreams(Stream stream1, Stream stream2) in C:\Users\atecce\RAPDiff\RAPDiff\Program.cs:line 90
   at RAPDiff.Program.Main(String[] args) in C:\Users\atecce\RAPDiff\RAPDiff\Program.cs:line 154
```

And the message was:

`'Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory.'`

I can get back to you in a bit to edit this. On my commute.

**Comment by andersnm** [comment]
Sounds like the stream either wasn't copied into the MemoryStream properly, or perhaps the underlying xlsx is corrupt?

This works for me:

```c#
            using (var zip = System.IO.Compression.ZipFile.OpenRead("..\\..\\file.test.zip"))
            {
                var entry = zip.Entries[0];
                using (var stream = entry.Open())
                {
                    using (var memstrm = new MemoryStream())
                    {
                        stream.CopyTo(memstrm);

                        using (var reader = ExcelReaderFactory.CreateReader(memstrm))
                        {
                            Console.WriteLine("rows: " + reader.RowCount.ToString());
                        }
                    }
                }
            }
```

**Comment by atecce** [comment]
Will definitely look into it once I’m at rest. I think it’s doubtful that the underlying .xlsx is corrupt because I had refactored it from an old solution which was trying to track diffs XML file by XML file (lol)

**Comment by atecce** [comment]
Rofl. Looks like I tried to load the same stream into memory stream twice. Thanks for all your help!
