### ISSUE TITLE
XLSX formula errors read as strings

### ISSUE THREAD

**Issue by andersnm** [ExcelDataReader/ExcelDataReader#329]
Same with CSV, but is unavoidable. XLS OK.

Example:
[ExcelNA.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/1915260/ExcelNA.xlsx)
[ExcelNA.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/1915263/ExcelNA.zip) (zipped xls)

https://stackoverflow.com/questions/49857097/exceldatareader-reading-values-like-n-a-as-string-instead-of-null-or-missing-wh

**Comment by sporifolous** [comment]
Cells containing strings matching errors are now read as those errors. E.g. a cell value of "#N/A" will be read as null.
A little weird, I know, but shouldn't a string that just happens to look like an error still be read as a string?

**Comment by andersnm** [comment]
@sporifolous Hi, the intended behaviour should be like you expect. I.e a cell with an error should be returned as null, whereas a cell with f.ex the string  "#N/A" should be returned as a string with the value "#N/A". The XLSX XML has a flag per cell whether the contents is an error or a string, and the reader returns null only for the errors:

https://github.com/ExcelDataReader/ExcelDataReader/blob/e5b7d41b580603c866b9097496139080c0bba105/src/ExcelDataReader/Core/OpenXmlFormat/XlsxWorksheet.cs#L579-L580

Are you experiencing something different?

**Comment by andersnm** [comment]
I created a new spreadsheet in Excel, and manually input the string "#N/A" into a cell, and the saved XML looks like this:

```xml
<c r="A1" t="e"><v>#N/A</v></c>
```

Apparently Excel recognizes the string and automatically sets `t="e"`, which basically means the datatype for the cell is "Error", which always returns as null in ExcelDataReader.

 (The "Text" cell formatting is set separately from the cell type and shouldn't have any effect on this)

So that explains what's going on. Looks like some kind of edge case. Not sure how to best handle this, maybe some kind of `GetCellError(i)` method to get the error string for a cell.
