### ISSUE TITLE
GetName

### ISSUE THREAD

**Issue by HillMountain** [ExcelDataReader/ExcelDataReader#330]
Hi,

Is it possible to somehow get the columnName from the rowreader? To do some kind of filtering like this:

if (rowReader.GetName("projekt").GetValue.ToString() == ("My Project"))
{
	return true;
}
else
{
	return false;
}

Thanks.

**Comment by andersnm** [comment]
Hi,

Are you trying to do something similar as described in this stackoverflow issue?

https://stackoverflow.com/questions/49908729/exceldatareader-filtercolumn-usage

**Comment by HillMountain** [comment]
Yes, thats it. Thanks!
