### ISSUE TITLE
“IExcelDataReader”未包含“AsDataSet”的定义

### ISSUE THREAD

**Issue by dcx013** [ExcelDataReader/ExcelDataReader#334]
“IExcelDataReader”未包含“AsDataSet”的定义

**Comment by appel1** [comment]
> Install the ExcelDataReader.DataSet extension package to use the AsDataSet() method to populate a System.Data.DataSet. This will also pull in the base package. Compatible with net20, net45 and netstandard2.0.

https://github.com/ExcelDataReader/ExcelDataReader#finding-the-binaries
