### ISSUE TITLE
Reading empty column 

### ISSUE THREAD

**Issue by umesh190690** [ExcelDataReader/ExcelDataReader#335]
Its read empty column in a large file it does not avoid empty column. File contains only 52 column but it reads 16k column which are empty 

                excelReader = ExcelReaderFactory.CreateReader(fileStream);
                DataSet dataset = excelReader.AsDataSet();

**Comment by andersnm** [comment]
I am guessing a cell in the right-most column contains some formatting, but not necessarily any data, so ExcelDataReader expands all the cells inbetween for you. We've seen (and fixed) something similar before where a spreadsheet only had ~100 rows of data, but generated a million empty rows afterwards because of formatting. Although I have to look at your spreadsheet to confirm, please anonymize and upload the xlsx if you can.

If you know the column indices/headers you need or want to exclude, you could look into the ExcelDataSetConfiguration.FilterColumn callback to remove unwanted columns.

Otherwise, you have to scan the dataset manually and remove empty columns yourself.

**Comment by umesh190690** [comment]
if i would know then how can i define cells(from i want to remove column) can you elaborate ?

```
 FilterColumn = (columnReader, columnIndex) =>
                headers.IndexOf("string") != columnIndex
```
tried with this example says must have already  predefined headers but in my case not storing header list

**Comment by andersnm** [comment]
If you know which headers to keep, you have to do something like this:

```c#
    var keepHeaders = new string[] { "Name", "Address" };
    var headers = new List<string>();

    ds = reader.AsDataSet(new ExcelDataSetConfiguration()
    {
        ConfigureDataTable = (tableReader) => new ExcelDataTableConfiguration()
        {
            UseHeaderRow = true,

            ReadHeaderRow = rowReader => {
                for (var i = 0; i < rowReader.FieldCount; i++)
                    headers.Add(Convert.ToString(rowReader.GetValue(i)));
            },

            FilterColumn = (columnReader, columnIndex) =>
                keepHeaders.Contains(headers[columnIndex])
        }
    });
```


Depending on the use case, maybe it is sufficient to remove columns without a header like this: (mostly same code as above, changed the FilterColumn callback):

```c#
	var headers = new List<string>();
	...

            FilterColumn = (columnReader, columnIndex) =>
                !string.IsNullOrEmpty(headers[columnIndex])
```


However, if you are happy to remove everything after f.ex the 52nd column, then you could use a simpler FilterColumn like this:

```c#
    FilterColumn = (columnReader, columnIndex) => columnIndex < 52
```

**Comment by umesh190690** [comment]
Yeah but it take first row only .but my header at 8 th position

**Comment by andersnm** [comment]
The `ReadHeaderRow` callback can skip rows before reading the header like this:

```c#
            ReadHeaderRow = rowReader => {
                for (var i = 0; i < 8; i++)
                    rowReader.Read();

                for (var i = 0; i < rowReader.FieldCount; i++)
                    headers.Add(Convert.ToString(rowReader.GetValue(i)));
            },
```

**Comment by umesh190690** [comment]
It working now thank you :) but can we get header name

**Comment by andersnm** [comment]
@umesh190690 If the header is skipped, try to reduce `8` to f.ex `7` in the `ReadHeaderRow` callback. This number determines how many rows the reader should skip before using the following row as headers.

**Comment by umesh190690** [comment]
but at 7 position cells value are empty it will again remove all columns which cell has value empty result in 0 rows

**Comment by andersnm** [comment]
Apologies, but I'm not following entirely. The headers should be in `DataTable.Columns[...].ColumnName`. Can you please share your code, describe the xlsx contents, describe the output you get and what output is expected?

**Comment by umesh190690** [comment]
This Code 
```
          var headers = new List<string>();
            DataSet dataset = excelReader.AsDataSet(new ExcelDataSetConfiguration()
            {
                ConfigureDataTable = (tableReader) => new ExcelDataTableConfiguration()
                {
                    UseHeaderRow = true,
                    ReadHeaderRow = rowReader =>
                    {
                        for (var i = 0; i < ; i++)
                            rowReader.Read();

                        for (var i = 0; i < rowReader.FieldCount; i++)
                            headers.Add(Convert.ToString(rowReader.GetValue(i)));
                    },
                    FilterColumn = (columnReader, columnIndex) =>
                        !string.IsNullOrEmpty(headers[columnIndex])
                }
            });
```

[http://jmp.sh/v/2z1n2M8VqcD0xfKn0FUV](file)

right now file does not content empty value but when i get header row ..i want header to be present in dataset also

**Comment by umesh190690** [comment]
Ok @andersnm thankx this will help me alot

**Comment by umesh190690** [comment]
Hello @andersnm  Is that possible to select multiColumn like 1-2(1 to 2 rows as columns )?

**Comment by andersnm** [comment]
@umesh190690 If you want to "rotate" the spreadsheet as described in issue #271, then there is no builtin way to do this (I'm guessing this is what you ask, can't quite parse your question, please clarify if I'm mistaken)

**Comment by umeshshende** [comment]
Can it be possible to read the previous row when its already read? using userheaderow=true
