### ISSUE TITLE
How to handle a comma enclosed inside double quotes

### ISSUE THREAD

**Issue by bowill0** [ExcelDataReader/ExcelDataReader#340]
It doesn't seem to handle when a comma is present inside a double quoted value. It treats this as two separate values. Is there any settings for configuring the CSV reader to handle this?

**Comment by andersnm** [comment]
Hi,

Any chance you could provide a CSV for us to reproduce? There is a unit test for this scenario:

Test CSV:
https://github.com/ExcelDataReader/ExcelDataReader/blob/22e24602a7baaa7e95b988a3392ce46dbb6e025a/test/Resources/csv/comma_in_quotes.csv#L2

Test assert:
https://github.com/ExcelDataReader/ExcelDataReader/blob/22e24602a7baaa7e95b988a3392ce46dbb6e025a/test/ExcelDataReader.Tests/ExcelCsvReaderTest.cs#L47

**Comment by bowill0** [comment]
You can grab a weekly update file.  The npidata file has this scenario in column K.

**Comment by andersnm** [comment]
Hi, unfortunately I cannot give a timeline for this. It could be a couple days, weeks or months. Apologies for not being more specific. 

If you need to resolve this quickly, there's always CsvHelper. Or I would really appreciate a PR or even just a smaller, more specific repro to help progress this.

So far I just opened one of the npidata files with the TestApp in the repo, but couldn't find anything immediately in the wall of cells. Big sheet :(

**Comment by bowill0** [comment]
I tried CsvHelper but realized the issue was my fault, i was not adding the quotation marks back in the new file i was writing out.  I didn't realize they were being stripped.  This is my mistake, you can probably close this issue.  Apologies.
