### ISSUE TITLE
Read cell indentation

### ISSUE THREAD

**Issue by appel1** [ExcelDataReader/ExcelDataReader#341]
I just need the indentation so one way would be to expose this using a method similar to GetNumberFormatString or we could have a GetCellStyle that includes all cell style metadata (color, font, border, alignment, text wrap etc). I think it'd be enough to expose this per cell and hide where the style comes from like inheritance and explicit cell styles. 

Any opinions?

**Comment by andersnm** [comment]
The only input I have, IMHO pr-cell data should be exposed through through a single GetCellStyle()/CellStyle object. This simplifies extensions like the [MergeCellsReader](https://gist.github.com/andersnm/7205389e5e5a71773a9716e0853e3ee7) which currently needs some maintenance whenever the interface is extended. If the reader returned a CellStyle, extensions can handle new pr-cell fields transparently

**Comment by appel1** [comment]
I've started implementing this, see https://github.com/appel1/ExcelDataReader/tree/issue341.
