### ISSUE TITLE
Need Dynamic reading of Column Header - without declaring List Property

### ISSUE THREAD

**Issue by Gardens18** [ExcelDataReader/ExcelDataReader#348]
We need to read the excel file and the output should be should be json object but without declaring the "column names" as properties of the list class. Because it is becoming like hard coded and not as a dynamic solution to read any excel file.

**Comment by andersnm** [comment]
Hi,

As a starting point, here is one way to convert an arbitrary Excel file to JSON without knowing the column names:

```c#
var result = new List<KeyValuePair<string, List<List<object>>>>();
...

do {
	var sheet = new List<List<object>>();
	while (reader.Read()) {
		var row = new List<object>();
		for (var i = 0; i < reader.FieldCount; i++) {
			row.Add(reader.GetValue(i));
		}
		sheet.Add(row);
	}
	result.Add(new KeyValuePair<string, List<List<object>>>(reader.Name, sheet));
} while (reader.NextResult());

... 
Console.WriteLine(JsonConvert.SerializeObject(result, Formatting.Indented));
```

Assuming the reader object is already created, this basic example prints a JSON with all rows in all sheets, where the column headers are part of the data. Depending on your requirements, you can adjust the JSON shape as needed with POCOs for sheets/columns/rows/cells.

Also, please note this issues tracker is primarily intended for reporting bugs in the ExcelDataReader library. For general support its better to use Stackoverflow. Thanks!

**Comment by Gardens18** [comment]
Thanks for update.
Our desired JSON Output as follows,

{sheet1 : [
{ "column_name1": "row_value1","column_name2": "row_value1","column_name3": "row_value1"},
{"column_name1": "row_value2","column_name2": "row_value2","column_name3": "row_value2"},
{ "column_name1": "row_value3","column_name2": "row_value3","column_name3": "row_value3"}
],
sheet2 : [
{ "column_name1": "row_value1","column_name2": "row_value1","column_name3": "row_value1"},
{"column_name1": "row_value2","column_name2": "row_value2","column_name3": "row_value2"},
{ "column_name1": "row_value3","column_name2": "row_value3","column_name3": "row_value3"}
],
sheet3 : [
{ "column_name1": "row_value1","column_name2": "row_value1","column_name3": "row_value1"},
{"column_name1": "row_value2","column_name2": "row_value2","column_name3": "row_value2"},
{ "column_name1": "row_value3","column_name2": "row_value3","column_name3": "row_value3"}
]
}

![image](https://user-images.githubusercontent.com/41816775/44846140-3a4ca080-ac58-11e8-888c-e69fa144900b.png)



Note: 

This below code seems to does the job but we are getting the desired output.

**Comment by andersnm** [comment]
Maybe this will work instead?

```c#
return new JsonResult { 
    Data = reader.AsDataSet(), 
    JsonRequestBehavior = JsonRequestBehavior.AllowGet 
};
```

**Comment by Gardens18** [comment]
Is this correct? Data = reader.AsDataSet(), or Data = result.AsDataSet(),

**Comment by andersnm** [comment]
It is `reader.AsDataSet()`, and replaces the code section I suggested initially. 

But you need to add a reference to the Nuget package "ExcelDataReader.DataSet" before you can use the `AsDataSet()` method.
