### ISSUE TITLE
Last line of CSV not read

### ISSUE THREAD

**Issue by guillaume-fr** [ExcelDataReader/ExcelDataReader#351]
The CSV reader doesn't read the last line of data when the file doesn't end with LF.

**Comment by andersnm** [comment]
Hi,

Do you have an example CSV demonstrating the problem?

I finally got around to test this, but the small CSVs I tried work as expected. Using the TestApp in the repo to read a simple, two rows CSV without linebreak at the end like this:

```
1,2,3
4,5,6
```

There is also a passing test in the repo which reads a single column, four rows CSV without linebreak at the end:
https://github.com/ExcelDataReader/ExcelDataReader/blob/de60db2a330f1cc95b7b36ce0ca63e416b104636/test/ExcelDataReader.Tests/ExcelCsvReaderTest.cs#L282

**Comment by andersnm** [comment]
Thanks for the repro! It appears the last line isn't read when the file ends with a separator, having an empty cell at the end. That should definitely be fixed

**Comment by arisliang** [comment]
Glad somebody raised this issue, any workaround for this now?

**Comment by arisliang** [comment]
I'm doing something like this for now:
>string lastLine = File.ReadLines(filename).Last();
            if (lastLine.EndsWith("\t"))
            {
                using (var stream = File.Open(filename, FileMode.Open, FileAccess.ReadWrite))
                {
                    stream.SetLength(stream.Length - 1);
                }
            }

`\t` being the separator of the file. Hope it helps

**Comment by jakubmaguza** [comment]
#358

**Comment by andersnm** [comment]
Thx @jakubmaguza, its released in in 3.4.2
