### ISSUE TITLE
There is no comma

### ISSUE THREAD

**Issue by torrhet** [ExcelDataReader/ExcelDataReader#353]
--ORIGINAL
BODY →
② OPTION1,
② OPTION2

--READER
"BODY →\n② OPTION1\n② OPTION2"

A comma is disappeared.

What's going on here.

**Comment by andersnm** [comment]
Could you please provide an Excel file which demonstrates this problem? Thanks

**Comment by torrhet** [comment]
I found a problem. It was my fault not this. Sorry.
