### ISSUE TITLE
Doesn't handle namespaces correctly for xlsx files

### ISSUE THREAD

**Issue by appel1** [ExcelDataReader/ExcelDataReader#354]
Instead of using namespaces properly we currently expect that a certain namespace uses a certain prefix. 

[Sample](https://github.com/ExcelDataReader/ExcelDataReader/files/2413942/namespaceissue.xlsx)

**Comment by andersnm** [comment]
@appel1 Nice find, are you looking into this?

Had a cursory look, and a proper fix should change all calls to GetAttribute() to take a namespace URI parameter. Right now the code assumes all attributes have no prefix, except for the sheet id attribute in the attached sample where it assumes the attribute is prefixed with "r:". Presumably the code should suppport any prefix on any attribute

**Comment by appel1** [comment]
Yes, should be fairly quick to fix so hopefully later this week.

**Comment by andersnm** [comment]
For later, it would be nice to fix the rest of the GetAttribute() calls with namespace URIs in case those have prefixes too.

**Comment by andersnm** [comment]
@appel1 You are absolutely right! I jokingly called myself Dr. XML in the early 2000s, but wasn't aware unprefixed attributes require special interpretation.
