### ISSUE TITLE
ExcelDataReader reads 1048576 rows of xlsx file generated by LibreOffice

### ISSUE THREAD

**Issue by ybinzu** [ExcelDataReader/ExcelDataReader#357]
### Problem
I have a xlsx file created in LibreOffice (6.1.0.3, macos) which contains only 10 rows of actual data. `ExcelDataReader` reads all 1048576 rows as if they contain something, at the same time `ExcelDataReader.DataSet` reads only 10 rows.

### Expected Behavior
`ExcelDataReader` reads only 10 actual data rows.

### Steps to reproduce
Source code:
https://github.com/ybinzu/dotnet_xlsx_playground

Xlsx file:
https://github.com/ybinzu/dotnet_xlsx_playground/blob/master/1048576_rows.xlsx

Program.cs:
```csharp
using System;
using System.IO;
using System.Data;

using ExcelDataReader;

namespace xlsx_playground
{
    class Program
    {
        public class Reader
        {
            private string xlsxFile = "1048576_rows.xlsx";

            public Reader()
            {
                System.Text.Encoding.RegisterProvider(
                    System.Text.CodePagesEncodingProvider.Instance);
            }

            public int RowsUsingReader()
            {
                using (var stream = File.Open(xlsxFile, FileMode.Open,
                    FileAccess.Read))
                {
                    using (var reader = ExcelReaderFactory.CreateReader(stream))
                    {
                        int rows = 0;
                        do
                        {
                            while (reader.Read())
                            {
                                rows++;
                            }
                        }
                        while (reader.NextResult());

                        return rows;
                    }
                }
            }

            public int RowsUsingDataSet()
            {
                using (var stream = File.Open(xlsxFile, FileMode.Open,
                    FileAccess.Read))
                {
                    using (var reader = ExcelReaderFactory.CreateReader(stream))
                    {
                        var result = reader.AsDataSet();

                        return result.Tables[0].Rows.Count;
                    }
                }
            }
        }

        static void Main(string[] args)
        {
            var r = new Reader();
            Console.WriteLine($"RowsUsingReader: {r.RowsUsingReader()}");
            Console.WriteLine($"RowsUsingDataSet: {r.RowsUsingDataSet()}");
        }
    }
}

//
// $ dotnet run
// RowsUsingReader: 1048576
// RowsUsingDataSet: 10
//
```

**Comment by wizardgsz** [comment]
[row r="1048576" customFormat="false" ht="13.8" hidden="false" customHeight="false" outlineLevel="0" collapsed="false"][/row]

**Comment by andersnm** [comment]
There's a bit discussion in #270 why there is a discrepancy in behavior of trailing empty rows between dataset/reader. Generally it is assumed users of the reader interface should ignore empty rows in their own code, whereas AsDataSet contains some logic to discard trailing empty rows to handle this exact isue.

**Comment by ybinzu** [comment]
> There's a bit discussion in #270 why there is a discrepancy in behavior of trailing empty rows between dataset/reader. Generally it is assumed users of the reader interface should ignore empty rows in their own code, whereas AsDataSet contains some logic to discard trailing empty rows to handle this exact isue.

Thanks for the answer. I end up with checking fields for null values and terminate reader early if there are too many null rows (my xlsx files allow empty rows in between actual data rows).
