### ISSUE TITLE
Make it possible to read a DataSet and leaving the values as string

### ISSUE THREAD

**Issue by robvanmieghem** [ExcelDataReader/ExcelDataReader#36]
At the end of ReadDataSet, the function Helpers.FixDataTypes is called that sets the columndatatypes.
If you want the values as strings, you need to convert the tables again, setting the column datatypes as string. It would be move convenient if you would have the option of just leaving them as they are and not fixing the datatypes.

**Comment by andersnm** [comment]
This works now, to bypass the potentially expensive FixDataTypes step in AsDataSet:
```C#
reader.AsDataSet(new ExcelDataSetConfiguration()
{
    UseColumnDataType = false
});
```

This leaves DataColumn.DataType to null always.

**Comment by krohnm1** [comment]
That isn't actually working in the present release. I have dates that look like 11/2018 being changed to dates still and my number fields are losing leading/trailing zeros

**Comment by andersnm** [comment]
@krohnm1 Hei, can you make a repro for that, feel free to open a new issue if it's real. Although the behaviour you describe matches that of 2.x and earlier, or possibly a mismatch in expectations.

In version 3.0 and later, the output value types generally match what is stored in the file. You might lose leading/trailing zeroes if the cell has a number format. If you need to display data like Excel, check out the ExcelNumberFormat library.
