### ISSUE TITLE
feature request - add support for UWP version

### ISSUE THREAD

**Issue by Pinox** [ExcelDataReader/ExcelDataReader#362]
Hi Guys,

would be nice to have a sample of this lib working on UWP.  current code requires "full admin rights" and many companies rightly don't like that any app have full access to their network.
UWP uses a "broker service" to hand off file access so it works slightly different but way more secure.

**Comment by Pinox** [comment]
Hi @andersnm 

My understanding is that if the user did not select a file/folder before requesting the excel file access, then the app would need full admin rights , otherwise if the user preselected a file/folder then you can include the "access rights" in a future access list.

So there is no full access to the file system accept if it's "brokered" by the user, that obviously makes it great from a security perspective.

I refer to some notes that I read, not sure if they factually correct.

https://stackoverflow.com/questions/47344292/how-to-get-all-sub-folders-and-its-files-uwp

**Comment by andersnm** [comment]
If I ever get around to test this, I would probably start with something like this:

```c#
using Windows.Storage;

...

// Let user open an Excel file with file picker, does not require admin permission:
var picker = new Windows.Storage.Pickers.FileOpenPicker();
picker.FileTypeFilter.Add(".xls");
picker.FileTypeFilter.Add(".xlsx");
picker.FileTypeFilter.Add(".csv");

var excelFile = await picker.PickSingleFileAsync();

// Alternatively, open a file programmically from app data, does not require admin permission:
// var excelFile = await ApplicationData.Current.LocalFolder.GetFileAsync(filePath);

using (var runtimeStream = await excelFile.OpenAsync(FileAccessMode.Read)) {

	// Convert from Windows Runtime Stream to .NET Framework Stream:
	using (var stream = await runtimeStream.AsStreamForRead()) {
	
		// Use ExcelDataReader as normal:
		using (var reader = ExcelReaderFactory.CreateReader(stream)) {
			var ds = reader.AsDataSet();

			...

		}
	}
}
```

But I'm on thin ice without the tools :) If you can, please share the code and error messages you've got so far
