### ISSUE TITLE
Incorrect DateTime format

### ISSUE THREAD

**Issue by isaachaw** [ExcelDataReader/ExcelDataReader#364]
I think the `BuiltinNumberFormat` for `numFmtId`= 14 should follow the short date format (`CultureInfo.CurrentCulture.DateTimeFormat.ShortDatePattern`) of the system instead of hardcoded "d/m/yyyy". As noted in "Format Cells" menu in Excel, date formats that begin with an asterisk (*) respond to changes in regional date and time settings that are specified for the operating system.

**Comment by acaciafoe** [comment]
Any follow up on this issue?

**Comment by andersnm** [comment]
Hi,

You are probably right this could be improved, however I don't think anybody is working on it.

A solution could be something like:

1. add a new CultureInfo option to the configuration object (default InvariantCulture)
2. change `IWorksheet.GetNumberFormatString` to take a CultureInfo parameter
3. change `BuiltinNumberFormat.GetBuiltinNumberFormat()` to take a CultureInfo parameter
4. implement a converter from .NET DateTimeFormat patterns to Excel NumberFormat patterns
5. determine which built-in formats respond to changes in regional date and time settings, then
6. check for these formats in `GetBuiltinNumberFormat` and return the converted format string
