### ISSUE TITLE
How to get column width?

### ISSUE THREAD

**Issue by Snoopy-dogg** [ExcelDataReader/ExcelDataReader#365]
I know i can get RowHeight like this:
`using(var xls2003Stream = new MemoryStream(xlsBytes))`
`{`
`        using(var reader = ExcelReaderFactory.CreateReader(xls2003Stream))`
`        {`
`                var height = reader.RowHeight;`
`                ...`
`        }`
`}`
But the question is - can i get column width in some way? If there no such feature would be great to add this.

**Comment by andersnm** [comment]
Hi,

This is not supported, but is a valid feature request. Should be pretty straightforward to implement for XLSX, and a little harder for XLS. And needs a bit of planning what the API should look like

For XLS it appears to be documented in [[MS-XLS]](https://interoperability.blob.core.windows.net/files/MS-XLS/[MS-XLS].pdf) 2.4.89 DefColWidth and 2.4.53 ColInfo
