### ISSUE TITLE
Video tutorial to use ExcelDataReader

### ISSUE THREAD

**Issue by cheenostarx** [ExcelDataReader/ExcelDataReader#366]
Can someone refer me to a video tutorial on how to use this new version? I am working on a C# Windows application that allows importing data from an excel file to an access database. I'm totally clueless to this new version. I am only familiar with the old one that adds a .dll file as a reference. By the way, I am still a newbie in programming.

**Comment by jakubmaguza** [comment]
Do you know how to add Nuget package to your solution?

**Comment by cheenostarx** [comment]
> Do you know how to add Nuget package to your solution?

Yes, I already found ExcelDataReader on the list and installed it. But I still need to know how to use it as I am currently a beginner on this technology.

**Comment by jakubmaguza** [comment]
Have you checked main page? You have an explanation on how to use it:
https://github.com/ExcelDataReader/ExcelDataReader#how-to-use

**Comment by andersnm** [comment]
It would be cool to have videos explaining every use case of the library, but IMO is a lot to expect from a volunteer project. For now, users of the library are expected to base their work off the code sample and API reference in the README as a starting point. Although I'm happy to assist with specific use cases/challenges if the problem can be specified clearly.
