### ISSUE TITLE
Retrieve schema only

### ISSUE THREAD

**Issue by apobekiaris** [ExcelDataReader/ExcelDataReader#367]
my files are large and I want to let the user configure based on the dataset schema, is it possible?

```cs
using (var excelDataReader = ExcelReaderFactory.CreateReader(memoryStream)){
                    using (var dataSet = excelDataReader.GetDataSet(excelImport)) {
                        var dataColumns = dataSet.Tables.Cast<DataTable>()
                            .First(table => table.TableName == excelImport.SheetName).Columns.Cast<DataColumn>();
                        foreach (var dataColumn in dataColumns){
```

i want to fast get the columns without the getting the full dataset

**Comment by andersnm** [comment]
Hi,

There is no built-in way to do it, but you can examine as much or as little of the file as needed using the reader APIs to generate a schema. Relevant methods/properties: `Read()`, `FieldCount`, `GetFieldType()`/`GetValue()`

The reader APIs operate per-row, and unlike `AsDataSet()`, do not read everything at once

**Comment by apobekiaris** [comment]
i do not see how to get the fieldname though

**Comment by apobekiaris** [comment]
stupid question its the actual data

**Comment by apobekiaris** [comment]
the problem now is how to tell from which DataTable the data come from?

**Comment by andersnm** [comment]
I guess if you generate a schema pr sheet, using `reader.NextResult()` to advance the sheets, then you can correlate the sheets by index, or by name using `reader.Name`<->`table.Name`.

F.ex, possible workflow in a web app:

1) User uploads workbook to server via UI
2) Server saves workbook to temp location and processes the workbook to generate schema for all sheets, and returns it to the client
3) Client shows a UI based on the schema where the user selects which sheets and columns to import.
4) User submits schema selections to the server
5) Server processes workbook again, using sheet+column filters selected by the user
