### ISSUE TITLE
Unable to load XLS file - "Invalid file signature" (CreateReader) / Garbage data (CSV)

### ISSUE THREAD

**Issue by ktox** [ExcelDataReader/ExcelDataReader#368]
Greetings.

First of all, let me thank you for this nice piece of code -- apart from this particular case, it just works with any other file I tried, without the need for an OleDb provider.

Now, onto this one:
I have this "xls" file I need to parse, whose origin I do not know, that fails whether I load it using CreateReader or CreateCsvReader.
CreateReader -> "Invalid file signature" Exception
CreateCsvReader -> It "loads" the file, but the row/column data is either empty or pure garbage (I guess that's to be expected, since the file _is not_ a CSV).

These are the file's first bytes (Big Endian), with the text on the 3rd row being the first cell (header's first column):
![imagen](https://user-images.githubusercontent.com/26175066/48553106-65d74280-e8b9-11e8-8eea-7eade875be1b.png)

This is the code I'm using, which works for other files but not this one:
```csharp
using (var stream = File.Open(path, FileMode.Open, FileAccess.Read))  
{  
	stream.Seek(0L, SeekOrigin.Begin);  
	using (var reader = ExcelReaderFactory.CreateReader(stream, new ExcelReaderConfiguration() { FallbackEncoding = System.Text.Encoding.GetEncoding(1252) }))  
	{  
		var ds = reader.AsDataSet(new ExcelDataSetConfiguration()  
		{  
			UseColumnDataType = false,  
			ConfigureDataTable = (tableReader) => new ExcelDataTableConfiguration() { UseHeaderRow = true }  
		}).Tables[0];  
	}  
}
```

The reason I tried setting up the FallbackEncoding for 1252 (which, if I'm not mistaken is already the default value) is because all this time we have been using a python script with the following piece of code, in order to "convert" those files into "proper" xls ones:  
```python
w = open_workbook(path, encoding_override="cp1252")     # xlrd package
wc = copy(w)
wc.get_sheet(0).name = file[:-4]
wc.save(path)
```

Also, Excel 2010 and Interop.Excel 14 both open the file correcty as-is, yet I can't rely on Interop and can't save any edits on the file either -- Excel forces me to save on a native format.

Any help would be greatly appreciated!

Regards.

**Comment by wizardgsz** [comment]
The attachment to verify?

**Comment by ktox** [comment]
> 
> 
> The attachment to verify?

Sorry, would love to, but can't upload it as it contains sensible data -- and I can't edit it either, since Excel forces me to save it in another format :(

**Comment by andersnm** [comment]
Hi,

I guess 09 08 is the header for a *raw* BIFF5+ BOF record:

https://github.com/ExcelDataReader/ExcelDataReader/blob/6793a9c2adc99d4ee6668f1e3585284f9e8f5db4/src/ExcelDataReader/Core/BinaryFormat/Enums.cs#L65

It should have been detected by this function:
https://github.com/ExcelDataReader/ExcelDataReader/blob/6793a9c2adc99d4ee6668f1e3585284f9e8f5db4/src/ExcelDataReader/Core/BinaryFormat/XlsWorkbook.cs#L91

Testing the header bytes in a fiddle based on the above function:
```c#
		var bytes = new byte[] {
			9, 8, 6, 0, 0, 0, 16, 0
		};
		Console.WriteLine(BitConverter.ToUInt16(bytes, 0) == 0x0809); // true
		Console.WriteLine(BitConverter.ToUInt16(bytes, 2)); // size = 6
		Console.WriteLine(BitConverter.ToUInt16(bytes, 4)); // bofVersion = 0
		Console.WriteLine(BitConverter.ToUInt16(bytes, 6)); // type = 16
```

So apparently, the BOF size and version values in the xls aren't handled.

Do you know where the xls came from? Which program made it?

**Comment by wizardgsz** [comment]
Ok, you can "anonymize" it to share your data, otherwise you can understand it is impossible to support you without a file :)

Double check if your XLS is saved as "95" format, it is not fully supported.

**Comment by ktox** [comment]
> Do you know where the xls came from? Which program made it?

Not sure, and can't easily find out either, sorry!


> So apparently, the BOF size and version values in the xls aren't handled.

Want me to try that same fiddle with the actual file and share the results?

> 
> Ok, you can "anonymize" it to share your data, otherwise you can understand it is impossible to support you without a file :)

I'm aware, yes, that's what's frustrating -- would you be so kind to share how can I "anonymize" this data? I guess it's worth a try, thanks!

> 
> Double check if your XLS is saved as "95" format, it is not fully supported.

Either Excel or LibreOffice properties show absolutely nothing about it. Know any other way to find out? Thanks!

**Comment by wizardgsz** [comment]
File -> Save As...

You'll see "Excel 95/5.0 Workbook" as File type most probably

**Comment by ktox** [comment]
This is what I get from Excel 2010:
![imagen](https://user-images.githubusercontent.com/26175066/48559353-3da40f80-e8ca-11e8-9a99-f1f8a689029c.png)

![imagen](https://user-images.githubusercontent.com/26175066/48559574-a4c1c400-e8ca-11e8-9121-aec8246c6367.png)

This is Save As... dialog just as it opens:
![imagen](https://user-images.githubusercontent.com/26175066/48559643-c1f69280-e8ca-11e8-906b-b231a7348e79.png)

Maybe it's got to do with that "Excel 2 Worksheets" filetype?

Thanks!

**Comment by wizardgsz** [comment]
It means this is an XLSX, not XLS. 

I'm using Excel 2010 and, for XLS 95 files, the combobox shows "Microsoft Excel 5.0/95 Workbook (*.xls)"

**Comment by andersnm** [comment]
Note that the problematic file is a raw BIFF5+ stream with unexpected (possibly invalid) values in its header. Its a variant of XLS with only one worksheet, which is not embedded in a Compound Document (CFB). This is unlike "regular" XLS workbooks using CFB as container format, which have embedded BIFF substreams for each worksheet

This raw format is generally supported by ExcelDataReader to support very early versions of Excel which saved raw BIFF2-4 streams. ExcelDataReader does support raw BIFF5+ streams as well, despite not having seen any in the wild.

This can very likely be resolved by loosening the rules in the `XlsWorkBook.IsRawBiffStream` method for BIFF5+, but have to cross-reference with the specs.

**Comment by andersnm** [comment]
It would help if you could use a hex editor on your file to replace sensitive strings with X'es before sharing. Assuming your file has no sensitive numbers/dates and its not too much work.

Per that description of non-Excel BOF records, it looks like `IsRawBiffStream` indeed should loosen its rules for validating the header. 

I believe the correct interpretation of your header is:

```c#
var bytes = new byte[] {
	// BIFF header: identifier 0x0809 (BOF)
	9, 8,
	// BIFF header: record size 6 bytes
	6, 0,
	// BOF record: BIFF stream version 0 (BIFF5)
	0, 0,
	// BOF record: file type 16 = Sheet
	16, 0
};
```

ExcelDataReader expects BIFF record size to be 8 or 16 bytes, and fails because the header has 6 bytes.

ExcelDataReader expects BIFF version to be 0x500 or 0x600, and would fail because the header has 0.

It's possible to use a hex editor to modify the header of an existing XLS to the same and verify it still loads in Excel for repro.

**Comment by ktox** [comment]
> 
> 
> It would help if you could use a hex editor on your file to replace sensitive strings with X'es before sharing. Assuming your file has no sensitive numbers/dates and its not too much work.
> 

Nice one! Definitely gonna try that -- but it's going to take some time, there're a lot of records here.

> Per that description of non-Excel BOF records, it looks like `IsRawBiffStream` indeed should loosen its rules for validating the header.
> 
> I believe the correct interpretation of your header is:
> 
> ```cs
> var bytes = new byte[] {
> 	// BIFF header: identifier 0x0809 (BOF)
> 	9, 8,
> 	// BIFF header: record size 6 bytes
> 	6, 0,
> 	// BOF record: BIFF stream version 0 (BIFF5)
> 	0, 0,
> 	// BOF record: file type 16 = Sheet
> 	16, 0
> };
> ```
> 
> ExcelDataReader expects BIFF record size to be 8 or 16 bytes, and fails because the header has 6 bytes.
> 

Sorry, could you please elaborate on the BIFF header Size part?
Is it feasable for ExcelDataReader to accept other record sizes other than 8 or 16 bytes?

> It's possible to use a hex editor to modify the header of an existing XLS to the same and verify it still loads in Excel for repro.

I failed miserably with this configuration -- it neither opened in Excel or EDR (the latter failed with an OutOfRange ex, probably precisely because of the "longer" size):
```cs
// changed size to 8 and version to 5 so it returns correctly from IsRawBiffStream
var bytes = new byte[] { 9, 8, 8, 0, 0, 5, 16, 0 };
```

Will upload the file as soon as I can!

**Comment by ktox** [comment]
[Finally managed to do it!](https://github.com/ExcelDataReader/ExcelDataReader/files/2590325/test_file.zip)

Tried erasing most of the rows or else it'd have taken me HOURS, yet somehow it still "remembers" the position for the last one (original had 10 columns and 360 rows) -- also reduced file size from 71KB to just 2KB.

Hope it helps!

**Comment by andersnm** [comment]
That definitely helps. Thanks. The following code changes fixes it in ExcelDataReader. That was the interesting part ;) If you want to submit a PR with a test, please do. Otherwise I'll try and get it done some time later.

```patch
diff --git a/src/ExcelDataReader/Core/BinaryFormat/XlsBiffStream.cs b/src/ExcelDataReader/Core/BinaryFormat/XlsBiffStream.cs
index 79d52c0..c551ee7 100644
--- a/src/ExcelDataReader/Core/BinaryFormat/XlsBiffStream.cs
+++ b/src/ExcelDataReader/Core/BinaryFormat/XlsBiffStream.cs
@@ -189,6 +189,7 @@ namespace ExcelDataReader.Core.BinaryFormat
                 case BIFFRECORDTYPE.MULBLANK:
                     return new XlsBiffMulBlankCell(bytes, offset, biffVersion);
                 case BIFFRECORDTYPE.LABEL_OLD:
+                    return new XlsBiffLabelCell(bytes, offset, 2);
                 case BIFFRECORDTYPE.LABEL:
                 case BIFFRECORDTYPE.RSTRING:
                     return new XlsBiffLabelCell(bytes, offset, biffVersion);
@@ -280,7 +281,13 @@ namespace ExcelDataReader.Core.BinaryFormat
                 case BIFFRECORDTYPE.BOF_V4:
                     return 4;
                 case BIFFRECORDTYPE.BOF:
-                    if (bof.Version == 0x500)
+                    if (bof.Version == 0x200)
+                        return 2;
+                    else if (bof.Version == 0x300)
+                        return 3;
+                    else if (bof.Version == 0x400)
+                        return 3;
+                    else if (bof.Version == 0x500 || bof.Version == 0)
                         return 5;
                     if (bof.Version == 0x600)
                         return 8;
```

```patch
diff --git a/src/ExcelDataReader/Core/BinaryFormat/XlsWorkbook.cs b/src/ExcelDataReader/Core/BinaryFormat/XlsWorkbook.cs
index c9948ea..2934770 100644
--- a/src/ExcelDataReader/Core/BinaryFormat/XlsWorkbook.cs
+++ b/src/ExcelDataReader/Core/BinaryFormat/XlsWorkbook.cs
@@ -103,14 +103,14 @@ namespace ExcelDataReader.Core.BinaryFormat
             switch (rid)
             {
                 case 0x0009: // BIFF2
-                    if (size != 4)
+                    if (size < 4)
                         return false;
                     if (type != 0x10 && type != 0x20 && type != 0x40)
                         return false;
                     return true;
                 case 0x0209: // BIFF3
                 case 0x0409: // BIFF4
-                    if (size != 6)
+                    if (size < 4)
                         return false;
                     if (type != 0x10 && type != 0x20 && type != 0x40 && type != 0x0100)
                         return false;
@@ -120,9 +120,9 @@ namespace ExcelDataReader.Core.BinaryFormat
                         return false;*/
                     return true;
                 case 0x0809: // BIFF5/BIFF8
-                    if (size != 8 && size != 16)
+                    if (size < 4)
                         return false;
-                    if (bofVersion != 0x0500 && bofVersion != 0x600)
+                    if (bofVersion != 0 && bofVersion != 0x0200 && bofVersion != 0x0300 && bofVersion != 0x0400 && bofVersion != 0x0500 && bofVersion != 0x600)
                         return false;
                     if (type != 0x5 && type != 0x6 && type != 0x10 && type != 0x20 && type != 0x40 && type != 0x0100)
                         return false;
```

**Comment by ktox** [comment]
> 
> That definitely helps. Thanks. The following code changes fixes it in ExcelDataReader. That was the interesting part ;) If you want to submit a PR with a test, please do. Otherwise I'll try and get it done some time later.
>

Awesome news!
Did the document help in some way?

Also unable to test it right now, but would love to try it out later on the weekend -- is this change already committed to one of the branches, or should I map out one of them and test it out locally?

Thank you for everything!

**Comment by andersnm** [comment]
Yes, the section about non-standard BOF in the PDF did help. The version checks in the updated code are based on that.

The code also laxes the requirements for BOF header sizes across all BIFF versions, and fixes a crash when BIFF2 label records occur in BIFF3+ streams. The last one was needed because the PDF says version 0 should be interpreted as BIFF5, but your file has BIFF2 label records in it.

I didn't commit anything yet, but happy to accept a PR against the develop branch with the above patches and a test

**Comment by ktox** [comment]
> 
> I didn't commit anything yet, but happy to accept a PR against the develop branch with the above patches and a test

Forked the project and implemented the proposed fixes -- it works!

Now, when I tried with the original file, all the "numeric" cells (which are correctly interpreted as Double, just as it does with normal files) are being read incorrectly:
![imagen](https://user-images.githubusercontent.com/26175066/48677618-43158a00-eb56-11e8-9c72-5ebbe4b26329.png)

Could you help me solve this issue by pointing me to the right direction?
I don't want to bother you more than necessary, yet don't have the time to fiddle around with the whole project to find what I'm looking for :(

Thank you!

**Comment by andersnm** [comment]
Hm ok, this could be one out of two things. It's either the interpretation of the "version 0" field should be BIFF2, or, we need to fix the handling of all specifically versioned *_OLD records in ExcelDataReader - f.ex NUMBER_OLD, like I already did for BOF_OLD. Should ideally rummage the internet for more "Excel 2 Worksheets" type XLS files to have wider range of test data.

One thing to try, and the pattern to set version of these *_OLD records, if you look in XlsBiffStream.cs:
```c#
                case BIFFRECORDTYPE.NUMBER:
                case BIFFRECORDTYPE.NUMBER_OLD:
                    return new XlsBiffNumberCell(bytes, offset, biffVersion);
```

The above could be rewritten as:
```c#
                case BIFFRECORDTYPE.NUMBER:
                    return new XlsBiffNumberCell(bytes, offset, biffVersion);
                case BIFFRECORDTYPE.NUMBER_OLD:
                    return new XlsBiffNumberCell(bytes, offset, 2);
```

(although I can't verify if this is correct with the attached file, am getting 2.0684E+272 in both Excel and the TestApp. Also, the same problem might still occur for other *_OLD record types)

**Comment by ktox** [comment]
> 
> 
> Hm ok, this could be one out of two things. It's either the interpretation of the "version 0" field should be BIFF2, or, we need to fix the handling of all specifically versioned *_OLD records in ExcelDataReader - f.ex NUMBER_OLD, like I already did for BOF_OLD.
> 
> One thing to try, and the pattern to set version of these *_OLD records, if you look in XlsBiffStream.cs:
> 
> ```cs
>                 case BIFFRECORDTYPE.NUMBER:
>                 case BIFFRECORDTYPE.NUMBER_OLD:
>                     return new XlsBiffNumberCell(bytes, offset, biffVersion);
> ```
> 
> The above could be rewritten as:
> 
> ```cs
>                 case BIFFRECORDTYPE.NUMBER:
>                     return new XlsBiffNumberCell(bytes, offset, biffVersion);
>                 case BIFFRECORDTYPE.NUMBER_OLD:
>                     return new XlsBiffNumberCell(bytes, offset, 2);
> ```
> 

Bullseye!
![imagen](https://user-images.githubusercontent.com/26175066/48728974-373ccd00-ec15-11e8-88d2-7d12ecbf3b62.png)
![imagen](https://user-images.githubusercontent.com/26175066/48729076-779c4b00-ec15-11e8-8794-e63d6120cad4.png)
![imagen](https://user-images.githubusercontent.com/26175066/48729106-8aaf1b00-ec15-11e8-90e3-bc4cd466861d.png)
Can confirm it works for the whole file with that fix!

> ([...] Also, the same problem might still occur for other *_OLD record types)

Right, that would certainly be problematic, especially if it breaks other BIFF files -- is there any way to "check" if a certain record is BIFF2 before calling XlsBiffCell?
I remember you previously confirmed this file had BIFF2 records, so maybe there's a way to implement your thought process into some sort of method so as not to break current functionality?

Just throwing it out there -- but what about reading a certain numeric cell as both `biffVersion` and `2`, and then taking a decision based on the results? Like maybe if one of them throws, then take the other; or in this case, choosing the "normal" (smaller?) one.
Another alternative is reading the cell as string, then parsing into a Double, and take the one which matches.

**Comment by andersnm** [comment]
>  is there any way to "check" if a certain record is BIFF2 before calling XlsBiffCell?

Yes, this is detailed in that PDF. Certain record identifiers are specifically BIFF2, with related but different identifiers variants for BIFF3+. ExcelDataReader used to normalize these identifiers and interpret the record contents purely based on `biffVersion`. However, we've discovered this is maybe not correct.

F.ex in Enums.cs, the label record identifiers:
```
        LABEL = 0x0204, // String cell (up to 255 symbols)

        LABEL_OLD = 0x0004, // String cell (up to 255 symbols), old format
```

BIFF2 uses 0x0004, and the string is saved in a "short string" format for the content (8 bit length, 8 bit char data)
BIFF3+ uses 0x0204, and the spec defines different string formats depending on the `biffVersion`:

- If 0x0204 occurs in a file where biffVersion indicates BIFF3-5, the string is saved in a "long string format" (16 bit length, 8 byte char data)
- If 0x0204 occurs in a file where biffVersion indicates BIFF8, the string is saved in a "unicode string format". (16 bit length, 16 bit char data)

So it looks like we have to verify all record identifiers if they are specific to a certain BIFF version, and change to parse accordingly.

**Comment by ktox** [comment]
> So it looks like we have to verify all record identifiers if they are specific to a certain BIFF version, and change to parse accordingly.

OK, want me to hold onto that PR, then?
Or should I just push it with the previously discussed proposed changes to BIFF detection, LABEL_OLD and NUMBER_OLD?

If you need a hand with this new development, let me know, I'll try to help as best as I can.

**Comment by andersnm** [comment]
I suspect we're on the right track, and we have your file as initial test data, so you may submit the pull request if you're happy with it.

Still thinking about what is the best approach to fully resolve this. It's probably a good idea to craft some XLS test data by hand to verify/reverse engineer exactly how Excel interprets "version 0" in the BOF header. It's probably not a trivial task.

This is a volunteer project, so any help is appreciated if you can. :)

**Comment by andersnm** [comment]
For reference, here is the code used to generate the raw BIFF stream test XLS files:
https://gist.github.com/andersnm/b874caaf0b96bab5f87ee3ef81940630
