### ISSUE TITLE
Is there a way to enforce that the column is untyped?

### ISSUE THREAD

**Issue by alexgman** [ExcelDataReader/ExcelDataReader#370]
I've got a value like `12/01/2013` in an XLS file, and when I'm converting this to a csv, the output I am getting is `12/01/2013 12:00:00AM`.

Here's how I am reading the XLS:

                var ds = reader.AsDataSet(new ExcelDataSetConfiguration()
                {
                    UseColumnDataType = false,
                    ConfigureDataTable = (tableReader) => new ExcelDataTableConfiguration()
                    {
                        UseHeaderRow = false
                    }
                });

**Is there a way to enforce that the column is untyped?**

Full code:
```

public static bool SaveAsCsv(string excelFilePath, string destinationCsvFilePath)
        {
            using (var stream = new FileStream(excelFilePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
            {
                IExcelDataReader reader = null;
                if (excelFilePath.EndsWith(".xls"))
                {
                    reader = ExcelReaderFactory.CreateBinaryReader(stream);
                }
                else if (excelFilePath.EndsWith(".xlsx"))
                {
                    reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                }

                if (reader == null)
                    return false;

                var ds = reader.AsDataSet(new ExcelDataSetConfiguration()
                {
                    UseColumnDataType = false,
                    ConfigureDataTable = (tableReader) => new ExcelDataTableConfiguration()
                    {
                        UseHeaderRow = false
                    }
                });

                var csvContent = string.Empty;
                int row_no = 0;
                while (row_no < ds.Tables[0].Rows.Count)
                {
                    var arr = new List<string>();
                    for (int i = 0; i < ds.Tables[0].Columns.Count; i++)
                    {
                        var cell = ds.Tables[0].Rows[row_no][i].ToString();
                        arr.Add(cell.Contains(",") ? "\"" + cell + "\"" : cell);
                    }
                    row_no++;
                    csvContent += string.Join(",", arr) + "\n";
                }
                StreamWriter csv = new StreamWriter(destinationCsvFilePath, false);
                csv.Write(csvContent);
                csv.Close();
                return true;
            }
        }
```

**Comment by andersnm** [comment]
Hi,

I'm glad you found how to write CSV, per #369 :)

To answer the title question, no, there is no way to enforce untyped columns. (if there were, dates would be returned as a double which cannot be interpreted reliably, probably not what you expect)

The reason you are getting the timestamp, is because both Excel's date type and the .NET DateTime both include time information in their underlying values, and by default `ToString()` prints both. There is no concept of a date without time in either type.

The reason the timestamp is not displayed in Excel, is because of the cells number format is set to 'yyyy-mm-dd' or something. You have to use the reader interface instead of AsDataSet and the reader method `GetNumberFormatString()` to view the format string. If you need to display the values exactly like Excel, please have a look at the [ExcelNumberFormat](https://github.com/andersnm/ExcelNumberFormat) library if it suits your use case (there is an example in ExcelDataReader's README)

**Comment by alexgman** [comment]
Thanks so much for your kind and thorough response. 

I've updated my code to include your suggestion, specifically regarding `GetNumberFormatString`; however, I am not sure how I would incorporate `ExcelNumberFormat`. I'd be very grateful for example, as the example that they have on their README, does not help. 

                var csvContent = string.Empty;
                do
                {
                    while (reader.Read())
                    {
                        var arr = new List<string>();
                        for (int i = 0; i < reader.FieldCount; i++)
                        {
                            var cell = reader[i]?.ToString();
                            var format = reader.GetNumberFormatString(i);
                            if (format == "mm\\/dd\\/yyyy" || format == "M/d/yyyy")
                            {
                                cell = cell.Replace(" 12:00:00 AM", "");
                            }
                            if (format == "h\\:mm\\:ss AM/PM")
                            {
                                cell = cell.Replace("12/31/1899 ", "");
                            }
                            var processedCell = cell == null ? string.Empty : cell.Contains(",") ? "\"" + cell + "\"" : cell;
                            arr.Add(processedCell);
                        }
                        csvContent += string.Join(",", arr) + "\n";
                    }
                } while (reader.NextResult());

**Comment by andersnm** [comment]
Hi,

The example I was refering to is the `GetFormattedValue()` method here which uses ExcelNumberFormat:
https://github.com/ExcelDataReader/ExcelDataReader#formatting

With that function, you can write your loop over FieldCount something like this:

```c#
var arr = new List<string>();
for (int i = 0; i < reader.FieldCount; i++) {
    var cellText = GetFormattedValue(reader, i, CultureInfo.InvariantCulture);
    arr.Add(cellText);
}
```

Just a point about CSV, I recommend to use a library like CsvHelper to handle those edge cases when strings have commas, quotes, linebreaks etc. I'm not very familiar with it, but looks like you could adapt your example to using the `CsvWriter.WriteField` and `CsvWriter.NextRecord` methods with few changes:
https://joshclose.github.io/CsvHelper/writing
