### ISSUE TITLE
How to read from HttpRequest rather than a File?

### ISSUE THREAD

**Issue by alexgman** [ExcelDataReader/ExcelDataReader#372]
I'd like to know how to extract the content from an HttpRequest, rather than a file. Currently I'm getting content from a file:

        public static bool SaveAsCsv(string excelFilePath, string destinationCsvFilePath)
        {
            using (var stream = new FileStream(excelFilePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
            {
                IExcelDataReader reader = null;
                if (excelFilePath.EndsWith(".xls"))
                {
                    reader = ExcelReaderFactory.CreateBinaryReader(stream);
                }
                else if (excelFilePath.EndsWith(".xlsx"))
                {
                    reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                }

                if (reader == null)
                {
                    return false;
                }

However, the requirement is to get the payload from an HttpRequest. 

I currently have the scaffolding for an Azure Function:

        [FunctionName("OnXlsxToCsvHttpTriggered")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            string name = req.Query["name"];

            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name = name ?? data?.name;

            return name != null
                ? (ActionResult)new OkObjectResult($"Hello, {name}")
                : new BadRequestObjectResult("Please pass a name on the query string or in the request body");
        }

I'd like to be able to get the payload from `req.Body` and somehow read it into `IExcelDataReader`?

**How do I take an HttpRequest payload and read it into the interface IExcelDataReader?**

**Comment by andersnm** [comment]
Hi,

I suppose `req.Body` is a System.IO.Stream:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequest.body?view=aspnetcore-2.1

`ExcelReaderFactory.CreateReader` takes a System.IO.Stream parameter, so there's a chance you can pass the body directly to it.

The docs dont say if the `req.Body` stream is seekable or not. You will get an error if it isn't. If so, you have to copy req.Body into a MemoryStream manually before passing it to CreateReader.
