### ISSUE TITLE
sheets management

### ISSUE THREAD

**Issue by QuAzI** [ExcelDataReader/ExcelDataReader#374]
How can I get how many sheets available?
Get current sheet number or name?
Set active sheet by name or number?

**Comment by andersnm** [comment]
Hi,

Assuming you are using the reader interface (from the README):

* `NextResult()` advances the cursor to the next sheet.
* `ResultsCount` returns the number of sheets in the current workbook.
* `Name` returns the name of the current sheet.

Seek to a sheet by name:
```c#
do {
   if (reader.Name == "Sheet2") {
     while (reader.Read()) {
     }
  }
} while (reader.NextResult());
```

Seek to sheet by index, and get current sheet number:
```c#
var sheetIndex = 0;
do {
   if (sheetIndex == 1) {
     while (reader.Read()) {
     }
  }
  sheetIndex++;
} while (reader.NextResult());
```
