### ISSUE TITLE
Large XLS file performance

### ISSUE THREAD

**Issue by uler3161** [ExcelDataReader/ExcelDataReader#375]
I inherited an application that used ExcelDataReader. I currently have it using version 3.4.0, but I've also been testing with the latest source code and it seems to have the same performance...

I have a 1GB xls file. Yes, I know that's probably a bad thing, but it's likely not going to be something I can change. I fully expect many more files that size or perhaps larger. Just for testing purposes, I opened this file in Excel 2016 and saved a copy to xlsx so I could compare performance side by side. 

Which brings me to the problem. I'm running the exact same code to parse the xls file as I am to parse the xlsx file. I've tested this on my laptop. It's only an i5-3210m with 8GB ram and a decent ssd. Definitely not high end, but I think enough to run a reasonable performance test. 

I should also note that while there's nothing wrong with the file itself, the data contained in it ended up not being valid for our business rules. As a result, when the parsing code got to that point, it stopped parsing. So, potentially the time spent to parse the entire 1GB file is even more than what I am showing below. And here, it is:

XLSX file: 7.34 minutes
XLS file: 18.66 hours

That's 152 times slower if I did my math right! Is xls format really that much harder to parse? 

I should note, that I also tried using OleDB and ODBC against this xls and every driver I tried gave me a system resources exceeded error. So maybe I should be glad ExcelDataReader can read it at all. But it's strange that I can use Excel to convert this xls to xlsx in only about 10 minutes. I don't really want to have to use interop to acheive that, but it's starting to look like the only solution.

Maybe there's something else I can do to speed this up?

**Comment by andersnm** [comment]
Hi,

Without testing or benchmarking anything myself yet, the first thing that came to mind is this bit of code in `ReadRegularSector`:

https://github.com/ExcelDataReader/ExcelDataReader/blob/6793a9c2adc99d4ee6668f1e3585284f9e8f5db4/src/ExcelDataReader/Core/CompoundFormat/CompoundStream.cs#L159

This code calls `BaseStream.Seek` every 512 bytes, but usually it's redundant because the file position is already at the right place. I never confirmed if `Seek` is smart enough to detect when the file position doesn't change. If it doesn't, I suspect it's a big performance drain on big files.

**Comment by uler3161** [comment]
> A sample file that exhibits this issue would be very useful since I can't reproduce it using my naive sample.

I'm first going to use your code against my file and see how long it takes. If that's still slow, I'll cleanse the data (it's got customer data now) and verify it's still slow, then I'll send it along. What would be the best way to send in a file this large?

**Comment by uler3161** [comment]
Ok, so I found something interesting while trying to cleanse the spreadsheet. The machine I'm working on now has LibreOffice. I opened the spreadsheet, cleansed the data, then saved to a new xls file. That file runs fast. So then I opened the original slow xls file again in LibreOffice and saved to a new xls without cleansing any data. That was fast. Whatever LibreOffice did, it fixes the problem. That leads me to believe whatever is creating the original file is saving something weird. I know virtually nothing about the product that's generating these spreadsheets. The only thing I can think is maybe it's generating an older xls version.

Anyway, since I wasn't able to cleanse this file without the cleansed version being fast, I asked one of the other people involved with the project if he had a file we could share with you and he did. It's about 140MB, so that'll be easier to get to you than a 1GB file. It shows the same symptoms. Very slow processing. Then opening in LibreOffice and saving back makes it go fast.

The file should be in the attached zip file.

[VH_1CCCV_Cell3_100cycles.069.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/2659257/VH_1CCCV_Cell3_100cycles.069.zip)

**Comment by andersnm** [comment]
The structure of the BIFF records in this file is like this:

```
ROW
ROW
ROW
ROW
... x 65531 rows
CELL
CELL
CELL
CELL
CELL
... x 42 columns x 65531 rows
```

Whereas ExcelDataReader prefers to work with data in order:

```
ROW
CELL
CELL
..
ROW
CELL
CELL
...
```

Effectively ExcelDataReader parses almost the entire sheet every 32 rows. (so it's not an issue with `Seek`)

The offending functions are `SetMinMaxRowOffset` (which builds the internal row index) and `ReadNextBlock` (which uses the internal row index)

**Comment by uler3161** [comment]
> Effectively ExcelDataReader parses almost the entire sheet every 32 rows. (so it's not an issue with `Seek`)
> 
> The offending functions are `SetMinMaxRowOffset` (which builds the internal row index) and `ReadNextBlock` (which uses the internal row index)

Thanks for the analysis. 

Is this such a weird case that I'll have to fix it myself? Or will someone on the ExcelDataReader team try to fix it?

**Comment by andersnm** [comment]
It's probably worth fixing in the ExcelDataReader, but I'm not sure I can commit to do it myself in the near term. PR welcome ;)

The absolutely simplest quickfix is to comment out this line:
https://github.com/ExcelDataReader/ExcelDataReader/blob/6793a9c2adc99d4ee6668f1e3585284f9e8f5db4/src/ExcelDataReader/Core/BinaryFormat/XlsWorksheet.cs#L513

This should speed up reading your raw data dramatically, but alas fail some features and tests with row height/collapse.

ExcelDataReader parses the file in two passes: The first pass (`ReadWorksheetGlobals`) creates an index of min/max BIFF record file offsets pr row. The second pass (`ReadWorksheetRows`) is during iteration, where it reads/buffers at least 32 rows at a time between the min offset for the row at (ChunkIndex\*32), and up until the max offset for the row at (ChunkIndex\*32+31).

This code has gone through some revisions already to handle files where row data is jumbled, but looks like it could be improved still.

One way to fix, is to include the ROW records in the index during the first pass, so they dont need to be read in the second pass. It would increase memory usage a bit, but not by much I suppose.
