### ISSUE TITLE
Dynamic List

### ISSUE THREAD

**Issue by weedkiller** [ExcelDataReader/ExcelDataReader#378]
Hi, I dont know the types prior to loading, can you help me, I need do something like...

How to get the TypedList from the Excel Or CSV file? I dont know what the col types & headers are ahead of time.

- How do I get that DynamicListFromExcel?

`var dynamicListFromExcel= JsonConvert.DeserializeObject<List<DynamicListFromExcel>>(testData);`

**Comment by andersnm** [comment]
Hi,

Are you asking how to get the column types and headers out of a spreadsheet ahead of time? Something similar to issue #367?

**Comment by andersnm** [comment]
Hi,

Note that creating DB tables and/or JSON is somewhat outside the scope of this project, as ExcelDataReader's primary concern is parsing Excel files and making the data accessible to developers. How to process the parsed data depends on the specific use case, requirements and data quality.

There are some suggestions how to create SQL tables from a DataTable here:
https://stackoverflow.com/questions/1348712/creating-a-sql-server-table-from-a-c-sharp-datatable

Check issue #348 for two examples of generating JSON from Excel without knowing the column names.

Using a search engine you can find more examples how to convert from IDataReader or DataSet instances into JSON or DB tables.
