### ISSUE TITLE
how to get the header /columns from a stream file

### ISSUE THREAD

**Issue by weedkiller** [ExcelDataReader/ExcelDataReader#379]
Hi, @andersnm I was able to make progress [from this help](https://github.com/ExcelDataReader/ExcelDataReader/issues/377), can you tell me how to get **a list of column names and types** from the stream read file. using this code as my base https://github.com/ExcelDataReader/ExcelDataReader/issues/377

I looked at the `HeaderFooter`, but its returning on string object? I want to get the list of all the column names on the first sheet.

**Comment by andersnm** [comment]
Hi,

The simplest way is to iterate over DataTable.Columns, and check the .Name and .ColumnType properties of the DataColumns.

Keep in mind Excel files don't really have column names and types. All there is is a grid of cells where the header could be anywhere and each cell could have a different type.

The AsDataSet() helper tries to determine the ColumnType by checking the type of all values per column. Although, if the column contains f.ex mixed strings and numbers, it would return a null ColumnType.

**Comment by weedkiller** [comment]
Does that mean, after the reader parses, if I read the first row I will have the col names (assuming they are in the first row) 

```
var i = rowDepth;
var conf = new ExcelDataSetConfiguration
{
    UseColumnDataType = true,
    ConfigureDataTable = _ => new ExcelDataTableConfiguration
    {
        FilterRow = rowReader => fromRow <= ++i - 1,
        FilterColumn = (rowReader, colIndex) => fromCol <= colIndex,
        UseHeaderRow = true
    }
};
```

Is there a call to get the header names here?

**Comment by andersnm** [comment]
Here is one way to iterate the columns in a DataTable:

```c#
var ds = reader.AsDataSet(conf);
var dt = ds.Tables[0];
foreach (var column in dt.Columns) {
	var columnName = column.ColumnName;
	var columnType = column.DataType;
}
```

(based loosely on the docs for [DataColumn](https://docs.microsoft.com/en-us/dotnet/api/system.data.datacolumn?view=netframework-4.7.2) )

**Comment by weedkiller** [comment]
yes, I got the code but it did not work for some reason.
