### ISSUE TITLE
converting 2.0 to 3.0 code

### ISSUE THREAD

**Issue by jlfreire** [ExcelDataReader/ExcelDataReader#380]
Hi,

I'm converting code from 2.0 to 3.0.
The code that I had the AsDataSet allowed a parameter "bool convertOADateTime"

(convertOADateTime - if set to true try auto convert OA date time format)

the usage would be in the following code.
                excelReader = ExcelReaderFactory.CreateBinaryReader(stream);
                ds_aux = excelReader.AsDataSet(true);

Can you please advise what would be equivelant in version 3.0 of setting the convertOADateTime to true ?

thanks,

**Comment by andersnm** [comment]
Hi,

Just remove it. The default (and only) behavior is equivalent to setting convertOADateTime to true.
