### ISSUE TITLE
AsDataSet Progress Indicator

### ISSUE THREAD

**Issue by PureDevelopers** [ExcelDataReader/ExcelDataReader#384]
Any chance some kind of progress indicator will be added to the AsDataSet method?
I am working with large files, and would love to show a progress indicator while the file is being converted to a dataset.
In my case, I am dealing with a single worksheet, so the dataset will contain only a single table.
It would be nice to get some info during the processing, like total number of rows and total number of rows processed.

BTW, this is a great extension. It is the fastest way I have found to read large files.

**Comment by andersnm** [comment]
Hi,

You could use the FilterRow callback, something like this:

```c#
var result = reader.AsDataSet(new ExcelDataSetConfiguration() {
    ConfigureDataTable = (tableReader) => new ExcelDataTableConfiguration() {
        FilterRow = (rowReader) => {
            var progress = rowReader.Depth / rowReader.RowCount;
            // progress is in the range 0..1
            return true;
        }
    }
});
```

**Comment by PureDevelopers** [comment]
Thanks  for the code snippet. That got me most of the way, but progress was always zero, so I did the following:

`            return reader.AsDataSet(new ExcelDataSetConfiguration
            {
                ConfigureDataTable = tableReader => new ExcelDataTableConfiguration
                {
                    UseHeaderRow = useHeaderRow,
                    FilterRow = rowReader => {
                        var progress = (decimal)rowReader.Depth * 100 / rowReader.RowCount;

                        return true;
                    }
                }
            });
`

**Comment by wizardgsz** [comment]
Something like this...

**IExcelDataReader** interface

```
	public interface IExcelDataReader : IDataReader
	{
...
		/// <summary>
		/// Called to update the progress while writing data: fired sheet by sheet, row by row.
		/// </summary>
		event UpdateProgressDelegate UpdateProgress;
	}
```

```
    /// <summary>
    /// Delegate to generate UpdateProgress event.
    /// </summary>
    /// <param name="iWorkTotal">An application-defined value that specifies the value iWorkSoFar will have when the operation is complete.</param>
    /// <param name="iWorkSoFar">An application-defined value that indicates the proportion of the operation that has been completed.</param>
    public delegate void UpdateProgressDelegate(int iWorkTotal, int iWorkSoFar);
```


`ExcelOpenXmlReader `xlsx reader

```
		/// <summary>
		/// Called to update the progress while writing data, sheet by sheet, row by row.
		/// </summary>
		public event UpdateProgressDelegate UpdateProgress;

		private int m_iWorkTotal = 0;
		private int m_iWorkSoFar = 0;

```
```
		private bool ReadSheetRow(XlsxWorksheet sheet)
		{
...
				// Fire UpdateProgress event
				if (UpdateProgress != null)
				{
					m_iWorkSoFar++;
					UpdateProgress((int)m_iWorkTotal, (int)m_iWorkSoFar);
				}

```

```
		public System.Data.DataSet AsDataSet(bool convertOADateTime)
		{
...
			if (UpdateProgress != null)
			{
				// Count total number of rows
				m_iWorkTotal = m_iWorkSoFar = 0;
				for (int index = 0; index < ResultsCount; index++)
				{
					ReadSheetGlobals(_workbook.Sheets[index]);
					if (_workbook.Sheets[index].Dimension == null) continue;
					m_iWorkTotal += _workbook.Sheets[index].Dimension.LastRow - _workbook.Sheets[index].Dimension.FirstRow + 1;
				}
			}
...
		}
```


**ExcelBinaryReader** binary reader

```
		/// <summary>
		/// Called to update the progress while writing data, sheet by sheet, row by row.
		/// </summary>
		public event UpdateProgressDelegate UpdateProgress;

		private uint m_iWorkTotal = 0;
		private uint m_iWorkSoFar = 0;

```

```
		private bool readWorkSheetRow()
		{
...
			// Fire UpdateProgress event
			if (UpdateProgress != null)
			{
				m_iWorkSoFar++;
				UpdateProgress((int)m_iWorkTotal, (int)m_iWorkSoFar);
			}

			return m_depth < m_maxRow;
		}

```

```
		public DataSet AsDataSet(bool convertOADateTime)
		{
...
			if (UpdateProgress != null)
			{
				// Count total number of rows
				m_iWorkTotal = m_iWorkSoFar = 0;
				for (int index = 0; index < ResultsCount; index++)
				{
					XlsBiffIndex idx;
					XlsBiffRow row;
					readWorkSheetGlobals(m_sheets[index], out idx, out row);
					m_iWorkTotal += m_sheets[index].Dimensions.LastRow - m_sheets[index].Dimensions.FirstRow + 1;
				}
			}
...
		}

```


In your "Main" you can handle % progress:

```
        static void UpdateProgress(int iWorkTotal, int iWorkSoFar)
        {
            int percentageNew = (int)Math.Ceiling((decimal)iWorkSoFar / (decimal)iWorkTotal * (decimal)100);
...
        }

```

**Comment by Seabizkit** [comment]
i know this was closed but has this been added? or what was the decision on this...?

**Comment by andersnm** [comment]
@Seabizkit Hi, the code in https://github.com/ExcelDataReader/ExcelDataReader/issues/384#issuecomment-450258865 is the "official" way to find progress with AsDataSet. I don't think we need a specific mechanism for this

**Comment by wizardgsz** [comment]
Committed code snippet do README.md

**Comment by appel1** [comment]
I don't think we should officially recommend people to use Depth to find out what row is being processed since it shouldn't be implemented like it is. Depth is for the level of nesting of the current row. Not sure if there even is a concept in Excel that would map in a good way to that. 

https://docs.microsoft.com/en-us/dotnet/api/system.data.idatareader.depth

**Comment by wizardgsz** [comment]
Well, using my suggested implementation ([here](https://github.com/ExcelDataReader/ExcelDataReader/issues/384#issuecomment-450339081)), I read daily dozens of XLS/XLSX having no problem.

Does Depth prop contain the "boundings" like the old Dimensions?

**Comment by appel1** [comment]
For ExcelDataReader that does not have the concept of nested tables Depth should always be 0. But for legacy reasons it is the current row. See https://github.com/ExcelDataReader/ExcelDataReader/issues/443. 

That's why I don't think we should recommend people using it but instead count rows themselves and/or if it makes sense add a RowIndex property or similar to the IExcelDataReader interface.
