### ISSUE TITLE
Large Numbers are being converted into scientific notation

### ISSUE THREAD

**Issue by Ian1971** [ExcelDataReader/ExcelDataReader#39]
From code plex
"Am I the only one experiencing this? I can't believe that.

I haven't seen any documentation on this issue.
I'm using version 2.1.2.0. Everything else works fine.

If I do Save as from excel the number formats just fine.

When doing excelDataReader.AsDataSet I get a scientific notation number.
This number 100025440003960000 becomes this - 1.00E+17.

This is a complete deal breaker for me.
I like the library because it's fast and easy to use but if I can't resolve this I have to find another library to use.

Any info would be greatly appreciated.

Thanks."

**Comment by pcalkins** [comment]
Actually I think this is Excel's display of the number.  I have a utility that exports the dataset to a CSV file... if you open the CSV in Excel, it'll display with the "...+E" number until I double-click on that cell... but the CSV itself displays the number as it is...   When creating the CSV I just take the value from a datagridview cell and do a .ToString()...

**Comment by olivegarg** [comment]
I am having the same issue. Is there a solution?

**Comment by Ian1971** [comment]
Ah you doing ToString on a double as indicated above?

**Comment by pcalkins** [comment]
For my purposes, I ended up having to use Excel's com to open the data and set all the column's formats to "Text".  (.opentext(...))  If this is what you are looking for I can list the code.... but my problem was only a  display issue in Excel.

**Comment by andersnm** [comment]
This sounds like a formatting/rendering issue. Closing this and defering to #215
