### ISSUE TITLE
AsDataSet with a list of columns

### ISSUE THREAD

**Issue by PureDevelopers** [ExcelDataReader/ExcelDataReader#390]
I am using the ExcelDataReader to read xlsx files that are uploaded by users. Some of the spreadsheets might be quite large.
Is there any way to pass a set of column names into the AsDataSet if you only wanted to return some of the columns in the spreadsheet.

**Comment by andersnm** [comment]
Hi,

You can use the FilterColumn configuration for this.  Check this stackoverflow (2nd answer):
https://stackoverflow.com/a/51839007

```c#
FilterColumn = (rowReader, colIndex) => 
    rowReader[colIndex].ToString() != "string"
```

or

```c#
FilterColumn = (rowReader, colIndex) => 
    !rowReader[colIndex].ToString().Contains("string")
```
