### ISSUE TITLE
Quick way to just get header row

### ISSUE THREAD

**Issue by PureDevelopers** [ExcelDataReader/ExcelDataReader#391]
What is the best way to grab just the header row data?

**Comment by andersnm** [comment]
Hi,

Something like this should work:

```c#
var headers = new List<string>();
using (var reader = ExcelReaderFactory.CreateReader(stream)) {
	if (reader.Read()) {
		for (var i = 0; i < reader.FieldCount; i++) {
			headers.Add(Convert.ToString(reader[i]));
		}
	}
}
```

**Comment by PureDevelopers** [comment]
This works great, but I would also like to get the cell location. (A,B,C, etc...) Is that information provided, or is it just the column index?

**Comment by andersnm** [comment]
> cell location. (A,B,C, etc...) Is that information provided, or is it just the column index?

Yes, that's right. Column index 0 → A, 1 → B, 2 → C etc.

**Comment by PureDevelopers** [comment]
I was implying that I wanted the values A, B, etc... but I didn't see how to get them. Is it possible to get the A, B?? If so, how do I get to it?

`headers.Add(Convert.ToString(reader[i]));`

**Comment by andersnm** [comment]
Ah gotcha. ExcelDataReader does not expose a built-in method to convert from numeric column indices to column references with letters. 

But something like this should do it:
https://stackoverflow.com/a/182924

(please note the comments on SO, `GetExcelColumnName` expects a 1-based index, whereas the counter `i` in my first snippet is 0-based, so you may want to +1 somewhere)

```c#
private string GetExcelColumnName(int columnNumber)
{
    int dividend = columnNumber;
    string columnName = String.Empty;
    int modulo;

    while (dividend > 0)
    {
        modulo = (dividend - 1) % 26;
        columnName = Convert.ToChar(65 + modulo).ToString() + columnName;
        dividend = (int)((dividend - modulo) / 26);
    } 

    return columnName;
}
```
