### ISSUE TITLE
Integrated docker

### ISSUE THREAD

**Issue by XuKer** [ExcelDataReader/ExcelDataReader#399]
Can it integrate docker?

**Comment by andersnm** [comment]
Hi,

What use case are you trying to solve?

There is nothing in ExcelDataReader that specifically relates to docker integration, and I don't think it needs to? Afaik its possible to reference ExcelDataReader in a project and deploy to a .net (core)-based docker image

https://docs.docker.com/engine/examples/dotnetcore/
https://docs.microsoft.com/en-us/dotnet/core/docker/intro-net-docker
