### ISSUE TITLE
Poor performance when reading non indexed XLS file

### ISSUE THREAD

**Issue by Ian1971** [ExcelDataReader/ExcelDataReader#4]
from codeplex issue https://exceldatareader.codeplex.com/workitem/11827

"This is based on source code downloaded on 27th May 2013. I had a file with +100000 records in it and this file doesn't have index. So it took ~ 3 hours to complete reading that file. I debugged source code and found out that ExcelBinaryReader.moveToNextRecordNoIndex method skips all 100000 records (with ID = ROW) each time it reads 1 record! So perfomance degrades even worse when file size become bigger. According to my file's structure first come all blocks with ID = ROW and then all blocks with ID related to cell. I don't know whether this is correct structure for all files which do not have index. But I modified code and skipped all rows on sheet initialization and then just reading cells it took 40 seconds to complete large file."

[NonIndexedXlsReadPatch.patch | uploaded via ZenHub](https://www.zenhub.io/files/53e09ca67511cda6220048f3)

**Comment by appel1** [comment]
This should be fixed.

**Comment by andersnm** [comment]
@appel1 I assume you mean that in the sense "this has been fixed already", as opposed to "somebody should fix this" :) Don't think the code currently behaves as originally described.
