### ISSUE TITLE
Async & await

### ISSUE THREAD

**Issue by jwillmer** [ExcelDataReader/ExcelDataReader#402]
I'm parsing some long files, is there an option to make the operations async so that I don't block my thread?

**Comment by andersnm** [comment]
Hi,

ExcelDataReader does not support async/await directly, but in a UI app, I think you can do something like `await Task.Run(() => CreateReaderAndParseExcelFile())`.

**Comment by jwillmer** [comment]
Yes, thx. this is what I did already 👍

**Comment by johnhamm** [comment]
Any plans to make a true async version that doesn't block current thread when using I/O operations?

**Comment by andersnm** [comment]
@johnhamm There aren't any plans to tackle this at the moment.

I think the main issues are lack of async support in System.IO.Compression (https://github.com/dotnet/runtime/issues/1541) and whether to drop support for the .NET 2.0 target (which does not have async). Besides those I can't think of any other blockers.
