### ISSUE TITLE
Not able to read xlsx file generated by ssrs

### ISSUE THREAD

**Issue by nhc2005** [ExcelDataReader/ExcelDataReader#404]
Hi,
I tried to use ExcelDataReader to read file from SQL Server Reporting Services generated xlsx (SSRS version 2012).  However the reader return zero column and row.
I subsequently opened the file with Excel and then resave it, ExcelDataReader can read it.

May I know what is the problem?

Attached is the xlsx generated by ssrs.
[sample.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/3097469/sample.xlsx)

**Comment by andersnm** [comment]
Hi,

This is the same as #401. The fix in the repo, but has not been released yet. Downgrading to 3.4.2 should help you to progress.

**Comment by nhc2005** [comment]
Hi, yes it works now. Thanks

**Comment by andersnm** [comment]
The fix was just released in version 3.6.0
