### ISSUE TITLE
1 is not a supported code page.

### ISSUE THREAD

**Issue by attiqeurrehman** [ExcelDataReader/ExcelDataReader#405]
Hi,

I am trying to read an xlsx worksheet and I am getting the following error when reading the workbook: 

> System.ArgumentException
>   HResult=0x80070057
>   Message=1 is not a supported code page.
> Parameter name: codepage
>   Source=mscorlib
>   StackTrace:
>    at System.Text.Encoding.GetEncoding(Int32 codepage)
>    at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
>    at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(Stream stream)
>    at ExcelDataReader.Core.ZipArchive..ctor(Stream stream)
>    at ExcelDataReader.Core.ZipWorker..ctor(Stream fileStream)
>    at ExcelDataReader.ExcelOpenXmlReader..ctor(Stream stream)
>    at ExcelDataReader.ExcelReaderFactory.CreateReader(Stream fileStream, ExcelReaderConfiguration configuration)

I believe it could be related to [this](https://github.com/icsharpcode/SharpZipLib/issues/195). Any ideas about how to resolve this?

**Comment by andersnm** [comment]
Hi,

According to https://stackoverflow.com/questions/46950386/sharpziplib-1-is-not-a-supported-code-page, you can add the following code somewhere before calling ExcelDataReader:

```cs
ICSharpCode.SharpZipLib.Zip.ZipConstants.DefaultCodePage = 850;
```

We should probably add it to ExcelDataReader too, but needs repro and more investigation.

This only happens with the net20 version of ExcelDataReader, and I guess only on machines with specific language settings.

Another fix is to update your project to at least .NET 4.5 or .NET Core, and/or make sure you are using one of the net45, netstandard1.1 or netstandard2.0 versions of ExcelDataReader, which does not use SharpZipLib.

**Comment by attiqeurrehman** [comment]
Thanks for the prompt reply. I will see if we can move to the .NET Core.

**Comment by attiqeurrehman** [comment]
It might sound weird but once I change my pacakge.json to Package Reference, I no longer got the issue. Thanks for the quick reply.
