### ISSUE TITLE
Returns no Rows for <AppVersion>12.0000</AppVersion> XLSX version

### ISSUE THREAD

**Issue by epicsoft** [ExcelDataReader/ExcelDataReader#406]
Broken in Version 3.5.0 (worked fine in 3.4.2)

**Comment by epicsoft** [comment]
Broken in Version 3.5.0 (worked fine in 3.4.2)

**Comment by andersnm** [comment]
Hi and thanks for the report. The fix was just released in version 3.6.0

**Comment by epicsoft** [comment]
Thank you!
