### ISSUE TITLE
InvalidCastException when use the AsDataSet extension method

### ISSUE THREAD

**Issue by attolee** [ExcelDataReader/ExcelDataReader#409]
The ExcelDataReader.DataSet.dll in `ExcelDataReader.DataSet3.6.0\lib\net20` is download by nuget, when processing a specific excel in .net 3.5 context, `reader.AsDataSet()` throw a InvalidCastException.  Call stack as follow,

```
DoubleDataContainer.DoCopyValue()
DataContainer.CopyValue()
RecordCache.CopyRecord()
```

The excel is a bit huge, I have no clue which cell do bed, so I try source files, after deleting all auto-properties with initializer statements, which are illegal in c# 4, the AsDataSet method is fine.

**Comment by appel1** [comment]
None of those classes are in ExcelDataReader. Do you have a more complete stack trace? 

Afaik, auto-properties with initializer statements are just syntactic sugar introduced in C# 6.0 which the compiler turns into a regular property with backing field that is initialized in a regular ctor. So it should work just fine.

**Comment by silkfire** [comment]
@AttoLee Could you upload a sample of the Excel file somewhere?

**Comment by andersnm** [comment]
Hi, FWIW, there are similar reports in #80, #73 and #30, but there was not sufficient info to diagnose it properly. Earlier reports indicate there is/was an issue with mixed datatypes in Mono's DataSet implementation, but this has not been verified. 

@AttoLee Any additional info would be helpful, f.ex can you share the spreadsheet here? Are you using Mono?

**Comment by AttoLee** [comment]
@andersnm It is Mono, the code run in Unity Editor 5.6.6, there is no more call stack and [the spreadsheet here](https://drive.google.com/open?id=1tBXkxy4R5_QcQS43mFVnrE6BzNG_2gh0). I step into the `AsDataSet()`, the decompiled code as follows,

```
    public static DataSet AsDataSet(
      this IExcelDataReader self,
      ExcelDataSetConfiguration configuration = null)
    {
      if (configuration == null)
        configuration = new ExcelDataSetConfiguration();
      self.Reset();
      int num = -1;
      DataSet dataset = new DataSet();
      do
      {
        ++num;
        if (configuration.FilterSheet == null || configuration.FilterSheet(self, num))
        {
          ExcelDataTableConfiguration configuration1 = (configuration.ConfigureDataTable != null ? configuration.ConfigureDataTable(self) : (ExcelDataTableConfiguration) null) ?? new ExcelDataTableConfiguration();
          DataTable table = ExcelDataReaderExtensions.AsDataTable(self, configuration1);
          dataset.Tables.Add(table);
        }
      }
      while (self.NextResult());
      dataset.AcceptChanges();
      if (configuration.UseColumnDataType)
        ExcelDataReaderExtensions.FixDataTypes(dataset);
      self.Reset();
      return dataset;
    }
```

the error occurs on the line `if (configuration.FilterSheet == null || configuration.FilterSheet(self, num))`.

**Comment by andersnm** [comment]
Hi,

@AttoLee Thanks for the spreadsheet! Although it loads on regular .NET. It will take some time getting around to diagnose more in depth.

I don't think the exception occurs exactly on the line with `FilterSheet` since there is no casting there, but rather I suspect it occurs inside the `FixDataTypes` method.

At the moment I have two ideas to progress your work, either:
- Set `UseColumnDataType` to false in the configuration object passed to the reader factory, or
- Do not use AsDataSet(), but instead use the reader interface directly (.Read(), .GetValue(), .FieldCount etc)

**Comment by AttoLee** [comment]
@andersnm I have a workaround, instead of `ExcelDataReader.DataSet.dll`, use the source files by deleting all auto-properties with initializer statements.

**Comment by andersnm** [comment]
Just for the record, if you deleted the initializers, I guess that includes this one:
https://github.com/ExcelDataReader/ExcelDataReader/blob/e5b7d41b580603c866b9097496139080c0bba105/src/ExcelDataReader.DataSet/ExcelDataSetConfiguration.cs#L13

That changes the default for `UseColumnDataType` to false, which bypasses the code that triggers the presumed bug with mixed datatypes in Mono's DataSet implementation, which in turn explains why it worked for you :-)
