### ISSUE TITLE
Converting Huge Integer/BigInt to Scientific Notation

### ISSUE THREAD

**Issue by 3e4rt5** [ExcelDataReader/ExcelDataReader#412]
[tokens.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/3184579/tokens.xlsx)

Code Used  - 
`
FileStream stream = File.Open(ExcelfilePath, FileMode.Open, FileAccess.Read);
excelReader = ExcelReaderFactory.CreateOpenXmlReader(stream);

var conf = new ExcelDataSetConfiguration
                    {
                        ConfigureDataTable = _ => new ExcelDataTableConfiguration
                        {
                            UseHeaderRow = true
                        }
                    };
DataSet result = excelReader.AsDataSet(conf);`

![example2](https://user-images.githubusercontent.com/12073928/57812305-875a9f00-7721-11e9-93df-ed3b5104a3f3.png)
![example1](https://user-images.githubusercontent.com/12073928/57812306-87f33580-7721-11e9-9441-2b9424c47724.png)

Attached is the excel file used as the Source and the code to read this excel file. It seems that if a number's length is greater than 15 digits it converts the number to a Scientific Notation, else it retains the Number (Please refer to screenshots). Any idea to retain large numbers as Numbers instead of it being explicitly being converted to Scientific Notations?

Thank You.

**Comment by andersnm** [comment]
Hi,

I guess that is just a side effect how the double is displayed in the debugger. This stackoverflow has some detail how it works (does not seem like you can change it):
https://stackoverflow.com/questions/10251879/how-does-visual-studio-display-a-system-double-during-debugging

You can control how numeric values are displayed in your app, f.ex with ToString("F"):
https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings

**Comment by 3e4rt5** [comment]
@andersnm Thank you for the response. I guess I can use ToString("F" or "D"), but this seems to happen for Integers with length > 15 only. All other numbers are displayed fine. I agree that the debugger displays it in a certain way, but the library reads anything with Numbers as System.Double. Any idea as to why it's doing that instead of reading it as System.Int64? I am guessing that the library is reading and/or converting it to Double explicitly and storing it as such as well (Again, only for Numbers > 15 digits)

**Comment by andersnm** [comment]
Hi,

The reason you only get doubles from ExcelDataReader's XLSX parser is basically this code:
https://github.com/ExcelDataReader/ExcelDataReader/blob/e5b7d41b580603c866b9097496139080c0bba105/src/ExcelDataReader/Core/OpenXmlFormat/XlsxWorksheet.cs#L582

Values that are not string, boolean, date or error are always parsed into a double, as this is presumably what Excel uses internally. There is no special handling for >15 digits.

It may be worth investigating if there are type hints for integers in the XLSX XML, and if so, implement those. I know at least the XLS format supports 16-bit integers.
