### ISSUE TITLE
How to read column names from the Excel worksheet's/CSV's file header/first row?

### ISSUE THREAD

**Issue by alekdavis** [ExcelDataReader/ExcelDataReader#414]
Given that the data can come from either an Excel worksheet or a tab- (or whatever-) delimited text file and the header row/first line contains the names of the columns, is there a way to get the column names? Not the cell indexes, like A1, B2, etc., but the names of the columns. I guess I can read the first line and have special code to skip it when processing data, but I'm wondering if there is a more elegant way to do this. Thanks.

**Comment by andersnm** [comment]
Hi,

If you used AsDataSet, then the column names are in [DataColumn.ColumnName](https://docs.microsoft.com/en-us/dotnet/api/system.data.datacolumn.columnname?view=netframework-4.8)

If using the reader APIs (Read(), GetValue() etc), then you'd have to extract the column names from the first row manually

**Comment by alekdavis** [comment]
Great! Thank you!!!
