### ISSUE TITLE
Error on build server with ExcelReader.DataSet.pdb

### ISSUE THREAD

**Issue by ADPangburn** [ExcelDataReader/ExcelDataReader#417]
I am trying to use your tool to create a test suite and we encountered an error on our build server - 

"Indexed source information could not be retrieved from \ExcelDataReader.DataSet.pdb. Error: Symbol indexes could not be retrieved. "

After some internal discussion we think it has to do with the DebugType setting since we use an older TFS server(TFS 2012). 

Version Information:
ExcelDataReader v3.6.0
ExcelDataReader.DataSet v3.6.0

I believe newtonsoft.Json had a similar issue and was able to fix this. Is there anything that can be done to resolve this on our build server?

**Comment by UnThwarted** [comment]
Hi, I have this very same issue - did you find a solution to it in the end? ; its all hunky dory on my PC, but I must be missing a step to get the pdb included somehow either by reference or wix component maybe?  I'm also using ancient TFS 2012

**Comment by wizardgsz** [comment]
> Indexed source information could not be retrieved

Did you test these solutions?

https://github.com/JoshClose/CsvHelper/issues/535
https://github.com/fluentassertions/fluentassertions/issues/767

**Comment by UnThwarted** [comment]
Hi, I see, thanks for those links (especially on a Saturday) very much appreciated.
