### ISSUE TITLE
.Net 2.0 Version : ExcelBinaryReader is not adding first row to dataset table even if _isFirstRowAsColumnNames==false

### ISSUE THREAD

**Issue by alexander121** [ExcelDataReader/ExcelDataReader#42]
Hello,
just a small bug.

In the .NET 2.0 version even if _isFirstRowAsColumnNames==false in the method readWholeWorkSheetNoIndex the first row is not added to the table of the dataset.

The line 

if (!justAddedColumns && m_depth > 0 && !(_isFirstRowAsColumnNames && m_maxRow == 1))

should become

if (!(justAddedColumns && _isFirstRowAsColumnNames) && m_depth > 0 && !(_isFirstRowAsColumnNames && m_maxRow == 1))

**Comment by appel1** [comment]
I think the issue is that initializeSheetRead reads to the first row, and then moveToNextRecordNoIndex starts by reading until the next row skipping the first one.

**Comment by andersnm** [comment]
Closing because inactivity, and there's been so many changes to the code in question, chances are this was fixed.
