### ISSUE TITLE
Unsupported encoding

### ISSUE THREAD

**Issue by Zumbalamambo** [ExcelDataReader/ExcelDataReader#422]
I'm using the following code to open the excel file to read it.

```
excelReader = ExcelReaderFactory.CreateReader(stream, new ExcelReaderConfiguration()
            {
                FallbackEncoding = Encoding.UTF8,

                LeaveOpen = false,

                AnalyzeInitialCsvRows = 0,
            });

```
I get the following error,

> Encoding 1252 data could not be found. Make sure you have correct international codeset assembly installed and enabled.

Is there any fix for the same?

**Comment by Sugnick** [comment]
Even I'm facing the same issue when I use excel file in netcore xunit tests

**Comment by appel1** [comment]
Probably this: https://github.com/ExcelDataReader/ExcelDataReader/blob/develop/README.md#important-note-on-net-core

**Comment by Sugnick** [comment]
Yes this resolved the issue for me System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);

**Comment by Zumbalamambo** [comment]
It doesnt help me with the mobile devices

**Comment by andersnm** [comment]
@Zumbalamambo What .NET runtime are you targeting? I assume Xamarin?

Perhaps this is this relevant?
https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/localization/encodings

**Comment by danielwolf1** [comment]
Thanks @andersnm  that helped for Xamarin on Mac - ticked "West".
