### ISSUE TITLE
Question: Why IWorkbook and IWorksheet are not public and expose by reader ?

### ISSUE THREAD

**Issue by reegeek** [ExcelDataReader/ExcelDataReader#423]
Hi,

All is in the title.
Sorry if it is not the right place to ask something.

Regards,

**Comment by andersnm** [comment]
Hi,

Having these interfaces internal allows us to reorganize and change things without regard for backwards compatibility, as we are still figuring things out. They sort of grew out of the refactoring efforts around v3.0, where the goal was to reuse code in the IDataReader implementations and not necessarily introducing a new public, duplicate API.

I can see some benefits of making them public as part of a future refactoring effort, but likely won't happen any time soon

**Comment by reegeek** [comment]
Very clear.
