### ISSUE TITLE
Expose row outline information.

### ISSUE THREAD

**Issue by phillipmunn** [ExcelDataReader/ExcelDataReader#424]
Firstly thanks for this excellent library for parsing Excel files. I have a business usecase where I need to obtain information from grouped rows in Excel using Excel's "Outline" feature. 

Today when the attached file is opened using ExcelDataReader, grouped information from rows is lost and the entire 49 rows of the attached document are read into a DataTable. It is then impossible to identify the grouping or structure of the table once this happens.

I would be happy to sponsor someone to implement such functionality to this library so it would be possible to access the outline information.

Sample file:
[Hourly Sales.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/3468258/Hourly.Sales.zip)

Desired outcome:
It should be possible to fill a DataTable by specifying the desired "Row Outline Level" e.g. "Row outline level 1" which would populate a DataTable as shown in the screenshot below.

[https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-xls/0b683865-eeee-4621-a3d8-b18d20a2afd9](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-xls/0b683865-eeee-4621-a3d8-b18d20a2afd9)

![image](https://user-images.githubusercontent.com/25081499/62476063-3a291f00-b79e-11e9-91f9-5fb91a4b7f21.png)

"Row outline level 2" would propulate the DataTable as shown below with the next level of information populated.

![image](https://user-images.githubusercontent.com/25081499/62476495-07cbf180-b79f-11e9-857e-9ad619b5dc46.png)

**Comment by phillipmunn** [comment]
@andersnm apprechiate you a probably a busy person - but if you or anyone else reading this would be interested in being sponsored to implement such functionality, my knowledge of the inner workings of excel files is non-existant.

**Comment by andersnm** [comment]
Hi,

This seems to be a popular feature request. There's a bit of research on it in issue #284

**Comment by phillipmunn** [comment]
Thanks so much - sorry I didn't see this other issue.
