### ISSUE TITLE
Retrieve cell value via column name via DataSet with ExcelDataReader

### ISSUE THREAD

**Issue by PingPongSet** [ExcelDataReader/ExcelDataReader#426]
I need to read all rows in a *.xlsx file by looping each row and read each cell value within a row, by using column name like below. 

     public  void ReadCSV(byte[] content){
     
     MemoryStream stream = new MemoryStream();
     stream.Write(content, 0, content.Length);
     stream.Position = 0;
    
      IExcelDataReader excelReader = ExcelReaderFactory.CreateReader(stream);
       DataSet result = excelReader.AsDataSet();
    
    //exception occurs below:
    result.Tables[0].Rows[1]["ColA"]

    
    }

However, an error occurs.

    System.ArgumentException
      HResult=0x80070057
      Message=Column 'ColA' does not belong to table Sheet1.
      Source=System.Data.Common
      StackTrace:
       at System.Data.DataRow.GetDataColumn(String columnName)
       at System.Data.DataRow.get_Item(String columnName)

Below works, but the column name is not the name on excel file.

    result.Tables[0].Rows[1]["Column0"]

[![enter image description here][1]][1]

Below results in `not implemented` exception, can anyone confirm this is correct?

      var aIndex = excelReader.GetOrdinal("ColA");  
      var c = (string)excelReader["ColA"];

  [1]: https://i.stack.imgur.com/sAF72.png

**Update**

Please review the code below to see if this is the best way in terms of performance and coding. e.g .          will using column name slow down compared to index?

1.I need to read the first row before header row on first tab using IExcelDataReader.Read(), on Q1 in the code. 

2.The code below uses row filter, column filter, `UseHeaderRow`. Is the code using API correctly.

3 rowReader.GetOrdinal("ColA"); is not supported within `ExcelDataSetConfiguration` and `IExcelDataReader `.  Any plan to implement it?

4 Is it possible to use row filter, column filter when load up the file?
 ```
public static async void ReadXlsx(byte[] content, ILogger log)
        {

            MemoryStream stream = new MemoryStream();
            stream.Write(content, 0, content.Length);
            stream.Position = 0;

            IExcelDataReader excelReader = ExcelReaderFactory.CreateReader(stream);

            //first sheet
            Console.WriteLine(excelReader.Name);

       //Q1: I need to read the first row before header row
            if (excelReader.Read())   
            {
                var a = excelReader.GetString(0);
                Console.WriteLine($"{a}");
            }
                         
            var result = excelReader.AsDataSet(new ExcelDataSetConfiguration()
            {
                // Gets or sets a callback to obtain configuration options for a DataTable. 
                ConfigureDataTable = (tableReader) => new ExcelDataTableConfiguration()
                {
                    // Gets or sets a value indicating whether to use a row from the 
                    // data as column names.
                    UseHeaderRow = true,

                    // Gets or sets a callback to determine which row is the header row. 
                    // Only called when UseHeaderRow = true.
                    ReadHeaderRow = (rowReader) => {

                        switch (rowReader.Name)
                        {
                            case "Sheet1":
                                // F.ex skip the first row and use the 2nd row as column headers:
                                rowReader.Read();
                                break;
                            case "Sheet2": 
                                break;   //first row as header
                            default:
                                break;
                        }
                    },
                    // Gets or sets a callback to determine whether to include the 
                    // current row in the DataTable.
                    FilterRow = (rowReader) => {
                        //var s = rowReader.GetOrdinal("ColA");  //not supported
                        return rowReader.GetValue(0).ToString() == "1";  //get rows with column "1"
                    },

                    // Gets or sets a callback to determine whether to include the specific
                    // column in the DataTable. Called once per column after reading the 
                    // headers.
                    FilterColumn = (rowReader, columnIndex) => {
                        //var s = rowReader.GetOrdinal("ColA");  //not supported
                        if (columnIndex == 0)
                            return true;

                      //  s = rowReader.GetOrdinal("ColB");  //not supported
                        if (columnIndex == 2)
                            return true;

                        return false;
                    }
                }
            });
           //read value using column name on both tabs.
          //Will using column name slow down compared to index?
            log.LogInformation(result.Tables[0].Rows[0]["ColA"].ToString());
            log.LogInformation(result.Tables[1].Rows[0]["ColA"].ToString());           
        }
```

[![enter image description here][2]][2]

  [2]: https://i.stack.imgur.com/3IgDi.png

**Comment by appel1** [comment]
You need to configure AsDataSet to use a row as header, see https://github.com/ExcelDataReader/ExcelDataReader/blob/develop/README.md#asdataset-configuration-options

**Comment by PingPongSet** [comment]
I have a *.xlsx file that has two tabs. First tab has the header on 2nd row, second tab has the header on 1st row. 

Is it possible still to use header?

Please provide code sample if possible.

The code below is using 2nd row as header, how to set 1st row as header for 2nd tab, as mentioned above?

```
var result = reader.AsDataSet(new ExcelDataSetConfiguration()
{
    // Gets or sets a callback to obtain configuration options for a DataTable. 
    ConfigureDataTable = (tableReader) => new ExcelDataTableConfiguration()
    {
        // Gets or sets a value indicating whether to use a row from the 
        // data as column names.
        UseHeaderRow = true,

        // Gets or sets a callback to determine which row is the header row. 
        // Only called when UseHeaderRow = true.
        ReadHeaderRow = (rowReader) => {
            // F.ex skip the first row and use the 2nd row as column headers:
            rowReader.Read();
        },
    }
});
```

Thanks in advance.

**Comment by appel1** [comment]
You can use the IExcelDataReader.Name property in the ReadHeaderRow delegate to determine how which sheet is being read so you know many rows to skip.

**Comment by PingPongSet** [comment]
Thx for the tips.

Please see my update on OP.

Please advise on the code.

**Comment by appel1** [comment]
Closing old issue.
