### ISSUE TITLE
Can't read the Column name with 'dot'

### ISSUE THREAD

**Issue by redcican** [ExcelDataReader/ExcelDataReader#427]
I am using ExcelDataReader for a WPF project. When I import file (.xlsx, .csv) that column name with `.`, It didn't show any data. Is this a bug?

e.g. the column `filter.`, it doesn't show any data. I have tested many other files, they are the same.

![Anmerkung 2019-09-03 083521](https://user-images.githubusercontent.com/10456402/64149312-ddb13200-ce25-11e9-986f-f345c9b782d7.png)

**Comment by andersnm** [comment]
Hi,

Dots in column name works for me:

![image](https://user-images.githubusercontent.com/16575282/64154188-941a1480-ce30-11e9-8d2d-962e0622975d.png)

Which version of ExcelDataReader are you using? Can you share a file having this problem?

**Comment by redcican** [comment]
@andersnm I am using the latest version v3.2.0.

The main method looks like this: 

`private async void PublishLoadExcelFile()
        {
            ExcelView = new ExcelViewModel(_eventAggregator);
            await Task.Run(() =>
            {
                var extension = Path.GetExtension(_excelFilePath)?.ToLower();
                using (var stream = new FileStream(_excelFilePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
                {
                    IExcelDataReader reader = null;
                    if (extension == ".xls") // file is old excel file
                    {
                        reader = ExcelReaderFactory.CreateBinaryReader(stream);
                    }
                    else if (extension == ".xlsx")// file is old excel file (2007 onwards)
                    {
                        reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                    }
                    else if (extension == ".csv") // file is old comma separated value
                    {
                        reader = ExcelReaderFactory.CreateCsvReader(stream);
                    }

                    // file is not acceptale
                    if (reader == null)
                    {
                        return;
                    }


                    using (reader)
                    {
                        _ds = reader.AsDataSet(new ExcelDataSetConfiguration()
                        {
                            UseColumnDataType = false,
                            ConfigureDataTable = (tableReader) => new ExcelDataTableConfiguration()
                            {
                                UseHeaderRow = true
                            }
                        });

                    }
                }
                ExcelContent = _ds.Tables[0].DefaultView;
                _eventAggregator.PublishOnBackgroundThread(
                            new DatasetImportMessage()
                            {
                                ImportType = DatasetImportTypes.Excel,
                                ExcelViewData = ExcelContent
                            });
            });
            
        }`

**Comment by andersnm** [comment]
The code looks OK. Maybe try updating to the latest ExcelDataReader version 3.6.0? There's been quite some fixes since 3.2.0.

If that doesn't help, I think we would need an example file to repro the issue.

**Comment by redcican** [comment]
I just updated to version 3.6.0, It doesn't work. can you please repo the issue?

**Comment by andersnm** [comment]
I was thinking, is this perhaps a WPF databinding issue?

https://stackoverflow.com/questions/13765308/wpf-datagrid-binding-errors-with-dots-in-column-headers
https://stackoverflow.com/questions/8979155/binding-to-fields-containing-a-period-in-datatable-in-c-wpf

Never used WPF, but if you are using WPFs datagrid, then this could be the issue. If so, you need to manipulate the column names before passing the dataset to the datagrid

**Comment by redcican** [comment]
Thank you,

it is a WPF Datagrid Problem. I just solved it.

andersnm <notifications@github.com> 于2019年9月3日周二 上午11:01写道：
