### ISSUE TITLE
disable column sorting default

### ISSUE THREAD

**Issue by AnilSingri** [ExcelDataReader/ExcelDataReader#428]
Hi,

Can someone please let me know if we can disable the column sorting, I am using AsDataSet() I am seeing columns are sorting by default, is there anyway we can disable so

**Comment by andersnm** [comment]
Hi, could you please elaborate a bit more? What do you see, where do you see it, and what are you expecting to see?

The DataSet returned by AsDataSet contains pretty much the raw data in the file without sorting.

**Comment by appel1** [comment]
Needs more info
