### ISSUE TITLE
security issues found by veracode 

### ISSUE THREAD

**Issue by onguarde** [ExcelDataReader/ExcelDataReader#429]
Hi all, found some security issues using veracode static analysis tool.
any chance of fixing these? or are they false positives?

![image](https://user-images.githubusercontent.com/681355/64408370-23d1f400-d0b9-11e9-811b-4ec0e36641f7.png)

![image](https://user-images.githubusercontent.com/681355/64408394-3cdaa500-d0b9-11e9-8755-5f35c7c03dbe.png)

**Comment by andersnm** [comment]
Hi,

Yes, I regard these as false positives. 

1) Hardcoded password: Excel applies the password "VelvetSweatshop" transparently on readonly workbooks. It's a feature, and removing it would cause pain for users.

2) Use of a broken or risky cryptographic algorithm: ExcelDataReader supports these algorithms to allow opening workbooks encrypted with these. For a library meant to read excel files, I think this is acceptable.
