### ISSUE TITLE
Ignore hidden sheets

### ISSUE THREAD

**Issue by tematim** [ExcelDataReader/ExcelDataReader#433]
Hello,

I have a file used like a template for EPPLUS package.
I change some sheets and hide others.

So if a user delete all sheets and add another one, he save the file with only one sheet.

If another program read it with your package, the output dataset is with a lot of tables and not the one which is visible when you open it.

Is it possible to add a filter of sheetnames to ignore not index, or to have a filter on visibility ?

Regards

**Comment by andersnm** [comment]
Hi,

IExcelDataReader has a (undocumented) property `VisibleState` you can use perhaps. F.ex with AsDataSet's `FilterSheet` callback (untested code):

```c#
var ds = reader.AsDataSet(new ExcelDataSetConfiguration()
{
    FilterSheet = (tableReader, sheetIndex) => tableReader.VisibleState == "visible",
});
```

To filter by sheet name, you could modify the FilterSheet callback to check the value of `tableReader.Name`.

If you meant the workbook has multiple visible worksheets, and you want to read the sheet that was currently focused upon saving, then alas no, I believe that is not supported.

**Comment by tematim** [comment]
Hello @andersnm,
The visible filter is the solution for my issue.
Regards
