### ISSUE TITLE
Add target .NET Core 3.0

### ISSUE THREAD

**Issue by rstm-sf** [ExcelDataReader/ExcelDataReader#445]
Hello!

Consider adding target .NET Core 3.0.

_What for?_

Starting from this target `System.Text.Encoding.CodePages` is present in the framework dotnet/corefx#38357

But I didn't find to be added to .NET Standard 2.1 (~~see [here](https://github.com/tarekgh/corefx/blob/d24ddc1a6fa8852f3a427b952bb435b38d5ec24e/pkg/Microsoft.Private.PackageBaseline/packageIndex.json#L4942-L4962)~~ Oops, it's fork)

**Comment by andersnm** [comment]
Hi!

As far as I can tell, it is not necessary to change anything in ExcelDataReader for this. 

It just means, if your app targets netcoreapp3.0 or newer, it is no longer necessary to install the Nuget package for `System.Text.Encoding.CodePages`, since it is now included in the shared frameworks that come with .NET Core 3.0. 

Verified in a simple console app. Still need to call `System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);`, but it works without the addional dependency.

**Comment by rstm-sf** [comment]
Thanks for the answer!

> Still need to call `System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);`

I wish it was spelled out on the library side (as far as I know, this will not affect the library user). I found only the following mention, but this is only for tests

https://github.com/ExcelDataReader/ExcelDataReader/blob/4bbe8e5693beac3d90ca559ea235193bcaa1c8f0/test/ExcelDataReader.Tests/SetUpFixture.cs#L17-L19

**Comment by andersnm** [comment]
Just to be sure, you wish ExcelDataReader would call `RegisterProvider` itself, so that users of the library don't have to? (as opposed to f.ex being documented better)

**Comment by rstm-sf** [comment]
As far as I can tell, in the source code of the library there are places where there is a [request for encodings](https://github.com/ExcelDataReader/ExcelDataReader/search?q=getencoding&unscoped_q=getencoding) that are not supported by Core without additional code.



> being documented better

Why to force the user of the library to write additional is considered the best?

> new ExcelReaderConfiguration()
{
    // Gets or sets the encoding to use when the input XLS lacks a CodePage
    // record, or when the input CSV lacks a BOM and does not parse as UTF8. 
    // __Default: cp1252 (XLS BIFF2-5 and CSV only)__
    FallbackEncoding = Encoding.GetEncoding(1252),

**Comment by rstm-sf** [comment]
> ~But I didn't find to be added to .NET Standard 2.1 (see [here](https://github.com/tarekgh/corefx/blob/d24ddc1a6fa8852f3a427b952bb435b38d5ec24e/pkg/Microsoft.Private.PackageBaseline/packageIndex.json#L4942-L4962))~ Oops, it's fork

I tried turning to CodePagesEncodingProvider in .Net Standart 2.1 and got the following
```
The type or namespace name 'CodePagesEncodingProvider' does not exist in the namespace 'System.Text' (are you missing an assembly reference?)
```

**Comment by andersnm** [comment]
> Why to force the user of the library to write additional is considered the best?

It's not necessarily considered the best, but at the time, it was easier (for me/us) to leave this to users of the library. F.ex it is not clear if it is safe to call `RegisterProvider` multiple times, and there could be differences how encodings are implemented and registered across the various .NET runtimes. E.g Core 2.x, Core 3.x, Full Framework and Xamarin all have differences how they deal with encodings. Some users might even want to provide their own encoding implementations.

I agree it seems pointless having to write additional code to use the library, but as long as it appears to apply only to some runtimes, I feel it is out of our hands. It may be worth revisiting again and investigating further, but that is for the backlog.

**Comment by rstm-sf** [comment]
> F.ex it is not clear if it is safe to call `RegisterProvider` multiple times

Do you know how to call unsupported encoding in another way on the library side? :)
Or do you often get encoding in library code? Because by adding `CodePagesEncodingProvider.Instance` on the library side, the library user will still not be able to get additional encodings.

> there could be differences how encodings are implemented and registered across the various .NET runtimes. E.g Core 2.x, Core 3.x, Full Framework and Xamarin all have differences how they deal with encodings

But, I asked only to consider Core 3.0, because, this is the future :)

**Comment by rstm-sf** [comment]
True, I just started thinking about how it works for Linux.

**Comment by rstm-sf** [comment]
In general, I thought and decided that the more interesting question is whether to use `System.Text.Encoding.CodePages`. This has both pros and cons (we can use [CodePagesEncodingProvider.Instance.GetEncoding](https://docs.microsoft.com/ru-ru/dotnet/api/system.text.codepagesencodingprovider.getencoding)).

**Comment by rstm-sf** [comment]
In general, I thought and decided that the more interesting question is whether to use `System.Text.Encoding.CodePages`. This has both pros and cons (we can use [CodePagesEncodingProvider.Instance.GetEncoding](https://docs.microsoft.com/en-us/dotnet/api/system.text.codepagesencodingprovider.getencoding)).
