### ISSUE TITLE
Register CodePagesEncodingProvider.Instance within constructor of the class using ExcelReader 

### ISSUE THREAD

**Issue by PingPongSet** [ExcelDataReader/ExcelDataReader#447]
Based on the link below, the code below needs to be registered in Startup.cs.
https://github.com/ExcelDataReader/ExcelDataReader

`System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);`

Instead, can the line above be registered within the constructor of the class that references `ExcelReader`?

**Comment by appel1** [comment]
Startup.cs is an example, you can do it where ever makes the most sense for your project as long as it is before you use ExcelDataReader.
