### ISSUE TITLE
'IExcelDataReader' does not contain a definition for 'AsDataSet' 

### ISSUE THREAD

**Issue by jeetu-gis** [ExcelDataReader/ExcelDataReader#449]
'IExcelDataReader' does not contain a definition for 'AsDataSet' and no accessible extension method 'AsDataSet' accepting a first argument of type 'IExcelDataReader' could be found (are you missing a using directive or an assembly reference?)

**Comment by andersnm** [comment]
Hi, you need to reference the `ExcelDataReader.DataSet` nuget package to use `AsDataSet`.

**Comment by jeetu-gis** [comment]
Thanks!!!
