### ISSUE TITLE
Error: Buffer size is less than minimum BIFF record size.

### ISSUE THREAD

**Issue by WesolyPierozek** [ExcelDataReader/ExcelDataReader#45]
Hi, I had error like in topic and i hope i found also solution which works fine for me.

I noticed XlsBiffEOF in ExcelBinaryReader record in some of cases doesn't break loading current workbook.
It was some reasons:
- If XlsBiffEOF is encouted m_depth is not incremented,
- Offset is not in end of the buffer,
- moveToNextRecord has line

``` c#
if (!m_canRead && m_depth > 0) m_canRead = true;
```

which continues execution. My stream from file which i have contains only 0x00 to end of the stream and it cannot be load correctly.

I solved my error by modifing function readWorkSheetRow
If there is XlsBiffEOF then i increment m_depth.

``` c#
if (rec is XlsBiffEOF) { m_depth++;  return false; };
```

Then loading of workbook is stopped correctly. Other solution which i found is to modiy moveToNextRecord by removing m_canRead = false or removing whole condition - i hadn't spotted reason of that line.

**Comment by mafshin** [comment]
I encountered the same exception while reading a XLS file.

**Comment by andersnm** [comment]
Closing because inactivity, and there's been so many changes to the code in question, chances are this was fixed.
