### ISSUE TITLE
Read the string value of a cell

### ISSUE THREAD

**Issue by jamesgurung** [ExcelDataReader/ExcelDataReader#452]
I am trying to get the string value of a cell which might contain text or numeric data, or might be blank. However, when I call `reader.GetString(i)` and the column is blank or contains numeric data, I receive an error, for example:

> Unable to cast object of type 'System.Double' to type 'System.String'

Therefore, to get the value as a string, I am needing to write:

    string val = reader.IsDBNull(i) ? null : (
      reader.GetFieldType(i) == typeof(double)
      ? reader.GetDouble(i).ToString()
      : reader.GetString(i)
    );

Is there a better way of doing this?

**Comment by appel1** [comment]
What is your goal here? 

If you want the string to be like what is shown in Excel then look at https://github.com/ExcelDataReader/ExcelDataReader/blob/develop/README.md#formatting

If you just want the value converted to some string using the current culture them something like `string s = reader.GetValue(i)?.ToString()` should work I think.

**Comment by jamesgurung** [comment]
Thank you.
