### ISSUE TITLE
Please add repository topics

### ISSUE THREAD

**Issue by gojanpaolo** [ExcelDataReader/ExcelDataReader#453]
Hello, I was searching for excel C# libraries using github topics but this library didn't show up because it does not have topics. I think adding topics to this repository will improve discoverability.

https://github.com/topics/excel?l=c%23

**Comment by andersnm** [comment]
Hi,

Good idea. @Ian1971 / @ExcelDataReader  Could you set the "excel" topic on this repo please? (using "Manage topics" link visible to owners on main page) Any others? Maybe "csharp", "parser", and "exceldatareader" topics too :)

**Comment by appel1** [comment]
Added a few topics.
