### ISSUE TITLE
[Feature-Request] - Make ["A"][1] possible

### ISSUE THREAD

**Issue by IT-VBFK** [ExcelDataReader/ExcelDataReader#458]
Hi,

I am using EDR now instead of Microsoft Office Object Library, because it's so much quicker. Thanks for that fist. :)

What I really think about is having some "other" methods or indexer possibilities (e.g. instead of table.Rows[1][1] for example table.Rows[1]["A"] or table.Rows["A"][1]). That would be more self-explaining.
But if I missing something and this sort of methods are already implemented I would be glad to get a hint ;)

Thanks anyways

**Comment by andersnm** [comment]
Hi!

This request is (IMHO) a bit outside the scope of this project. This project is mostly about parsing excel files, and we generally leave data access patterns to the users of the library.

What you describe could be implemented as helper extension methods on the `System.Data.DataSet` and/or `System.Data.DataRowCollection` classes based on https://stackoverflow.com/a/2652855. Alas I don't know any pre-made stuff that does this already

**Comment by IT-VBFK** [comment]
Coming back to this issue: I have done this myself on base of this stackoverflow article you provided.

If you are interested, I am happy to contribute this to this project..
If not.. you can close this issue safley.
