### ISSUE TITLE
Excel Reader Error C#

### ISSUE THREAD

**Issue by BondPOS** [ExcelDataReader/ExcelDataReader#462]
I am getting these two errors. Need Help Please.

ExceptionType | Exception | ExceptionSource | ExceptionStackTrace

System.IndexOutOfRangeException | Index was outside the bounds of   the array. | ExcelUtilities : ReadCsvFile | at   Demo.Service.Core.Excel.ExcelUtilities.ReadCsvFile(String filePath) in   D:\Xamarin\Web\Demo.Service\Demo.Service.Core\Excel\ExcelUtilities.cs:line   37

ExcelDataReader.Exceptions.HeaderException | Invalid file signature. | ExcelUtilities : ReadExcelFile | at   ExcelDataReader.ExcelReaderFactory.CreateBinaryReader(Stream fileStream,   ExcelReaderConfiguration configuration)

--

Here is the code. Can someone please help me. 

using Demo.Service.Core.AppCode;
using ExcelDataReader;
using Demo.Common;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Reflection;

namespace Demo.Service.Core.Excel
{
  public class ExcelUtilities
  {
    public static string ErrorMessage { get; set; }

    public static DataTable ReadCsvFile(string filePath)
    {
      DataTable dataTable = new DataTable();
      try
      {
        using (StreamReader streamReader = new StreamReader(filePath))
        {
          string str1 = streamReader.ReadLine();
          string[] strArray1;
          if (str1 == null)
            strArray1 = (string[]) null;
          else
            strArray1 = str1.Split(',');
          string[] strArray2 = strArray1;
          if (strArray2 != null)
          {
            foreach (string columnName in strArray2)
              dataTable.Columns.Add(columnName);
            while (!streamReader.EndOfStream)
            {
              string str2 = streamReader.ReadLine();
              string[] strArray3;
              if (str2 == null)
                strArray3 = (string[]) null;
              else
                strArray3 = str2.Split(',');
              string[] strArray4 = strArray3;
              DataRow row = dataTable.NewRow();
              for (int index = 0; index < strArray2.Length; ++index)
              {
                if (strArray4 != null)
                  row[index] = (object) strArray4[index];
              }
              dataTable.Rows.Add(row);
            }
          }
        }
      }
      catch (Exception ex)
      {
        ExceptionUtilities.LogException(ex, "ExcelUtilities : ReadCsvFile");
        return new DataTable();
      }
      return dataTable;
    }

    public static DataTable ReadExcelFile(string fileName, string fileExt)
    {
      DataTable dataTable;
      try
      {
        FileStream fileStream = File.Open(fileName, FileMode.Open, FileAccess.Read);
        try
        {
          IExcelDataReader self = (IExcelDataReader) null;
          if (fileExt.ToLower() == "xls")
            self = ExcelReaderFactory.CreateBinaryReader((Stream) fileStream, (ExcelReaderConfiguration) null);
          else if (fileExt.ToLower() == "xlsx")
            self = ExcelReaderFactory.CreateOpenXmlReader((Stream) fileStream, (ExcelReaderConfiguration) null);
          DataSet dataSet = self.AsDataSet(new ExcelDataSetConfiguration()
          {
            ConfigureDataTable = (Func<IExcelDataReader, ExcelDataTableConfiguration>) (_ => new ExcelDataTableConfiguration()
            {
              UseHeaderRow = true
            })
          });
          self?.Close();
          dataTable = dataSet.Tables[0];
          ExcelUtilities.ErrorMessage = string.Empty;
        }
        finally
        {
          fileStream.Close();
          fileStream.Dispose();
        }
      }
      catch (Exception ex)
      {
        ExcelUtilities.ErrorMessage = ex.Message;
        dataTable = new DataTable();
        ExceptionUtilities.LogException(ex, "ExcelUtilities : ReadExcelFile");
      }
      return dataTable;
    }

    public static List<T> ConvertProductDataTable<T>(DataTable dt)
    {
      List<T> objList = new List<T>();
      foreach (DataRow row in (InternalDataCollectionBase) dt.Rows)
      {
        T productItem = ExcelUtilities.GetProductItem<T>(row);
        objList.Add(productItem);
      }
      return objList;
    }

    public static T GetProductItem<T>(DataRow dr)
    {
      Type type = typeof (T);
      T instance = Activator.CreateInstance<T>();
      foreach (DataColumn column in (InternalDataCollectionBase) dr.Table.Columns)
      {
        foreach (PropertyInfo property in type.GetProperties())
        {
          if (property.Name == column.ColumnName)
          {
            if (property.Name == "IngredientQuantity")
              property.SetValue((object) instance, (object) dr[column.ColumnName].ConvertToDecimal(), (object[]) null);
            else if (property.Name == "IsMandatory")
              property.SetValue((object) instance, (object) dr[column.ColumnName].ConvertToBool(), (object[]) null);
            else if (property.Name == "ProductionCost")
              property.SetValue((object) instance, (object) dr[column.ColumnName].ConvertToDecimal(), (object[]) null);
            else if (property.Name == "Markup")
              property.SetValue((object) instance, (object) dr[column.ColumnName].ConvertToDecimal(), (object[]) null);
            else if (property.Name == "RetailPrice")
              property.SetValue((object) instance, (object) dr[column.ColumnName].ConvertToDecimal(), (object[]) null);
            else if (property.Name == "MaximumRetailPrice")
              property.SetValue((object) instance, (object) dr[column.ColumnName].ConvertToDecimal(), (object[]) null);
            else if (property.Name == "ReorderQuantityLevel")
              property.SetValue((object) instance, (object) dr[column.ColumnName].ConvertToDecimal(), (object[]) null);
            else if (property.Name == "ReorderQuantity")
              property.SetValue((object) instance, (object) dr[column.ColumnName].ConvertToDecimal(), (object[]) null);
            else if (property.Name == "MaximumQuantityLevel")
              property.SetValue((object) instance, (object) dr[column.ColumnName].ConvertToDecimal(), (object[]) null);
            else if (property.Name == "ProcurementTimeInMinutes")
              property.SetValue((object) instance, (object) dr[column.ColumnName].ConvertToInt(), (object[]) null);
            else if (property.Name == "ShelfLifeTimeInMinutes")
              property.SetValue((object) instance, (object) dr[column.ColumnName].ConvertToInt(), (object[]) null);
            else if (property.Name == "Quantity")
              property.SetValue((object) instance, (object) dr[column.ColumnName].ConvertToDecimal(), (object[]) null);
            else if (property.Name == "IsEnabledForOrder")
              property.SetValue((object) instance, (object) dr[column.ColumnName].ConvertToBool(), (object[]) null);
            else if (property.Name == "OpeningStock")
              property.SetValue((object) instance, (object) dr[column.ColumnName].ConvertToDecimal(), (object[]) null);
            else if (property.Name == "StoreCreditLimit")
              property.SetValue((object) instance, (object) dr[column.ColumnName].ConvertToDecimal(), (object[]) null);
            else if (property.Name == "StoreCreditLimitDays")
              property.SetValue((object) instance, (object) dr[column.ColumnName].ConvertToInt16(), (object[]) null);
            else
              property.SetValue((object) instance, (object) dr[column.ColumnName].ConvertToString(), (object[]) null);
          }
        }
      }
      return instance;
    }
  }
}

**Comment by andersnm** [comment]
Hi,

>  `System.IndexOutOfRangeException | Index was outside the bounds of the array. | ExcelUtilities : ReadCsvFile | at Demo.Service.Core.Excel.ExcelUtilities.ReadCsvFile(String filePath)`

This is a problem in your CSV parsing code. Consider using a "real" CSV parser library like CsvHelper, or use ExcelDataReader's `CreateCsvReader`

>  `ExcelDataReader.Exceptions.HeaderException | Invalid file signature. | ExcelUtilities : ReadExcelFile | at ExcelDataReader.ExcelReaderFactory.CreateBinaryReader(Stream fileStream, ExcelReaderConfiguration configuration)`

You may have better luck using `ExcelReaderFactory.CreateReader` for both .xls and .xlsx in case the file in question is an .xlsx that has been renamed to .xls.

Otherwise: Are you sure the file is a valid Excel file? Did you try open it in Excel? If it loads in Excel, we need to look at the file: there is near infinite ways to get that error. Can you attach the excel file here? Remember to zip it first to bypass Github blocking it. If the Excel file contains personal information and cannot be shared, can you paste a hex dump of the first 8 bytes here instead?

**Comment by ks1990cn** [comment]
Seems like solved, why its open?

**Comment by chkrishna2001** [comment]
Hi, I am getting same error. I opened the excel and saved in excel with xls format. still same error for xls files
[Mfd Import Template (2).zip](https://github.com/ExcelDataReader/ExcelDataReader/files/8452475/Mfd.Import.Template.2.zip)
