### ISSUE TITLE
linux cent os 8 dependencies was not found

### ISSUE THREAD

**Issue by bingxueyinlian** [ExcelDataReader/ExcelDataReader#465]
An assembly specified in the application dependencies manifest xxx was not found:
    package: 'ExcelDataReader.DataSet', version: '3.6.0'
    path: 'lib/netstandard2.0/ExcelDataReader.DataSet.dll'

**Comment by andersnm** [comment]
Hi!

First of all, I don't think this is a problem with ExcelDataReader, but rather a more general problem related to the .NET Core tooling and the use thereof. The error message has lots of hits in search engines, but no single solution and plenty frustrated developers :(

Are you able to use other libraries as dependencies or does it only happen with ExcelDataReader? 

Some ideas; 
- publish your app as being self contained  (`dotnet publish ... --self-contained true`)
- make sure you specify a runtime specifier (`dotnet publish ... -r linux-x64`)
- delete all build outputs (i.e bin and obj directories) to force a full rebuild of your project
- make sure all projects making up your app reference the same version of ExcelDataReader
- create a minimal repro in a github repository and link it here so we can try and reproduce
