### ISSUE TITLE
Is there a way to distinguish between formula errors and empty cells?

### ISSUE THREAD

**Issue by mgregory22** [ExcelDataReader/ExcelDataReader#466]
I'm reading sheets using method 1, the reader methods.

When a cell contains a formula error, I want to reject the operation and report an error to the user, so they can correct the sheet before importing it.

Formula errors return null for the cell type, but so do empty cells.

How do I tell the difference between the two?

**Comment by andersnm** [comment]
Hi, unfortunately there is currently no way to tell apart empty cells and formula errors.

A related idea came up in https://github.com/ExcelDataReader/ExcelDataReader/issues/329#issuecomment-548267233 but nothing has been done about it so far

**Comment by mgregory22** [comment]
What would happen if formula errors were treated as strings with the value set to the error code, "#DIV/0!" or whatever?  I don't know all the possible formula errors Excel has.  Maybe ExcelDataReader could provide a predicate that reports if the string matches an error code.

I think that would work for me.  No one is going to enter #DIV/0! as a value.

**Comment by andersnm** [comment]
Afaik there are already users who depend on cells with errors being empty, so we can't just change that behavior. But there are no problems adding some new reader method `GetCellError(i)` to determine if a cell has an error.

Please note this will remain in the backlog unless you'd like to have a go at it. Should be relatively easy to add, although should be supported in all of XLS, XLSX, XSLB and with tests for all errors in all formats.

**Comment by mgregory22** [comment]
So you would call GetCellError(i) when GetCellType(i) returns null?  What would GetCellError() return?  A string?

**Comment by andersnm** [comment]
> What would GetCellError() return? A string?

Yes, a string sounds good to me. And can return null if there is no error in the cell. (alternatively an enum, but not sure if that would always work)

**Comment by mgregory22** [comment]
Yeah, of course, the method would return the inner text of the v element.  Well, I don't know about the other formats.  XLS and XSLB formats must contain the same information, huh?

**Comment by mgregory22** [comment]
I could give it a shot.

**Comment by andersnm** [comment]
XLSX and XLSB have common parsing code, and I agree both should do the equivalent of returning the inner text of the v element when the t attribute of the containing c element is "e".

The XLS formula error code is apparently already parsed, but not converted to a string nor exposed publicly:
https://github.com/ExcelDataReader/ExcelDataReader/blob/b0ad266dc76976e8bbe22509cba7a3e7047e6bce/src/ExcelDataReader/Core/BinaryFormat/XlsBiffFormulaCell.cs#L46


A reference for XLS is here: https://www.openoffice.org/sc/excelfileformat.pdf

Relevant XLS sections:
2.5.6 Error Codes
5.50 FORMULA

**Comment by mgregory22** [comment]
Awesome, thank you!  This doesn't sound too hard.
