### ISSUE TITLE
Bad SST error when reading XLS File

### ISSUE THREAD

**Issue by LukeKirbyDG** [ExcelDataReader/ExcelDataReader#467]
Hi,

Just come across an issue when using exceldatareader to convert an xls file provided by a customer to CSV format, and we're getting the message "Bad SST Format", which appears to be related to this issue from a year ago https://github.com/ExcelDataReader/ExcelDataReader/issues/392 

I've asked the customer for some more information on what they're using to save the file. Its set template that gets sent out, filled out by people and then when it's received, convert it to CSV and process it, so I'd assume it's directly related to whatever software the customer is using. 

It's a fairly small file but I can't send it over directly as it has payer address & bank details in but I'm seeing if I can get the customer to re-save the template file without any personal data in. If I re-save the file they sent over using Excel from Office 365, the error goes away so I'd assume it was from 

Any ideas why the character count would be 0 in such a column where the bad SST message is triggered? 
https://github.com/ExcelDataReader/ExcelDataReader/blob/22e24602a7baaa7e95b988a3392ce46dbb6e025a/src/ExcelDataReader/Core/BinaryFormat/XlsSSTReader.cs#L87 

Thanks,
Luke

**Comment by andersnm** [comment]
Hi,

I'd really like to have a look at that file to be sure whats going on. Is it possible to remove any personal information in a hex editor before zipping and uploading the xls here? You could also email me the file, but I'm not giving out my email so you have to poke me f.ex through the "Contact Owners" form on Nuget first and I'll get back to you.

That exception appears to be more of an internal assertion than a real error, as it shouldn't happen under normal circumstances. I guess perhaps it would trigger if there is a mismatch between the BIFF record length and string length in the file.  There's a chance it would work to just remove the code block which throws "Bad SST format". The following code does not appear harmful.

**Comment by TechSavvySam** [comment]
I'm getting the same error on a file I'm trying to read in.  I was able to read it with version 2.1.2.3, but I get the error in 3.6.0.0.

If I load the file in Excel and save it, Excel cleans up whatever is causing the problem and then it can be read.

I can send the file to you, but don't want to post it publicly.

**Comment by andersnm** [comment]
Thanks @TechSavvySam ! Looks like your file specified a wrong number of strings in the SST. Also found some related bugs using hex edited files, so the SST parser got an overhaul in 9383b470f282508c37176d7421bfb69ff7f01d21

**Comment by TechSavvySam** [comment]
Thanks @andersnm -- that fixed my issue.  I figured it was a problem with an imperfection in the XLS file--I've seen this a lot with XLSX files where Excel can "clean up" some issues with the input file that can't be read by 3rd party APIs.  

I hope this fixes it for @LukeKirbyDG too!

**Comment by sarawgeek** [comment]
This issue has been fixed in their Pre-release build - [v3.7.0-develop00310](https://github.com/ExcelDataReader/ExcelDataReader/releases/tag/v3.7.0-develop00310)
Not sure when the stable build will be released.

**Comment by sarawgeek** [comment]
@andersnm , is there any plan to release the new build with this fix?
