### ISSUE TITLE
silverlight 5 vb project problem to install ExcelDataReader 

### ISSUE THREAD

**Issue by reza-attitude** [ExcelDataReader/ExcelDataReader#469]
Could not install package 'ExcelDataReader 3.6.0'. You are trying to install this package into a project that targets 'Silverlight,Version=v5.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author

**Comment by andersnm** [comment]
Hi! Unfortunately Silverlight isn't supported
