### ISSUE TITLE
Continuous loop for: Importing values from excel and assigning them to variables, solving equations and outputing the solution of the equations

### ISSUE THREAD

**Issue by ShreeniketJoshi** [ExcelDataReader/ExcelDataReader#470]
Hello community,
I'm a mechanical engineer, and quite new to github. I'm doing research in Thinfilms. For my project, I have to take my experimental values which are in excel sheet format and use a python code to substitute these values in analytical equations, solve them and output the answer in a new excel column. This code should run on a continuous loop and automatically calculate solution for each input value (present in the column)

I'm a beginner in python and tried searching the web for answers, can someone please give me a hint as to how I can go about this? 
Thanks

**Comment by silkfire** [comment]
This is a C# .NET library, you should probably look for a library compatible with Python instead.

**Comment by ShreeniketJoshi** [comment]
Oh sorry, my bad. Thanks for letting me know
