### ISSUE TITLE
Support parsing a single sheet at a time as a data table

### ISSUE THREAD

**Issue by gandhis1** [ExcelDataReader/ExcelDataReader#471]
So the `AsDataSet()` method of the `IExcelDataReader` is very useful, as it creates a `DataTable` object for each sheet with the appropriate headers. 

However, it only allows a single `ExcelDataSetConfiguration` to be passed in. This configuration object is the primary way to determine (1) which rows should be skipped, (2) which columns should be skipped, (3) what row is the header row.

If you have 3 heterogeneous sheets, which each need a different configuration, you would have to call AsDataSet() multiple times with each configuration. *If you have N sheets, this means redundant work - parsing each sheet N times.* 

1) Is my interpretation above accurate? Is there any way I am not aware of to avoid this redundant work? 

2) If it is, there are several solutions I can think of:
  * Add a new parameter to `ExcelDataTableConfiguration` - e.g. `FilterSheet` or something similar
  * Allow passing in of multiple configurations for each sheet to `AsDataSet()`
  * Pass information to `ReadHeaderRow`/`FilterRow`/`FilterColumn` that allows identifying each sheet, but this seems like it would be very convoluted

**Comment by andersnm** [comment]
Hi,

`ExcelDataSetConfiguration.ConfigureDataTable` is a callback, so you can return different configurations per sheet. A simple, untested example:

```c#
ConfigureDataTable = (tableReader) => {
    if (tableReader.Name == "Sheet1") {
        // Headers on first row in first sheet
        return new ExcelDataTableConfiguration()
        {
            UseHeaderRow  = true,
        };
    } else if (tableReader.Name == "Sheet2") {
        // Headers on second row in second sheet
        return new ExcelDataTableConfiguration()
        {
            UseHeaderRow  = true,
            ReadHeaderRow = (rowReader) => {
                rowReader.Read();
            },
        };
    } else {
        // No headers on the remaining sheets
        return new ExcelDataTableConfiguration()
        {
            UseHeaderRow  = false,
        };
    }
}
```

**Comment by gandhis1** [comment]
Thanks, that was very helpful. One follow-up before I close - what should I return from `ConfigureDataTable` to skip a sheet entirely?

**Comment by andersnm** [comment]
There is another callback `ExcelDataSetConfiguration.FilterSheet` intended for skipping sheets.

**Comment by gandhis1** [comment]
Thanks again, closing.
