### ISSUE TITLE
Read rows with limit

### ISSUE THREAD

**Issue by junsp** [ExcelDataReader/ExcelDataReader#472]
I am looking into how I can speed up the reading time, especially for large data with multiple sheets.

One good solution would be if reading data can be actually limited by user requested number of rows. 

I was trying to find if there is any argument or parameter I can set to achieve it.
Is it possible to stop reading after first 200 rows, for example, instead of reading all rows (sometimes can be very large)

**Comment by andersnm** [comment]
Hi, are you using AsDataSet()? For max performance, please look into the reader APIs.

**Comment by junsp** [comment]
Does the reader API support such as reading only 200 rows out of 100,000 ?  I think closest thing I found was FilterRow in ExcelDataTableConfiguration() but not sure if that improves performance or still going row by row.

**Comment by silkfire** [comment]
Are you going to read all of those 100,000 rows, but 200 at a time? Or always just the first X rows?

**Comment by junsp** [comment]
Looking for an option to read just first 200 rows.

And another good option to have is only reading selected columns.

**Comment by nafis00141** [comment]
@silkfire @junsp 
Did you guys find a way to read all of those 100,000 rows, but 200 at a time? I am searching for a way to do this. Any help will be appreciated

**Comment by andersnm** [comment]
If you use the reader API, you simply `break;` out of the loop after as many rows you need, and no further rows will be read (although internally a couple more rows _may_ be cached, but usually not more than 32). 

At the moment there is no supported/pretty way to break out of AsDataSet prematurely unless you throw an an exception from `FilterRow` or something (but do keep in mind exceptions aren't meant for program flow like this)

**Comment by xmione** [comment]
> If you use the reader API, you simply `break;` out of the loop after as many rows you need, and no further rows will be read (although internally a couple more rows _may_ be cached, but usually not more than 32).
> 
> At the moment there is no supported/pretty way to break out of AsDataSet prematurely unless you throw an an exception from `FilterRow` or something (but do keep in mind exceptions aren't meant for program flow like this)

Hi @andersnm, I tried to do this but sadly I was not able to make it work. Instead I've downloaded the codes and modified the sample TestApp.

Link here: ====> https://drive.google.com/file/d/1hsv7ZlLp14BRNpxuN45mtKIqvefmtkin/view?usp=sharing

![22-41-21](https://user-images.githubusercontent.com/13359515/89796318-142a1d80-db5c-11ea-9540-7c8e375641ed.gif)
