### ISSUE TITLE
AsDataset does not respect number format

### ISSUE THREAD

**Issue by landym** [ExcelDataReader/ExcelDataReader#473]
I have a spreadsheet with a cell value of 130407320826770000.  It is formatted as a number.  If it is formatted as General, it will display scientific notation and lose precision "1.30407E+17".  When exporting the dataset to a file it gets even worse with a value of 1.30E+17.  The AsDataset does not seem to respect the cell formatting causing the dataset to contain bad data.

**Comment by andersnm** [comment]
Hi,

Indeed, AsDataSet ignores the number format, but that doesn't mean it contains bad data. A double is a double. ExcelDataReader returns bitwise identical doubles as Excel uses internally.

If you need to format the output in your program exactly like Excel, you'd have to use the reader APIs (Read(), GetValue(), GetNumberFormat()) and the ExcelNumberFormat library. It works similar to .NET's ToString(), but using Excel's number format syntax instead.
