### ISSUE TITLE
XLSB support not in latest Nuget package

### ISSUE THREAD

**Issue by spetersn** [ExcelDataReader/ExcelDataReader#474]
Hi, thank you so much for recent addition of XLSB support. Would it be possible to release new Nuget package that includes that? It will be much more convenient to use. 
Thank you!

**Comment by gandhis1** [comment]
Seconded - this issue is actually fairly timely for me as I've just come across a few XLSB files that I'd like to process.

**Comment by gandhis1** [comment]
@andersnm @appel1 Any update on this? Would really appreciate it as this would be a highly useful feature for me

**Comment by andersnm** [comment]
This is available in the latest prerelease packages on Nuget:

https://www.nuget.org/packages/ExcelDataReader/3.7.0-develop00306
https://www.nuget.org/packages/ExcelDataReader.DataSet/3.7.0-develop00306

**Comment by gandhis1** [comment]
Thanks! I upgraded and tested it out on some of the typical XLSB files I have. Appears to work no issues.

**Comment by andrericardo** [comment]
> This is available in the latest prerelease packages on Nuget:
> 
> https://www.nuget.org/packages/ExcelDataReader/3.7.0-develop00306 https://www.nuget.org/packages/ExcelDataReader.DataSet/3.7.0-develop00306

Any idea when these could be promoted to release version?

**Comment by appel1** [comment]
No ETA yet, but I've started going through issues and PRs. I'll close this and just leave one 3.7 ETA related issue open, #516.
