### ISSUE TITLE
Return extra worksheet 

### ISSUE THREAD

**Issue by rsk-rajnish** [ExcelDataReader/ExcelDataReader#475]
Hi,
In one of .xlsx file where it contains multiple sheet, It return one extra sheet. This issue is related to one 
.xlsx file. I tried to save it into .xls file but it not resolve the issue.

Kindly guide me what cause the issue.

**Comment by appel1** [comment]
Could you provide the .xlsx file so we can reproduce? Either as an attachment or in private if you don't want it to be public?

**Comment by silkfire** [comment]
The extra sheet could actually be a hidden sheet that you won't see when you open the spreadsheet in Excel but is still loaded by the library. But hard to tell for sure without having access to the source document.
