### ISSUE TITLE
Password protected file is throwing InvalidPassword even it's correct one!

### ISSUE THREAD

**Issue by pajacz** [ExcelDataReader/ExcelDataReader#477]
Dear developer, 

please i've reached dead end by using your lib as it's doesn't support password protected workbooks properly. I have file from customer where Excel open just fine but not your lib. 

Please can you check with the dummy text file attached? 

pass: vw12020
[EDIT: removed]

Thanks!

**Comment by pajacz** [comment]
Have been trying to use NPOI and got this exception: "HSSF does not currently support CryptoAPI encryption". Isn't this the same case?

**Comment by andersnm** [comment]
Hi and thanks for the report!

There appears to be an unhandled edge case in our CryptoAPI implementation. The last sentence in this article mentions this:
https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-offcrypto/12ec1195-af2d-44e6-8c73-003e79e635d5

>  If keyLength is exactly 40 bits, the encryption key MUST be composed of the first 40 bits of Hfinal and 88 bits set to zero, creating a 128-bit key.

This means the following code:

https://github.com/ExcelDataReader/ExcelDataReader/blob/bc7ae9eb84f789b34aaeffe8b1ef730c50d0e452/src/ExcelDataReader/Core/OfficeCrypto/StandardEncryption.cs#L177-L183

... should be changed to:

```c#
                var salt = CryptoHelpers.Combine(secretKey, BitConverter.GetBytes(blockNumber));
                salt = CryptoHelpers.HashBytes(salt, HashAlgorithm);
                Array.Resize(ref salt, (int)KeySize / 8);
                if (KeySize == 40)
                {
                    // If keyLength is exactly 40 bits, the encryption key MUST be composed of the first 40 bits of Hfinal and 88 bits set to zero, creating a 128-bit key.
                    salt = CryptoHelpers.Combine(salt, new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 });
                }

                return salt;
```

Have tested with your file and it works!

**Comment by andersnm** [comment]
@pajacz Apologies, but I edited your comment to remove the download link since it seemed to contain personal information.  Are you able to create a new version of that XLS without the first sheet for use in our unit tests? I don't have a version of Excel to create a repro myself

**Comment by pajacz** [comment]
Thanks! Is is already as part of released nuget version? Thanks once more! And thank you for removing the file, I've forgot to remove one sheet.

**Comment by pajacz** [comment]
> @pajacz Apologies, but I edited your comment to remove the download link since it seemed to contain personal information. Are you able to create a new version of that XLS without the first sheet for use in our unit tests? I don't have a version of Excel to create a repro myself

Sorry for not to reply, I've seen your reactions just today :-/
