### ISSUE TITLE
Can I open a file read-only that is simultaneously open in Excel

### ISSUE THREAD

**Issue by EthicsGradient** [ExcelDataReader/ExcelDataReader#479]
Hi,
I've a excel file which I need to work on in Excel before using my code, and it's a pretty iterative process. It's a pain to have to close the file every  time I want to run it through my code. I think I'm using readonly to open this already;
```
using (var stream = File.Open(filename, FileMode.Open, FileAccess.Read))
                {
                    var extensionPos = filename.LastIndexOf(".");

                    var extension = filename.Substring(extensionPos + 1, filename.Length - (extensionPos + 1));
                    IExcelDataReader excelReader;

                    switch (extension)
                    {
                        case "xls":
                            excelReader = ExcelReaderFactory.CreateBinaryReader(stream);
                            break;
                        case "xlsx":
                            excelReader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                            break;
                        default:
                            throw new Exception(String.Format("Unknown file type {0}", extension));
                    }

```
Is there anyway to achieve this?

**Comment by wizardgsz** [comment]
I think it is Excel to "lock" the file, you could just try to open it in any hex editor or text editor to double check it. 
Cannot you "copy" it to a temporary file before opening it in ExcelDataReader?

**Comment by andersnm** [comment]
Hi,

Try to add `FileShare.Read` as the last parameter to File.Open:

```c#
using (var stream = File.Open(filename, FileMode.Open, FileAccess.Read, FileShare.Read))
```

**Comment by EthicsGradient** [comment]
Hi,
I can't take a copy, as we're using our app to take an Excel file and
produce a xml, so there's a fair bit of back and forth, which makes opening
and closing excel annoying.

I've tried the FileShare.Read option but that line of code still throws an
exception.

Any other ideas?
James

**Comment by EthicsGradient** [comment]
Change the last argument to FileShare.ReadWrite then it works!
