### ISSUE TITLE
not support .net 4.8(not found “System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)

### ISSUE THREAD

**Issue by neozhu** [ExcelDataReader/ExcelDataReader#481]
.net 4.5 use System.IO.Compression, Version=4.0.0.0
.net 4.6 use System.IO.Compression, Version=4.0.0.0
.net 4.8 use System.IO.Compression, Version=4.2.0.0
now laster version System.IO.Compression, Version=4.3

**Comment by appel1** [comment]
I don't understand. ExcelDataReader can be used without issue from a .net 4.8 project. Could you provide steps to reproduce your issue?

**Comment by neozhu** [comment]
.net 4.8 
web.config  default
`<dependentAssembly>
        <assemblyIdentity name="System.IO.Compression" publicKeyToken="b77a5c561934e089" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0" />
  </dependentAssembly>`
modify
`<dependentAssembly>
        <assemblyIdentity name="System.IO.Compression" publicKeyToken="b77a5c561934e089" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="**4.0.0.0**" />
  </dependentAssembly>`
this issue solve
thank you reply

**Comment by appel1** [comment]
The assembly version of System.IO.Compression is 4.0.0.0 in .NET Framework 4.8 which is why it doesn't work when you redirect it to System.IO.Compression 4.2.0.0 that doesn't exist in 4.8.

**Comment by neozhu** [comment]
at C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.IO.Compression.dll
ver 4.2.0
in the project sourcecode reference assembly 4.0 for .net 4.5
in my .net 4.8 project default reference 4.2 , when call "ExcelReaderFactory.CreateReader(stream)" excpetion error

**Comment by appel1** [comment]
The reference assemblies are not used during runtime. 

I just created a new wpf app targetting .NET Framework 4.8 and added a package reference to ExcelDataReader and ran it. Looking at the modules window I can see that the expected System.IO.Compression.dll was loaded from the GAC. 

```
System.IO.Compression.dll	System.IO.Compression.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.IO.Compression\v4.0_4.0.0.0__b77a5c561934e089\System.IO.Compression.dll	Yes	N/A	Symbol loading disabled by Include/Exclude setting.		15	4.8.4084.0 built by: NET48REL1	2019-11-24 10:23	00007FFE73F40000-00007FFE73F77000	[23652] WpfApp5.exe	[1] WpfApp5.exe	
```

Could it be that you are using some other NuGet package that incorrectly changed web.config to redirect to System.IO.Compression.dll 4.2.0.0? That redirection does not get created by default when I try to create a new project of any kind and it is not something ExcelDataReader does either.

**Comment by neozhu** [comment]
create new project  nuget install this package web.config add reference 4.0.0.not issus.
my original project default reference web.config  4.2.0.0,web.config session must be manually modified 4.0.0 to be used normally
Can it be considered compatible with the 4.2.4.0 two versions

**Comment by appel1** [comment]
Since System.IO.Compression.dll with assembly version 4.2.0.0 does not exist during runtime for .NET Framework 4.8 it is not possible.

**Comment by neozhu** [comment]
ok,thanks
