### ISSUE TITLE
AsDataSet() causes the excelDataReader to reset to the first sheet

### ISSUE THREAD

**Issue by RRobbins94** [ExcelDataReader/ExcelDataReader#482]
The issue I'm having has to do when working with xlsx file that contains multiple sheets. 
Whenever AsDataSet is executed, the excelReader will change back to the first sheet.

![image](https://user-images.githubusercontent.com/31695796/91436317-c7368e80-e85f-11ea-8d0a-67597aa397f3.png)

![image](https://user-images.githubusercontent.com/31695796/91436366-e03f3f80-e85f-11ea-8eab-4bc58c89bd5d.png)

This is causing issues when trying to do a loop through the readers results

**Comment by appel1** [comment]
What are you trying to accomplish? AsDataSet reads all tables in the excel file. The idea is that you either use AsDataSet and then work with the DataSet or use the reader interface directly if you want greater control.

**Comment by RRobbins94** [comment]
The problem is that each sheet might follow a different ExcelDataSetConfiguration. For example, the first sheet might have the headers in row 1 while the second sheet might have them in row 5.
So even though I'm using AsDataSet, I'm calling AsDataSet for each sheet and passing the required configuration for that particular sheet.

**Comment by andersnm** [comment]
Hi,

This issue discusses something similar - how to use different configurations per sheet and skipping sheets with AsDataSet https://github.com/ExcelDataReader/ExcelDataReader/issues/471

**Comment by RRobbins94** [comment]
Hi, thanks for the response I'll give that a go
