### ISSUE TITLE
GetCellError() throwing exception when cell is empty

### ISSUE THREAD

**Issue by RRobbins94** [ExcelDataReader/ExcelDataReader#483]
Using ExcelDataReader v3.7.0-develop00310 nugets
Issue here is that when an xlsx cell is empty and has no value, the new GetCellError() method throws an NullReferenceException, instead of returning null.

**Comment by appel1** [comment]
Is this still an issue or has it been fixed? The tests in the PR passes.

**Comment by appel1** [comment]
Missed that a fix was included in the PR. Sorry for the noise.
