### ISSUE TITLE
Feature Request: Option in ExcelDataTableConfiguration to prioritize cell error values over cell value

### ISSUE THREAD

**Issue by RRobbins94** [ExcelDataReader/ExcelDataReader#486]
I would like to make a feature request if possible for release v3.7.0-develop00310, which has the new GetCellError() method.
It would be useful to have a new bool option in the ExcelDataTableConfiguration() that would prioritize RowCells[].Error (if it has one) over the RowCells[].Value.

**Comment by RRobbins94** [comment]
Hello, any chance this can be added to the develop NuGet? @andersnm

**Comment by matthetherington-pa** [comment]
Are there any plans to release this via nuget?
