### ISSUE TITLE
Return Dates in current view vs re format or setting a format

### ISSUE THREAD

**Issue by michaelbrack** [ExcelDataReader/ExcelDataReader#490]
I am attempting to import an excel file into a datatable.  I do not want to change/update any format from the original excel file.  Everything looks to be coming over correctly except for a date field.  In the excel file it looks like this "22-Sep".  What is actually in the cell is this "9/22/2020".  What is imported in using the code below is this "9/22/2020 12:00:00 AM".  The excel data never comes in the same way twice, so i can not just assume what field is the date, or what format its in.  Is there a way to import the data as seen in the excel sheet? For example i want the "22-Sep" format, because that is what is displayed when you open up the excel sheet.  I also tried UseColumnDataType = false and UseColumnDataType = true without any change to either.

DataTable MainData = new DataTable();
            string location = @"C:\MyExcelFile.xlsx";
            using (var stream = File.Open(location, FileMode.Open, FileAccess.Read)) {
                using (IExcelDataReader reader = ExcelReaderFactory.CreateReader(stream)) {
                    var result = reader.AsDataSet(new ExcelDataSetConfiguration() {
                        ConfigureDataTable = (_) => new ExcelDataTableConfiguration() {
                            UseHeaderRow = true
                        }
                    });
                    tableCollection = result.Tables;
                }
            }

            DataTable dt_Temp = tableCollection[0];
            dt_Temp = dt_Temp.AsEnumerable().CopyToDataTable();
            DataTable dtClone = dt_Temp.Clone(); //just copy structure, no data
            for (int i = 0; i < dtClone.Columns.Count; i++) {
                if (dtClone.Columns[i].DataType != typeof(string))
                    dtClone.Columns[i].DataType = typeof(string);
            }

            foreach (DataRow dr in dt_Temp.Rows) {
                dtClone.ImportRow(dr);
            }
            MainData = dtClone.Clone();
            foreach (DataRow row in dtClone.Rows) {
                MainData.ImportRow(row);
            }

            dataGridView1.DataSource = MainData;

**Comment by andersnm** [comment]
Hi, at the moment you cannot do this through AsDataSet(). However in the next version you probably can, have yet to go through and merge the PR in #487.

If you need to resolve immediately you have to drop down to the reader API. And either way refer to the [Formatting](https://github.com/ExcelDataReader/ExcelDataReader#formatting) section in the README for how to manually convert the raw Excel values to what they look like in Excel

**Comment by michaelbrack** [comment]
Is there an estimate when the next version get released?

**Comment by andersnm** [comment]
Alas no.
