### ISSUE TITLE
The maximum allowed size error when calling ReadAllSync

### ISSUE THREAD

**Issue by ZapRiver** [ExcelDataReader/ExcelDataReader#491]
When calling ReadAllAsync I'm getting this error:

"The maximum allowed size is 1048576, but the supplied file is of length 1203571. Parameter fileListEntry"

The file size is 1,176,000 bytes.

What is the file size limit for ExcelDataReader?

Is there any way to load files this size?

**Comment by andersnm** [comment]
Hi,

`ReadAllAsync` is not part of ExcelDataReader, and ExcelDataReader has no explicit file size limit on input files.

Please show your code and the full stacktrace
