### ISSUE TITLE
unable to use exceldata reader connection in SSIS package deployment model

### ISSUE THREAD

**Issue by ayo2kunle** [ExcelDataReader/ExcelDataReader#494]
I am using the dll in a SSIS package code in C#. It runs successfully on my desktop which has Excel installed, but not on a server without excel installed. The error i get when trying to access a password protected excel sheet is 

Error: Access to the path '' is denied. at
System.IO.__Error.WinIOError(Int32 errorCode, String
maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode,
FileAccess access, Int32 rights, Boolean useRights,
FileShare share, Int32 bufferSize, FileOptions options,
SECURITY_ATTRIBUTES secAttrs, String msgPath,
Boolean bFromProxy, Boolean useLongPath, Boolean
checkHost)
at System.IO.FileStream..ctor(String path, FileMode
mode, FileAccess access, FileShare share)
at ScriptMain.CreateNewOutputRows()

The file path is accessible I was able to open the file from the server.

**Comment by andersnm** [comment]
Hi, this stacktrace does not involve ExcelDataReader. The exception likely occurs in your code (`ScriptMain.CreateNewOutputRows()`) where it fails to create the FileStream instance before it is passed to ExcelDataReader.

**Comment by ayo2kunle** [comment]
is it possible you help me? Below is my code: 

string FilePath = @"\\Networkdrive\MyNetworkFile.xlsx";


            var excelStream = File.Open(FilePath, FileMode.Open, FileAccess.Read);

            var conf = new ExcelReaderConfiguration { Password = "xxxxx" };
            var excelReader = ExcelReaderFactory.CreateOpenXmlReader(excelStream, conf);

            var excelDataSet = excelReader.AsDataSet(new ExcelDataSetConfiguration()
            {
                UseColumnDataType = true,
                ConfigureDataTable = (__) => new ExcelDataTableConfiguration()
                {
                    UseHeaderRow = true,
                }

            });

**Comment by andersnm** [comment]
Hi,

The error message: "Access to the path '' is denied" sounds like a permissions issue - assuming that the path is valid as you say and not actually a blank string. 

Facing that error I'd probably check the permissions. When your application runs on the server- maybe it runs under a different user account which does not have permission to read from that directory/network share.
