### ISSUE TITLE
Returning wrong value for float by ExcelDataReader

### ISSUE THREAD

**Issue by vikingcodes** [ExcelDataReader/ExcelDataReader#495]
We have one Excel , Its have "73.5793103448276" value in first second column of first row .

But ExcelDataReader column out is 73.57931034482759

Following is example of row

0001720295 , 73.5793103448276

**Comment by silkfire** [comment]
Can you attach a sample file?

**Comment by andersnm** [comment]
Hi,

Are you sure this is not just a difference in how Excel and your program renders the float?

```
73.5793103448276
73.57931034482759
```

ExcelDataReader should give you bitwise identical doubles value as Excel uses internally. You could use a third party library like ExcelNumberFormat if you need the values to look exactly like Excel: https://github.com/ExcelDataReader/ExcelDataReader#formatting

**Comment by virenderkverma** [comment]
Have look into this sheet.
[ListSearch_Book and markup 1.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/5432857/ListSearch_Book.and.markup.1.xlsx)

**Comment by appel1** [comment]
I believe this the same as https://github.com/ExcelDataReader/ExcelDataReader/issues/468#issuecomment-649045221

That is, Excel only shows at most 15 digits even though the stored float has more.

**Comment by virenderkverma** [comment]
Currently I am using ExcelDataReader two times, 

1. .Net Project - When using same code on .net project its returning "73.5793103448276"
2. .Net Core -  But when using same code on .Net Core project its returning "73.57931034482759"

See following code.

**.Net code - Returning - 73.5793103448276**

 ```
string myColumn = "";
                                for (int i = 0; i < fieldCount; i++)
                                {
                                    if (reader[i] != null)
                                    {
                                        myColumn = reader[i].ToString();
                                        var matches = _ExcelColumnsMapping.Where(p => p.Value == myColumn)
                                        .Select(p => p.Key);
                                        if (matches.Count() > 0) myColumn = string.Format("{0}({1})", myColumn, matches.Count());
                                        _ExcelColumnsMapping.Add(myColumn, reader[i].ToString());

                                        headersList.Add(myColumn);
                                    }
                                } 
```


**.Net Core Code - Returning - 73.57931034482759**

```
for (int i = 0; i < fieldCount; i++)
                            {
                                if (reader[i] == null)
                                {
                                    myColumn = null; //merged cell
                                    strValue = "";
                                }
                                else
                                {
                                    myColumn = reader[i].ToString();
                                    strValue = myColumn;
                                }

                                if (myColumn == null)//use colymn header as column name
                                {
                                    myColumn = GetExcelColumnName(i + 1);
                                    strValue = myColumn;
                                }

                                var matches = columnMapping.Where(p => p.Value == myColumn).Select(p => p.Key);

                                if (matches.Count() > 0) myColumn = string.Format("{0}({1})", myColumn, matches.Count());

                                columnMapping.Add(myColumn, strValue);

                                stringList.Add(myColumn);

                            } 
```

**Comment by andersnm** [comment]
Here's some info about changes to formatting in .NET Core 3.0:
https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/

Key take away is the default precision for string.Format() & co and floats changed in 3.0, so it is expected for values to round differently depending on the runtime. (also handled in the ExcelNumberFormat library)

**Comment by appel1** [comment]
@virenderkverma it is possible that double.ToString does not do the same thing on on .NET Framework and .NET Core. 

I know they've fixed some round trip issues in .NET Core but don't know off the top of my head what format ToString uses by default for double.

**Comment by appel1** [comment]
Anyways, the double you get from ExcelDataReader is the same as Excel stores in the file. How it is displayed or formatted as string is up to you.

**Comment by vikingcodes** [comment]
Found solutions.

 
**Installed - Install-Package ExcelNumberFormat**

https://github.com/andersnm/ExcelNumberFormat

     var value = reader.GetValue(i);
                                var formatString = reader.GetNumberFormatString(i);
                                if (formatString != null)
                                {
                                    var format = new NumberFormat(formatString);
                                    var formatedValue = format.Format(value, CultureInfo.InvariantCulture);
                                        myColumn = formatedValue;
                                }
