### ISSUE TITLE
When will be 3.7 available for production?

### ISSUE THREAD

**Issue by umeshshende** [ExcelDataReader/ExcelDataReader#496]
Its been 3 month still in pre release will it be safe for production use? i have been using this since last 2 year need xlsb support now.

**Comment by andersnm** [comment]
Hi, the only problem I'm aware of with XLSB is a performance issue on .NET Core 3.1 (see #493), but other than that it appears to be stable and safe to use.  Alas, cannot promise a date for the next (non-prerelease) version.

**Comment by umeshshende** [comment]
Thank you
