### ISSUE TITLE
CSV character separator auto-detection choosing `#` instead of comma in a file with many commas but only one `#`

### ISSUE THREAD

**Issue by gbirchmeier** [ExcelDataReader/ExcelDataReader#500]
I thought I found a [bug](https://github.com/ExcelDataReader/ExcelDataReader/issues/499), but it turns out the csv-separator auto-detection was just making a really bad choice.  It took me a long time to figure this out.

Given this file:
```
Item_Number,Pmt_Amount,Type,Voided,Note
200212812,$462.76,Check,06/06/2018,Hash#hash

```

(**Note the intentionally empty last line -- it is key to this situation happening.**  My data source sometimes gives empty lines in the CSV.)

...the parser is choosing `#`.  Why would it choose `#` when the entire first line contains a bunch of commas but no `#`?

I'm not demanding a fix, but maybe at least a review.  At least by creating this issue, maybe it'll pop up on someone's search and save them some trouble.  If you guys want to just close this, go ahead.

**Comment by andersnm** [comment]
Hi, Thanks for the report and apologies for putting you through this!

Alas it's not a new issue, we had similar reports before in #360 and #463.
