### ISSUE TITLE
ExcelDataReader.Exceptions.HeaderException: 'Invalid file signature.'

### ISSUE THREAD

**Issue by Leodez** [ExcelDataReader/ExcelDataReader#501]
The XLS file can be opened with Excel 2003 without problems, it also opens, although with problems, in Excel 365 (16).

I have the same exception using:

```
using (var stream = File.Open(filePath, FileMode.Open, FileAccess.Read))
{
    // ExcelDataReader.Exceptions.HeaderException: Invalid file signature
    using (var reader = ExcelReaderFactory.CreateReader(stream)) 
    { ...
```
or
```
using (var stream = File.Open(filePath, FileMode.Open, FileAccess.Read))
{
    ExcelReaderConfiguration config = new ExcelReaderConfiguration
    {
        FallbackEncoding = Encoding.GetEncoding(1252)
    };
    // ExcelDataReader.Exceptions.HeaderException: Invalid file signature
    using (var reader = ExcelReaderFactory.CreateReader(stream, config))
    { ...
```

The file XLS is attached here. This XLS file is generated by third party software.
[TestingWorkbook.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/5675483/TestingWorkbook.zip)

**Comment by andersnm** [comment]
Hi!

Looks like you got a csv that's been renamed to .xls there. Unfortunately there is no automatic detection of those.

It starts like this:

```csv
ID;PW2W 3000;N;E
P;PGeneral
P;FArial;M160;SB
```

**Comment by Leodez** [comment]
Thanks @andersnm, I have finally understood that the format is Symbolic Link (SYLK) used by old spreadsheet applications.

Changing the extension to .slk Excel 16 opens it without complaint, also with the extension .csv.

I think I will have to write my own API because possibly no one is interested in reading the SYLK format in their programs anymore.
