### ISSUE TITLE
read csv file by character range

### ISSUE THREAD

**Issue by melizav** [ExcelDataReader/ExcelDataReader#502]
Hello, I wanted to know if it was possible to read this type of file but by character that is to say that if character 0 to 10 is the data of a column and so on
3152460707 00004000030000413213200003201810090158925201810099514512018101200000001
3505387060 00001000040000114314300004201908050107436201908059602462019081500000001
3226591807 00002000040000314312100004202009240104300202009247435572020100700000001
3163109394 00004000030000413213200003201107290100010201107291334002011080500000001

**Comment by andersnm** [comment]
Hi,

The CSV format expects some kind of separator between the fields, so no, ExcelDataReader probably can't read your files.

But there are other libraries out there that can read files with fixed length fields. I worked on a project using the "FileHelpers" library to parse structured, fixed-length data out of OCR scans, and it worked: https://www.nuget.org/packages/FileHelpers/
