### ISSUE TITLE
Leading 0

### ISSUE THREAD

**Issue by mconnors100** [ExcelDataReader/ExcelDataReader#506]
As an example, having 0001 in an excel cell and it is being read as 1 when doing reader.AsDataSet().  I know one workaround is to format the cell as text prior to using the ExcelDataReader

**Comment by andersnm** [comment]
Hi @mconnors100,

It could be you are using an old version of ExcelDataReader. There was a problem in versions before 3.0 where number-like strings were converted to numbers.

It could also be that your value is physically stored as a number, but formatted with a Number Format. If you need formatted output, please refer to the "Formatting" section in the readme.

On the other hand, if you think there is a bug or other problem we need more info to reproduce.
