### ISSUE TITLE
Can read excel locally, but when running on server, it just hangs

### ISSUE THREAD

**Issue by dtsob75** [ExcelDataReader/ExcelDataReader#511]
I have developed an app that simply reads an excel spreadsheet and the loads the data.  It works perfectly on my local box, but when I deploy it to a server, it attempts to load the spreadsheet, but it just hangs up, with no feedback.  I have trapped around the code that uses the ExcelDataReader and still nothing reports.

My question is, does Excel have to be installed on the server for the ExcelDataReader to work?

Could there be any other reason that it hangs?

**Comment by appel1** [comment]
No, ExcelDataReader is standalone and does not depend on Excel. 

Perhaps you can create a dump from the process when it has hanged on the server and load that in a debugger to see where it is stuck. Or remote debug it.
