### ISSUE TITLE
I have been using ExcelDataReader and want to use it in a free plug-in. 

### ISSUE THREAD

**Issue by SWLyonPaw** [ExcelDataReader/ExcelDataReader#512]
This is not an issue but more of a question. 

I think this is Ok to use in non-commercial (free) stuff but I just wanted to check in. 

I also wanted to know if there is an option to eliminate the ExcelDataReader.xml and ExcelDataReader.DataSet.xml files that go along with the build. I am only using ExcelDataReader to return data and not looking further into the excel sheet for formatting information. I would like to release my entire package into one dll to make it as easy as possible for end users.

Please let me know if you need any further info.

Best;

Steve

**Comment by wizardgsz** [comment]
https://stackoverflow.com/questions/10564336/whats-the-xml-file-that-comes-together-with-a-net-assembly-file

**Comment by SWLyonPaw** [comment]
Thanks a bunch.

Best

Steve
