### ISSUE TITLE
Release 3.7.0 ETA

### ISSUE THREAD

**Issue by inqb** [ExcelDataReader/ExcelDataReader#516]
Is there an ETA on stable 3.7.0 release?
Or at least a prerelease nuget with ExcelDataTableConfiguration.TransformValue?
It's been six months since the last change...

**Comment by andersnm** [comment]
Unfortunately there is no ETA for a new release. I've usually done the releases since 3.0 in conjunction with a weekend, but for the last year personal issues have gotten in the way, and seemingly no end in sight :-(

**Comment by appel1** [comment]
3.7.0 has been released. 

https://github.com/ExcelDataReader/ExcelDataReader/releases/tag/v3.7.0
