### ISSUE TITLE
[Request] Support multiple header rows

### ISSUE THREAD

**Issue by The-MAZZTer** [ExcelDataReader/ExcelDataReader#518]
As you know, we're at war. Specifically, the war between non-developers, who see fit to put even vaguely tabular data into Excel spreadsheets regardless of whether or not using a spreadsheet makes sense, and us developers, who use excellent tools such as ExcelDataReader to free essential data from these spreadsheets and continue on our day. The non-developers are thinking up new ways every day to make this task more difficult for us, and thus I would like to request a feature to close one of these loopholes.

OK, joking aside, I have a real spreadsheet that is presenting some issues since it has multiple header rows. I can point EDR to the last header row, but some of the columns have the same name if you only look at that row making it difficult to tell them apart (another weapon the non-developers use is reordering columns in seemingly random order, so I don't want to have to rely on that).

Here is an example to show what I am talking about:

    +---------------+---------------+
    |    Group 1    |    Group 2    |
    +-------+-------+-------+-------+
    | Col 1 | Col 2 | Col 1 | Col 2 |
    +-------+-------+-------+-------+

There are four columns but there are overlapping names if I just use the second header row. I want to be able to also include the first to differentiate between all columns.

For example if this feature were added, if I check the column name of the first column from my code I might see something like "Group 1 Col 1".

**Comment by andersnm** [comment]
Hi,

I can certainly relate to having "difficult" users :-)

This is such a specialized case, I'd probably use the reader API and write a custom version of `AsDataSet()` which composes the headers like you describe. Alternatively, it is also possible to extract the first row in the `ReadHeaderRow()` callback, and amend `DataColumn.ColumnName` manually afterwards based on the extracted data. Looking at your example, the `reader.MergedCells`-property might be key either way.

As you noticed, there is nothing ready-made in EDR to do this easily, and if we were to do something, it'd probably be some general callback to assist transforming values in the header row (interestingly also [requested on stackoverflow](https://stackoverflow.com/questions/66365929/c-sharp-exceldatareader-trim-header-columns) recently).

**Comment by jgilbert2017** [comment]
+1

**Comment by jgilbert2017** [comment]
created pull request to address this issue.  if the patch is acceptable what is the timeframe for getting this into the nuget pacakge?  thanks.

https://github.com/ExcelDataReader/ExcelDataReader/pull/577

**Comment by jgilbert2017** [comment]
I've been using the patch in https://github.com/ExcelDataReader/ExcelDataReader/pull/577 for the past 1.5 years with no issue.

@appel1 Can you please review the pull request and merge if acceptable?

**Comment by appel1** [comment]
@jgilbert2017 Wouldn't a simpler implementation be to have a `Func<IExcelDataReader, IReadOnlyList<string>>` or `Func<IExcelDataReader, IReadOnlyDictionary<int, string>` instead?  That maps a column index to a header name.

**Comment by jgilbert2017** [comment]
@appel1 yes, either of those work for me but i think `Func<IExcelDataReader, IReadOnlyDictionary<int, string>` is preferable due to the ability to ignore columns.  (hope i'm understanding this correctly, it's been a while since i've worked on the code).  thanks.

**Comment by jgilbert2017** [comment]
hi- is there anything you need me to do in order to get the pull request approved?  thank you.

**Comment by appel1** [comment]
@jgilbert2017 I was waiting for you to update to a IReadOnlyDictionary. Or did you figure out some reason it is not a good idea?
