### ISSUE TITLE
Issue reading .xls file with header information on top

### ISSUE THREAD

**Issue by olivegarg** [ExcelDataReader/ExcelDataReader#52]
I am trying to read an .xls file with some extra lines of header information on top above the column names and the data. I keep getting the "Input array is longer than the number of columns in this table." error. Is there a way to work around this?

**Comment by Ian1971** [comment]
Are you using the AsDataset method? If so a workaround could be to use the IDataReader interface.

**Comment by olivegarg** [comment]
So instead of using IExcelDataReader just use IDataReader?

**Comment by Ian1971** [comment]
I think IExcelDataReader is an IDataReader. So you can just do something
like

while (excelReader.Read())
{
    //excelReader.GetInt32(0);
}


On Wed, Jan 28, 2015 at 3:51 PM, olivegarg <notifications@github.com> wrote:

> So instead of using IExcelDataReader just use IDataReader?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/52#issuecomment-71857628>
> .
>



-- 

Ian Cox
C.T.O.

Release  Mobile

m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.releasemobile.com

Registered in England.  Number 06323661

**Comment by andersnm** [comment]
Closing because inactivity, and sounds somewhat resolved. Will need sample code and test data to investigate further if still a problem.
