### ISSUE TITLE
Handling values formatting - example 0.00_

### ISSUE THREAD

**Issue by krostecki** [ExcelDataReader/ExcelDataReader#520]
We have had excel with cell format '0.00_'. For example when we had cell with value 2021.1 and formatting 0.00_, it has been displayed like 2021.10 in Excel, but when we read it with Reader, we got 2021.1

I wanted to have possibility to read these values with correct formatting.

**Comment by appel1** [comment]
ExcelDataReader reads raw values, so if Excel has stored the value as a 64-bit float, double in .NET, that is what you get when you read it using IExcelDataReader.GetValue. Unless it really is a non-numeric text in the Excel document? 

If you want to format the text as it is shown in Excel then you can use [this library](https://github.com/ExcelDataReader/ExcelDataReader#formatting).

**Comment by krostecki** [comment]
Provided by you library is enough. Thanks!
