### ISSUE TITLE
Long string of digits not possible to retireve loss of information

### ISSUE THREAD

**Issue by musarosro** [ExcelDataReader/ExcelDataReader#521]
Hi, I am using the library to import data from a XLSX file with cells containing long strings of digits like "3200010730102020". I need to work with them  as strings but the  GetValue method returns such string as a float (3.2000107301020E+15), and there is nothing I can find to retrieve the original value. 

I belive it is similar to #495. The problem seems to be that the cell value is guessed and if it parses as a number, it just returns that and GetString method just casts different type to the object and does not change the way the information is retrieved.

If open in Excel, the value is there correctly.

Sample file attached.
[xlsx_test.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/6334214/xlsx_test.xlsx)

**Comment by silkfire** [comment]
So what happens when you use GetString instead?

**Comment by appel1** [comment]
There's no loss of information, Excel has stored it in the xlsx file as a numeric value, a 64-bit float that matches double in .NET, and that's just how the default double.ToString implementation happens to format the numeric value in that cell. As you can see if you for example format the value using the format string G17. 

If you want to attempt to format the cell contents to generate the same strings as shown in Excel then you can use https://github.com/ExcelDataReader/ExcelDataReader#formatting

**Comment by musarosro** [comment]
Thanks for very quick response. I will try to get that to work and report back.

**Comment by musarosro** [comment]
So it seems that even without the 3rd party lib for formatting I was able to retrieve information by
reader.GetDouble(col).ToString("G17"). But I cannot use GetValue for that, because it returns a Double object that is not the same Double data type as GetDouble returns.

**Comment by appel1** [comment]
GetValue does return a double if it is a 64-bit float in the Excel document. You just need to cast it.
