### ISSUE TITLE
Option to skip .NET object binding when reading files

### ISSUE THREAD

**Issue by SpiritBob** [ExcelDataReader/ExcelDataReader#523]
the `Get*` methods are nice for a lot of reasons, but when you just want to get a text representation of the values. you're forced to go through `reader.GetValue?.ToString()`. Wouldn't it be nice to have a perf flag to skip binding altogether and just return the text as a string via `reader.GetString()`?

**Comment by andersnm** [comment]
Hi,

There was some discussion on this topic here: https://github.com/ExcelDataReader/ExcelDataReader/issues/268

IMHO such feature could easily grow into something unwieldy, so I'd prefer if applications dealt with this themselves.

**Comment by appel1** [comment]
What text representation are we talking about here? The raw binary data as stored in the source xls/xlsx/xlsb file? Or localized and formatted text as you see it if you open the file in Excel? Or something else?

**Comment by SpiritBob** [comment]
> What text representation are we talking about here? The raw binary data as stored in the source xls/xlsx/xlsb file? Or localized and formatted text as you see it if you open the file in Excel? Or something else?

The general and mass-use case would be to see the localized and formatted text as if you opened the file in Excel, yes.

**Comment by appel1** [comment]
> > What text representation are we talking about here? The raw binary data as stored in the source xls/xlsx/xlsb file? Or localized and formatted text as you see it if you open the file in Excel? Or something else?
> 
> The general and mass-use case would be to see the localized and formatted text as if you opened the file in Excel, yes.

So not the raw data at all then. 

For formatted text see https://github.com/ExcelDataReader/ExcelDataReader#formatting.

**Comment by SpiritBob** [comment]
> > > What text representation are we talking about here? The raw binary data as stored in the source xls/xlsx/xlsb file? Or localized and formatted text as you see it if you open the file in Excel? Or something else?
> > 
> > 
> > The general and mass-use case would be to see the localized and formatted text as if you opened the file in Excel, yes.
> 
> So not the raw data at all then.
> 
> For formatted text see https://github.com/ExcelDataReader/ExcelDataReader#formatting.

What would reading the raw binary data look like then? You mean to say formulas and etc won't be handled? But for any other cell, it'd still be in human readable form?
