### ISSUE TITLE
Issue with reading header rows

### ISSUE THREAD

**Issue by ghendric** [ExcelDataReader/ExcelDataReader#526]
I ran across a problem with reading a header row to get the field names. If the text in a column header has a space at the end of it, the code can't find it if you are looking for the text without the space on the end.

Example:
Excel file column header text: "Hours "
Data row value looking for: dr["Hours"]

Is there a way to trim the spaces off of the column header text when its reading the excel file?

**Comment by andersnm** [comment]
Hi, this is not supported currently. This is a variation on the request in #518 and the linked [stackoverflow](https://stackoverflow.com/questions/66365929/c-sharp-exceldatareader-trim-header-columns)

**Comment by gojimmypi** [comment]
I wonder if it would be a good idea to have an optional `SafeFieldName`, perhaps created in @appel1's [proposed adapter wrapper idea](https://github.com/ExcelDataReader/ExcelDataReader/issues/538#issuecomment-854142587), as not only do I need to [get the bulk insert working](https://github.com/ExcelDataReader/ExcelDataReader/issues/536) - but I also will need to address the issue of "safe" field names. 

I'm currently doing this manually in my resulting `DataSet`: cleaning up the field names by trimming leading and trailing spaces and replacing characters I don't want with an underscore at load time before inserting into SQL via XML raw data; Although I did have a problem with types as mentioned in https://github.com/ExcelDataReader/ExcelDataReader/issues/508. Alas the XLS files have grown and even change over time (changing field names, field order, add/remove fields).

This is a bit more interesting problem for the `SqlBulkCopy` exercise as I don't allow odd field names in the target SQL table. Also [GetName() is not implemented](https://github.com/ExcelDataReader/ExcelDataReader/blob/2f14bd4a53186b1c99de05efe4dbee2de1fd3725/src/ExcelDataReader/ExcelDataReader.cs#L94) anyhow as noted in https://github.com/ExcelDataReader/ExcelDataReader/issues/535  (also more of an argument that this all needs to be [implemented in a wrapper](https://github.com/ExcelDataReader/ExcelDataReader/issues/538#issuecomment-854177176))

**Comment by ghendric** [comment]
I think i found a way around this by using ExcelDataReader.Mapping where on your class, add an attribute like this that maps the excel column to a property on your class like this:

	[ExcelColumnIndex(1)]
	public string Employee { get; set; }

**Comment by gojimmypi** [comment]
That might work in some situations. For me `Employee` is not always in column 1, and may not even always be called `Employee`. 

I really need to be able to access the columns by _name_ for the SQL Bulk Insert.

The data I have to deal with:

- Comes from a third party I cannot control
- Field names are added / removed / renamed / reordered - often unexpectedly and unannounced
- May have up to 700 columns or more, with up to hundreds of thousands of rows
- Is being loaded by my app that handles many different files based on fields in first row

Sure, I could first get a list of the names from the first row, then get the ordinal reference for each. But I'd rather have something more graceful and intuitive.

When accessing by name, I can do a "best fit" of the data, and simply send an alert when expected fields are missing and/or new field are found. I probably could force similar logic into ordinal references, but that's not the right solution for me.

My [initial PR](https://github.com/ExcelDataReader/ExcelDataReader/pull/537) has a solution that works with the [sample code shown in #536](https://github.com/ExcelDataReader/ExcelDataReader/issues/536#issue-910733467), but I still plan to take a look at creating a data adapter.
