### ISSUE TITLE
small questions about documentation

### ISSUE THREAD

**Issue by graysuit** [ExcelDataReader/ExcelDataReader#530]
Respected developers,
I used it 1 day, and got very happy due to its simplicity, ease, and working functionalities.

I have some questions, which I didn't found on front read me page:
1. Does it supports writing/creation excel files ?
2. Can I use it even without when office/excel is NOT installed ?
3.  What are tips for optimizing speed ?

Thanks.

**Comment by appel1** [comment]
1. No, it's called reader for a reason. 
2. Yes
3. That's a bit too unspecific,

**Comment by graysuit** [comment]
Hi sir, Thanks so much for quick reply.

3. I'm looping through all excel files and append to output.xlsx file. Current speed is 0.5s per 101 lined xlsx file. and it get 144-155s per 73 files. Can I optimize it more ?

**Comment by appel1** [comment]
Do you use the reader interface or AsDataSet? If you don't need the DataSet it is faster to use the reader interface.

**Comment by graysuit** [comment]
I'm already using direct reader interface instead of DataSet:
https://github.com/ExcelDataReader/ExcelDataReader#how-to-use

And before as I used backgroundworker, speed was increased 50%.
Mean 4s to 2s.

I guess it can be optimized more via threads.

**Comment by appel1** [comment]
I'd start with using a profiler to see if anything sticks out.

**Comment by graysuit** [comment]
Thanks a lot appel.
I got all answers. So closing this. 
Cheers !
