### ISSUE TITLE
Skip trailing empty columns or rows

### ISSUE THREAD

**Issue by appel1** [ExcelDataReader/ExcelDataReader#532]
Sometimes Excel files have lots of trailing rows and/or columns without any content, just formatting. Perhaps we could skip them by default, and possibly have a setting in ExcelReaderConfiguration that lets you include them if you want. In the common case I don't think anyone is interested in completely empty trailing rows or columns even if there is some kind of formatting applied to them.

Thoughts?

**Comment by Seabizkit** [comment]
yes please, i see there are open PR, but no more new release.... it would be awesome for more PR to be merge and some more releases plz

**Comment by markmcdelm** [comment]
I'm waiting for this to be included in a release
