### ISSUE TITLE
GetName and GetOrdinal not implemented

### ISSUE THREAD

**Issue by gojimmypi** [ExcelDataReader/ExcelDataReader#535]
These two lines in [ExcelDataReader.cs](https://github.com/ExcelDataReader/ExcelDataReader/blob/master/src/ExcelDataReader/ExcelDataReader.cs), [here](https://github.com/ExcelDataReader/ExcelDataReader/blob/e5b7d41b580603c866b9097496139080c0bba105/src/ExcelDataReader/ExcelDataReader.cs#L93)  and [here](https://github.com/ExcelDataReader/ExcelDataReader/blob/e5b7d41b580603c866b9097496139080c0bba105/src/ExcelDataReader/ExcelDataReader.cs#L95):

```
        public string GetName(int i) => throw new NotSupportedException();

        public int GetOrdinal(string name) => throw new NotSupportedException();
```
... are not implemented, and of course throw the shown `NotSupportedException` during the use of a stream read, such as `ExcelReaderFactory.CreateReader(stream)`

See PR https://github.com/ExcelDataReader/ExcelDataReader/pull/537

**Comment by appel1** [comment]
If I remember correctly this is intentional because Excel files do not have this concept and we've tried to keep the core reader implementation as simple as possible. Maybe you could argue that GetName and GetOrdinal should expose the letter based column names that Excel uses. Not sure how helpful that would be to anyone though.

**Comment by gojimmypi** [comment]
Well, the stream reader was expecting the `GetName` to return the field name (not excel name such as `A1`) as well as the `GetOrdinal`. That was the only reason I stumbled upon the missing implementation. 

I agree that Excel does not have the concept of stream readers, but that's the whole point of this `ExcelDataReader`: to get data out of XLS files and into something else.

What do you think would be the best implementation? Perhaps a separate `BulkExcelDataReader`?

**Comment by appel1** [comment]
ExcelDataReader doesn't know of any other fields than column names in Excel like A or BD. So if you need something else perhaps an adapter class in your project would be a better solution.

**Comment by gojimmypi** [comment]
I agree that Excel support of field names is a bit wonky: it "knows" that there can be field names in the first row for sorting and such, but as far as I can tell - there's no support for actually using them. As you noted: formulas use something like `=A1`  and not `=Fieldname[rownum]`  (which personally I think would be a very cool feature)

In some ways, it would be nice if it just worked as is; passing the stream reader. But I get it: your point is to keep the library clean and free from corner-case clutter.

What do you think of me opening a separate issue for "Missing `BulkExcelDataReader` Adapter", and if @andersnm agrees, and if I can actually get the `SqlBulkCopy` to accept that new adapter as a `WriteToServer` parameter - adding that instead?
