### ISSUE TITLE
SQL Bulk Insert of ExcelDataReader stream fails with "Specified method is not supported"

### ISSUE THREAD

**Issue by gojimmypi** [ExcelDataReader/ExcelDataReader#536]
When attempting to use `SqlBulkCopy` to bulk insert a `ExcelDataReader` stream reader (for example, a Very Large XLS that one might not want to load into memory all at once in a dataset), the call fails with `Specified method is not supported` during `WriteToServer`:

For example:
```
            using (var stream = File.Open(fromFileXLSX, FileMode.Open, FileAccess.Read))
            {
                using (var r = ExcelReaderFactory.CreateReader(stream))
                {
                    using (SqlBulkCopy bulkCopy = new SqlBulkCopy(TrustedConnectionString(toServer, toDatabase)))
                    {
                        bulkCopy.WriteToServer(r);  // fails here
                    }
                }
            }
```

Returns this error:

```
 at ExcelDataReader.ExcelDataReader`2.GetOrdinal(String name) in C:\\workspace-PR\\ExcelDataReader\\src\\ExcelDataReader\\ExcelDataReader.cs:line 95
   at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerCommon(Int32 columnCount)
   at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)
   at BulkCopyStreamReader.Program.XlsFetch(String fromFileXLSX, String toServer, String toDatabase, String toTable) in C:\\workspace-PR\\ExcelDataReader\\Example\\BulkCopyStreamReader\\Program.cs:line 168
   at BulkCopyStreamReader.Program.Main(String[] args) in C:\\workspace-PR\\ExcelDataReader\\Example\\BulkCopyStreamReader\\Program.cs:line 187"
```

The root cause of this error is the not-yet-implemented `GetName` and `GetOrdinal` as noted in https://github.com/ExcelDataReader/ExcelDataReader/issues/535

See PR https://github.com/ExcelDataReader/ExcelDataReader/pull/537

**Comment by andersnm** [comment]
Hi!

It should be possible to configure the `SqlBulkCopy` instance with column mappings to prevent from throwing (assuming I'm reading https://stackoverflow.com/q/60266053 correctly). The example project in the PR does this too, and shouldn't need any changes in the reader.

It would be nice with a reader-based bulk copy example in the readme or a wiki (which we don't have, alas). I'd rather not have to maintain examples in the repo as suggested in the PR.

**Comment by gojimmypi** [comment]
Hi! 

I agree that's what I expected to happen, but after doing the [column mapping](https://github.com/gojimmypi/ExcelDataReader/blob/360e87727c6ce9f5734c925582be58e4004272a7/Example/BulkCopyStreamReader/Program.cs#L184) in what essentially appears to be the same as the SO link (but instead pulling XLS fields and assuming they are the same in SQL table) like this:
```
  foreach (DataColumn column in xlsHeader.Tables[0].Columns)
  {
    bulkCopy.ColumnMappings.Add(column.ColumnName, "[" + column.ColumnName + "]");
   }
```
the runtime call `bulkCopy.WriteToServer(r)` expected them to work, but failed with the exception.

As for the examples, well - I do believe that fully operational examples can be quite helpful. I also see your perspective on maintaining them here. Perhaps they belong in a new `ExcelDataReader-Examples` repo?  So many times I've tried to understand someone's wiki code segments, when simply having a full project tells the whole story so much better. The project is also much more maintainable, as it is otherwise impossible to ensure code in a wiki is complete and actually compiles properly.

**Comment by andersnm** [comment]
Hi,

I suppose it throws if you use the `(string, string)` arguments overload of `ColumnMappings.Add`, since the bulk copier still needs to resolve the ordinals from the name:name mappings. The stackoverflow mentions an `(int, string)` overload to specify ordinal:name mappings directly:

```c#
for (var i = 0; i < xlsHeader.Tables[0].Columns.Length; i++)
  {
    DataColumn column = xlsHeader.Tables[0].Columns[i];
    bulkCopy.ColumnMappings.Add(i, "[" + column.ColumnName + "]");
   }
```

I didn't test this, but at least two people in the stackoverflow indicate this should work.

Also, in a perfect example, the target column names should be read manually from the reader rather than from a DataSet.
