### ISSUE TITLE
Feature addition: Inject static field values into stream reader

### ISSUE THREAD

**Issue by gojimmypi** [ExcelDataReader/ExcelDataReader#538]
When using `SqlBulkCopy` to insert stream reader data, at times it is desirable to have additional fields in the target table that is being populated, not found in the source XLS file. For example, the bulk insert SQL target table may support uploads from multiple users, but a specific data update at a given time would be interested only a single user and respective upload rows. One solution is to "inject" static field values into the stream to identify the user and perhaps a session id.

Before doing any of this, https://github.com/ExcelDataReader/ExcelDataReader/issues/536 needs to be address due to the runtime error that otherwise occurs during bulk insert due to the not-yet-implemented `GetName` and `GetOrdinal` as described in https://github.com/ExcelDataReader/ExcelDataReader/issues/535

See PR https://github.com/ExcelDataReader/ExcelDataReader/pull/539

**Comment by appel1** [comment]
Does this really have to be part of ExcelDataReader? Sounds fairly specific and can be easily done with an adapter class that wraps the reader if I understand you correctly.

**Comment by gojimmypi** [comment]
@appel1 thanks for taking a look. As with most software implementations, there are a variety of ways to solve this. I am certainly interested in the most stable and appropriate solution.

What I did was add a feature to [pass an optional dictionary object](https://github.com/gojimmypi/ExcelDataReader/blob/360e87727c6ce9f5734c925582be58e4004272a7/src/ExcelDataReader/ExcelReaderFactory.cs#L28) of keys (field names) and values to be injected to the stream. When present, at runtime the [field list is appended with key values](https://github.com/gojimmypi/ExcelDataReader/blob/360e87727c6ce9f5734c925582be58e4004272a7/src/ExcelDataReader/ExcelDataReader.cs#L133) and when reading values in the stream, if an injected field name is found, I [return the fixed value from the dictionary object](https://github.com/gojimmypi/ExcelDataReader/blob/360e87727c6ce9f5734c925582be58e4004272a7/src/ExcelDataReader/ExcelDataReader.cs#L197), as the value of course does not exist in the `RowCells`.

I have an example of [the dictionary creation](https://github.com/gojimmypi/ExcelDataReader/blob/360e87727c6ce9f5734c925582be58e4004272a7/Example/BulkCopyStreamReaderInjection/Program.cs#L172), which is [passed as an optional parameter](https://github.com/gojimmypi/ExcelDataReader/blob/360e87727c6ce9f5734c925582be58e4004272a7/Example/BulkCopyStreamReaderInjection/Program.cs#L176), then the [column mapping](https://github.com/gojimmypi/ExcelDataReader/blob/360e87727c6ce9f5734c925582be58e4004272a7/Example/BulkCopyStreamReaderInjection/Program.cs#L194) that occurs in preparation for the [bulk insert](https://github.com/gojimmypi/ExcelDataReader/blob/360e87727c6ce9f5734c925582be58e4004272a7/Example/BulkCopyStreamReaderInjection/Program.cs#L202).

**Comment by appel1** [comment]
I don't think we should change the reader for this special case and complicating it further. Is there some reason this can't be accomplished in an adapter wrapper?

**Comment by andersnm** [comment]
Hi,

IMO the proper way to implement this - as @appel1 suggests - is to create a wrapper class in your application that implements IDataReader (or IExcelDataReader if needed) and modifies the column layout of an underlying / inner IExcelDataReader instance.

For reference, here are some examples of other kinds of wrapper classes:

`LooselyTypedReader` converts data to requested types in `GetString()`, `GetInt32()` etc
https://gist.github.com/andersnm/7205389e5e5a71773a9716e0853e3ee7#file-looselytypedreader-cs

`MergeCellsReader` repeats the top left value in merged cells:
https://gist.github.com/andersnm/7205389e5e5a71773a9716e0853e3ee7#file-mergecellsreader-cs

Usage:

```
using (var reader = new MergeCellsReader(ExcelReaderFactory.CreateReader(stream))) {
 ...
}
```

**Comment by gojimmypi** [comment]
That does look promising... thanks very much for the suggestion and samples. I agree it seemed a bit hackish to have the optional injection dictionary parameter. Let me see what I can do with that. It might take a bit of time, as I need to get something working in production sooner than later.

Also - I noticed the `master` branch is a bit behind your `develop` branch. What are the plans & which do you prefer PR's? (or perhaps no PR, and initially just ask in advance?)

**Comment by andersnm** [comment]
PRs should always be submitted against the develop branch. I guess I'm the main person with the power to commit and merge PRs, altho I'm just a random person with little time on my hands. The "plan" is to merge at least 2-3 of the current PRs into develop (strict Open XML support, initial formulas support), update the documentation/readme, and then merge to master and release a new non-prerelease version to Nuget. However I have no idea when; it could happen this weekend (unlikely), or in a couple months (more likely).

If you have an idea for a PR, it is usually a good idea to ask in advance; often times we can help finding an alternative approach without modifying the library.

**Comment by gojimmypi** [comment]
for reference,  see https://github.com/JoshClose/CsvHelper/issues/1215 that has an example implementation of `AddStaticData`:

> If you want to add a static column called "Foo" with a value of "Bar", you'd do:
> 
> `reader.AddStaticData( "Foo", ( csv ) => "Bar" );`
> 
> If you wanted to do something like concat two CSV columns together, you'd do :
> 
> `reader.AddStaticData( "Foo", ( csv ) => csv[0] + csv[1] );`

I like this implementation: simple, graceful. Do you think it belongs in the base class or a wrapper adapter?
