### ISSUE TITLE
How skip N rows

### ISSUE THREAD

**Issue by psychomonkey911** [ExcelDataReader/ExcelDataReader#542]
I am facing the problem of skipping N lines
i have int wich indicate how much row i need skip

at first i try use EmptyColumnNamePrefix = "Column"
but when read i see empty column with name Column0, Column1...
[
![image](https://user-images.githubusercontent.com/24847110/122826662-14528800-d2ec-11eb-8b5e-416318a3a6bd.png)
](url)
```
using (var stream = File.Open(filePath, FileMode.Open, FileAccess.Read))
            {
                //  - Binary Excel files (2.0-2003 format; *.xls)
                //  - OpenXml Excel files (2007 format; *.xlsx, *.xlsb)
                using (var reader = ExcelReaderFactory.CreateReader(stream))
                {
                    return reader.AsDataSet(new ExcelDataSetConfiguration
                    {
                        ConfigureDataTable = _ => new ExcelDataTableConfiguration
                        {
                            **EmptyColumnNamePrefix = "Column",**
                            UseHeaderRow = true,
                        }
                    });
                }
            }
```
then i try use FilterRow = rowReader => rowReader.Depth > firstRowNumber-1,
but result same

Is this a bug or am I doing something wrong?

**Comment by andersnm** [comment]
Hi!

If you need to skip lines _before_ the header row, use the `ReadHeaderRow` callback. If you need to skip rows _after_ the header row, use the `FilterRow` callback.
