### ISSUE TITLE
recovery of password of protected excel sheet

### ISSUE THREAD

**Issue by emshihab008** [ExcelDataReader/ExcelDataReader#544]
Hello Everyone,
I have an enquiry regarding recovery of old password which is used to protect excel sheet. Can anyone provides any solution? (for my cases, it is highly important to know the old password).

Regards,
Ekram

**Comment by andersnm** [comment]
Hi,

Sounds like a sticky situation. You can probably hire a security company to analyze your file and give a probability how long it would take to brute force the password. The password protection in Excel is pretty solid, so I wouldn't be surprised at an estimate in the literally billions of years. There are ways to bring the time down, but depends on the version of Excel and how much you know about the password (length, complexity). It is certainly outside the scope of the ExcelDataReader project.
