### ISSUE TITLE
OperationNotSupported exception when Stream is not writable.

### ISSUE THREAD

**Issue by SpiritBob** [ExcelDataReader/ExcelDataReader#546]
I get a `OperationNotSupported` exception when the stream passed to `ExcelDataReader` does not support writing.

Is this by design?

Thank you.

**Comment by andersnm** [comment]
There is no code in ExcelDataReader that writes to the input stream. What does the stacktrace say?

**Comment by SpiritBob** [comment]
I'm sorry for the confusion, it appears the actual problem is that the stream is not seekable. This is related to https://github.com/ExcelDataReader/ExcelDataReader/issues/431.

I don't understand the decision behind not making a ZipArchiveEntry not seekable when the `ZipArchiveMode` is set to `ZipArchiveMode.Read`.
