### ISSUE TITLE
All data not being pulled

### ISSUE THREAD

**Issue by riehlers** [ExcelDataReader/ExcelDataReader#55]
I am having issues seeing all the columns in a file. When stepping through the file I only see the first column. This creates issues in my code when I try to rename columns that do not exist. Could you please help me come up with a solution as to why I can't see the whole file. 

I have attached a link to a sample xlsx file that is giving me the problem. 

https://www.dropbox.com/s/4f8n29p9l2cab8x/HRA%20Medical.xlsx?dl=0

**Comment by Ian1971** [comment]
Are you using the version in master or develop?

**Comment by Ian1971** [comment]
I found an issue with some async calls in the develop version, so assuming that is where you were trying it.
