### ISSUE TITLE
the problem of adding text from excel does not match

### ISSUE THREAD

**Issue by kana88** [ExcelDataReader/ExcelDataReader#563]
Dear All master,

I'm using the exceldatareader library version 2 because I'm using vs 2010 with .net framework 4. So the problem with the add text result only takes the last value from the last row in column B. It should match the value according to the row from the path image in column A. I attach the excel file and the output of the image. Please solution.

[Template_Image - Copy.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/7088893/Template_Image.-.Copy.xlsx)
![RESULT3](https://user-images.githubusercontent.com/53716175/131626162-6aee4284-e82a-4430-aaf6-d80876a986c3.PNG)
![RESULT4](https://user-images.githubusercontent.com/53716175/131626170-1a725615-f251-412d-a574-635efd99d5be.PNG)

`
                  Dim excelReaderXlsx As IExcelDataReader = Nothing
                  Dim dsTable As DataSet = New DataSet
                   If (extension = ".xlsx") Then
                        'open(xlsm)
                        excelReaderXlsx = ExcelReaderFactory.CreateOpenXmlReader(fs)
                        excelReaderXlsx.IsFirstRowAsColumnNames = True
                        dsTable = excelReaderXlsx.AsDataSet
                   End If
                    Dim z As Integer = 0
                    For Each dr As DataRow In dsTable.Tables(0).Rows
                        If z > 0 Then
                            Dim pathImage As String = dr(0).ToString().Trim()
                            Dim type As String = dr(1).ToString().Trim()
                        End If
                        w.InitLibrary("demo", "demo")
                        w.AddInputFile(dr(0).ToString().Trim())

                        preset.Text = dr(1).ToString().Trim() 'problem text in column B
                        preset.Transparency = 50
                        w.AddWatermark(preset)
                        w.OutputOptions.OutputDirectory = "c:\emp\output"
                        w.Execute()
                        ListBox1.Items.Add(dr(0).ToString().Trim())
                    Next
`
Thanks
kana88

**Comment by andersnm** [comment]
Hi!

You should definitely upgrade to ExcelDataReader version 3.x - it has 5+ years of fixes and works in VS2010 and .NET 4 too.

I don't think the attached screenshots has any relation to your problem?

**Comment by kana88** [comment]
> Hi!
> 
> You should definitely upgrade to ExcelDataReader version 3.x - it has 5+ years of fixes and works in VS2010 and .NET 4 too.
> 
> I don't think the attached screenshots has any relation to your problem?

dear sir,
can you provide a solution to my problem?
thanks

**Comment by andersnm** [comment]
Hi @kana88,

I haven't used VS2010/.NET4 in ages, but the the basic steps to upgrade ExcelDataReader from 2.x to 3.x are:

- change the version number in `packages.config`
- restore packages
- fix code :  https://github.com/ExcelDataReader/ExcelDataReader#important-note-when-upgrading-from-exceldatareader-2x

**Comment by kana88** [comment]
> Hi @kana88,
> 
> I haven't used VS2010/.NET4 in ages, but the basic steps to upgrade ExcelDataReader from 2.x to 3.x are:
> 
> * change the version number in `packages.config`
> * restore packages
> * fix code :  https://github.com/ExcelDataReader/ExcelDataReader#important-note-when-upgrading-from-exceldatareader-2x

dear sir,
what series version 3 uses .netframework 4
thanks

**Comment by kana88** [comment]
> > Hi @kana88,
> > I haven't used VS2010/.NET4 in ages, but the basic steps to upgrade ExcelDataReader from 2.x to 3.x are:
> > 
> > * change the version number in `packages.config`
> > * restore packages
> > * fix code :  https://github.com/ExcelDataReader/ExcelDataReader#important-note-when-upgrading-from-exceldatareader-2x
> 
> dear sir,
> what series version 3 uses .netframework 4
> thanks

dear sir ,
After I upgraded from version 2 to version 3.6.0, I got an error in the process. I attached a screenshot of the error
thanks
![error01-09-2021](https://user-images.githubusercontent.com/53716175/131687090-42adcfa4-1832-47a6-996e-acd46abc537f.JPG)

**Comment by andersnm** [comment]
@kana88 Apologies, but I can't really help you with this. It's specific to your outdated environment and tools, and it's not something I particularly want to refresh at this time. You need to either make sure you are using the net45 binary of ExcelDataReader, or install SharpZipLib v0.86 into your project if you are on NET4.0.

**Comment by kana88** [comment]
> @kana88 Apologies, but I can't really help you with this. It's specific to your outdated environment and tools, and it's not something I particularly want to refresh at this time. You need to either make sure you are using the net45 binary of ExcelDataReader, or install SharpZipLib v0.86 into your project if you are on NET4.0.
dear sir ,
for the SharpZipLib problem I have the solution. when I open the excel file there is an error. I attach below a screenshot and also the code

`Dim excelReaderXlsx As IExcelDataReader = Nothing
Dim dsTable As DataSet = New DataSet
  If (extension = ".xlsx") Then
  excelReaderXlsx = ExcelReaderFactory.CreateOpenXmlReader(fs)
                        Dim result =  excelReaderXlsx.AsDataSet(New ExcelDataSetConfiguration() With {
 .ConfigureDataTable = Function(underscore) New ExcelDataTableConfiguration() With {.UseHeaderRow = True}
})
End If
Dim z As Integer = 0
                    For Each dr As DataRow In dsTable.Tables(0).Rows
                        If z > 0 Then
                            Dim pathImage As String = dr(0).ToString().Trim()
                            Dim type As String = dr(1).ToString().Trim()
 End If
                        w.InitLibrary("demo", "demo")
                        w.AddInputFile(dr(0).ToString().Trim())

                        preset.Text = dr(1).ToString().Trim()
                        'preset.Font = New WatermarkFont("Tahoma", FontStyle.Regular, FontSizeType.Points, 30)
                        'preset.TextColor = Color.Red
                        preset.Transparency = 50
                        w.AddWatermark(preset)
                        w.OutputOptions.OutputDirectory = "c:\emp\output"
                        w.Execute()
                        ListBox1.Items.Add(dr(0).ToString().Trim())
                    Next
![openerror](https://user-images.githubusercontent.com/53716175/131692916-315361cb-fc65-48e6-b780-ac8117ed4176.JPG)
`

**Comment by kana88** [comment]
dear sir,
sorry i'm late reply
for variable w and preset information.
`Public Class Form1
    Dim w As Watermarker = New Watermarker()
    Dim preset As New TextFitsPage()`

the problem reads First Row As Column Name. so it's not a variable w. Previously I used exceldatareader version 2 with the code below
`excelReaderXlsx.IsFirstRowAsColumnNames = True`
so it doesn't read First Row As Column Name.

`Dim excelReaderXlsx As IExcelDataReader = Nothing
Dim dsTable As DataSet = New DataSet
If (extension = ".xlsx") Then
                        'open(xlsx)
                        excelReaderXlsx = ExcelReaderFactory.CreateOpenXmlReader(fs)
                        Dim result = excelReaderXlsx.AsDataSet(New ExcelDataSetConfiguration() With {
 .ConfigureDataTable = Function(underscore) New ExcelDataTableConfiguration() With {.UseHeaderRow = True}
})
 dsTable = excelReaderXlsx.AsDataSet
End If
 Dim z As Integer = 0
                    For Each dr As DataRow In dsTable.Tables(0).Rows
                        If z > 0 Then
                            Dim pathImage As String = dr(0).ToString().Trim()
                            Dim type As String = dr(1).ToString().Trim()
 End If
                        w.InitLibrary("demo", "demo")
                        w.AddInputFile(dr(0).ToString().Trim())

                        preset.Text = dr(1).ToString().Trim()
                        preset.Transparency = 50
                        w.AddWatermark(preset)
                        w.OutputOptions.OutputDirectory = "c:\emp\output"
                        w.Execute()
                        ListBox1.Items.Add(dr(0).ToString().Trim())
                    Next`

**Comment by kana88** [comment]
dear sir,
i still have problem add text from excel to image. the text appears only in the last row in all image
` Using openFileDialog1 = New OpenFileDialog With {
    .Filter = "Excel Workbook|*.xls;*.xlsx;*.xlsm",
    .ValidateNames = True
   }
            If openFileDialog1.ShowDialog() = DialogResult.OK Then
                Dim fs = File.Open(openFileDialog1.FileName, FileMode.Open, FileAccess.Read)
                Dim reader = ExcelReaderFactory.CreateOpenXmlReader(fs)
Dim dataSet = reader.AsDataSet(New ExcelDataSetConfiguration With {
                 .ConfigureDataTable = Function(underscore) New ExcelDataTableConfiguration With {.UseHeaderRow = True}
                })
                If dataSet.Tables.Count > 0 Then
                    For Each dr As DataRow In dataSet.Tables(0).Rows

                        Dim dtData = dataSet.Tables(0)
                        Dim pathtxt As String = dr(0).ToString().Trim()
                        Dim text As String = dr(1).ToString().Trim() 'this is the row text code in excel

                    Next
                End If
            End If
        End Using`
![result excel](https://user-images.githubusercontent.com/53716175/134911564-18aeae57-f379-4347-846a-153c8d63d547.JPG)
![image1](https://user-images.githubusercontent.com/53716175/134911614-ea232cf0-c7ba-4a0b-a03e-3c22b11d60a8.JPG)
![image2](https://user-images.githubusercontent.com/53716175/134911641-8dd67edb-d568-4a09-978d-79961050fbb6.jpg)

**Comment by kana88** [comment]
> Dear All master,
> 
> I'm using the exceldatareader library version 2 because I'm using vs 2010 with .net framework 4. So the problem with the add text result only takes the last value from the last row in column B. It should match the value according to the row from the path image in column A. I attach the excel file and the output of the image. Please solution.
> 
> [Template_Image - Copy.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/7088893/Template_Image.-.Copy.xlsx) ![RESULT3](https://user-images.githubusercontent.com/53716175/131626162-6aee4284-e82a-4430-aaf6-d80876a986c3.PNG) ![RESULT4](https://user-images.githubusercontent.com/53716175/131626170-1a725615-f251-412d-a574-635efd99d5be.PNG)
> 
> ` Dim excelReaderXlsx As IExcelDataReader = Nothing Dim dsTable As DataSet = New DataSet If (extension = ".xlsx") Then 'open(xlsm) excelReaderXlsx = ExcelReaderFactory.CreateOpenXmlReader(fs) excelReaderXlsx.IsFirstRowAsColumnNames = True dsTable = excelReaderXlsx.AsDataSet End If Dim z As Integer = 0 For Each dr As DataRow In dsTable.Tables(0).Rows If z > 0 Then Dim pathImage As String = dr(0).ToString().Trim() Dim type As String = dr(1).ToString().Trim() End If w.InitLibrary("demo", "demo") w.AddInputFile(dr(0).ToString().Trim())
> 
> ```
>                     preset.Text = dr(1).ToString().Trim() 'problem text in column B
>                     preset.Transparency = 50
>                     w.AddWatermark(preset)
>                     w.OutputOptions.OutputDirectory = "c:\emp\output"
>                     w.Execute()
>                     ListBox1.Items.Add(dr(0).ToString().Trim())
>                 Next
> ```
> 
> ` Thanks kana88

I want delete this post because 
because this is a code error from me
