### ISSUE TITLE
ERROR DOWNLOADING THE EXCELDATAREADER PACKAGE

### ISSUE THREAD

**Issue by iamlozano** [ExcelDataReader/ExcelDataReader#564]
**Cycle detected** 
Download the ExcelDataReadeR.DataSet package first and then ExcelDataReader, which as it says in the package document, these were divided into two. The error it throws at me in VS is this error: Severity Code Description Project File Line Status suppressed
**Error NU1108** **Cycle detected**.
  ExcelDataReader -> ExcelDataReader (> = 2.1.0). ExcelDataReader C: \ Users \ Admin \ source \ repos \ ExcelDataReader \ ExcelDataReader \ ExcelDataReader.csproj 1

Is it a problem with the package or is it that I am installing it the wrong way? **(I am using .NET 3.1)**

**Comment by andersnm** [comment]
Hi, Is your project also named "ExcelDataReader" by any chance? If so, can you try and rename it to "MyExcelSomethingElse"

This was the first hit for https://www.google.com/search?q=NU1108+Cycle+detected :
https://kmatyaszek.github.io/2019/05/30/nuget-nu1108-cycle-detected.html

**Comment by SpiritBob** [comment]
@iamlozano Did the above reply resolve your issue? If so, feel free to close it.
