### ISSUE TITLE
ExcelDataReder file not found error on Azure Pipelines

### ISSUE THREAD

**Issue by PriyadarshaniPatil** [ExcelDataReader/ExcelDataReader#565]
I am running Specflow tests on the pipeline with the Specflow External Data Package. It is working fine on the local machine but it is giving the following error on the Azure Pipeline. 
"Could not load file or assembly 'ExcelDataReader, Version=3.6.0.0, Culture=neutral, PublicKeyToken=93517dbe6a4012fa'. The system cannot find the file specified."
The assembly is restored and present but still build is getting failed. I have raised the same issue in the Soecflow community but not sure what's wrong with the pipeline.  
Note- the specified file is also present on the mentioned path. 

Any lead is appreciated.
Thanks!

**Comment by matt-cave** [comment]
Had an issue in an Azure function with same type of error. Could this issue be related to this?
https://stackoverflow.com/questions/65375906/epplus-system-text-encoding-codepages-dll-not-found-in-net-core-3-1-azure-func

**Comment by kazantsev-v** [comment]
Could u please try to run tests locally using "dotnet test" command. Do u have the same error?

**Comment by PriyadarshaniPatil** [comment]
Yes @kazantsev-v  I am unable to build it using dotnet build. 
but it is strange as it is running by Visual Studio Run Tests.
