### ISSUE TITLE
Error ExcelDataReaderExtension

### ISSUE THREAD

**Issue by marowar13** [ExcelDataReader/ExcelDataReader#567]
Hi,

I have etl ssis and I get the following error when executing the package where I have added the libraries ExcelDataReader and ExcelDataReader.Dataset 

Error:
could not load type ExcelDataReader.ExcelDataReaderExtensions from aseembly ExcelDataReader, Version=3.7.0.0, Culture=neutral, PublicKeyToken=93517dbe6a4012fa.

in development and testing environment it works fine but in production it doesn't

my code:

![WhatsApp Image 2021-09-13 at 11 28 59 AM](https://user-images.githubusercontent.com/25389892/133121932-4abcdd6b-5a85-4f94-95dd-4ec1d0798e5b.jpeg)

Please help me!

**Comment by appel1** [comment]
Did you include the ExcelDataReader DLLs when deploying to your production machine?

**Comment by Kdinesh13** [comment]
How to Exceldatareader to ssis package? When am adding this from nugget it is getting removed automatically

**Comment by Kdinesh13** [comment]
Hi, I'm using visual stuidio 2019 and framework is 4.8.  I have created SSIS package and installed ExcelDataReader from nugget. For some reason, script task it is not recognizing ExcelDataReader. Could someone help me please.
