### ISSUE TITLE
Reading only filtered values from sheet

### ISSUE THREAD

**Issue by miranemec** [ExcelDataReader/ExcelDataReader#568]
Hi, your work is really great and save me lots of time. Thank you very much!

Is there any chance to get only filtered rows from excel? I've been using it in other solutions and It will be very nice to do it with your nugget, to make code cleaner and nicer. 

Thank you!

**Comment by appel1** [comment]
Have you tried using ExcelDataTableConfiguration.FilterRow ?

**Comment by miranemec** [comment]
> Have you tried using ExcelDataTableConfiguration.FilterRow ?

No I didn't, I am really not sure how to use it. Could you help?

**Comment by appel1** [comment]
https://github.com/ExcelDataReader/ExcelDataReader#asdataset-configuration-options

**Comment by miranemec** [comment]
I have excel with applied filter. I need just visible rows. Not using filter in code. I have no chance to filter it via code conditions.

**Comment by miranemec** [comment]
I found [this](https://github.com/ExcelDataReader/ExcelDataReader/issues/433#issuecomment-534932066_), but it doesn't work.
```
                                            FilterRow = (rowReader) =>
                                            {
                                                return rowReader.VisibleState == "visible";
                                            }
```

**Comment by appel1** [comment]
VisibleState is for the whole sheet as the xml doc says. So your code above will exclude all rows from non-visible sheets but still create the table in the dataset. 

If you want to exclude hidden rows then you can check the IExcelDataReader.RowHeight property that is 0 for hidden rows.
