### ISSUE TITLE
Problem adding Settings file to TestApp

### ISSUE THREAD

**Issue by iluxury** [ExcelDataReader/ExcelDataReader#569]
Hi--

I want to add a Settings file to my modification of TestApp to contain a connection string.  I add an application-level setting to Settings in the project.  The Settings.Designer.cs file gets created OK.  However, there is no app.config created in the project folder. There is a Testapp.exe.config in the bin\debug folder. However, it contains no actual settings.  This is all I get:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
  </startup>
</configuration>

I have never seen a configuration behave in this way.

Any help will be appreciated.

Thanks!

**Comment by andersnm** [comment]
Hi,

The TestApp project in the repo has gone through several VS and .NET upgrades and is not intended as a starting point for new apps. It was probably created around 2010, then hacked to work with the early .NET Core tooling, and currently serves as a tool for developers to quickly test problematic files. I think you will have better luck if starting your app from a fresh Windows Forms project template designed to work with recent versions of VS.
