### ISSUE TITLE
AsDataSet convert #N/A,#Value and #Ref to DBNull

### ISSUE THREAD

**Issue by ViktorKirichenko** [ExcelDataReader/ExcelDataReader#570]
Hi,

When reading data, values such as # N / A, # Value and #Ref are converted to DBNull. How can you understand that this is not DBNull and take the cell text?

**Comment by andersnm** [comment]
Hi,

In the latest prerelease Nuget there is a `reader.GetCellError(i)` method which helps to disambiguate errors from actual null cells.

**Comment by VovaYa** [comment]
HI, iis it now possibly to know is there error or not after AsDataSet call?

**Comment by appel1** [comment]
I'm not aware of any generic way to store error state for a cell in DataSet. 

But you can use the new TransformValue callback, #486, to handle this yourself.
