### ISSUE TITLE
Unable to get Data through Web Api

### ISSUE THREAD

**Issue by chungyau97** [ExcelDataReader/ExcelDataReader#572]
Please help. 
I can get the data with the same code while doing it with WinForm but unable to get any data through Web API.

![image](https://user-images.githubusercontent.com/33013947/135975944-2001734c-f55d-4e58-96ab-431d446b74e5.png)

Thanks in advance.

**Comment by andersnm** [comment]
Sorry, but this is not a very good description of a problem. If you need help with Web API, you should refer to their documentation.
