### ISSUE TITLE
FileNotFoundException after publishing project

### ISSUE THREAD

**Issue by jasoncarr** [ExcelDataReader/ExcelDataReader#575]
Everything works fine using Visual Studio 2019 but when publishing to single file using net5.0 platform I get the following error...

System.IO.FileNotFoundException: File name: 'ExcelDataReader, Version=3.6.0.0, Culture=neutral ...'

**Comment by andersnm** [comment]
It's impossible to tell from your problem description if you made a mistake, or if there's a problem in the tooling, or if there is an actual problem in ExcelDataReader.
