### ISSUE TITLE
AsDataSet converts zero-padded number to whole number

### ISSUE THREAD

**Issue by erwinjrivera** [ExcelDataReader/ExcelDataReader#576]
In my excel file, I formatted the column as "Text"  format. The data looks  something like this:

```
  Material_Number
  000000000000000001
  000000000000000002
  000000000000000003
  000000000000000004
  000000000000000005
```

When I read the excel file using the **AsDataSet** method,  the output is being converted to a whole number. 
Is this a bug? E.g.:

```
  Material_Number
  1
  2
  3
  4
  5
```

Is there a configuration that I could use to import the data from excel as it is (without the 0 paddings being removed)?
This how  my code  looks  like:

```
if (fileExtension == ".xlsx")
                {
                    using (IExcelDataReader excelReader = ExcelReaderFactory.CreateOpenXmlReader(stream))
                    {
                        
                        return excelReader.AsDataSet(new ExcelDataSetConfiguration()
                        {
                            ConfigureDataTable = (_) => new ExcelDataTableConfiguration()
                            {
                                UseHeaderRow = true
                            }
                        });
                    }
                }
```

**Comment by andersnm** [comment]
Hi, can't tell if its a bug without a test spreadsheet to reproduce here. ExcelDataReader should not change strings like that.

We had a similar report before: https://github.com/ExcelDataReader/ExcelDataReader/issues/506#issuecomment-753316911

> It could also be that your value is physically stored as a number, but formatted with a Number Format. If you need formatted output, please refer to the "Formatting" section in the readme.
