### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by heretic13** [ExcelDataReader/ExcelDataReader#579]
1. An example of reading data from a table is poorly designed. The method of data reading is not clear.

2. Substitution of concepts.

"GetDouble(), GetInt32(), GetBoolean(), GetDateTime(), GetString() return a value from the current row cast to their respective type."

These methods get the value from the cell, not from row.

Documentation requires verification

**Comment by andersnm** [comment]
IMHO that sentence is technically correct: it tries to convey the "current row" is implicit, which is not apparent looking at the method signatures. The wording "a value" vaguely refers to the cell / column index parameter.

(I wrote that sentence and felt the need to defend against claims of "Incorrect documentation". However your input is useful to understand how it can be misunderstood. Your first point is also valid. In general I agree the documentation can be improved)
