### ISSUE TITLE
Nuget changes: ExcelDataReader organization, prefix and checkmark

### ISSUE THREAD

**Issue by andersnm** [ExcelDataReader/ExcelDataReader#581]
This is a kind of announcement, lacking any other suitable forums for communication.

I just created an organization for [ExcelDataReader on Nuget](https://www.nuget.org/profiles/ExcelDataReader) and added @Ian1971 and @wizardgsz as members. Please check your email for continued access. This is not a takeover :)

Ownership of the `ExcelDataReader` and `ExcelDataReader.DataSet` packages have been transferred to the new organization and all individual users were removed as package owners. I have not added inactive users back to the organization.

Background: A NuGet PM at Microsoft reached out and asked if we were interested in reserving an ID prefix. They suggested to create an organization before reserving the prefix, and that part is done now. The packages should get a nice checkmark real soon. The "ExcelDataReader" prefix will be public, allowing other contributors to upload packages like "ExcelDataReader.Mapping" still - although without the checkmark.

@appel1 I can add you to the organization too if you want, please let me know your username on Nuget.

**Comment by wizardgsz** [comment]
I got it, thanks a lot ;)

**Comment by appel1** [comment]
Didn't have an account before but I've created one now, username appel.

**Comment by appel1** [comment]
@andersnm Any way I can contact you so perhaps I could get access to at least clean up issued and maybe accept some pull requests?

**Comment by andersnm** [comment]
@appel1 We need @Ian1971 / @ExcelDataReader for granting repo permissions, although he hasn't been responsive for a while

**Comment by appel1** [comment]
Ok. Wasn't aware of that. We'll see if he sees this then.

**Comment by appel1** [comment]
@Ian1971 @ExcelDataReader Attempting to ping you again in case you missed the mention above.
