### ISSUE TITLE
The read data and the displayed data do not match

### ISSUE THREAD

**Issue by gchling** [ExcelDataReader/ExcelDataReader#582]
For some merge cells, The read data do not match the displayed data.
The Data like:
```
	<sheetData>
		<row r="8" spans="1:3" ht="14.5" customHeight="1" thickBot="1" x14ac:dyDescent="0.35">
			<c r="A8" s="19" t="s">
				<v>54</v>
			</c>
			<c r="B8" s="19" t="s">
				<v>15</v>
			</c>
			<c r="C8" s="1">
				<v>5</v>
			</c>
		</row>
		<row r="9" spans="1:3" ht="14.5" thickBot="1" x14ac:dyDescent="0.35">
			<c r="A9" s="26" t="s">
				<v>9</v>
			</c>
			<c r="B9" s="19"/>
			<c r="C9" s="1">
				<v>10</v>
			</c>
		</row>
	</sheetData>
	<mergeCells count="4">
		<mergeCell ref="A4:A7"/>
		<mergeCell ref="B4:B7"/>
		<mergeCell ref="A8:A11"/>
		<mergeCell ref="B8:B11"/>
	</mergeCells>
```

The A8:A11 are merged,so the excel only display A8, But A9 has some string, the read function shoud ignore the string in A9.

**Comment by andersnm** [comment]
Hi! One could argue that ExcelDataReader naively returns all the raw data in the file, and also naively returns all the merged cell ranges separately. Users of the library can then choose how to deal with merged cells: either by repeating values in merged cells, ignoring completely or ignoring all but the top-left merged cell. Ultimately ExcelDataReader has no opinions about presentation logic.

This comment links to a gist implementing a MergeCellsReader wrapper: https://github.com/ExcelDataReader/ExcelDataReader/issues/269#issuecomment-348756467
