### ISSUE TITLE
Getting .net4.5 not installed issue, but its present in my system.

### ISSUE THREAD

**Issue by ks1990cn** [ExcelDataReader/ExcelDataReader#583]
I'm Getting this error:

**Error	MSB3644	The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks**	_ExcelDataReader_	_C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	1217_

**Comment by ks1990cn** [comment]
![image](https://user-images.githubusercontent.com/29522704/145682682-1ea2a8ef-6478-44c8-9975-ac910c63c919.png)

This is installations in my control panel.

**Comment by andersnm** [comment]
Hi,

I don't know the answer to this, but surely somebody must've encountered the same problem before. Did you try to put the error message into a search engine?

**Comment by ks1990cn** [comment]
Yes i tried, but found nothing
