### ISSUE TITLE
.Net Core 3.1 - No data is available for encoding 1252

### ISSUE THREAD

**Issue by shahrukhhp1** [ExcelDataReader/ExcelDataReader#584]
**Using .Net core 3.1:**
I tried to read simple excel file using ExcelDataReader (NuGet package), while debugging I found that thread passed through reading file and getting its stream but then on following line :

`var reader = ExcelReaderFactory.CreateReader(stream,{myConfiguration or even null})`

It throws exception "No data is available for encoding 1252".

I took sample code from this repo, and executed that , it was running fine. Then I saw it was using .Net framework 4.5.
I did that too and changed my solution's framework to .Net 4.5.2, then it started working.
After some research I found out about **'System.Text.Encoding.CodePages'**, which I added in my .Net core project as well but still its giving me the same error.

My conclusion is that there is still something missing in .Net core environment that is not supporting encoding 1252.

Please have  a look.

**Comment by andersnm** [comment]
Hi,

Have a look at #445 and https://github.com/ExcelDataReader/ExcelDataReader#important-note-on-net-core

**Comment by shahrukhhp1** [comment]
Thanks @andersnm  for response, I got the reader to work. Had to call encoding in following to register it before reader.

                ```
var enc = CodePagesEncodingProvider.Instance.GetEncoding(1252);
                Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);


                using var stream = new FileStream(file, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);

                using IExcelDataReader reader = ExcelReaderFactory.CreateReader(stream);

                DataSet ds = reader.AsDataSet(new ExcelDataSetConfiguration()
                {
                    UseColumnDataType = false,
                    ConfigureDataTable = (tableReader) => new ExcelDataTableConfiguration()
                    {
                        UseHeaderRow = false
                    }
                });
```
