### ISSUE TITLE
no function

### ISSUE THREAD

**Issue by Siptrixed** [ExcelDataReader/ExcelDataReader#586]
![изображение](https://user-images.githubusercontent.com/94737852/147772889-45ae40fb-9149-453f-ac08-d0d400c4e328.png)

**Comment by andersnm** [comment]
Hi, you need to reference the ExcelDataReader.DataSet nuget package to use AsDataSet.

**Comment by Siptrixed** [comment]
Where ROWS????????????
![изображение](https://user-images.githubusercontent.com/94737852/147775220-a352b7cd-de23-417b-8a78-3366c2099898.png)
