### ISSUE TITLE
TO dictionary

### ISSUE THREAD

**Issue by mustaeenqazi** [ExcelDataReader/ExcelDataReader#589]
Hi,
Thanks for a Great excel reading library
I am new to c# and want to convert the " var result = reader.AsDataSet();" into a dictionary object. Please guide me thanks. 
Cheers,

**Comment by andersnm** [comment]
Hi,

There is no way we can offer general C# support to new programmers here. As a start and general advice, I recommend using a search engine to find if somebody had the same problem before. F.ex https://www.google.com/search?q=dataset+to+dictionary+c%23
