### ISSUE TITLE
How to read an excel file with repeated column names?

### ISSUE THREAD

**Issue by olivegarg** [ExcelDataReader/ExcelDataReader#59]
I need to read excel files with the same column names repeated several times.
DataTables will not allow repeated column headers so excelReader.AsDataSet() throws an error if the excel file has repeated column headers. Is there a way to handle this?

Thank you!

**Comment by Ian1971** [comment]
You could use the IDataReader interface, or failing that you'd have to
modify the code (or the spreadsheet).

On Mon, Mar 23, 2015 at 2:42 PM, olivegarg <notifications@github.com> wrote:

> I need to read excel files with the same column names repeated several
> times.
> DataTables will not allow repeated column headers so
> excelReader.AsDataSet() throws an error if the excel file has repeated
> column headers. Is there a way to handle this?
>
> Thank you!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/59>.
>



-- 

Ian Cox
C.T.O.

System Sync
m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.systemsyncsolutions.com
<http://www.releasemobile.com/>

Registered in England as systemsync solutions ltd.
Number: 9326325 VAT: 202729923

**Comment by wizardgsz** [comment]
Hope you found useful this enhancement: [Set Column.Caption to original read columnName (Dont hand duplcate for Caption) #103](https://github.com/ExcelDataReader/ExcelDataReader/pull/103)
