### ISSUE TITLE
Ver 3.6  - "End of Central Directory record could not be found"

### ISSUE THREAD

**Issue by TecumStricto** [ExcelDataReader/ExcelDataReader#593]
This is a Blazor app, using .NET Core 6.0 (6.0.2), under VS2022.

Using code mentioned bellow, code fails on line   using (var excelReader = ExcelReaderFactory.CreateReader (memoryStream)), with 
error "End of Central Directory record could not be found".

Using ver 3.4.2 there is no such error, I got different one: "Array dimensions exceeded supported range".

----------------- code --------------------
 private async Task<DataTable> ReadExcel(IBrowserFile file, string ExcelSheet)
    {
        string sError = "OK";
        DataSet dsRresult = null;
        try
        {
            var buffers = new byte[file.Size];
            await file.OpenReadStream().ReadAsync(buffers);
           using (System.IO.MemoryStream memoryStream = new System.IO.MemoryStream(buffers))
           {
-->                using (var excelReader = ExcelReaderFactory.CreateReader (memoryStream))     <---
                {

                    dsRresult = excelReader.AsDataSet(new ExcelDataSetConfiguration()
                        {
                            ConfigureDataTable = (tableReader) => new ExcelDataTableConfiguration()
                            {
                                UseHeaderRow = true
                            }

                        });
...
-------------------------------------------------

**Comment by andersnm** [comment]
Hi,

It would help to see the stack traces and the excel file. Can't do anything but search for your error messages in a search engine:

"End of Central Directory record could not be found" <- your file or stream is broken/in an unexpected state

"Array dimensions exceeded supported range" <- cannot allocate arrays that big

Don't use the intermediate byte array to copy from the `file` stream to the memory stream. Refer to `Stream.CopyTo`: https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.copyto?view=net-6.0. Also make sure to "rewind" the stream afterwards, `Stream.Seek`: https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.seek?view=net-6.0

**Comment by TecumStricto** [comment]
Hi,


There is a stack trace, screen shot, as well a .xlsx file.

![image](https://user-images.githubusercontent.com/43401050/156162174-18fb8650-2e72-42ff-92b1-f582a309da20.png)
[Demo_podaci_Faros_FAR_DZELEZNIK749007441.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/8161214/Demo_podaci_Faros_FAR_DZELEZNIK749007441.xlsx)

Full source for method, .NET 6.0.2, Blazor server app + Radzen.

private async Task<DataTable> ReadExcel(IBrowserFile file, string ExcelSheet)
    {
        string sError = "OK";
        DataSet dsRresult = null;
        try
        {
            var buffers = new byte[file.Size];
            await file.OpenReadStream().ReadAsync(buffers);
           using (System.IO.MemoryStream memoryStream = new System.IO.MemoryStream(buffers))
           {
                using (var excelReader = ExcelReaderFactory.CreateReader (memoryStream))
                {

                    dsRresult = excelReader.AsDataSet(new ExcelDataSetConfiguration()
                        {
                            ConfigureDataTable = (tableReader) => new ExcelDataTableConfiguration()
                            {
                                UseHeaderRow = true
                            }

                        });

                    for (int h = 0; h < dsRresult.Tables[ExcelSheet].Rows.Count; h++)
                    {

                        if (string.IsNullOrEmpty(dsRresult.Tables[ExcelSheet].Rows[h][1].ToString()))
                        {
                            dsRresult.Tables[ExcelSheet].Rows[h].Delete();
                        }
                    }
                }
            }
            return dsRresult.Tables[ExcelSheet];
        }
        catch (Exception ex)
        {
            Log.Error(ex, "ReadExcel()");
            NotificationMessage message = new NotificationMessage()
            {
                Severity = NotificationSeverity.Error,
                Summary = "Exception() + ReadExcel()",
                Detail = ex.Message + " -  inner ex:" + ex.InnerException + " - stack trace:" + ex.StackTrace,
                Duration = 20000
            };
            sError = ex.Message;
            ShowNotification(message);
            return null;
        }
    }

**Comment by andersnm** [comment]
Hi,

You're really asking for general support on ASP.NET/Blazor file uploads and .NET streams. It's outside the scope of this project, but do refer to my comments about using CopyTo and Seek. Pretty sure the problem relates to the stream initialization.

I recommend to take a step back and learn how streams work. Perhaps write a small console app and try to load Excel files from both FileStream and MemoryStream instances. That would be an excellent exercise for getting a feeling about both streams and ExcelDataReader. Then you can move on to integrating with file uploads in ASP.NET/Blazor which uses streams too (same interface, different implementation, works similarly).
