### ISSUE TITLE
ExcelDataReader on Docker

### ISSUE THREAD

**Issue by ollih1980** [ExcelDataReader/ExcelDataReader#599]
Hello Community,

I've an issue with ExcelDataReader on Docker (Debain). When I try to load a xlsb File I'm not getting the actual column names. At least not all of them. Some I got some gets replaced with e.g. Column0, Column1 etc.
I'm using .NET 6.
I've added the the package System.Text.Encoding.CodePages and included `System.Text.Encoding.CodePages`

Any idea what I'm doing wrong?

**Comment by andersnm** [comment]
If you are reporting an issue it is really useful if you can supply an example Excel file as this makes debugging much easier and without it we may not be able to resolve any problems.
