### ISSUE TITLE
Default name for columns with no name

### ISSUE THREAD

**Issue by Ian1971** [ExcelDataReader/ExcelDataReader#6]
migrated from codeplex https://exceldatareader.codeplex.com/workitem/12857

"I have a .xlsx file where only some of the columns in row 1 has names. The columns with no name is automatically named 'Column?' (This is both Caption and ColumnName).
I have previously used Excel by opening as a database via oledb and where these columns were automatically named 'F?'. No I have a backward compatibility problem because of this.
This is giving me problems as I do not feel I can just rename Column? to F? because I cannot seem to differentiate between a column actually named Column2 and one which was internally named Column2 because no name is specified in the spreadsheet.

So basically I have two questions;
Is is possible to change the default behavior of this auto naming of columns with no name? Basically exchange 'Column' with 'F'
Or is possible to tell if column didn't actually have a name (was blank). Then I can write the logic myself.
Thanks in advance :)

Ok, after reading the documentation I created a patch with the id; 16126. Hopefully it will accepted as my issue is now resolved by it.

REVIEW patch and apply if appropriate"

"
bleze wrote Apr 4 at 10:23 AM

It turns out that this patch is not enough to get the correct behavior. 

The column index starts at 0 and I need it to start at 1. 

I've found 3 places in the code where the column name is handled; 

Helpers.AddColumnHandleDuplicate(table, string.Concat(COLUMN, i)); 

I've added a backward compatible bool setting for changing this index behavior. Attached is rev. 2 of the patch.
"
[DefaultColumnName-rev2.patch | uploaded via ZenHub](https://www.zenhub.io/files/53e09e017511cda6220048fc)

**Comment by andersnm** [comment]
This works now:
```C#
reader.AsDataSet(new ExcelDataSetConfiguration()
{
    ConfigureDataTable = (_) => new ExcelDataTableConfiguration()
    {
        UseHeaderRow = true,
        EmptyColumnNamePrefix = "F"
    }
});
```

The blank column headers would be named F? instead Column?. DataColumn.Caption is currently set to the string representation of the original header without the prefix. That must've been fixed since the original report.
