### ISSUE TITLE
Excel Reader Factory  gives  Error

### ISSUE THREAD

**Issue by Amy353** [ExcelDataReader/ExcelDataReader#600]
ExcelReaderFactory.CreateReader(stream); gives error  following:

System.NotSupportedException: 'No data is available for encoding 1252. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.'

**Comment by AEIsmason** [comment]
Okay for .Net Core 6 this worked for me:

**using System.Text;**

Then in Program.cs I added:

**Encoding.RegisterProvider(CodePagesEncodingProvider.Instance)**
