### ISSUE TITLE
Can`t Read Array formula Data

### ISSUE THREAD

**Issue by kakukaku86** [ExcelDataReader/ExcelDataReader#601]
Dear Guys.
I've been using it well this ExcelDataReade Thank.

Anyway while using this library, i identified one issue.
When reading 'Array formula Data'  type of data, it is read as DBNULL.
* ex - {=SUM(LEN(range))}
* ex - {=IF(SUM(CG9:CJ9)=0,"",INDEX(IF(D9="TEST",TEST!U:U,TEST!T:T),MATCH(TEST!M9&VLOOKUP(TEST!N9,TEST!$E$11:$Z$242))}
* more Type Info - https://exceljet.net/glossary/array-formula

There seems to be a problem with not being able to read '{}'keywords(Array).
Is there a way to change the settings and read them?

Thank you in advance for your excellent knowledge and reply.

**Comment by andersnm** [comment]
Hi,

ExcelDataReader is not parsing and calculating any formulas, just reading the precalculated values stored in the file. 

If you get a DBNULL, there is likely no value in the file, i.e the formula was likely not calculated by the authoring program. F.ex if the Excel file was created by a library and not by Excel itself. But need to look at the file to confirm.

**Comment by kakukaku86** [comment]
First of all, I'm sorry for the late reply.
The information you gave me is correct.
I'll check if I can bypass the problematic part.
