### ISSUE TITLE
.xlsb not all shared strings being read (being set to null instead)

### ISSUE THREAD

**Issue by rjlyon** [ExcelDataReader/ExcelDataReader#602]
I cannot share the document in question, but I have a .xlsb file where it reads around 500 shared strings instead of the 3917 in the sharedStrings file. I cannot replicate this issue outside of the file that isn't working for me.

It appears that in `BiffReader.cs`, when reading the stream it returns null if the bytes read are not the same as the bytes requested. However, this can be expected behaviour according to the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=net-6.0).

If `public override Record? Read()` has the stream reading modified it fixes this issue:
Change
```csharp
byte[] buffer = recordLength < _buffer.Length ? _buffer : new byte[recordLength];
if (Stream.Read(buffer, 0, (int)recordLength) != recordLength)
    return null;
```
To
```csharp
byte[] buffer = recordLength < _buffer.Length ? _buffer : new byte[recordLength];
int numBytesToRead = (int)recordLength;
int numBytesRead = 0;
do
{
    int n = Stream.Read(buffer, numBytesRead, numBytesToRead);
    numBytesRead += n;
    numBytesToRead -= n;
} while(numBytesToRead > 0);
```

I will look to create a PR for this issue

**Comment by appel1** [comment]
Please reopen if https://github.com/ExcelDataReader/ExcelDataReader/commit/f4d4828ce588a9430c7f14300a1173918f4defad didn't fix this.
