### ISSUE TITLE
Wrong return value when read from function cell 

### ISSUE THREAD

**Issue by duyngepi** [ExcelDataReader/ExcelDataReader#604]
My excel has a function cell, the next cell's value is the sum of the preceding value + 0.1

![image](https://user-images.githubusercontent.com/61035588/182760659-5ebb9e6a-b699-4d4c-9038-eb9013f4251d.png)

and here is the result

![image](https://user-images.githubusercontent.com/61035588/182760779-c0c4dfff-9e0f-4a0e-90b2-990e0fb2e60f.png)

**Comment by appel1** [comment]
See https://github.com/ExcelDataReader/ExcelDataReader/issues/495#issuecomment-715906231
