### ISSUE TITLE
Parsing Integers

### ISSUE THREAD

**Issue by jim108dev** [ExcelDataReader/ExcelDataReader#606]
Thank you for providing the library. I have a question concerning the number format.
If I put integer numbers into an excel cell like
```
A        B 
Int      1
``` 
and read the xlsx file, the resulting field type of B is double. That's a feature, right? If I would like integers to be parsed. I have to check every double field of the reader afterwards and parse it analogous to #47 ?

**Comment by appel1** [comment]
Excel only ever stores doubles. But if you know it is an integer you can cast the double to int without any loss of precision in most cases.
