### ISSUE TITLE
 NU1108: Cycle detected error while installing ExcelDataReader package in VS 2022

### ISSUE THREAD

**Issue by manish-are** [ExcelDataReader/ExcelDataReader#607]
I am trying to install ExcelDataReader in VS 2022 and getting below error.
Install-Package : NU1108: Cycle detected. 
  ExcelDataReader -> ExcelDataReader (>= 3.6.0).
At line:1 char:1
+ Install-Package ExcelDataReader
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'ExcelDataReader'.
At line:1 char:1
+ Install-Package ExcelDataReader
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by andersnm** [comment]
Are you trying to add ExcelDataReader to a project of your own which is also named "ExcelDataReader"?

**Comment by manish-are** [comment]
yes, now I changed the project name and issue solved. Thanks!!
