### ISSUE TITLE
ExcelReaderFactory.CreateReader() throws "System.ArgumentNullException: Value cannot be null. (Parameter 's')."

### ISSUE THREAD

**Issue by mathias-ho** [ExcelDataReader/ExcelDataReader#608]
I'm having a problem with some Excel files from an external source (generated by SAP I guess). When executing ```ExcelReaderFactory.CreateReader()``` it results in ```System.ArgumentNullException: Value cannot be null. (Parameter 's')```.

```csharp
...
            using (FileStream fileStream = new FileStream(excelFilePath, FileMode.Open, FileAccess.Read))
            {
                using (MemoryStream memoryStream = new MemoryStream())
                {
                    fileStream.CopyTo(memoryStream);
                    using (var excelReader = ExcelReaderFactory.CreateReader(memoryStream))
                    {
...
```

So I replaced the ExcelDataReader package with the source code (v3.6.0) and did some debugging to find out the cause. The reason is the missing width attribute for the third col element when parsing the first worksheet:

OpenXML of the problematic Excel file:
xl\worksheets\sheet1.xml
```xml
...
	<cols>
		<col min="1" max="1" width="3.0000000000000000E+00" hidden="true" customWidth="true"/>
		<col min="2" max="2" width="1.2410937500000000E+02" customWidth="true"/>
		<col min="3" max="16384" hidden="1"/>
	</cols>
...
```

Error is caused by:

ExcelDataReader.Core.OpenXmlFormat.XlsxWorksheet
```csharp
private XlsxCols ReadCols(XmlReader xmlReader)
{
...
while (!xmlReader.EOF)
            {
                if (xmlReader.IsStartElement(NCol, NsSpreadsheetMl))
                {
                    var min = xmlReader.GetAttribute(AMin);
                    var max = xmlReader.GetAttribute(AMax);
                    var width = xmlReader.GetAttribute(AWidth);
                    var customWidth = xmlReader.GetAttribute(ACustomWidth);
                    var hidden = xmlReader.GetAttribute(AHidden);

                    var maxVal = int.Parse(max);
                    var minVal = int.Parse(min);
                    var widthVal = double.Parse(width, CultureInfo.InvariantCulture);
...
}
```

```width``` is null which results in ```System.ArgumentNullException: Value cannot be null. (Parameter 's')``` at ```double.Parse()```.

I couldn't find any OpenXml specification which states if the ```width``` attribute is mandatory or not.

However replacing the line
```csharp
                    var widthVal = double.Parse(width, CultureInfo.InvariantCulture);
```
with
```csharp
                    double.TryParse(width, NumberStyles.Float, CultureInfo.InvariantCulture, out double widthVal);
```
would fix the error for me.

Finally my question is if the Excel file invalid or if this kind of error should be handled by ExcelDataReader?

**Comment by andersnm** [comment]
Hi, looks like a bug! If the file opens in Excel it should also work in ExcelDataReader

**Comment by mathias-ho** [comment]
Test document:
[issues-608-test.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/10131971/issues-608-test.xlsx)

**Comment by appel1** [comment]
Thank you.
