### ISSUE TITLE
ExcelReaderFactory.CreateReader  error - index out of range

### ISSUE THREAD

**Issue by sosilv** [ExcelDataReader/ExcelDataReader#609]
Got 
{"Index was out of range. Must be non-negative and less than the size of the collection.\r\nParameter name: startIndex"}
reading attached xls
[FD072AW.xls](https://github.com/ExcelDataReader/ExcelDataReader/files/9576895/FD072AW.xls)

  DataTable dt = new DataTable();
            using (var stream = File.Open(FilePathViaggi, FileMode.Open, FileAccess.Read))
            {
                
                using (var reader = ExcelDataReader.ExcelReaderFactory.CreateReader(stream)) //-->ERROR
                {                

                    var _result = reader.AsDataSet(new ExcelDataSetConfiguration()
                    {
                        ConfigureDataTable = (_) => new ExcelDataTableConfiguration()
                        {
                            UseHeaderRow = true,
                            ReadHeaderRow = (rowReader) =>{
                                for (int ix = 0; ix < 15; ix++)
                                { rowReader.Read(); }
                            }

                        }
                    });
                    // The result of each spreadsheet is in result.Tables

                    dt = _result.Tables[0];
                }
            }

**Comment by appel1** [comment]
The file contains an empty 0x000 (biff2 DIMENSIONS) record. I'm not sure if that is the correct record id but I think we can solve this particular case by ensuring that we don't attempt to read such records unless they contain enough data to be read as a DIMENSIONS record.
