### ISSUE TITLE
can't not read excel2013 file?

### ISSUE THREAD

**Issue by gatspy** [ExcelDataReader/ExcelDataReader#61]
i create excel file with excel2013, read this file in my solution.get error.
Cannot find central directory--ICSharpCode.SharpZipLib
visual studio 2013,.netframewrok 4.0
install exceldatareader with nuget,the version is 2.1.2.3

**Comment by Ian1971** [comment]
Try the version in develop branch

**Comment by fredrik-lundin** [comment]
This exact problem happend to me when trying to read a .xls file as .xlsx file. If that is you problem, take a look at this part of the docs:

//1. Reading from a binary Excel file ('97-2003 format; *.xls)
IExcelDataReader excelReader = ExcelReaderFactory.CreateBinaryReader(stream);

//2. Reading from a OpenXml Excel file (2007 format; *.xlsx)
IExcelDataReader excelReader = ExcelReaderFactory.CreateOpenXmlReader(stream);

**Comment by gandarez** [comment]
Thanks that worked like a charm.
