### ISSUE TITLE
Read muliple DataTables from one sheet

### ISSUE THREAD

**Issue by Insane96** [ExcelDataReader/ExcelDataReader#612]
Is it possible to read multiple tables from a single Sheet into a DataSet?

| Table1Col1  | Table1Col2  |
|-------------|-------------|
| Table1Data1 | Table1Data2 |
|             |             |
| Table2Col1  | Table2Col2  |
| Table2Data1 | Table2Data2 |

This should result as two DataTables

**Comment by andersnm** [comment]
Possible? Yes, but you have to implement it yourself using the reader APIs.
