### ISSUE TITLE
Adding features

### ISSUE THREAD

**Issue by Kavignon** [ExcelDataReader/ExcelDataReader#62]
I've started looking through this library and I'm thinking that either I'd fork it and provide a data reader for microsoft word and power point or the library could directly be incremented with those features.
I'm just thinking out loud and would like some insight about this !

Thanks for the time you're taking to answer my query !

**Comment by FuchsiaSoft** [comment]
I was thinking the same actually... I need a general purpose office doc
format reader. I'm happy to collaborate if you like.

**Comment by Kavignon** [comment]
I'm going to continue looking though the library this week-end.
What I can do is keep you update here on which office technology I'm going to do and I'll either fork the project or do a pull request to increment it here.
