### ISSUE TITLE
Cannot read data from specific XLS file

### ISSUE THREAD

**Issue by slosa13** [ExcelDataReader/ExcelDataReader#624]
Dear authors,

i have to read data from a stream of an XLS file like this: 
[example.XLS](https://github.com/ExcelDataReader/ExcelDataReader/files/10227159/example.XLS)

I am using ExcelDataReader 3.6.0 to create a DataTable out of a stream:
```
private static DataTable GetData(Microsoft.AspNetCore.Http.IFormFile someFile)
{
   using Stream stream = someFile.OpenReadStream();
   IExcelDataReader? reader = ExcelReaderFactory.CreateBinaryReader(stream);
   DataSet dataSet = reader.AsDataSet();
   DataTable dataTable = dataSet.Tables.Cast<DataTable>().First();

   return dataTable;
}
```

In this way the resulting DataTable is empty. I have also tried to use `ExcelReaderFactory.CreateReader(stream);` but received the same result.
After opening the XLS file with Microsoft Office 365 (Version 2108 - Build 14326.21200), hitting the save button and closing it, I receive a DataTable with all the cells of the excel file. Here is the working file after saving (without changing anything): 
[example_after_saving.XLS](https://github.com/ExcelDataReader/ExcelDataReader/files/10227163/example_after_saving.XLS)

Converting the file to XLSX (via Excel) without changing the content of the file works as well.

Unfortunately I am not able to change the incoming XLS file I have to process. I also thought of using e.g. `Microsoft.Office.Interop.Excel` to open the file and save it as XLSX. But this does not seem to work with streams and I would like to keep the current logic of my program and avoid saving files to disk.

Maybe you have got a suggestion for me on how to process these kind of XLS files.

Thank you!
Patrik

**Comment by appel1** [comment]
Thank you for the sample file. 

Looks like the worksheet is missing the expected BOF record. Possibly we can ignore this.

**Comment by slosa13** [comment]
Thank you very much for solving my problem!
Do you already know when version 3.7 is going to be published?

**Comment by appel1** [comment]
No, but I'll try to do a new prerelease soon.
