### ISSUE TITLE
Cannot read data from a specific Xlsx file.

### ISSUE THREAD

**Issue by maa263** [ExcelDataReader/ExcelDataReader#629]
Hi,
I have an issue with a xlsx file when reading data from a stream.
the file: [executions.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/10822871/executions.xlsx)

I get the following Error Message: 
![2023-02-23 15_45_56-WPA Tram (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/126239535/221148691-044a361f-db8a-4d77-b507-b653a377da1a.png)

The code:
            reader = ExcelReaderFactory.CreateReader(data);
 
I have tried using the CreateBinaryReader; however, that also does not work.

If I open the file once and save it the error does not occur anymore. Unfortunately I am unable to change the incoming XLSX file I have to process. 

Do you have any idea what can be done to process this type of file the first time?

Best,

Marie

**Comment by appel1** [comment]
Looks like that file doesn't follow the standard pattern of putting workbook and worksheet xml in a xl subdirectory. 

To fix this the the paths must be retrieved from [Content_Types].xml if they are specified there.

**Comment by maa263** [comment]
Thank you for your response. Do you have an example how one would do that?
[Content_Types].xml does contains paths; however, I'm not sure how to access and create stream with them.

**Comment by appel1** [comment]
It's a bug, oversight, in ExcelDataReader. It was mostly a note to myself or someone else who want to fix it.
