### ISSUE TITLE
Cannot find table 0

### ISSUE THREAD

**Issue by seadb** [ExcelDataReader/ExcelDataReader#63]
Hi I'm getting an error with ExcelDataReader
I have two versions of a file, one is pulled from a database and modified and one is not modified.
I am using the following syntax to access the first sheet in the file:

                DataTable table = result.Tables[0];

When I use the modified file I can access it just fine. 

 However whenever I upload the unmodified file it tells me:

    A first chance exception of type 'System.IndexOutOfRangeException' occurred in System.Data.dll
    Additional information: Cannot find table 0."

I'm not sure what the error is as the file I'm uploading contains the same information.

**Comment by Ian1971** [comment]
Where did the original one come from? Which version of excel?

On Tue, Apr 14, 2015 at 11:27 PM, chelsea <notifications@github.com> wrote:

> Hi I'm getting an error with ExcelDataReader
> I have two versions of a file, one is modified and one is not modified.
> I am using the following syntax to access the first sheet in the file:
>
>             DataTable table = result.Tables[0];
>
> When I use the modified file I can access it just fine.
>
> However whenever I upload the unmodified file it tells me:
>
> A first chance exception of type 'System.IndexOutOfRangeException' occurred in System.Data.dll
> Additional information: Cannot find table 0."
>
> I'm not sure what the error is as the file I'm uploading contains the same
> information.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/63>.
>



-- 

Ian Cox
C.T.O.

System Sync
m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.systemsyncsolutions.com
<http://www.releasemobile.com/>

Registered in England as systemsync solutions ltd.
Number: 9326325 VAT: 202729923

**Comment by bridsonc** [comment]
Im not sure which version of excel created the file as it gets
autogenerated by some script that I didnt run.  Is there a way I can check
the file itself?

**Comment by Ian1971** [comment]
I think your best bet would be download the source and try and debug it. It
sounds like there is something in the original file that ExcelDataReader
does not expect (which doesn't mean it isn't a valid excel file - it just
might be unusual).

On Wed, Apr 15, 2015 at 11:25 AM, chelsea <notifications@github.com> wrote:

> Im not sure which version of excel created the file as it gets
> autogenerated by some script that I didnt run. Is there a way I can check
> the file itself?
> On Apr 15, 2015 5:02 AM, "Ian1971" <notifications@github.com> wrote:
>
> > Where did the original one come from? Which version of excel?
> >
> > On Tue, Apr 14, 2015 at 11:27 PM, chelsea <notifications@github.com>
> > wrote:
> >
> > > Hi I'm getting an error with ExcelDataReader
> > > I have two versions of a file, one is modified and one is not modified.
> > > I am using the following syntax to access the first sheet in the file:
> > >
> > > DataTable table = result.Tables[0];
> > >
> > > When I use the modified file I can access it just fine.
> > >
> > > However whenever I upload the unmodified file it tells me:
> > >
> > > A first chance exception of type 'System.IndexOutOfRangeException'
> > occurred in System.Data.dll
> > > Additional information: Cannot find table 0."
> > >
> > > I'm not sure what the error is as the file I'm uploading contains the
> > same
> > > information.
> > >
> > > --
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/ExcelDataReader/ExcelDataReader/issues/63>.
> > >
> >
> >
> >
> > --
> >
> > Ian Cox
> > C.T.O.
> >
> > System Sync
> > m: Matrix Studios, 91 Peterborough Road, London, SW6 3BU
> > w: http://www.systemsyncsolutions.com
> > <http://www.releasemobile.com/>
> >
> > Registered in England as systemsync solutions ltd.
> > Number: 9326325 VAT: 202729923
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ExcelDataReader/ExcelDataReader/issues/63#issuecomment-93272079
> >
>
> > .
> >
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/63#issuecomment-93308414>
> .
>



-- 

Ian Cox
C.T.O.

Release  Mobile

m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.releasemobile.com

Registered in England.  Number 06323661

**Comment by bridsonc** [comment]
The source of excel data reader?

**Comment by Ian1971** [comment]
yes. Is it xls or xlsx?

On Wed, Apr 15, 2015 at 11:35 AM, chelsea <notifications@github.com> wrote:

> The source of excel data reader?
> On Apr 15, 2015 6:32 AM, "Ian1971" <notifications@github.com> wrote:
>
> > I think your best bet would be download the source and try and debug it.
> It
> > sounds like there is something in the original file that ExcelDataReader
> > does not expect (which doesn't mean it isn't a valid excel file - it just
> > might be unusual).
> >
> > On Wed, Apr 15, 2015 at 11:25 AM, chelsea <notifications@github.com>
> > wrote:
> >
> > > Im not sure which version of excel created the file as it gets
> > > autogenerated by some script that I didnt run. Is there a way I can
> check
> > > the file itself?
> > > On Apr 15, 2015 5:02 AM, "Ian1971" <notifications@github.com> wrote:
> > >
> > > > Where did the original one come from? Which version of excel?
> > > >
> > > > On Tue, Apr 14, 2015 at 11:27 PM, chelsea <notifications@github.com>
> > > > wrote:
> > > >
> > > > > Hi I'm getting an error with ExcelDataReader
> > > > > I have two versions of a file, one is modified and one is not
> > modified.
> > > > > I am using the following syntax to access the first sheet in the
> > file:
> > > > >
> > > > > DataTable table = result.Tables[0];
> > > > >
> > > > > When I use the modified file I can access it just fine.
> > > > >
> > > > > However whenever I upload the unmodified file it tells me:
> > > > >
> > > > > A first chance exception of type 'System.IndexOutOfRangeException'
> > > > occurred in System.Data.dll
> > > > > Additional information: Cannot find table 0."
> > > > >
> > > > > I'm not sure what the error is as the file I'm uploading contains
> the
> > > > same
> > > > > information.
> > > > >
> > > > > --
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/ExcelDataReader/ExcelDataReader/issues/63>.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > >
> > > > Ian Cox
> > > > C.T.O.
> > > >
> > > > System Sync
> > > > m: Matrix Studios, 91 Peterborough Road, London, SW6 3BU
> > > > w: http://www.systemsyncsolutions.com
> > > > <http://www.releasemobile.com/>
> > > >
> > > > Registered in England as systemsync solutions ltd.
> > > > Number: 9326325 VAT: 202729923
> > > >
> > > > --
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/ExcelDataReader/ExcelDataReader/issues/63#issuecomment-93272079
> > > >
> > >
> > > > .
> > > >
> > >
> > > --
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/ExcelDataReader/ExcelDataReader/issues/63#issuecomment-93308414
> > >
> > > .
> > >
> >
> >
> >
> > --
> >
> > Ian Cox
> > C.T.O.
> >
> > Release Mobile
> >
> > m: Matrix Studios, 91 Peterborough Road, London, SW6 3BU
> > w: http://www.releasemobile.com
> >
> > Registered in England. Number 06323661
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ExcelDataReader/ExcelDataReader/issues/63#issuecomment-93312772
> >
>
> > .
> >
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/63#issuecomment-93314893>
> .
>



-- 

Ian Cox
C.T.O.

Release  Mobile

m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.releasemobile.com

Registered in England.  Number 06323661

**Comment by bridsonc** [comment]
Xls

**Comment by bridsonc** [comment]
I have ExcelDataReader open and I've been using "TestApp" as my start up project.

However, whenever I start debugging, select a file, and hit process, nothing happens.  Am I trying to go about this correctly?

**Comment by bridsonc** [comment]
I figured out the row that is causing the error because I when I delete it I no longer have the problem.   Would you like me to email the file to you?  It might help debug the ExcelDataReader.  I'm trying to debug it but I don't really know the code-base or how to debug it.

**Comment by Ian1971** [comment]
I wish I had time to help, but I am super busy.

On Thu, Apr 16, 2015 at 2:05 PM, chelsea <notifications@github.com> wrote:

> I figured out the row that is causing the error because I when I delete it
> I no longer have the problem. Would you like me to email the file to you?
> It might help debug the ExcelDataReader. I'm trying to debug it but I don't
> really know the code-base or how to debug it.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/63#issuecomment-93729306>
> .
>



-- 

Ian Cox
C.T.O.

Release  Mobile

m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.releasemobile.com

Registered in England.  Number 06323661

**Comment by bridsonc** [comment]
That's okay, thanks anyways
