### ISSUE TITLE
How to ignore blank columns and EXCEL header names on the left

### ISSUE THREAD

**Issue by FreeVB** [ExcelDataReader/ExcelDataReader#632]
![无标题1](https://user-images.githubusercontent.com/30093956/226567156-6c67e528-fc82-45f0-b15a-a16fe283f9d8.png)

As shown in the screenshot above,

How do I ignore the blank column and EXCEL header name on the left and correctly read the following data?

**Comment by appel1** [comment]
Perhaps you can use the FilterRow and FilterColumn callbacks. 

https://github.com/ExcelDataReader/ExcelDataReader#asdataset-configuration-options
