### ISSUE TITLE
Question about security of the library

### ISSUE THREAD

**Issue by ItSkary** [ExcelDataReader/ExcelDataReader#633]
As stated in the title mine is not an issue related to the library but rather a question about its security. 

I need to parse many Excel (xlsx) from untrusted source, in an ASP.NET application, as other people suggested to me, a good idea should be access only data inside the XML file of the Excel checking those XML against the proper schema before. 

I expect that libraries as this one already do that (or can be configured to do that), so i have not to reinvent the wheel. But because i don't know this library in detail, i would ask to this community if i can safely use this tool even to parse untrusted Excel (xlsx); or if not by default, if there are any best practice to follow to achieve my goal (security).

Thank in advance for help. 
Best regards.

**Comment by appel1** [comment]
I can't make any guarantees but ExcelDataReader only reads raw data from Excel files and does not attempt to evaluate even formulas. So it should be safe enough.
