### ISSUE TITLE
Biff12  BrtCellRString

### ISSUE THREAD

**Issue by asheinkin** [ExcelDataReader/ExcelDataReader#635]
Hi!

Please add support for the type **BrtCellRString** record (sections 2.4.327  BrtCellRString, 2.5.121 RichStr of the [MS-XLSB].pdf manual)
Found in the clipboard, not in the files

================
BiffWorksheetReader.cs: 

                    case String:
                    case FormulaString:
                    {
                        // Must be less than 32768 characters
                        var length = GetDWord(buffer, 8);
                        return ReadCell(GetString(buffer, 8 + 4, length));
                    }
                    case 62  /* BrtCellRString */ :                    
                    {               
                        // The number of Unicode characters MUST be less than or equal to 0x7FFF         
                        var length = GetDWord(buffer, 9);
                        return ReadCell(GetString(buffer, 9 + 4, length));
                    }

**Comment by appel1** [comment]
Can you provide a sample file for use as test input?

**Comment by asheinkin** [comment]
Hi Johan!

The file is saved from the clipboard viewer.
Excel 2016 has been used, 2010 with the same result.

Best regards,
Alexey .


[image: image.png]

**Comment by appel1** [comment]
@asheinkin Looks like the file didn't get attached properly or was filtered out by github. Can you try again?
