### ISSUE TITLE
Cannot Read .xlsb file in .NET 7

### ISSUE THREAD

**Issue by rvdingDev** [ExcelDataReader/ExcelDataReader#637]
Hello.
I am currently using the trial version of ExcelDataReader in order to read .xlsb files.
In the .NET Framework, reading .xlsb files is well supported, and no errors are seen in the .NET 7.0. However, data is not being properly read within the 'Watch' in the .NET 7.0.
I need help with this part.

I tried to create a reader object using CreateReader() and, made it as DataSet. I also tried to read one line at a time through Read() and read the value through GetValue(). But I can't get it to read properly.
If anything you can do to solve this problem in your current environment, I would greatly appreciate.

Thank you.

**Comment by appel1** [comment]
Do you get any exception or in what way does it not work?

**Comment by rvdingDev** [comment]
No exceptions occur.
However, when reading with DataSet or using the Read() method, the number of rows in the sheet is properly imported, but the values corresponding to the cells that should exist in the row are read as DBNull values and the number of columns is properly imported, but column names are not properly read and Column1 and Column2 are generated.

**Comment by appel1** [comment]
Could you provide me with a sample .xlsb file that reproduces this issue? The .xlsb files I've tried works with .NET 7.0. 

Does .xlsx files in Korean work for you?

**Comment by rvdingDev** [comment]
![image](https://github.com/ExcelDataReader/ExcelDataReader/assets/34082253/e16fcc45-23b1-4a61-85f8-3a1ec4891734)
I will attach a picture.  
The sheet is entirely in English.
The data 'PC101' is a calculated value from a referenced formula, and that value appears correctly.
However, cells consisting of strings are replaced with 'DBNull'. 
I can't send the file, but I think I have found the reason it's not working.
Our data file has multiple sheets and many file references, sheet references, and table references. 
When I delete the sheets related to the references and clear the formula values connected to the references, the data appears correctly.

It seems like the references are causing the issue. Is there any solution?

**Comment by rvdingDev** [comment]
I wanted to make a test file, but if I made the file myself, it worked really well. But the object is created as an OpenXmlReader object and is read.

I can't give you the file because the data is prohibited from leaking.
Files are contain many sheet references, file references, and column references in the company excel file. 
But I'll show you the results of UnitTest.
![image](https://github.com/ExcelDataReader/ExcelDataReader/assets/34082253/70b39dc8-a83b-48ce-8060-988d87744f1e)


I am importing the sheet called '#TargetDefine' in the .xlsb file, but the sheet is all written in English and there are no empty cells, and the column 'PatentName' is written in a formula, so I think it comes out properly. String is not working.

 
I tried cloned and debugged the repository.
The .xlsb file is created as an OpenXmlReader object without being read to the BinaryReader() method through the CreateReader() method, so the AsDataTable method itself.Value is null when proceeding GetValue(i)...

I'm not sure what to do.

**Comment by rvdingDev** [comment]
I'm trying to create a test file for replication, but it's not going well. 
It seems like there are certain conditions that make it difficult.

**Comment by PanosKousidis** [comment]
I ran into the same issue and traced it down to the breaking change introduced in .NET 6: https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams
The DeflateStream behaves differently now as it is more similar to the way the standard streams work. 
I created the PR above that solves this issue - I wasn't able to produce a simple file with the problem, as the one I was using was pretty complex. But I think it happens when the sheet has a lot of data (my example had 81 rows 255 columns and it was only loading a few), due to the fact that the DeflateStream in BiffReader.cs returns less data than expected even if the stream is not finished

**Comment by appel1** [comment]
Thanks. 

I thought I had fixed this as part of #621 but obviously it was not a complete fix. 

Can ReadAtLeast be used here too?

**Comment by PanosKousidis** [comment]
Nice, it looks like you already addressed this issue but missed this bit. ReadAtLeast seems to be doing the job as well so that simplified the PR a lot

**Comment by rvdingDev** [comment]
@PanosKousidis, 
Thank you for providing additional comments.

**Comment by rvdingDev** [comment]
I'm sorry. I pressed the wrong button.

**Comment by joydeep19** [comment]
Is this big fixed,still I am facing this issue.

**Comment by appel1** [comment]
> Is this bug fixed,still I am facing this issue.

No, not yet. Hopefully next week.

**Comment by stevie6410** [comment]
Hi, i've also just updated to .NET 7 from 5 and .xlsb is is broken for me too. v3.6.0 package. 

Is there any workaround I can apply in the meantime?

**Comment by stevie6410** [comment]
Hi, I see the issue has been resolved and built. When does this package hit nuget as a pre-release?

**Comment by joydeep19** [comment]
When it will available in Nuget as a prerelease?

**Comment by rvdingDev** [comment]
I'm also eagerly awaiting the beta release.
