### ISSUE TITLE
<target>.ColumnName and <source>.ColumnName have conflicting properties: DataType property mismatch.

### ISSUE THREAD

**Issue by gregarican** [ExcelDataReader/ExcelDataReader#639]
Using ExcelDataReader v3.6.0. So I have run into this error, although when I re-run the same code against the same Excel source files it completes without error. The goal is to read all Excel 8.0 files in a directory and combine them into a consolidated master file. When the error occurs, the column that fires off the exception is a string/text column. The first column from the first sheet attempting to be merged into the inferred table. There aren't any numeric-only values for this first column in the sheets.

Here is how I am connecting to the Excel data source:

`System.Data.DataTable CumulativeData = new System.Data.DataTable();`
`excelConnectionString = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + fileName + ";Extended Properties='Excel 8.0; HDR=YES; IMEX=1; READONLY=TRUE'";`
`using (OleDbConnection con = new OleDbConnection(excelConnectionString))`
` {`
`    OleDbCommand sqlcom = new OleDbCommand();`
`    using (var stream = File.Open(fileName, FileMode.Open, FileAccess.Read))`
`    {`
`        using (var xlReader = ExcelReaderFactory.CreateReader(stream))`
`        {`
`              var sheets = xlReader.AsDataSet(new ExcelDataSetConfiguration()`
`               {`
`                    ConfigureDataTable = (_) => new ExcelDataTableConfiguration()`
`                     {`
`                          UseHeaderRow = true`
`                      }`
`                       });`
`                               var firstSheet = sheets.Tables[0];`
`                                int newRecordCount = firstSheet.Rows.Count;`
`                                CumulativeData.Merge(firstSheet);`
`                                string thisRecordCount = (newRecordCount - oldRecordCount).ToString();`
`                                log.InfoFormat("Pulled {0} rows from {1}.", thisRecordCount, fileName);`
`                            }`
`                        }`
`                     }`
`...`

Any suggestions for properly handling this?

**Comment by appel1** [comment]
Check what column has a data type mismatch and then figure out why from the source Excel files. 

Closing this since it seems to be more of a general programming help question which is better suited for sites like [stackoverflow](stackoverflow.com). Please reopen if you think there's an issue with ExcelDataReader.

**Comment by gregarican** [comment]
You are 100% correct. The issue involved merging the DataTable values dervied from iterating through my Excel source files. And the first source sheet I was reading was blank. Then my routine iterated to the second sheet, which had valid values. The inferred DataTable column values from that first sheet threw off things. Fixed that now. Appreciate your patience!
