### ISSUE TITLE
String values converted to blank in some XLS format files

### ISSUE THREAD

**Issue by snowstorm0951** [ExcelDataReader/ExcelDataReader#64]
In some XLS format files cells with string values convert to blank in the Datatable cell.

In once old test file in BIFF8 format values like 'a', 'b','c' etc converted to blank.
Changing the font in the file to Arial and re-saving bypassed the problem.

In a second test file only string cells with the value TOTAL UNITS converted correctly and all other string cells converted to blanks.  Could not find a way to bypass the problem.  Could not find any characteristic that made this XLS file different than many others.  If I copied and pasted values into a new sheet conversion worked.

Could not figure out how to attach sample files to this issue report.

**Comment by Ian1971** [comment]
Where did the original files come from?

On Mon, Apr 20, 2015 at 1:17 PM, snowstorm0951 <notifications@github.com>
wrote:

> In some XLS format files cells with string values convert to blank in the
> Datatable cell.
>
> In once old test file in BIFF8 format values like 'a', 'b','c' etc
> converted to blank.
> Changing the font in the file to Arial and re-saving bypassed the problem.
>
> In a second test file only string cells with the value TOTAL UNITS
> converted correctly and all other string cells converted to blanks. Could
> not find a way to bypass the problem. Could not find any characteristic
> that made this XLS file different than many others. If I copied and pasted
> values into a new sheet conversion worked.
>
> Could not figure out how to attach sample files to this issue report.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/64>.
>



-- 

Ian Cox
C.T.O.

System Sync
m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.systemsyncsolutions.com
<http://www.releasemobile.com/>

Registered in England as systemsync solutions ltd.
Number: 9326325 VAT: 202729923

**Comment by snowstorm0951** [comment]
Thx,
I have the two files.

The Book1.xls file is, I think, from NPOI install as sample to NPIO

The Invoice _TE-132-SA-2.xls file was part of ExcelDataReader CodePlex issue Id #11928 GetValue returns empty string for cells in some xls file

Both files convert correctly if I use LinqToExcel which I switched to when I could not figure out how to get them to work under ExcelDataReader.

The Book1.xls file seems, I just saw, to have similar issue as ExcelDataReader CodePlex issue #Id6027, Chinese Encoding Reading Error.

For Invoice _TE-132-SA-2.xls: If I copied data into a new XLS file conversion would work.  I tried a number of combinations within version of the sheet itself, I copied, moved, retyped cells but nothing seemed to change the problem, whatever I tried would result in "TOTAL UNITS" cells convert correctly and all other String cells convert to blank)



Best regards,
Peter

________________________________

**Comment by Ian1971** [comment]
This would require stepping through the code to figure out what it is about
these specific sheets that cause a problem. Unfortunately, I am snowed
under at the moment, so don't have time to do that.

On Mon, Apr 20, 2015 at 2:11 PM, snowstorm0951 <notifications@github.com>
wrote:

> Thx,
> I have the two files.
>
> The Book1.xls file is, I think, from NPOI install as sample to NPIO
>
> The Invoice _TE-132-SA-2.xls file was part of ExcelDataReader CodePlex
> issue Id #11928 GetValue returns empty string for cells in some xls file
>
> Both files convert correctly if I use LinqToExcel which I switched to when
> I could not figure out how to get them to work under ExcelDataReader.
>
> The Book1.xls file seems, I just saw, to have similar issue as
> ExcelDataReader CodePlex issue #Id6027, Chinese Encoding Reading Error.
>
> For Invoice _TE-132-SA-2.xls: If I copied data into a new XLS file
> conversion would work. I tried a number of combinations within version of
> the sheet itself, I copied, moved, retyped cells but nothing seemed to
> change the problem, whatever I tried would result in "TOTAL UNITS" cells
> convert correctly and all other String cells convert to blank)
>
>
>
> Best regards,
> Peter
>
> ________________________________
> From: Ian1971 [mailto:notifications@github.com]
> Sent: Monday, April 20, 2015 8:34 AM
> To: ExcelDataReader/ExcelDataReader
> Cc: Sandin, Peter
> Subject: Re: [ExcelDataReader] String values converted to blank in some
> XLS format files (#64)
>
> Where did the original files come from?
>
> On Mon, Apr 20, 2015 at 1:17 PM, snowstorm0951 <notifications@github.com>
> wrote:
>
> > In some XLS format files cells with string values convert to blank in the
> > Datatable cell.
> >
> > In once old test file in BIFF8 format values like 'a', 'b','c' etc
> > converted to blank.
> > Changing the font in the file to Arial and re-saving bypassed the
> problem.
> >
> > In a second test file only string cells with the value TOTAL UNITS
> > converted correctly and all other string cells converted to blanks. Could
> > not find a way to bypass the problem. Could not find any characteristic
> > that made this XLS file different than many others. If I copied and
> pasted
> > values into a new sheet conversion worked.
> >
> > Could not figure out how to attach sample files to this issue report.
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ExcelDataReader/ExcelDataReader/issues/64>.
> >
>
>
>
> --
>
> Ian Cox
> C.T.O.
>
> System Sync
> m: Matrix Studios, 91 Peterborough Road, London, SW6 3BU
> w: http://www.systemsyncsolutions.com
> <http://www.releasemobile.com/>
>
> Registered in England as systemsync solutions ltd.
> Number: 9326325 VAT: 202729923
>
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/ExcelDataReader/ExcelDataReader/issues/64#issuecomment-94440772
> >.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/64#issuecomment-94447794>
> .
>



-- 

Ian Cox
C.T.O.

Release  Mobile

m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.releasemobile.com

Registered in England.  Number 06323661

**Comment by snowstorm0951** [comment]
Ok, no prob, feel free to close out issue in Github, i worked around using linqtoexcel and just reported it while i had material fresh at hand
Best regards
Peter

Sent from my iPhone

On Apr 20, 2015, at 9:26 AM, Ian1971 <notifications@github.com<mailto:notifications@github.com>> wrote:

This would require stepping through the code to figure out what it is about
these specific sheets that cause a problem. Unfortunately, I am snowed
under at the moment, so don't have time to do that.

On Mon, Apr 20, 2015 at 2:11 PM, snowstorm0951 <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Thx,
> I have the two files.
>
> The Book1.xls file is, I think, from NPOI install as sample to NPIO
>
> The Invoice _TE-132-SA-2.xls file was part of ExcelDataReader CodePlex
> issue Id #11928 GetValue returns empty string for cells in some xls file
>
> Both files convert correctly if I use LinqToExcel which I switched to when
> I could not figure out how to get them to work under ExcelDataReader.
>
> The Book1.xls file seems, I just saw, to have similar issue as
> ExcelDataReader CodePlex issue #Id6027, Chinese Encoding Reading Error.
>
> For Invoice _TE-132-SA-2.xls: If I copied data into a new XLS file
> conversion would work. I tried a number of combinations within version of
> the sheet itself, I copied, moved, retyped cells but nothing seemed to
> change the problem, whatever I tried would result in "TOTAL UNITS" cells
> convert correctly and all other String cells convert to blank)
>
>
>
> Best regards,
> Peter
>
> ________________________________
> From: Ian1971 [mailto:notifications@github.com]
> Sent: Monday, April 20, 2015 8:34 AM
> To: ExcelDataReader/ExcelDataReader
> Cc: Sandin, Peter
> Subject: Re: [ExcelDataReader] String values converted to blank in some
> XLS format files (#64)
>
> Where did the original files come from?
>
> On Mon, Apr 20, 2015 at 1:17 PM, snowstorm0951 <notifications@github.com<mailto:notifications@github.com>>
> wrote:
>
> > In some XLS format files cells with string values convert to blank in the
> > Datatable cell.
> >
> > In once old test file in BIFF8 format values like 'a', 'b','c' etc
> > converted to blank.
> > Changing the font in the file to Arial and re-saving bypassed the
> problem.
> >
> > In a second test file only string cells with the value TOTAL UNITS
> > converted correctly and all other string cells converted to blanks. Could
> > not find a way to bypass the problem. Could not find any characteristic
> > that made this XLS file different than many others. If I copied and
> pasted
> > values into a new sheet conversion worked.
> >
> > Could not figure out how to attach sample files to this issue report.
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ExcelDataReader/ExcelDataReader/issues/64>.
> >
>
>
>
> --
>
> Ian Cox
> C.T.O.
>
> System Sync
> m: Matrix Studios, 91 Peterborough Road, London, SW6 3BU
> w: http://www.systemsyncsolutions.com
> <http://www.releasemobile.com/>
>
> Registered in England as systemsync solutions ltd.
> Number: 9326325 VAT: 202729923
>
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/ExcelDataReader/ExcelDataReader/issues/64#issuecomment-94440772
> >.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/64#issuecomment-94447794>
> .
>



--

Ian Cox
C.T.O.

Release Mobile

m: Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w: http://www.releasemobile.com

Registered in England. Number 06323661

**Comment by Ian1971** [comment]
Thanks

On Mon, Apr 20, 2015 at 2:33 PM, snowstorm0951 <notifications@github.com>
wrote:

> Ok, no prob, feel free to close out issue in Github, i worked around using
> linqtoexcel and just reported it while i had material fresh at hand
> Best regards
> Peter
>
> Sent from my iPhone
>
> On Apr 20, 2015, at 9:26 AM, Ian1971 <notifications@github.com<mailto:
> notifications@github.com>> wrote:
>
> This would require stepping through the code to figure out what it is about
> these specific sheets that cause a problem. Unfortunately, I am snowed
> under at the moment, so don't have time to do that.
>
> On Mon, Apr 20, 2015 at 2:11 PM, snowstorm0951 <notifications@github.com
> <mailto:notifications@github.com>>
>
> wrote:
>
> > Thx,
> > I have the two files.
> >
> > The Book1.xls file is, I think, from NPOI install as sample to NPIO
> >
> > The Invoice _TE-132-SA-2.xls file was part of ExcelDataReader CodePlex
> > issue Id #11928 GetValue returns empty string for cells in some xls file
> >
> > Both files convert correctly if I use LinqToExcel which I switched to
> when
> > I could not figure out how to get them to work under ExcelDataReader.
> >
> > The Book1.xls file seems, I just saw, to have similar issue as
> > ExcelDataReader CodePlex issue #Id6027, Chinese Encoding Reading Error.
> >
> > For Invoice _TE-132-SA-2.xls: If I copied data into a new XLS file
> > conversion would work. I tried a number of combinations within version of
> > the sheet itself, I copied, moved, retyped cells but nothing seemed to
> > change the problem, whatever I tried would result in "TOTAL UNITS" cells
> > convert correctly and all other String cells convert to blank)
> >
> >
> >
> > Best regards,
> > Peter
> >
> > ________________________________
> > From: Ian1971 [mailto:notifications@github.com]
> > Sent: Monday, April 20, 2015 8:34 AM
> > To: ExcelDataReader/ExcelDataReader
> > Cc: Sandin, Peter
> > Subject: Re: [ExcelDataReader] String values converted to blank in some
> > XLS format files (#64)
> >
> > Where did the original files come from?
> >
> > On Mon, Apr 20, 2015 at 1:17 PM, snowstorm0951 <notifications@github.com
> <mailto:notifications@github.com>>
> > wrote:
> >
> > > In some XLS format files cells with string values convert to blank in
> the
> > > Datatable cell.
> > >
> > > In once old test file in BIFF8 format values like 'a', 'b','c' etc
> > > converted to blank.
> > > Changing the font in the file to Arial and re-saving bypassed the
> > problem.
> > >
> > > In a second test file only string cells with the value TOTAL UNITS
> > > converted correctly and all other string cells converted to blanks.
> Could
> > > not find a way to bypass the problem. Could not find any characteristic
> > > that made this XLS file different than many others. If I copied and
> > pasted
> > > values into a new sheet conversion worked.
> > >
> > > Could not figure out how to attach sample files to this issue report.
> > >
> > > --
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/ExcelDataReader/ExcelDataReader/issues/64>.
> > >
> >
> >
> >
> > --
> >
> > Ian Cox
> > C.T.O.
> >
> > System Sync
> > m: Matrix Studios, 91 Peterborough Road, London, SW6 3BU
> > w: http://www.systemsyncsolutions.com
> > <http://www.releasemobile.com/>
> >
> > Registered in England as systemsync solutions ltd.
> > Number: 9326325 VAT: 202729923
> >
> >
> > -
> > Reply to this email directly or view it on GitHub<
> >
> https://github.com/ExcelDataReader/ExcelDataReader/issues/64#issuecomment-94440772
> > >.
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ExcelDataReader/ExcelDataReader/issues/64#issuecomment-94447794
> >
> > .
> >
>
>
>
> --
>
> Ian Cox
> C.T.O.
>
> Release Mobile
>
> m: Matrix Studios, 91 Peterborough Road, London, SW6 3BU
> w: http://www.releasemobile.com
>
> Registered in England. Number 06323661
>
> --
> Reply to this email directly or view it on GitHub<
> https://github.com/ExcelDataReader/ExcelDataReader/issues/64#issuecomment-94450447
> >.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/64#issuecomment-94451807>
> .
>



-- 

Ian Cox
C.T.O.

Release  Mobile

m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.releasemobile.com

Registered in England.  Number 06323661
