### ISSUE TITLE
ExcelDataReader reading partial data from .xlsb file in .net 6

### ISSUE THREAD

**Issue by joydeep19** [ExcelDataReader/ExcelDataReader#646]
ExcelDataReader reading partial data from .xlsb file in .net 6 azure function.Please provide a solution on that.

**Comment by appel1** [comment]
What is it you want to do that you can't do? What have you tried?

**Comment by joydeep19** [comment]
I am reading a .xlsb file from blob storage using exceldatareader using .net 6 function.my xlsb has 255 column and 10200 row but it is reading only 29 row and some column value also coming blank

**Comment by dimitriskad** [comment]
I encountered a similar issue after upgrading to .NET6. Some of my unit tests that used to pass now fail because some cell values are read as null.

I can share a couple of files privately to help you replicate the issue.

**Comment by dimitriskad** [comment]
I see now that this issue might be related to https://github.com/ExcelDataReader/ExcelDataReader/issues/637.
