### ISSUE TITLE
Reading data as a string

### ISSUE THREAD

**Issue by MrSent** [ExcelDataReader/ExcelDataReader#651]
I have some input data in a spreadsheet. The column data is 694142.01

I have no control over the formatting as the spreadsheet is created by an external system. When I do reader.GetString(0) on that file is throws an exception "Unable to cast object of type 'System.Double' to type 'System.String'."

I don't really care that the data can be treated as a double. I want it as a string. Why does reading the data as a string cause it to throw an error?

**Comment by MrSent** [comment]
Found this that solves this issue: https://github.com/ExcelDataReader/ExcelDataReader/issues/452

**Comment by MrSent** [comment]
Found a workaround https://github.com/ExcelDataReader/ExcelDataReader/issues/452

**Comment by kerams** [comment]
It isn't solved, particularly for dates. For whatever reason the library decides to interpret strings as dates/numbers if possible. If I wanted to do that, I can trivially do it myself. What isn't trivial is getting the original raw representation.

**Comment by appel1** [comment]
The raw representation is a double.
