### ISSUE TITLE
Read data from specific column/row?

### ISSUE THREAD

**Issue by TH3GAM3K1NG** [ExcelDataReader/ExcelDataReader#652]
Hello, I'm trying to read data from a specific column the user has selected (e.g. column 2) and check what type the data is. I am unsure how to read data from specific columns and as for the data check I keep getting an error and I was wondering if anyone could help.
The code for checking the type is the following.
```
Type x = reader.GetFieldType(0, column);
                if (x == typeof(DateTime))
                {
                    DO STUFF HERE
                }
```
Any help is appreciated!

**Comment by andersnm** [comment]
That's a good start, but this is the wrong place if you need general programming help.
