### ISSUE TITLE
IExcelDataReader.Read() and .GetXXX() methods are so slow

### ISSUE THREAD

**Issue by t-zhai** [ExcelDataReader/ExcelDataReader#659]
Installed version 3.6 from Nuget, it is so slow, using the while(reader.Read()) example code, it took 30 seconds to open and read a spreadsheet of 78 rows and 20 columns with only string and double values.

**Comment by andersnm** [comment]
Hi,

Can you give us any info about the file and your environment? Obviously this is not as intended.

**Comment by t-zhai** [comment]
On windows 11, Microsoft Excel version 2309 Build 16.0.16827.20166, 64-bit

**Comment by andersnm** [comment]
That's not enough information.

**Comment by t-zhai** [comment]
Tried the open/read of the same excel data file using the AsDataSet() method, it is blazing fast.
so, there is issue with the reader.Read() method.

**Comment by t-zhai** [comment]
Ok, I was using the reader.Read() method to read the .xlsx file, not the binary .xls file. So, maybe that is why it is slow? I worked though, just slow. I see the comment in the sample code saying OpenXml is used for xlsx files and perhaps the reader.Read() for the older .xls file.

**Comment by appel1** [comment]
AsDataSet is just a helper method that uses the reader implementation so it cannot be faster. 

Most likely the issue lies in your code.
