### ISSUE TITLE
How do I get data in a DataTable and/or Observablecollection?

### ISSUE THREAD

**Issue by jhon65496** [ExcelDataReader/ExcelDataReader#661]
How do I get data in a DataTable and/or Observablecollection?
Show a complete example.
I don't understand your example.

```cs
using (var stream = File.Open(filePath, FileMode.Open, FileAccess.Read))
{
    // Auto-detect format, supports:
    //  - Binary Excel files (2.0-2003 format; *.xls)
    //  - OpenXml Excel files (2007 format; *.xlsx, *.xlsb)
    using (var reader = ExcelReaderFactory.CreateReader(stream))
    {
        // Choose one of either 1 or 2:

        // 1. Use the reader methods
        do
        {
            while (reader.Read())
            {
                // reader.GetDouble(0);
            }
        } while (reader.NextResult());

            ???????????????
    }
}
```

**Comment by jhon65496** [comment]
@wizardgsz 
The documentation says `Choose one of either 1 or 2:`
If I choose `1. Use the reader methods', then how do I use it?
I get an error in `reader.getDouble(0);`
Error text: `The specified cast is invalid`
How to use `reader.getDouble(0);`?


`DataTable dt = reader.AsDataSet()` works fine for the same file.


![image](https://github.com/ExcelDataReader/ExcelDataReader/assets/128128859/e9ffe4c7-201c-45eb-a1a8-23668b2ee9bb)


I am reading a file of this type: **TestProducts.xlsx**
![image](https://github.com/ExcelDataReader/ExcelDataReader/assets/128128859/e8d60815-971b-4cea-bbee-08e41ea9fca9)

**Comment by appel1** [comment]
You get a cast exception if the cell does not contain a number. You can use GetValue and check the type of the returned object instead. See https://github.com/ExcelDataReader/ExcelDataReader?tab=readme-ov-file#using-the-reader-methods.
