### ISSUE TITLE
CSV File - Delimiter Between Quotes 

### ISSUE THREAD

**Issue by LC6529** [ExcelDataReader/ExcelDataReader#666]
Sample Header Line

"Last Name", "First Name", "Last Name, First Name", "Address Line One"

There needs to be a way to tell CSVReader to ignore delimiters between quotes.

Currently when trying to read this file it sees four delimiters in the line above when it should only see three.

The only way to get the file to be read is to open it in excel and save it as an XLS file which is not an option.

**Comment by LC6529** [comment]
Not without getting in trouble at work, it's healthcare data.
Basically I have run into the issue when the data looks like this:
"Brown","John","123 Mockingbird Lane, Apt 3G", "Oakland", "California",...
In the above example, a delimiter is in between the quotes in the 3rd column.      On Monday, April 15, 2024 at 04:09:39 PM EDT, Johan Appelgren ***@***.***> wrote:  
 
 


I cannot reproduce this. Could you provide a sample .csv file and code that reproduces this issue?

**Comment by appel1** [comment]
What version are you using? 

Using the latest prerelease this test passes.

```csharp
[Test]
public void GitIssue666()
{
    MemoryStream ms = new(Encoding.UTF8.GetBytes("\"Brown\",\"John\",\"123 Mockingbird Lane, Apt 3G\", \"Oakland\", \"California\""));
    using var reader = ExcelReaderFactory.CreateCsvReader(ms);
    reader.Read();
    var values = new object[reader.FieldCount];
    reader.GetValues(values);

    Assert.That(values, Is.EqualTo(new object[] { "Brown", "John", "123 Mockingbird Lane, Apt 3G", "Oakland", "California" }));
}
````
