### ISSUE TITLE
DotNet 8 Support

### ISSUE THREAD

**Issue by Shamina05** [ExcelDataReader/ExcelDataReader#669]
Hi All, 

Does .Net 8 support ExcelDataReader and are there any code changes required when adopting the new framework with this package? 

One thing I noticed from another package I'm currently using is that the malformed URI scan check when opening a spreadsheet, which worked with .NET 6, no longer works and you'd need to read each cell to figure out if it is a URI and whether it is well formed. This adds greatly to performance.

**Comment by appel1** [comment]
I don't understand your issue but maybe you can try a recent pre release?
