### ISSUE TITLE
Empty cells are being created as DBNull

### ISSUE THREAD

**Issue by JeffB42** [ExcelDataReader/ExcelDataReader#67]
I'm running into an issue, and I was wondering if this is by design or a bug.  We're using ExcelDataReader to parse XLS and XLSX files into a DataTable and then insert the table into our database.  The format of the table is such that some fields are required and some are optional.  Those which are optional need to be an empty string (not null).

For example, Let's say that we had a format where we were expecting 4 columns - FirstName, MiddleName, LastName, and Age.  The first row in the XLS or XLSX file will be the column header, and will always have all 4 column names.

In the data rows,  FirstName and LastName will always be present, but MiddleName and Age are optional.  For example, suppose we had a file with the following contents:

FirstName, MiddleName, LastName, Age
A1, B1, C1, 1
A2,,C2,,
A3,,C3,,

In this example, A1 has all 4 fields, but A2 and A3 only have the first name and last name, but not the middle name or age.  For what I'd like to do, this is valid XLS/XLSX data.

However the issue I'm having is that the fields which are empty are coming back as DBNull.  I just spoke to our DBA and was told the insert sproc and UDT require an empty string for fields not present, and can't be null, so I'm between a rock and a hard place.

Is it possible to configure ExcelDataReader to generate a string cell and have the value be an empty string when the value is empty in the spreadsheet?

I suppose I could iterate through the DataTable after the data set is crated via excelDataReader.AsDataSet(), see if the type is DBNull, and then set the cell, but I'd like to not have to do that.

Thanks for any help and advise,

Jeff

**Comment by Ian1971** [comment]
I guess you could modify the exceldatareader code to replace dbnull with
empty string.
