### ISSUE TITLE
Error CS0426 The type name 'CreateReader' does not exist in the type 'ExcelReaderFactory'

### ISSUE THREAD

**Issue by mattAnonomatic** [ExcelDataReader/ExcelDataReader#670]
I have added both nuget packages to my project. When I try to use the sample code, I get this error message 'CreateReader' does not exist in the type 'ExcelReaderFactory'.

What am I missing?

Thank you

**Comment by appel1** [comment]
Did you accidentally create your own class called ExcelReaderFactory ?

**Comment by mattAnonomatic** [comment]
Good question but no I did not. I scanned the entire solution and there is nothing close.

**Comment by mattAnonomatic** [comment]
My mistake was even dumber than that. I thought I had installed both ExcelDataReader and ExcelDataReader.DataSet but when I just double-checked, I only had the data set library installed.  All is well now.

Thanks for responding.

From: Matthew Fleck
Sent: Friday, May 31, 2024 7:54 AM
To: ExcelDataReader/ExcelDataReader ***@***.***>; ExcelDataReader/ExcelDataReader ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [ExcelDataReader/ExcelDataReader] Error CS0426 The type name 'CreateReader' does not exist in the type 'ExcelReaderFactory' (Issue #670)

Good question but no I did not. I scanned the entire solution and there is nothing close.

**Comment by appel1** [comment]
Thanks for letting us know you got it sorted!
