### ISSUE TITLE
Detected ZIP file, but not a valid OpenXml file.

### ISSUE THREAD

**Issue by peeyushsinghal94** [ExcelDataReader/ExcelDataReader#672]
I am trying to conbvert XLSB file into CSV, but getting "Detected ZIP file, but not a valid OpenXml file." error message.  I have written below code for it. Anyone help is appriciated. I have spent too much time on it. 

 string xlsbFilePath = "C:/Users/peeyu/Downloads/testxlsb.xlsb";
           // using (FileStream fileStream = new FileStream(xlsbFilePath, FileMode.Open, FileAccess.Read))

            using (var stream = File.Open(xlsbFilePath, FileMode.Open, FileAccess.Read))
            {
                using (var reader = ExcelReaderFactory.CreateReader(stream))
                {
                    // DataSet - The result of each spreadsheet will be created in the result.Tables
                    var result = reader.AsDataSet();

                    // Write the data to CSV
                    WriteDataTableToCsv(result.Tables[0], csvFilePath);
                }
            }

 public void WriteDataTableToCsv(DataTable dataTable, string csvFilePath)
        {
            using (StreamWriter writer = new StreamWriter(csvFilePath))
            {
                foreach (DataRow row in dataTable.Rows)
                {
                    var values = row.ItemArray;
                    writer.WriteLine(string.Join(",", Array.ConvertAll(values, x => x.ToString())));
                }
            }
        }

**Comment by appel1** [comment]
Which version of ExcelDataReader?

**Comment by peeyushsinghal94** [comment]
Version 3.6.0

**Comment by peeyushsinghal94** [comment]
It worked Thanks a lot !
