### ISSUE TITLE
Is there any plan to support encrypted export in xls format?

### ISSUE THREAD

**Issue by zurmokeeper** [ExcelDataReader/ExcelDataReader#678]
Is there any plan to support encrypted export in xls format?

**Comment by appel1** [comment]
Could you give some more context here and a sample .xls file?

**Comment by zurmokeeper** [comment]
@appel1 
The pseudo code is as follows

        const input = readFile(`unencrypted_test.xls`);
        const output = encrypt(input, {password: '123456'});
        writeFile(`encrypted_out_success.xls`, output);
        
        To open the encrypted_out_success.xls file you need to output the password first
        
        
    For example, my sample3.xls is an encrypted file.  Output the password 123456 to open it。

![image](https://github.com/user-attachments/assets/cd874b8c-7048-494d-b389-e71fb2bb1ecf)

[sample3.xls](https://github.com/user-attachments/files/16345657/sample3.xls)

**Comment by appel1** [comment]
Have you tried setting the Password property when creating the reader? 

https://github.com/ExcelDataReader/ExcelDataReader?tab=readme-ov-file#createreader-configuration-options

**Comment by appel1** [comment]
Ok. ExcelDataReader is reading only and there are no plans to support any kind of writing.
