### ISSUE TITLE
NullRefernceException in ExcelOpenXmlReader.ReadSheetGlobals method

### ISSUE THREAD

**Issue by oleksandrmeister** [ExcelDataReader/ExcelDataReader#68]
The bug with parsing *.xlsm was discovered:
###### Steps to reproduce:
1. Try to open *.xlsm
   ...
   DataSet ds = excelReader.AsDataSet();
   ...
   where excelReader is an open xml reader.
###### Expected result:

Dataset created without errors
###### Actual result:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Excel.ExcelOpenXmlReader.ReadSheetGlobals(XlsxWorksheet sheet) in c:\development\ExcelDataReader\Excel\ExcelOpenXmlReader.cs:line 105
   at Excel.ExcelOpenXmlReader.AsDataSet(Boolean convertOADateTime) in c:\development\ExcelDataReader\Excel\ExcelOpenXmlReader.cs:line 363
...

The problem code is in ExcelOpenXmlReader.ReadSheetGlobals method:
###### _sheetStream = _zipWorker.GetWorksheetStream(sheet.Path);

If "sheet.Path" is null then we have NullReferenceException.

**Comment by Ian1971** [comment]
I'm not sure if it's ever been tested with xlsm.

On Wed, May 13, 2015 at 10:54 AM, oleksandrmeister <notifications@github.com
> wrote:

> The bug with parsing *.xlsm was discovered:
> Steps to reproduce:
>
>    1. Try to open *.xlsm ... DataSet ds = excelReader.AsDataSet(); ...
>    where excelReader is an open xml reader.
>
> Expected result:
>
> Dataset created without errors
> Actual result:
>
> System.NullReferenceException: Object reference not set to an instance of
> an object.
> at Excel.ExcelOpenXmlReader.ReadSheetGlobals(XlsxWorksheet sheet) in
> c:\development\ExcelDataReader\Excel\ExcelOpenXmlReader.cs:line 105
> at Excel.ExcelOpenXmlReader.AsDataSet(Boolean convertOADateTime) in
> c:\development\ExcelDataReader\Excel\ExcelOpenXmlReader.cs:line 363
> ...
>
> The problem code is in ExcelOpenXmlReader.ReadSheetGlobals method:
> _sheetStream = _zipWorker.GetWorksheetStream(sheet.Path);
>
> If "sheet.Path" is null then we have NullReferenceException.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/68>.
>



-- 

Ian Cox
C.T.O.

System Sync
m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.systemsyncsolutions.com
<http://www.releasemobile.com/>

Registered in England as systemsync solutions ltd.
Number: 9326325 VAT: 202729923

**Comment by oleksandrmeister** [comment]
After fixing that bug it works fine for me with *.xlsm files as well.

My fix looks like:
...
if (null == sheet.Path) return;
_sheetStream = _zipWorker.GetWorksheetStream(sheet.Path);
...

**Comment by Ian1971** [comment]
Ok, great.

On Wed, May 13, 2015 at 11:47 AM, oleksandrmeister <notifications@github.com
> wrote:

> After fixing that bug it works fine for me with *.xlsm files as well.
>
> My fix looks like:
> ...
> if (null == sheet.Path) return;
> _sheetStream = _zipWorker.GetWorksheetStream(sheet.Path);
> ...
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/68#issuecomment-101622766>
> .
>



-- 

Ian Cox
C.T.O.

Release  Mobile

m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.releasemobile.com

Registered in England.  Number 06323661

**Comment by oleksandrmeister** [comment]
Can I fix it?

**Comment by Ian1971** [comment]
Yes. You can submit a pull request.

On Mon, May 18, 2015 at 1:22 PM, oleksandrmeister <notifications@github.com>
wrote:

> Can I fix it?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/68#issuecomment-103041336>
> .
>



-- 

Ian Cox
C.T.O.

Release  Mobile

m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.releasemobile.com

Registered in England.  Number 06323661

**Comment by oleksandrmeister** [comment]
The pull request is created.

**Comment by Ian1971** [comment]
Thanks

On Mon, May 18, 2015 at 2:24 PM, oleksandrmeister <notifications@github.com>
wrote:

> The pull request is created.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/68#issuecomment-103058306>
> .
>



-- 

Ian Cox
C.T.O.

Release  Mobile

m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.releasemobile.com

Registered in England.  Number 06323661

**Comment by oleksandrmeister** [comment]
Hi!

Is there any plan to release the next version/update of ExcelDataReader with included fixes (a few pull requests are pending)?
Thanks!

**Comment by Ian1971** [comment]
I'd like to but I don't have time to do it.

**Comment by andersnm** [comment]
Fixed
