### ISSUE TITLE
How to skip 1 sheet from worksheet while using reader.asdataset?

### ISSUE THREAD

**Issue by mraakashjoshi** [ExcelDataReader/ExcelDataReader#681]
How to skip 1 sheet from worksheet while using reader.asdataset?

Example
I have 1 excel file like below
Sheet1
Sheet2
Sheet3
Sheet4
Sheet5
Sheet6
Sheet7
Sheet8

i want to take this excel in dataset but **want to skip sheet1 and sheet7 then what to do?**

**Comment by appel1** [comment]
Have you looked at ExcelDataSetConfiguration.FilterSheet? 

https://github.com/ExcelDataReader/ExcelDataReader?tab=readme-ov-file#asdataset-configuration-options
