### ISSUE TITLE
Reading incorrect amount of columns in csv file.

### ISSUE THREAD

**Issue by CanduD** [ExcelDataReader/ExcelDataReader#686]
I'm using the asdataset functionality to read a csv file and populate a table and for 8/10 csv files it works perfectly. However I have a couple csv files where it reads that there is only 2 columns when there is 6 just like the over csv files.
`        private bool LoadCSV(string FilePath)
        {
            FileStream stream;
            bool success;
            try
            {

                stream = File.Open(FilePath, FileMode.Open, FileAccess.Read);
                IExcelDataReader reader = ExcelReaderFactory.CreateCsvReader(stream);

                var conf = new ExcelDataSetConfiguration
                {
                    ConfigureDataTable = _ => new ExcelDataTableConfiguration
                    {
                        UseHeaderRow = false,
                        FilterColumn = (rowReader, columnIndex) => { return true; }
                    }
                };

                var dataset = reader.AsDataSet(conf);
                var dataTable = dataset.Tables[0];

                int f = 1;
                for (int i = 5; i < dataTable.Rows.Count; i++)
                {
                    if (i % 2 == 0)
                    {
                        ZoneTable.RowGroups[0].Rows.Add(new TableRow());
                        for (int j = 0; j < ZoneTable.Columns.Count; j++)
                        {
                            TableRow currentRow = ZoneTable.RowGroups[0].Rows[f];
                            TableCell currentCell = (new TableCell(new Paragraph(new Run(dataTable.Rows[i][j].ToString()))));
                            int g = dataTable.Columns.Count;
                            currentCell.BorderThickness = new Thickness(2, 2, 2, 0);
                            currentRow.Cells.Add(currentCell);
                        }
                        f++;
                    }
                }
                reader.Close();

                return success = true;
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
                return success = false;
            }
        }`

**Comment by appel1** [comment]
What version of ExcelDataReader and do you have an example we can use to reproduce it?

**Comment by CanduD** [comment]
I'm using 3.7.0. I can't give you a copy of the project but I can assist with giving code snippets of how its used like what I pasted above. I've attached 2 csv files. Example one gives me the error and example 2 works.
[HX1 Vacuum Zone 10.csv](https://github.com/user-attachments/files/16788213/HX1.Vacuum.Zone.10.csv)
[HX1 Vacuum Zone 1.csv](https://github.com/user-attachments/files/16788229/HX1.Vacuum.Zone.1.csv)

**Comment by CanduD** [comment]
Did some messing around and found that resaving the first csv file allowed it t open normally.

**Comment by appel1** [comment]
Not sure what is going on then, I can't reproduce the issue with [Zone example 1.csv](https://github.com/user-attachments/files/16788251/Zone.example.1.csv). It gives me 13 columns and 13 rows.

**Comment by andersnm** [comment]
@CanduD That code got some potentially nasty side effects that makes bold assumptions about what's in the  `ZoneTable` variable. F.ex it will insert columns on the wrong row unless ZoneTable has exactly one row before you call this function, and it will only load as many columns as there are in the ZoneTable. I don't think your problems are with ExcelDataReader.

**Comment by CanduD** [comment]
@andersnm when I read the csv file into a dataset and then set a datatable equal to that dataset. The number of columns in the datatable is usually correct except for a couple files.
@appel1 try this csv I just attached it should cause this issue.
[HX1 Vacuum Zone 10.csv](https://github.com/user-attachments/files/16788759/HX1.Vacuum.Zone.10.csv)

**Comment by appel1** [comment]
It's the header that causes the problem. If you set ExcelReaderConfiguration.AutodetectSeparators to `[',', ';', '\t', '|']` instead, that is without the `#`, it might work better. 

Or you could remove those header rows first. 

Or if you know that it is always comma separated you can set AutodetectSeparators  to just `[ ',' ]`.

**Comment by CanduD** [comment]
@appel1 Thank you so much that fixed it! Cheers
