### ISSUE TITLE
System.Reflection.TargetInvocationException error occured when file being streamed.

### ISSUE THREAD

**Issue by appliedHouse** [ExcelDataReader/ExcelDataReader#688]
System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'

using (var stream = File.Open(filePath, FileMode.Open, FileAccess.Read))

above error comes at the file is being stream (above line)

**Comment by appel1** [comment]
What is the stack trace for the error? If the exception is thrown by File.Open then it most likely doesn't have anything to do with ExcelDataReader.
