### ISSUE TITLE
AsDataSet incorrectly generates 1048508 rows x 16384 cols dataset (and huge memory usage)

### ISSUE THREAD

**Issue by gr1-pro** [ExcelDataReader/ExcelDataReader#690]
Sporadically I experience small (<200 kB) xslx files which allocates several GB potentially crashing the server during the call to AsDataSet(). When the server does not crash, the resulting dataset contains 1048508 rows with 16384 columns.

I have finally managed to get an example causing this behaviour - it contains highly sensitive data and cannot be shared, but I can see that the embedded xl\worksheets\sheet1.xml is slightly malformed:

`	<cols>
		<col min="1" max="1" width="15.5703125" style="1" bestFit="1" customWidth="1"/>
		<col min="2" max="2" width="30.28515625" style="1" customWidth="1"/>
		<col min="3" max="3" width="12.5703125" style="1" customWidth="1"/>
		<col min="4" max="4" width="42.140625" style="1" customWidth="1"/>
                                                 :
		<col min="32" max="32" width="25.5703125" style="3" customWidth="1"/>
		<col min="33" max="33" width="19.28515625" style="3" customWidth="1"/>
		<col min="34" max="16384" width="8.85546875" style="1"/>
	</cols>
`
`	<sheetData>
		<row r="1" spans="1:33" ht="15.75" x14ac:dyDescent="0.25"> [rowdata] </row>
		<row r="2" spans="1:33" s="5" customFormat="1" x14ac:dyDescent="0.25"> [rowdata] </row>
                                                   :
		<row r="142" spans="1:33" x14ac:dyDescent="0.25"> [rowdata] </row>
		<row r="143" spans="1:33" ht="18.75" x14ac:dyDescent="0.3"> [rowdata] </row>
		<row r="1048508" spans="7:13" x14ac:dyDescent="0.25"> [rowdata] </row>
	</sheetData>
`

This 144 rows x 34 cols spreadsheet (when opened in Excel) is 1048508 rows x 16384 cols in the resulting dataset,

**Comment by appel1** [comment]
But there is data in row 1048508? 

You can probably use the filter callbacks to skip empty rows for example to reduce the size of the data set. 

https://github.com/ExcelDataReader/ExcelDataReader?tab=readme-ov-file#asdataset-configuration-options

**Comment by gr1-pro** [comment]
> But there is data in row 1048508?
> 
> You can probably use the filter callbacks to skip empty rows for example to reduce the size of the data set.
> 
> https://github.com/ExcelDataReader/ExcelDataReader?tab=readme-ov-file#asdataset-configuration-options

No, the spreadsheet contains only 144 rows with data (numbered 1-143 and 1048508).
Likewise the spreadsheet contains only 34 columns.

**Comment by appel1** [comment]
There's no such concept in DataSet. If you want to ignore all those empty rows between 143 and 1048508 you need to filter them out.

**Comment by gr1-pro** [comment]
Maybe I'm not being clear:
In the sheet1.xml embedded in the xlsx (partly shown in the first comment), there are 144 rows and 34 columns in total.
This is also how the spreadsheet is shown in Excel application.
After calling ToDataSet() there are 1048508 rows and 16384 columns.

**Comment by andersnm** [comment]
@gr1-pro Hi, could you please provide some more details whats inside the `[rowdata]` in this part (without the PII):

```xml
<row r="1048508" spans="7:13" x14ac:dyDescent="0.25"> [rowdata] </row>
```

Iirc the library should detect and ignore if there's only formatting, but there is likely some edge case causing expansion of all the empty rows.

**Comment by gr1-pro** [comment]
> @gr1-pro Hi, could you please provide some more details whats inside the `[rowdata]` in this part (without the PII):
> 
> ```
> <row r="1048508" spans="7:13" x14ac:dyDescent="0.25"> [rowdata] </row>
> ```
> 
> Iirc the library should detect and ignore if there's only formatting, but there is likely some edge case causing expansion of all the empty rows.

This is the last two rows in the sheet1.xml:
`		<row r="143" spans="1:33" ht="18.75" x14ac:dyDescent="0.3">
			<c r="A143" s="41">
				<f>SUM(A2:A142)</f>
				<v>100.89583333333334</v>
			</c>
			<c r="D143" s="25"/>
			<c r="E143" s="25"/>
			<c r="G143" s="1"/>
			<c r="H143" s="25"/>
			<c r="AD143" s="8" t="s">
				<v>327</v>
			</c>
			<c r="AE143" s="8">
				<f>SUM(AE2:AE142)</f>
				<v>1670904.2199999997</v>
			</c>
			<c r="AF143" s="8">
				<f>SUM(AF2:AF142)</f>
				<v>1623841.2699999996</v>
			</c>
			<c r="AG143" s="8">
				<f>SUM(AG2:AG142)</f>
				<v>1190501.51</v>
			</c>
		</row>
		<row r="1048508" spans="7:13" x14ac:dyDescent="0.25">
			<c r="G1048508" s="3">
				<f t="shared" ref="G1048508:L1048508" si="0">SUM(G2:G1048507)</f>
				<v>339519.16999999981</v>
			</c>
			<c r="H1048508" s="3">
				<f t="shared" si="0"/>
				<v>131635.74000000011</v>
			</c>
			<c r="I1048508" s="3">
				<f t="shared" si="0"/>
				<v>367971.20999999961</v>
			</c>
			<c r="J1048508" s="3">
				<f t="shared" si="0"/>
				<v>146670.75000000012</v>
			</c>
			<c r="K1048508" s="3">
				<f t="shared" si="0"/>
				<v>367605.30999999971</v>
			</c>
			<c r="L1048508" s="3">
				<f t="shared" si="0"/>
				<v>146308.75000000015</v>
			</c>
			<c r="M1048508" s="3">
				<f>SUM(G1048508:L1048576)</f>
				<v>1499710.9299999995</v>
			</c>
		</row>
`

**Comment by appel1** [comment]
To get the 1048508th row to be at the correct location in the row collection in the data set data table you need to have all the rows up to that row. So that is what ToDataSet does by default. 

You can change this by filtering out rows you are not interested in.

**Comment by gr1-pro** [comment]
> To get the 1048508th row to be at the correct location in the row collection in the data set data table you need to have all the rows up to that row. So that is what ToDataSet does by default.
> 
> You can change this by filtering out rows you are not interested in.

It seems like a quirk in Excel as the spreadsheet does not have a million rows and 16384 columns.
I would be nice with a possibility to override the default 'padding' behavior.
I CAN implement a custom filtering, but it seems very ineffective to 'throw away' 99.998% of data.

**Comment by andersnm** [comment]
Looks like there is actual data and formulas on row 1048508. Interesting case. It would be the most effective if we/appel could get our hands on an actual file where the problem reproduces - i.e a file which ExcelDataReader returns a million rows but Excel only renders 100ish. 

Maybe try and clear out the PII manually and save to a new file? Or fix the XML manually?

Please also consider using the lower level reader methods instead of AsDataSet(), because the problem is more about fighting the DataSet abstractions rather than data itself.

(apologies for backseating this, am not using .net anymore these days)
