### ISSUE TITLE
Is there any Plan to Support .Net Core and ASP.NET 5

### ISSUE THREAD

**Issue by alfkonee** [ExcelDataReader/ExcelDataReader#72]
I'd like to inquire if there are any plans to add support for the .NET Core Framework for the new ASP.NET platform

**Comment by Ian1971** [comment]
No ,  but that would be cool. Fancy doing it?  😉

**Comment by alfkonee** [comment]
I would like to try porting it to the new .Net Core  as a side project. Is there an email or other contact channel(s) I can use to I can use to get some clarifications on the current architecture??

**Comment by wizardgsz** [comment]
What do you need to build .NET Core "compatible" library?
Curiosity: there are guidelines?
Regards and thanks

**Comment by wizardgsz** [comment]
Follow-up here: [.NET Core Support #129](http://github.com/ExcelDataReader/ExcelDataReader/issues/129)
Closed.
