### ISSUE TITLE
Time in xlsx is read incorrectly. Xls is read correctly

### ISSUE THREAD

**Issue by aklahr72** [ExcelDataReader/ExcelDataReader#75]
If you read a time into a DateTime field the date part becomes 1899-12-31 when read from xlsx. 
When read from xls it is correctly 1899-12-30

**Comment by appel1** [comment]
Could you provide a sample for this? Afaik it is not possible to create an Excel document with 1899-12-30 as a date, at least not when using Excel. Cells with that content will be a string even if you try to set the format to date.

**Comment by andersnm** [comment]
Been meaning to test this when I have a proper Excel, which I do atm. However, ExcelDataReader seems to consistently return the date 12/31/1899 on timestamps for both xls and xlsx (or the next day when using times like "24:00")

Pretty sure this can be closed, but please reopen and attach samples if they demonstrate a different behavior.

[timestamps.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/1155490/timestamps.zip)

**Comment by appel1** [comment]
Ah, misread the issue.
