### ISSUE TITLE
Set specific row as column name

### ISSUE THREAD

**Issue by gandarez** [ExcelDataReader/ExcelDataReader#77]
I've an excel where the first 4 rows are definitions and the 5th is the column name. Is it possible to define 5th row as column name?

![image](https://cloud.githubusercontent.com/assets/782854/8873907/bed85bae-31e1-11e5-99d1-4a37c560c1f8.png)

**Comment by fduverger** [comment]
Could you find the answer to this issue?
I have a similar situation because I am reading a worksheet that has the column names on the second row. Any luck?

**Comment by gandarez** [comment]
I didn't fnd any answer. What I did was to skip the first 5 rows.

**Comment by fduverger** [comment]
Did your dataset detect the fifth row as the columns?
If so would you mind to share an code example.
Thanks

**Comment by gandarez** [comment]
@fduverger No it didn't. The library detects every single line in excel file as a row into the dataset. I just skipped the first 5 rows (Linq). Because I changed my code I don't have any source code to show you.

**Comment by madks13** [comment]
I'd also like a function that lets us offset the column name row or choose the row used for column names. As it is, i deal with many documents made by other people with first rows containing definitions or useless information (for the code) and this makes reading the documents with this library very bothersome.

**Comment by andersnm** [comment]
This works now, to use the 5th row as column headers:

```C#
reader.AsDataSet(new ExcelDataSetConfiguration() {
    ConfigureDataTable = (_) => new ExcelDataTableConfiguration() {
        UseHeaderRow = true,
        ReadHeaderRow = (rowReader) => {
            rowReader.Read();
            rowReader.Read();
            rowReader.Read();
            rowReader.Read();
        }
    }
});
```

**Comment by GeekMasterX** [comment]
Thanks, man this helped a lot I have modified @andersnm 's logic a bit. I'm taking user input for the header row.

reader.AsDataSet(new ExcelDataSetConfiguration() {
    ConfigureDataTable = (_) => new ExcelDataTableConfiguration() {
        UseHeaderRow = true,
        ReadHeaderRow = (rowReader) => {
           for (int i = 0; i < (HeaderRow-1); i++)
                rowReader.Read();
        }
    }
});
