### ISSUE TITLE
Your bat delete my files on HDD, WTF?

### ISSUE THREAD

**Issue by SiriusED** [ExcelDataReader/ExcelDataReader#78]
Can you explane me, why your bat file `D:\ExcelDataReader-develop\Excel\Build.Debug.CF.bat` Delete my files and folders on my disc D? WTF???

**Comment by Ian1971** [comment]
No idea sorry.  I didn't write that bat  file. Looking at it it looks like
it deletes files in a sub folder if the current directory.  So I don't know
what happened in your case.  Why did you run the bat file?

**Comment by tcsaddul** [comment]
lol 


     On Thursday, July 30, 2015 2:59 PM, Ian1971 <notifications@github.com> wrote:
   

 No idea sorry. I didn't write that bat file. Looking at it it looks like
it deletes files in a sub folder if the current directory. So I don't know
what happened in your case. Why did you run the bat file?

**Comment by SiriusED** [comment]
Ian1971, Why I started this file - this is not the right question, the question is why this file in Projects? Delete this file from the Projects, it is worse than any virus ... Lord ...

**Comment by Ian1971** [comment]
I think it is related to building the project for the compact framework.
I'm not sure how it wiped your drive, unless %cd% evaluated to null
perhaps, not sure. I've renamed the file in the repo to append
.use_at_your_own_risk
as it may be a useful file for some people who want to build for CF, I
really don't know though.


On Thu, Jul 30, 2015 at 1:03 PM, SiriusED <notifications@github.com> wrote:

> Ian1971, Why I started this file - this is not the right question, the
> question is why this file in Projects? Delete this file from the Projects,
> it is worse than any virus ... Lord ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/78#issuecomment-126296251>
> .
>



-- 

Ian Cox
C.T.O.

Release  Mobile

m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.releasemobile.com

Registered in England.  Number 06323661

**Comment by andersnm** [comment]
These files are gone now as part of #139
