### ISSUE TITLE
Drop Framework 2.0 support?

### ISSUE THREAD

**Issue by Ian1971** [ExcelDataReader/ExcelDataReader#8]
I really want to drop framework 2.0 support, because maintaining it is restricting the rest of the project and how it can be structured. Personally I have no use for framework 2.0 support so my motivation to keep supporting it is very low.

What do people feel about this?

**Comment by andersnm** [comment]
With the new tooling and reorganizations I don't think theres any reason to abandon the net20 target yet. Suggest to close
