### ISSUE TITLE
Add support for "date1904" dates

### ISSUE THREAD

**Issue by ZanderRollins** [ExcelDataReader/ExcelDataReader#82]
Reading from an xls or xlsx file, I get a 2011 date every time even though the data in the file is 2015.  This is consistent across all dates in the file.

StartDate = excelReader.GetDateTime(0)

Date in correct column and cell is 9/2/2015  4:00:00 PM
Date returned from code above is: {9/1/2011 4:00:00 PM}

I have zero 2011 dates in the file.

Please advise.

**Comment by Ian1971** [comment]
Are you able to provide a sample of the spreadsheet? Perhaps dropbox link or similar?

**Comment by ZanderRollins** [comment]
https://dl.dropboxusercontent.com/u/2761631/Example.xlsx

thank you for the help.

**Comment by Ian1971** [comment]
This is quite strange. When I debug I see that for example one of the dates is OA Date = 40787.6666666667
When converted to a string date you get the 2011 date.
You can see it here
http://www.silisoftware.com/tools/date.php?inputdate=40787.6666666667&inputformat=microsoft

**Comment by Ian1971** [comment]
Ah ha. I think it is related to date1904 property
https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.workbookproperties(v=office.14).aspx

That explains the 4 years difference. So it would see the ExcelDataReader is not taking that property in to account.

So, I think this is a valid bug.

However, I have no time to fix it. So either:
1. You try to fix it
2. You modify your spreadsheet to use date 1900 system http://www.techrepublic.com/blog/microsoft-office/office-solution-clearing-up-that-wacky-date-problem-when-copying-sheets/  (note you'll need to adjust dates after this anyway)

**Comment by ZanderRollins** [comment]
Thanks, I'll check it out.  Odd that we'd have a date issue like this in 2015.

**Comment by Ian1971** [comment]
I don't know why excel supports two date systems.  Legacy I guess.  Thia is
the first issue I came across for it so guessing most default to 1900.

**Comment by andersnm** [comment]
There is a trove of test data here: http://oss.sheetjs.com/test_files/

For the "date1904" issue:
http://oss.sheetjs.com/test_files/roo_1900_base.xls
http://oss.sheetjs.com/test_files/roo_1900_base.xlsx
http://oss.sheetjs.com/test_files/roo_1904_base.xls
http://oss.sheetjs.com/test_files/roo_1904_base.xlsx

Failing test:
```C#
        [TestMethod]
        public void GitIssue_82_Date1904()
        {
            using (IExcelDataReader excelReader = ExcelReaderFactory.CreateOpenXmlReader(Configuration.GetTestWorkbook("xroo_1904_base")))
            {
                // 15/06/2009
                // 4/19/2013

                DataSet result = excelReader.AsDataSet();
                Assert.AreEqual(new DateTime(2009, 6, 15), (DateTime)result.Tables[0].Rows[0][0]);
                Assert.AreEqual(new DateTime(2013, 4, 19), (DateTime)result.Tables[0].Rows[1][0]);
            }
        }
```

For XLS, see section 2.4.77 Date1904 here:
http://interoperability.blob.core.windows.net/files/MS-XLS/[MS-XLS].pdf
