### ISSUE TITLE
excelReader.Error : Invalid file signature in xls..but reads same in xlsx file 

### ISSUE THREAD

**Issue by sourabhtiwari** [ExcelDataReader/ExcelDataReader#83]
ftype = Path.GetExtension(filename);
            if (ftype == ".xls")
            {
                // Reading from a binary Excel file ('97-2003 format; *.xls)
                excelReader = ExcelReaderFactory.CreateBinaryReader(stream);
            }
            else
            {
                // Reading from a OpenXml Excel file (2007 format; *.xlsx)
                excelReader = ExcelReaderFactory.CreateOpenXmlReader(stream);
            }

**Comment by eastwood84** [comment]
Any fix for this?

**Comment by andersnm** [comment]
@eastwood84 There has been a lot of fixes for .xls compatibility in the recent 3.0 prereleases. Are you using the latest prerelease version of ExcelDataReader?

If you have an xls still not loading in the latest version, any chance you could upload it here or in a new issue ticket?

**Comment by kkho** [comment]
It seems to be the same issue that I have. It would be nice to get it fixed though

**Comment by andersnm** [comment]
Any chance to share the xls? If not, just the first 8 bytes of the file would help immenselyt  (f.ex from a hexviewer or something). Need something to go on here

**Comment by johnboker** [comment]
I seem to be getting the same error with the most recent nuget package (3.0.0).

The first 8 bytes of the file are 

> D0CF11E0 A1B11AE1

.

I noticed in [src/ExcelDataReader/Core/BinaryFormat/XlsWorkbook.cs](https://github.com/ExcelDataReader/ExcelDataReader/blob/93cfa4796ffa4b49e4c3864fe5780179756c4dfe/src/ExcelDataReader/Core/BinaryFormat/XlsWorkbook.cs#L100)


```
public static bool IsCompoundDocument(byte[] probe)
{
    return BitConverter.ToUInt64(probe, 0) == 0xE11AB1A1E011CFD0;
}
```

The bytes seem to be reversed.

**Comment by johnboker** [comment]
Disregard my last comment.  It seems my problem was i needed to seek to the beginning of the stream before trying to use the stream to create the reader.

`ms.Seek(0, SeekOrigin.Begin)`

**Comment by andersnm** [comment]
Thanks for the update @johnboker, I was about to reopen the issue, but keeping it closed unless we get more feedback/reports.

I can think of two other situations where this could happen:
- When using CreateBinaryReader with an .xlsx (use CreateReader instead)
- On big endian machines (f.ex Xbox, or some odd Mono platforms - not supported!)

The only way to get a HeaderException("Invalid file signature.") is when these bytes do not match. The reverse order has to do with endian-ness.

Relating to your situation, it's a valid question whether to support loading from the middle of a stream, or to assume the stream always represents an entire workbook. Right now there is some inconsistency: ExcelDataReader probes for format/version at the current stream position, but then rewinds to the beginning of the stream before parsing the detected format

**Comment by johnboker** [comment]
So, if we want to keep it reading from the current position, wouldn't it make sense just to rewind 8 bytes to be at the start when the method was called?

**Comment by MikeCoderr** [comment]
Hi everybody. I get a same error:
[Index_Historical.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/1634254/Index_Historical.zip)
With this code: 
`using (var excelFile = File.Open(kvp.Value, FileMode.Open, FileAccess.Read))
                using (var excelReader = ExcelReaderFactory.CreateBinaryReader(excelFile))`

I get: 
Message = "Invalid file signature."
StackTrace = "   at ExcelDataReader.ExcelReaderFactory.CreateBinaryReader(Stream fileStream, ExcelReaderConfiguration configuration)....

Maybe somebody can help or help me how to get this fixed and lets me read in the file.

**Comment by andersnm** [comment]
@MikeCoderr Trend_Index_Historical.xls is a CSV file that's been renamed to .xls

**Comment by wizardgsz** [comment]
Raw Data tab separated :D

**Comment by MikeCoderr** [comment]
thanks for your support!!! I need to speak to the provider of that file!

**Comment by sebastianamaro** [comment]
Hi! 

This is my code

`  /// <summary>
        /// Se utiliza ExcelDataReader para llenar el dataset del DocumentoExcel. 
        /// </summary>
        private void CargarDataSet()
        {
            try
            {
                using (var stream = File.Open(DocumentoExcel.Path, FileMode.Open, FileAccess.Read))
                {
                    IExcelDataReader reader = GetExcelReaderFactory(DocumentoExcel.Path, stream);

                    var conf = new ExcelDataSetConfiguration
                    {
                        ConfigureDataTable = _ => new ExcelDataTableConfiguration
                        {
                            UseHeaderRow = true
                        }
                    };

                    DocumentoExcel.DataSet = reader.AsDataSet(conf);
                }
            }
            catch (Exception ex)
            {
                throw new ExcepcionModelo($"No se pudo cargar la hoja {Hoja}. Error: " + ex.Message, 10008);
            }
        }

        /// <summary>
        /// Genera una instancia de ExcelReaderFactory dependiendo la extension del Excel.
        /// </summary>
        /// <param name="path"></param>
        /// <param name="stream"></param>
        /// <returns></returns>
        private IExcelDataReader GetExcelReaderFactory(string path, FileStream stream)
        {
            if (Path.GetExtension(DocumentoExcel.Path) == ".xls")
            {
                return ExcelReaderFactory.CreateBinaryReader(stream);
            }
            else
            {
                return ExcelReaderFactory.CreateOpenXmlReader(stream);
            }
        }`

I get invalid file signature, from this file 
[FACTURA ESTANDAR.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/3567263/FACTURA.ESTANDAR.zip)

This is a XLS 97-2003 (not .XML) 

The weirdest part is that on my machine, this code works ok, but on a cloud server this same code fails with above exception. 

I checked the endianess on the file and it seems ok, here is the screenshot from the hexviewer 

![image](https://user-images.githubusercontent.com/1429677/64136043-ace8e280-cdbc-11e9-8dcc-3ffaea81d724.png)

Help please :(

**Comment by andersnm** [comment]
Hi @sebastianamaro It sounds like the file was corrupted during upload to the server? I can't think of a way to get that error message with the attached file.

**Comment by sebastianamaro** [comment]
mmm but the code is the same, if i run it locally it runs ok :/ And the upload is a standard procedure among other file types (xml, txt) and those arent corrupted. Besides, we used before ExcelInterop and it worked ok both local and cloud
