### ISSUE TITLE
Read excel sheet internal formatting. 

### ISSUE THREAD

**Issue by mikeon** [ExcelDataReader/ExcelDataReader#87]
Hi. Is this possible to somehow load dataset with the same formatting as in file? I focus on "indentation" it's totally not recognizable by ExcelDataReader, data are loaded losing those informations. Thanks!

**Comment by wizardgsz** [comment]
Do you mean cells and/or columns formats (like general, numeric, currency, datetime, custom and so on)?
I think you should implement it yourself starting from file formats specifications :(
The library just read the cells values, not their "representation and formatting" (fonts, color, alignment are not parsed).
