### ISSUE TITLE
After read excel into DataSet, the extra space of column names are not trimmed.

### ISSUE THREAD

**Issue by alexeyqian** [ExcelDataReader/ExcelDataReader#88]
FileStream stream = System.IO.File.Open(filePath, FileMode.Open, FileAccess.Read);
            IExcelDataReader excelReader = ExcelReaderFactory.CreateOpenXmlReader(stream);
            excelReader.IsFirstRowAsColumnNames = isFirstRowAsColumnNames;
            DataSet dataSet = excelReader.AsDataSet();
            excelReader.Close();

If the excel column headers have extra space at the end, they will also be included in column names of data table inside dataset.

**Comment by wizardgsz** [comment]
Hi, I think this is the correct behaviour: it reads exactly what your Excel sheet contains, trailing spaces also. Remember that columns with same name will have a numeric suffix to make them unique in DataTable.
Maybe you can just trim header after loading data...
Don't you?
