### ISSUE TITLE
reader.Read() sometimes skips the last row

### ISSUE THREAD

**Issue by pwitvoet** [ExcelDataReader/ExcelDataReader#89]
I encountered a few .xls files where using `while (reader.Read())` results in the last row being skipped. However, `reader.AsDataSet()` does return the correct number of rows.

Cursory debugging shows that the last row has been read correctly. `readWorksheetRow` returns false, which I assume is what it should do. `moveToNextRecord` seems to have special-case code for reading the last row, to make `Read` return true, but I'm dealing with Excel files without index, and `moveToNextRecordNoIndex` doesn't have that special-case code (it's commented out). Uncommenting those lines fixes the problem (at least for the files I've got here).

What's the reason that those lines have been disabled? Does it break things for other Excel files?

**Comment by andersnm** [comment]
Fixed in b9df46924c52ddb858f075fa3b16bcd8a46aa7c0
