### ISSUE TITLE
CreateOpenXmlReader throwing object reference exception while reading .xslx file

### ISSUE THREAD

**Issue by sarithareddy-g** [ExcelDataReader/ExcelDataReader#91]
I have an .xslx file which was generated using ExcelExporter nuget package. When I tried to read the file using CreateOpenXmlReader method it is throwing object reference not set to instance of an object exception. When I debug more into that I found that _workbook.Styles is null and reading _workbook.Styles.NumFmts value is throwing the exception. 
If open the same excel sheet in msoffice and save it without doing any changes I am able to read the data without any issues. Please find the excel sheet as an attachment. Please find the attached excel sheet for your reference. Can some body let me know why _workbook.Styles is null in first case.
[Download (12).xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/43895/Download.12.xlsx)

**Comment by grumpycatsaysno** [comment]
+ 1 with the same null reference exception. Is there any progress on the problem or any explanation why it's happening?

**Comment by wizardgsz** [comment]
Hello, the enclosed same has issues to fix:

1. Sheet has no <dimension> and no <cols> so you should handle it in ReadStyles(Stream xmlFileStream): _Styles = new XlsxStyles();

2. Each cell <c> as no "r" attribute so column number isn't updated.

3. Each <row> as no "r" attribute, so ReadSheetRow(XlsxWorksheet sheet) fails querying it. Probably we could handle it with a new 1-based index (same as <c>).

Here there is a "fixed" sheet just to compare with original one and undestand my comments.
Regards

**Comment by wizardgsz** [comment]
Let's try this in:

**XlsxWorkbook.cs**
```
        private void ReadStyles(Stream xmlFileStream)
        {
            _Styles = new XlsxStyles();

            if (null == xmlFileStream) return;
```
**ExcelOpenXmlReader.cs**

Declare row/column "auto incremental" counters and reset them in constructor `AsDataSet()`:
```
        private int _iRowCounter = 0;
        private int _iColCounter = 0;
```
Modify the main cycle using them: each time `XlsxWorksheet.A_r is null`, we use previous value (if read) incrementing it.
```
		private bool ReadSheetRow(XlsxWorksheet sheet)
		{
...
                _iColCounter = 0;
                int rowIndex = ++_iRowCounter;
                if (!String.IsNullOrEmpty(_xmlReader.GetAttribute(XlsxWorksheet.A_r)))
                    rowIndex = int.Parse(_xmlReader.GetAttribute(XlsxWorksheet.A_r));
				if (rowIndex != (_depth + 1))
				if (rowIndex != (_depth + 1))
...
                            a_s = _xmlReader.GetAttribute(XlsxWorksheet.A_s);
                            a_t = _xmlReader.GetAttribute(XlsxWorksheet.A_t);
                            a_r = _xmlReader.GetAttribute(XlsxWorksheet.A_r);
                            if (!String.IsNullOrEmpty(a_r))
                            {
                                XlsxDimension.XlsxDim(a_r, out col, out row);
                                _iColCounter = col;
                            }
                            else
                            {
                                col = ++_iColCounter;
                                row = _iRowCounter;
                            }
```
One more open point: find a "convenient" way to determine the dimension of the sheet, as we have no `<dimension>` and no `<cols>`:
```
		private void ReadSheetGlobals(XlsxWorksheet sheet)
		{
...
		    int biggestColumn = 666; //used when no col elements and no dimension
```

**Comment by wizardgsz** [comment]
Verify also https://github.com/ExcelDataReader/ExcelDataReader/pull/115

**Comment by andersnm** [comment]
This appears to be fixed, the attached "Download.12.xlsx" works fine with latest.
