### ISSUE TITLE
importing XLS file ends with "Buffer size is less than minimum BIFF record size"

### ISSUE THREAD

**Issue by krwl** [ExcelDataReader/ExcelDataReader#92]
XLS file is properly read by Excel. XLS file is created from C# app using Provider=Microsoft.Jet.OLEDB.4.0..

I cannot sumbit that file throu this form, however can provide it throu e-mail..

Stacktrace:

   w Excel.Core.BinaryFormat.XlsBiffRecord..ctor(Byte[] bytes, UInt32 offset, ExcelBinaryReader reader)
   w Excel.Core.BinaryFormat.XlsBiffRecord.GetRecord(Byte[] bytes, UInt32 offset, ExcelBinaryReader reader)
   w Excel.Core.BinaryFormat.XlsBiffStream.Read()
   w Excel.ExcelBinaryReader.readWorkBookGlobals()
   w Excel.ExcelBinaryReader.Initialize(Stream fileStream)
   w Excel.ExcelReaderFactory.CreateBinaryReader(Stream fileStream)

**Comment by metatypeman** [comment]
I can not read xls file by yours library. LibreOffice display that xls file fully. Is the library alive? Are you fixing bugs?

**Comment by metatypeman** [comment]
Yous library displays only 7 first rows form more 200.

**Comment by Ian1971** [comment]
I don't have time to work on it at the moment, but anyone can fork it. Or
take it over if they want.

On Fri, Dec 11, 2015 at 12:14 PM, metatypeman <notifications@github.com>
wrote:

> I can not read xls file by yours library. LibreOffice display that xls
> file fully. Is the library alive? Are you fixing bugs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/92#issuecomment-163924676>
> .
>



-- 

Ian Cox
C.T.O.

System Sync
m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.systemsyncsolutions.com
<http://www.releasemobile.com/>

Registered in England as systemsync solutions ltd.
Number: 9326325 VAT: 202729923
