### ISSUE TITLE
TestExcel_2040.xlsx fails

### ISSUE THREAD

**Issue by greenboxent** [ExcelDataReader/ExcelDataReader#96]
The TestExcel_2040.xlsx has reader.IsValid==false after 
            IExcelDataReader reader = ExcelReaderFactory.CreateOpenXmlReader(Helper.GetTestWorkbook("xTestExcel_2040"));

When will this be fixed?

**Comment by wizardgsz** [comment]
Did you see the XLSX file referenced by unit test?
It's not a valid ZIP archive so the file itself is corrupted, nothing related to the library :D

`d0 cf 11 e0 a1 b1 1a e1 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 3e 20 03 20 fe ff 09 20 06 20 20 20 20 20 20 20 20 20 20 20 01 20 20 20 01 20 20 20 20 20 20 20 20 10 20 20 02 20 20 20 01 20 20 20 fe ff ff ff 20 20 20 20 20 20 20 20 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  `
