### ISSUE TITLE
Failed to read XLSX

### ISSUE THREAD

**Issue by igvk** [ExcelDataReader/ExcelDataReader#97]
[Fillreport.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/82661/Fillreport.xlsx)
Here is a sample XLSX file that fails to be read with simple code (latest branch is used):

```
            IExcelDataReader excelReader = ExcelReaderFactory.CreateOpenXmlReader(stream);
            do
            {
                while (excelReader.Read())
                {
                }
            } while (excelReader.NextResult());
```

It fails to calculate the number of columns in ReadSheetGlobalsAsync().

**Comment by wizardgsz** [comment]
Hello.

Please take a look here: https://github.com/ExcelDataReader/ExcelDataReader/issues/91
It seems the same issue on input Excel file: you're missing `<dimension>` tag in Sheet.xml.

Moreover, your file uses 1-based index for rows but 0-based for columns. 
I don't know it's ok in Excel:
```
<x:row r="1"><x:c **r="0" t="str"><x:v>Fills Reported as of 04/01/2016 12:55:42</x:v></x:c></x:row>
<x:row r="2"><x:c **r="0" t="str"><x:v>Account Number</x:v></x:c><x:c r="1" t="str"><x:v>Trader</x:v></x:c><x:c r="2" t="str"><x:v>Order Number</x:v></x:c><x:c r="3" t="str"><x:v>Leg Number</x:v></x:c><x:c r="4" t="str"><x:v>Buy Or Sell</x:v></x:c><x:c r="5" t="str"><x:v>Quantity</x:v></x:c><x:c r="6" t="str"><x:v>Contract</x:v></x:c><x:c r="7" t="str"><x:v>Fill Price</x:v></x:c><x:c r="8" t="str"><x:v>Fill Price Decimal</x:v></x:c><x:c r="9" t="str"><x:v>Fill Time</x:v></x:c></x:row>
```

**Comment by igvk** [comment]
Hello,
I see that this file is somewhat non-compliant, but it was generated by other party, and it loads in Excel.
I needed to make adjustments to source code to make it load. Don't know whether they are correct in general case, but the helped to load the file.

**Comment by wizardgsz** [comment]
Did you follow my advice to modify source code?
Did it work?

**Comment by igvk** [comment]
Sorry, I apparently referred to another file I had trouble loading.
This file is still not loadable for me.

**Comment by wizardgsz** [comment]
Excel totally ignores cells indexing with no range delimiter (i.e. character ':').

Please take your Sheet.xml, change it as below (note the modified `r="###"` indices):
`<x:row r="2"><x:c r="10" t="str"><x:v>Account Number</x:v></x:c><x:c r="2" t="str"><x:v>Trader</x:v></x:c><x:c r="3" t="str"><x:v>Order Number</x:v></x:c><x:c r="4" t="str"><x:v>Leg Number</x:v></x:c><x:c r="5" t="str"><x:v>Buy Or Sell</x:v></x:c><x:c r="6" t="str"><x:v>Quantity</x:v></x:c><x:c r="7" t="str"><x:v>Contract</x:v></x:c><x:c r="8" t="str"><x:v>Fill Price</x:v></x:c><x:c r="9" t="str"><x:v>Fill Price Decimal</x:v></x:c><x:c r="15" t="str"><x:v>Fill Time</x:v></x:c></x:row>
`
Try loading it in Excel and you'll have a "surprise" (as stated Excel ignores indexing).

I slightly modified my proposed solution in https://github.com/ExcelDataReader/ExcelDataReader/issues/91 to handle your file and it works:
`if (!String.IsNullOrEmpty(a_r) && a_r.IndexOf(':') > 0)`
Hope it helps.

**Comment by wizardgsz** [comment]
Verify also https://github.com/ExcelDataReader/ExcelDataReader/pull/115
