### ISSUE TITLE
File Read Faults With Null Reference

### ISSUE THREAD

**Issue by rmcohen** [ExcelDataReader/ExcelDataReader#99]
The attached file was written by a 3rd party app and causes the reader to fail with a null ref exception.

If I copy the data to a native workbook, it is read OK.
[Flingor Skus.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/103557/Flingor.Skus.zip)

**Comment by wizardgsz** [comment]
Please use latest develop build: no problem opening binary file in TestApp :+1:
